/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : FCDTRONL_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_OLTBS_CONTRACT":"CONTREFNO~MODULE~BRANCH~CUSTOMREFNO~PRODUCT~USERREFNO~PRODUCTDESCRIPTION~LATVERNO~VERNO~LATEVTSQNO~ORGACTCOD~ONCEAUTH~PROCESSREFNUM~CHANNELREFNUM~SOURCECODE~ALT_REFNO~ECAREQSTATUS","BLK_LBTBS_SYNDICATION_MASTER":"COUNTERPARTY~CURRENCY~AMOUNT~FACSTDT~FACENDT~INTAGENCYID~CUSIPNO~USRDEFSTAT~AGENTCIF~MCONTERFNO~TRSTDT~MINAMT~TRENDT~MAXTRCAMT~NAMEDAGENT~PURSYN~PURSYN2~REMARKS~PURSYN1~NAMEDAGENTNAME~AGENCYTYPE~WATFAC~WATREM~TXTAGMOD~PARPRCSTAT~TXTREPCCY~TXTREPAMT~SUBSYSSTAT~EVENTSEQNO","BLK_LSTBS_SYNDICATION_PREFERENCE":"SCHMOVACRMNTH~SCHIGNHOL~SCHMOV~SCHCONBRNHOL~APPFACHOLCCY~SCHHOLCCY~APPLOCHOLCCY~CASCSCH~MATSCHMOV~MATFACHOLCCY~MATHOLCCY~MATLOCHOLCCY~MATMOVACMNTH~MATIGNHOL~MATCONBRNHOL~PCONTREFNO~PVERSIONNO~ADMINID~SECADMINID~ADMINNAME~SECADMINNAME~PREPAYMTD~APPLY_FC_HOL_TREATMENT~APPLY_MAT_FC_HOL_TREATMENT~PARTIAL_LIQD_ALLOWED","BLK_OLTBS_CONTRACT_EVENT_LOG":"MAKDT~MAKERID~TXNSTAT1~CHECKERID~AUTHSTAT~CHECKERDT~TXNSTAT","BLK_LBTBS_FACILITY_CCY":"FACCCY~FACCCYDESC","BLK_LBTBS_ASSIGNMENT_FEE_DETAILS":"FEECCY~FEECCYDESC~FEEAMOUNT","BLK_SYND_CON_FINCENTRE_SCH":"CONTRACT_REF_NO~FIN_CENTRE~FIN_CENTRE_DESC~SCHEDULE_TYPE~VERSION_NO","BLK_SYND_CON_FINCENTRE_MAT":"CONTRACT_REF_NO~FIN_CENTRE~FIN_CENTRE_DESC~SCHEDULE_TYPE~VERSION_NO","BLK_CONT_SCH":"SCH_COMP~SCH_STDT~SCH_ENDDT~SCH_NO_OF_SCH~SCH_FREQ~SCH_FREQ_UNIT~SCH_AMT~SCH_CONT_REF~SCH_ESN~SCH_TYPE~SCH_FLAG~SCH_VERNO~SCH_MONTH_END_IND","BLK_SCH_DET":"SCHDT_PAYDT~SCHDT_AMT_CCY~SCHDT_TOT_AMT_DUE~SCHDT_AMT_SET~SCHDT_ADJ_AMT","BLK_SCH_AMT_DUE":"AMTDUE_COMP~AMTDUE_CCY~AMTDUE_AMT_DUE~AMTDUE_AMT_SET~AMTDUE_ADJ_AMT~AMTDUE_EXP_BAL~AMTDUE_CONT_CCY~AMTDUE_CONTREF~AMTDUE_DUEDT~AMTDUE_PAYDT","BLK_SCH_AMT_SETLLED":"AMTSET_DATE~AMTSET_CCY~AMTSET_PAIDDT~AMTSET_AMT_SET~AMTSET_LCY_AMT~AMTSET_COMP~AMTSET_CONTREF~AMTSET_DUEDT","BLK_PAID_SCH":"PAIDSCH_SCHTY~PAIDSCH_COMP~PAIDSCH_STDT~PAIDSCH_ENDDT~PAIDSCH_NO_SCH~PAIDSCH_FREQ~PAIDSCH_FREQ_UNIT~PAIDSCH_SCH_PER~PAIDSCH_AMT~PAIDSCH_LCY~PAIDSCH_VERNO~PAIDSCH_CONTREF~PAIDSCH_ESN"};

var multipleEntryPageSize = {"BLK_SYND_CON_FINCENTRE_SCH" :"15" ,"BLK_SYND_CON_FINCENTRE_MAT" :"15" ,"BLK_LBTBS_FACILITY_CCY" :"15" ,"BLK_LBTBS_ASSIGNMENT_FEE_DETAILS" :"15" ,"BLK_CONT_SCH" :"15" ,"BLK_SCH_DET" :"15" ,"BLK_SCH_AMT_DUE" :"15" ,"BLK_SCH_AMT_SETLLED" :"15" ,"BLK_PAID_SCH" :"15" };

var multipleEntrySVBlocks = "";

var tabMEBlks = {"CVS_MAIN__TAB_HOL":"BLK_SYND_CON_FINCENTRE_SCH~BLK_SYND_CON_FINCENTRE_MAT","CVS_MAIN__TAB_CCYDET":"BLK_LBTBS_FACILITY_CCY","CVS_MAIN__TAB_ASSFEE":"BLK_LBTBS_ASSIGNMENT_FEE_DETAILS","CVS_MAIN__TAB_FEE_SCH":"BLK_CONT_SCH","CVS_FEE_PAY_SCH__TAB_MAIN":"BLK_SCH_DET~BLK_SCH_AMT_DUE~BLK_SCH_AMT_SETLLED","CVS_SCH_PAID__TAB_MAIN":"BLK_PAID_SCH"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT">CONTREFNO~MODULE~BRANCH~CUSTOMREFNO~PRODUCT~USERREFNO~PRODUCTDESCRIPTION~LATVERNO~VERNO~LATEVTSQNO~ORGACTCOD~ONCEAUTH~PROCESSREFNUM~CHANNELREFNUM~SOURCECODE~ALT_REFNO~ECAREQSTATUS</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="1" TYPE="BLK_LBTBS_SYNDICATION_MASTER">COUNTERPARTY~CURRENCY~AMOUNT~FACSTDT~FACENDT~INTAGENCYID~CUSIPNO~USRDEFSTAT~AGENTCIF~MCONTERFNO~TRSTDT~MINAMT~TRENDT~MAXTRCAMT~NAMEDAGENT~PURSYN~PURSYN2~REMARKS~PURSYN1~NAMEDAGENTNAME~AGENCYTYPE~WATFAC~WATREM~TXTAGMOD~PARPRCSTAT~TXTREPCCY~TXTREPAMT~SUBSYSSTAT~EVENTSEQNO</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="1" TYPE="BLK_LSTBS_SYNDICATION_PREFERENCE">SCHMOVACRMNTH~SCHIGNHOL~SCHMOV~SCHCONBRNHOL~APPFACHOLCCY~SCHHOLCCY~APPLOCHOLCCY~CASCSCH~MATSCHMOV~MATFACHOLCCY~MATHOLCCY~MATLOCHOLCCY~MATMOVACMNTH~MATIGNHOL~MATCONBRNHOL~PCONTREFNO~PVERSIONNO~ADMINID~SECADMINID~ADMINNAME~SECADMINNAME~PREPAYMTD~APPLY_FC_HOL_TREATMENT~APPLY_MAT_FC_HOL_TREATMENT~PARTIAL_LIQD_ALLOWED</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT_EVENT_LOG">MAKDT~MAKERID~TXNSTAT1~CHECKERID~AUTHSTAT~CHECKERDT~TXNSTAT</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_LBTBS_FACILITY_CCY">FACCCY~FACCCYDESC</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_LBTBS_ASSIGNMENT_FEE_DETAILS">FEECCY~FEECCYDESC~FEEAMOUNT</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_SYND_CON_FINCENTRE_SCH">CONTRACT_REF_NO~FIN_CENTRE~FIN_CENTRE_DESC~SCHEDULE_TYPE~VERSION_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_SYND_CON_FINCENTRE_MAT">CONTRACT_REF_NO~FIN_CENTRE~FIN_CENTRE_DESC~SCHEDULE_TYPE~VERSION_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_CONT_SCH">SCH_COMP~SCH_STDT~SCH_ENDDT~SCH_NO_OF_SCH~SCH_FREQ~SCH_FREQ_UNIT~SCH_AMT~SCH_CONT_REF~SCH_ESN~SCH_TYPE~SCH_FLAG~SCH_VERNO~SCH_MONTH_END_IND</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_SCH_DET">SCHDT_PAYDT~SCHDT_AMT_CCY~SCHDT_TOT_AMT_DUE~SCHDT_AMT_SET~SCHDT_ADJ_AMT</FN>'; 
msgxml += '      <FN PARENT="BLK_SCH_DET" RELATION_TYPE="N" TYPE="BLK_SCH_AMT_DUE">AMTDUE_COMP~AMTDUE_CCY~AMTDUE_AMT_DUE~AMTDUE_AMT_SET~AMTDUE_ADJ_AMT~AMTDUE_EXP_BAL~AMTDUE_CONT_CCY~AMTDUE_CONTREF~AMTDUE_DUEDT~AMTDUE_PAYDT</FN>'; 
msgxml += '      <FN PARENT="BLK_SCH_AMT_DUE" RELATION_TYPE="N" TYPE="BLK_SCH_AMT_SETLLED">AMTSET_DATE~AMTSET_CCY~AMTSET_PAIDDT~AMTSET_AMT_SET~AMTSET_LCY_AMT~AMTSET_COMP~AMTSET_CONTREF~AMTSET_DUEDT</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_PAID_SCH">PAIDSCH_SCHTY~PAIDSCH_COMP~PAIDSCH_STDT~PAIDSCH_ENDDT~PAIDSCH_NO_SCH~PAIDSCH_FREQ~PAIDSCH_FREQ_UNIT~PAIDSCH_SCH_PER~PAIDSCH_AMT~PAIDSCH_LCY~PAIDSCH_VERNO~PAIDSCH_CONTREF~PAIDSCH_ESN</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="1" TYPE="BLK_OL_LNVWS_CONTRACT_SUMMARY">CONTREFNO~PRODUCT~CONTSTAT~AUTHSTAT~COUNTERPARTY~CUSTNAM~NAME~CCY~SYNDAMT~FACSTDT~FACEDDT~ADMIN~NOOFTR~NOOFDD~USRRFNO~DTDEALID</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "FCDTRONL";
var defaultWhereClause = "module_code='FC' and branch=global.current_branch";
var defaultOrderByClause ="";
var multiBrnWhereClause ="Branch IN (SELECT BRANCH_CODE FROM SMVW_USER_BRANCHES WHERE USER_ID = GLOBAL.USER_ID INTERSECT SELECT BRANCH_CODE FROM SMTB_USER_ROLE WHERE USER_ID = GLOBAL.USER_ID UNION SELECT BRANCH_CODE FROM SMVWS_USER_CENTRAL_ROLES WHERE USER_ID = GLOBAL.USER_ID)";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_OL_LNVWS_CONTRACT_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_OLTBS_CONTRACT" : "","BLK_LBTBS_SYNDICATION_MASTER" : "BLK_OLTBS_CONTRACT~1","BLK_LSTBS_SYNDICATION_PREFERENCE" : "BLK_OLTBS_CONTRACT~1","BLK_OLTBS_CONTRACT_EVENT_LOG" : "BLK_OLTBS_CONTRACT~1","BLK_LBTBS_FACILITY_CCY" : "BLK_OLTBS_CONTRACT~N","BLK_LBTBS_ASSIGNMENT_FEE_DETAILS" : "BLK_OLTBS_CONTRACT~N","BLK_SYND_CON_FINCENTRE_SCH" : "BLK_OLTBS_CONTRACT~N","BLK_SYND_CON_FINCENTRE_MAT" : "BLK_OLTBS_CONTRACT~N","BLK_CONT_SCH" : "BLK_OLTBS_CONTRACT~N","BLK_SCH_DET" : "BLK_OLTBS_CONTRACT~N","BLK_SCH_AMT_DUE" : "BLK_SCH_DET~N","BLK_SCH_AMT_SETLLED" : "BLK_SCH_AMT_DUE~N","BLK_PAID_SCH" : "BLK_OLTBS_CONTRACT~N"}; 

 var dataSrcLocationArray = new Array("BLK_OLTBS_CONTRACT","BLK_LBTBS_SYNDICATION_MASTER","BLK_LSTBS_SYNDICATION_PREFERENCE","BLK_OLTBS_CONTRACT_EVENT_LOG","BLK_LBTBS_FACILITY_CCY","BLK_LBTBS_ASSIGNMENT_FEE_DETAILS","BLK_SYND_CON_FINCENTRE_SCH","BLK_SYND_CON_FINCENTRE_MAT","BLK_CONT_SCH","BLK_SCH_DET","BLK_SCH_AMT_DUE","BLK_SCH_AMT_SETLLED","BLK_PAID_SCH"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside FCDTRONL.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside FCDTRONL.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_OLTBS_CONTRACT__CONTREFNO";
pkFields[0] = "BLK_OLTBS_CONTRACT__CONTREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_LBTBS_ASSIGNMENT_FEE_DETAILS":["FEEAMOUNT","FEECCY"],"BLK_LBTBS_FACILITY_CCY":["FACCCY","FACCCYDESC"],"BLK_LBTBS_SYNDICATION_MASTER":["AMOUNT","CUSIPNO","FACENDTI","INTAGENCYID","MAXTRCAMT","MINAMT","PURSYN","PURSYN1","PURSYN2","REMARKS","SUBSYSSTAT","TRENDTI","TRSTDTI","USRDEFSTAT","WATFAC","WATREM"],"BLK_LSTBS_SYNDICATION_PREFERENCE":["ADMINID","APPFACHOLCCY","APPLOCHOLCCY","APPLY_FC_HOL_TREATMENT","APPLY_MAT_FC_HOL_TREATMENT","CASCSCH","MATCONBRNHOL","MATFACHOLCCY","MATHOLCCY","MATIGNHOL","MATLOCHOLCCY","MATMOVACMNTH","MATSCHMOV","PARTIAL_LIQD_ALLOWED","SCHCONBRNHOL","SCHHOLCCY","SCHIGNHOL","SCHMOV","SCHMOVACRMNTH","SECADMINID"],"BLK_OLTBS_CONTRACT_EVENT_LOG":["AUTHSTAT","CHECKERDT","CHECKERID","MAKDT","MAKERID","TXNSTAT1"],"BLK_OLTBS_CONTRACT":["ALT_REFNO"],"BLK_SYND_CON_FINCENTRE_MAT":["CONTRACT_REF_NO","FIN_CENTRE","FIN_CENTRE_DESC","SCHEDULE_TYPE","VERSION_NO"],"BLK_SYND_CON_FINCENTRE_SCH":["CONTRACT_REF_NO","FIN_CENTRE","FIN_CENTRE_DESC","SCHEDULE_TYPE","VERSION_NO"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_OLTBS_CONTRACT__PRODUCT__LOV_PRODUCT":["BLK_OLTBS_CONTRACT__PRODUCT~BLK_OLTBS_CONTRACT__PRODUCTDESCRIPTION~","BLK_OLTBS_CONTRACT__BRANCH!VARCHAR2","N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__COUNTERPARTY__LOV_COUNTERPARTY":["BLK_LBTBS_SYNDICATION_MASTER__COUNTERPARTY~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2~BLK_OLTBS_CONTRACT__BRANCH!VARCHAR2","N~N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__CURRENCY__LOV_CONTCCY":["BLK_LBTBS_SYNDICATION_MASTER__CURRENCY~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2","N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__INTAGENCYID__LOV_INTAGENCYID":["BLK_LBTBS_SYNDICATION_MASTER__INTAGENCYID~~","BLK_OLTBS_CONTRACT__PRODUCT!~BLK_OLTBS_CONTRACT__BRANCH!","N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__USRDEFSTAT__LOV_STATUS":["BLK_LBTBS_SYNDICATION_MASTER__USRDEFSTAT~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2","N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__AGENTCIF__LOV_AGENTCIF":["BLK_LBTBS_SYNDICATION_MASTER__AGENTCIF~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2~BLK_OLTBS_CONTRACT__BRANCH!VARCHAR2","N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__NAMEDAGENT__LOV_NAMEDAGENT":["BLK_LBTBS_SYNDICATION_MASTER__NAMEDAGENT~BLK_LBTBS_SYNDICATION_MASTER__NAMEDAGENTNAME~","","N~N",""],"BLK_LBTBS_SYNDICATION_MASTER__WATREM__LOV_WLREMARKS":["BLK_LBTBS_SYNDICATION_MASTER__WATREM~","","N",""],"BLK_LSTBS_SYNDICATION_PREFERENCE__SCHHOLCCY__LOV_CONTCCY":["BLK_LSTBS_SYNDICATION_PREFERENCE__SCHHOLCCY~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2","N~N",""],"BLK_LSTBS_SYNDICATION_PREFERENCE__MATHOLCCY__LOV_CONTCCY":["BLK_LSTBS_SYNDICATION_PREFERENCE__MATHOLCCY~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2","N~N",""],"BLK_LSTBS_SYNDICATION_PREFERENCE__ADMINID__LOV_ADMIN":["BLK_LSTBS_SYNDICATION_PREFERENCE__ADMINID~BLK_LSTBS_SYNDICATION_PREFERENCE__ADMINNAME~","","N~N",""],"BLK_LSTBS_SYNDICATION_PREFERENCE__SECADMINID__LOV_ADMIN":["BLK_LSTBS_SYNDICATION_PREFERENCE__SECADMINID~BLK_LSTBS_SYNDICATION_PREFERENCE__SECADMINNAME~","","N~N",""],"BLK_LBTBS_FACILITY_CCY__FACCCY__LOV_FACILITY_CCY":["BLK_LBTBS_FACILITY_CCY__FACCCY~BLK_LBTBS_FACILITY_CCY__FACCCYDESC~","","N~N",""],"BLK_SYND_CON_FINCENTRE_SCH__FIN_CENTRE__LOV_FINCENTRE":["BLK_SYND_CON_FINCENTRE_SCH__FIN_CENTRE~BLK_SYND_CON_FINCENTRE_SCH__FIN_CENTRE_DESC~","","N~N",""],"BLK_SYND_CON_FINCENTRE_SCH__FIN_CENTRE_DESC__LOV_FINCENTRE":["BLK_SYND_CON_FINCENTRE_SCH__FIN_CENTRE~BLK_SYND_CON_FINCENTRE_SCH__FIN_CENTRE_DESC~","","N~N",""],"BLK_SYND_CON_FINCENTRE_MAT__FIN_CENTRE__LOV_FINCENTRE":["BLK_SYND_CON_FINCENTRE_MAT__FIN_CENTRE~BLK_SYND_CON_FINCENTRE_MAT__FIN_CENTRE_DESC~","","N~N",""],"BLK_SYND_CON_FINCENTRE_MAT__FIN_CENTRE_DESC__LOV_FINCENTRE":["BLK_SYND_CON_FINCENTRE_MAT__FIN_CENTRE~BLK_SYND_CON_FINCENTRE_MAT__FIN_CENTRE_DESC~","","N~N",""],"BLK_CONT_SCH__SCH_COMP__LOV_SCH_COMP":["BLK_CONT_SCH__SCH_COMP~~~","BLK_OLTBS_CONTRACT__PRODUCT!VARCHAR2","N~N~N",""],"BLK_OL_LNVWS_CONTRACT_SUMMARY__COUNTERPARTY__LOV_CUST_NAME_S":["BLK_OL_LNVWS_CONTRACT_SUMMARY__COUNTERPARTY~BLK_OL_LNVWS_CONTRACT_SUMMARY__CUSTNAM~~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_SYND_CON_FINCENTRE_SCH","BLK_SYND_CON_FINCENTRE_MAT","BLK_LBTBS_FACILITY_CCY","BLK_LBTBS_ASSIGNMENT_FEE_DETAILS","BLK_CONT_SCH","BLK_SCH_DET","BLK_SCH_AMT_DUE","BLK_SCH_AMT_SETLLED","BLK_PAID_SCH");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("LBCCONBW~BLK_OLTBS_CONTRACT","LBCPARAT~BLK_OLTBS_CONTRACT","LFCFEECF~BLK_LBTBS_SYNDICATION_MASTER","OLCONDET~BLK_LBTBS_SYNDICATION_MASTER","OLCTRMIS~BLK_OLTBS_CONTRACT","OLCTRUDF~BLK_OLTBS_CONTRACT","LBCONPTY~BLK_OLTBS_CONTRACT","LBCPRTAX~BLK_OLTBS_CONTRACT","LBCAGDET~BLK_LBTBS_SYNDICATION_MASTER","TXCTRTAX~BLK_OLTBS_CONTRACT","LFCFRMNT~BLK_OLTBS_CONTRACT"); 

 var CallFormRelat=new Array("OLTBS_CONTRACT.CONTRACT_REF_NO=OLTBS_CONTRACT__CONBW.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_VERSION_NO=OLTBS_CONTRACT__CONBW.LATEST_VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO=OLTBS_CONTRACT__PARAT.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_VERSION_NO=OLTBS_CONTRACT__PARAT.LATEST_VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO=LFTBS_CONTRACT_FEE.CONTRACT_REF_NO AND LBTBS_SYNDICATION_MASTER.EVENT_SEQ_NO = LFTBS_CONTRACT_FEE.EVENT_SEQ_NO","LBTBS_SYNDICATION_MASTER.CONTRACT_REF_NO=OLTBS_CONTRACT__SETT.CONTRACT_REF_NO AND LBTBS_SYNDICATION_MASTER.EVENT_SEQ_NO=OLTBS_CONTRACT__SETT.LATEST_EVENT_SEQ_NO","OLTBS_CONTRACT.CONTRACT_REF_NO=OLTBS_CONTRACT__MIS.CONTRACT_REF_NO","OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_CONTRACT__FLD.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_VERSION_NO = OLTBS_CONTRACT__FLD.LATEST_VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO =OLTBS_CONTRACT_PARTY_DETAILS.CONTRACT_REF_NO and OLTBS_CONTRACT.LATEST_VERSION_NO =OLTBS_CONTRACT_PARTY_DETAILS.VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO =OLTBS_CONTRACT__TAX.CONTRACT_REF_NO","LBTBS_SYNDICATION_MASTER.CONTRACT_REF_NO = OLTBS_CONTRACT__AGDET.CONTRACT_REF_NO AND LBTBS_SYNDICATION_MASTER.VERSION_NO = OLTBS_CONTRACT__AGDET.LATEST_VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO=OLTBS_CONTRACT__TAX.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_EVENT_SEQ_NO=OLTBS_CONTRACT__TAX.LATEST_EVENT_SEQ_NO","OLTBS_CONTRACT.CONTRACT_REF_NO=LFTMS_FEE_COMPONENT.CONTRACT_REF_NO"); 

 var CallRelatType= new Array("1","1","1","1","1","1","1","1","1","1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["FCDTRONL"]="KERNEL";
ArrPrntFunc["FCDTRONL"]="";
ArrPrntOrigin["FCDTRONL"]="";
ArrRoutingType["FCDTRONL"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["FCDTRONL"]="N";
ArrCustomModified["FCDTRONL"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"LBCCONBW":"fccref~esn~ver","LBCPARAT":"fccref~esn~verno","LFCFEECF":"CONTREFNO~","OLCONDET":"CONREFNO~ESN","OLCTRMIS":"CONTREF~ESN~PRDCD~BRNCD","OLCTRUDF":"CONTREFNO~LATVERNO","LBCONPTY":"CONTREFNO~VERSIONNO","LBCPRTAX":"CONTRACTREFNO","LBCAGDET":"FCCREF~ESN~VER","TXCTRTAX":"CONTREF~ESN","LFCFRMNT":"MODULE~CONTREFNO~USERREFNO~BOOKDATE~VALUEDATE~CUST~CCY","OLDEVENT":"CONTREF~ACTION_CODE","LPSCOMNT":"","OLSDRYET":"","OLDMSPRV":"CONTREF~ESN~MODULE~PARENTFUNCTION~ACTION_CODE"};
var scrArgSource = {"LBCCONBW":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_LBTBS_SYNDICATION_MASTER__EVENTSEQNO~BLK_OLTBS_CONTRACT__LATVERNO","LBCPARAT":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_LBTBS_SYNDICATION_MASTER__EVENTSEQNO~BLK_OLTBS_CONTRACT__LATVERNO","LFCFEECF":"BLK_OLTBS_CONTRACT__CONTREFNO~","OLCONDET":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_LBTBS_SYNDICATION_MASTER__EVENTSEQNO","OLCTRMIS":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_LBTBS_SYNDICATION_MASTER__EVENTSEQNO~BLK_OLTBS_CONTRACT__PRODUCT~BLK_OLTBS_CONTRACT__BRANCH","OLCTRUDF":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_OLTBS_CONTRACT__LATVERNO","LBCONPTY":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_OLTBS_CONTRACT__LATVERNO","LBCPRTAX":"BLK_OLTBS_CONTRACT__CONTREFNO","LBCAGDET":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_LBTBS_SYNDICATION_MASTER__EVENTSEQNO~BLK_OLTBS_CONTRACT__VERNO","TXCTRTAX":"BLK_OLTBS_CONTRACT__CONTREFNO~BLK_OLTBS_CONTRACT__LATEVTSQNO","LFCFRMNT":"BLK_OLTBS_CONTRACT__MODULE~BLK_OLTBS_CONTRACT__CONTREFNO~BLK_OLTBS_CONTRACT__USERREFNO~~BLK_LBTBS_SYNDICATION_MASTER__FACSTDT~BLK_LBTBS_SYNDICATION_MASTER__COUNTERPARTY~BLK_LBTBS_SYNDICATION_MASTER__CURRENCY","OLDEVENT":"BLK_OLTBS_CONTRACT__CONTREFNO~","LPSCOMNT":"","OLSDRYET":"","OLDMSPRV":"BLK_OLTBS_CONTRACT__CONTREFNO~~~~"};
var scrArgVals = {"LBCCONBW":"~~","LBCPARAT":"~~","LFCFEECF":"~","OLCONDET":"~","OLCTRMIS":"~~~","OLCTRUDF":"~","LBCONPTY":"~","LBCPRTAX":"","LBCAGDET":"~~","TXCTRTAX":"~","LFCFRMNT":"~~~~~~","OLDEVENT":"~EXECUTEQUERY","LPSCOMNT":"","OLSDRYET":"","OLDMSPRV":"~~FC~FCDTRONL~EXECUTEQUERY"};
var scrArgDest = {};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"LBCCONBW":"BLK_LBTBS_SYNDICATION_MASTER__COUNTERPARTY~BLK_LBTBS_SYNDICATION_MASTER__CURRENCY","LBCPARAT":"","LFCFEECF":"BLK_LBTBS_SYNDICATION_MASTER__FACSTDT~BLK_LBTBS_SYNDICATION_MASTER__FACENDT","OLCONDET":"","OLCTRMIS":"","OLCTRUDF":"","LBCONPTY":"","LBCPRTAX":"","LBCAGDET":"","TXCTRTAX":"BLK_LBTBS_SYNDICATION_MASTER__COUNTERPARTY~BLK_LBTBS_SYNDICATION_MASTER__FACSTDT","LFCFRMNT":""};
var dpndntOnSrvs = {"LBCCONBW":"","LBCPARAT":"","LFCFEECF":"","OLCONDET":"LBCCONBW","OLCTRMIS":"","OLCTRUDF":"","LBCONPTY":"","LBCPRTAX":"","LBCAGDET":"","TXCTRTAX":"","LFCFRMNT":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------