/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBCINTRS_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = '';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_MASTER_INT":"CONTRACTREFNO~MODULE~PRDCD~LATEVNSEQNO~PRODUCTDESC~COUNTERPARTY~AGENCY_CONTRACT~MATURITY_DATE~AMOUNT~VALUE_DATE~TENOR_BASED_SPREAD~CONTRACT_CCY~TXTMAINFUNCTION~ONCE_AUTH","BLK_LFTBS_CONTRACT_INTEREST":"AMORTIZATIONCONSTCOMPONENT~NETRATEDESC~RATESIGN~NETACCRUALDESC~SPECIALRATETYPE~TOTALAMTLIQUIDATEDDESC~COMPONENT~EVENTDESC~CONTRACTREFERENCENO~EVENT~INTERESTBASIS~RATE~BORROWLENDINDDESC~SPREAD~RATETYPE~LIQUIDITYPREMIUMTYPE~LIQUIDITYPREMIUM~MARGIN~PENALTYTENOR~SPECIALPENALTYCOMPONENTDESC~RATECALCTYPE~BORROWLENDIND~MAINCOMPONENT~RESETTENOR~WAIVER~ACQUIREDAMOUNT~CURRENCY~AMOUNT~PREPAYMENTPENALTYRATECODE~FIXEDRATECODE~FIXEDRATETYPE~DOMICILECCY~FLOATINGRATE~LIQUIDITYPREMIUMCOMPONENT~RATECODEUSAGE~RATEREVISIONMETHOD~MINRATE~MAXRATE~ACCRUALREQD~STATUS~RATECODE~PICKUPEVENTSEQNO~EVENTSEQNO~CHANGEDURINGAMENDMENT~TRANSACTIONDATE~VALUEDATE~SHOWNINCONTRACTMAINSCREEN~PENALTYTYPE~ADJUSTMENTRATE~DISCACCRAPPLICABLE~CUSTMARGIN~ACCRUALCCY~INTPERIODBASIS~CCYROUNDUNIT~CCYDECIMALS~CCYROUNDRULE~NOINTONPREMATUREWITHDRAWL~REAPPLYINTONOUTSTANDAMT~REAPPLYINTONPREPAIDAMT~REPLICATE~RETAINMAINCOMPPROP~BILLINGNOTICEDAYS~BILLINGNOTICEREQD~INTCOMPUTATION~PENALTYSTARTDATEBASIS~MAXRATESIGN~MINRATESIGN~TENORAMTSPREAD~TENORWISESPREAD~AMOUNTWISESPREAD~TILLDATEACCDESC~HOLCOMPOUND~NEGATIVE_INTEREST_RATE_ALLOWED~RATEFIXINGREQD~RATEFIXINGDAYS~RATEUI~TXTCONTAMT~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~COMPTYPEIN~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_SPREAD_ADJ_COMP_METH~SPREAD_ADJ~RFR_RATE_COMPOUNDING~RFR_RATE_TYPE~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~OBSERVATION_SHIFT~RISK_COMPONENT","BLK_MARGIN_INT":"CONTRACT_REF_NO~COMPONENT~MARGIN_COMPONENT~VALUE_DATE~EVENT_SEQ_NO~MARGIN_RATE~UI_MARGIN_DESC~UI_MARGIN_BASIS~UI_BASIS_AMT_TAG","BLK_RATE_SETTING":"CONTRACT_REF_NO~COMPONENT~SPLIT_SERIAL_NO~SPLIT_NUMBER~EVENT_SEQ_NO~ROUNDING_RULE~ROUNDING_UNIT~TENOR~TXTROLLPRD~TXTCCY~TXTPRINCIPALROLLAMT~TXTINTROLLAMT~TXTTOTALROLLAMT~TXTMATURITYDATE~TXTINTRATEFIXINGDATE~TXTDRIVERCONTRACT","BLK_RTFX":"RTFX_COMP~RTFX_COMPDESC~RTFX_CCY~RTFX_CCYDESC~RTFX_RTCD~RTFX_TNRVAL~RTFX_ACTFIXDT~RTFX_NXTRTFIXDT~RTFX_STDT~RTFX_NXTFIXNOTICEDT~RTFX_ENDDT~RTFX_NXTSTDT~RTFX_RATE~RTFX_REMARKS~RTFX_TNRTYPE~RTFX_ESN~RTFX_TNRUNIT~RTFX_FIXESN~RTFX_AMDESN~RTFX_FIXSTAT~RTFX_FIXTIME~RTFX_FIXDT~RTFX_FIXNOTICE~RTFX_INOTGEN~RTFX_FCCREF","BLK_CONTRACT_RISK_PART_DTLS":"COMPONENT~CONTRACT_REF_NO~FUNDING_PARTICIPANT~RISK_AMOUNT~RISK_COMPENSATION_RATE~RISK_PARTICIPANT~STATUS~FUNDING_PART_UI~RISK_PART_UI~EVENT_SEQ_NO~SSI_MNEMONIC~VALUE_DATE~DD_CURRENCY~TRANSACTION_DATE"};

var multipleEntryPageSize = {"BLK_MARGIN_INT" :"15" ,"BLK_CONTRACT_RISK_PART_DTLS" :"15" };

var multipleEntrySVBlocks = "BLK_LFTBS_CONTRACT_INTEREST~BLK_RTFX";

var tabMEBlks = {"CVS_INTEREST__TAB_MARGIN":"BLK_MARGIN_INT","CVS_RISK_PARTICIPANT__TAB_MAIN":"BLK_CONTRACT_RISK_PART_DTLS"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_MASTER_INT">CONTRACTREFNO~MODULE~PRDCD~LATEVNSEQNO~PRODUCTDESC~COUNTERPARTY~AGENCY_CONTRACT~MATURITY_DATE~AMOUNT~VALUE_DATE~TENOR_BASED_SPREAD~CONTRACT_CCY~TXTMAINFUNCTION~ONCE_AUTH</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER_INT" RELATION_TYPE="N" TYPE="BLK_LFTBS_CONTRACT_INTEREST">AMORTIZATIONCONSTCOMPONENT~NETRATEDESC~RATESIGN~NETACCRUALDESC~SPECIALRATETYPE~TOTALAMTLIQUIDATEDDESC~COMPONENT~EVENTDESC~CONTRACTREFERENCENO~EVENT~INTERESTBASIS~RATE~BORROWLENDINDDESC~SPREAD~RATETYPE~LIQUIDITYPREMIUMTYPE~LIQUIDITYPREMIUM~MARGIN~PENALTYTENOR~SPECIALPENALTYCOMPONENTDESC~RATECALCTYPE~BORROWLENDIND~MAINCOMPONENT~RESETTENOR~WAIVER~ACQUIREDAMOUNT~CURRENCY~AMOUNT~PREPAYMENTPENALTYRATECODE~FIXEDRATECODE~FIXEDRATETYPE~DOMICILECCY~FLOATINGRATE~LIQUIDITYPREMIUMCOMPONENT~RATECODEUSAGE~RATEREVISIONMETHOD~MINRATE~MAXRATE~ACCRUALREQD~STATUS~RATECODE~PICKUPEVENTSEQNO~EVENTSEQNO~CHANGEDURINGAMENDMENT~TRANSACTIONDATE~VALUEDATE~SHOWNINCONTRACTMAINSCREEN~PENALTYTYPE~ADJUSTMENTRATE~DISCACCRAPPLICABLE~CUSTMARGIN~ACCRUALCCY~INTPERIODBASIS~CCYROUNDUNIT~CCYDECIMALS~CCYROUNDRULE~NOINTONPREMATUREWITHDRAWL~REAPPLYINTONOUTSTANDAMT~REAPPLYINTONPREPAIDAMT~REPLICATE~RETAINMAINCOMPPROP~BILLINGNOTICEDAYS~BILLINGNOTICEREQD~INTCOMPUTATION~PENALTYSTARTDATEBASIS~MAXRATESIGN~MINRATESIGN~TENORAMTSPREAD~TENORWISESPREAD~AMOUNTWISESPREAD~TILLDATEACCDESC~HOLCOMPOUND~NEGATIVE_INTEREST_RATE_ALLOWED~RATEFIXINGREQD~RATEFIXINGDAYS~RATEUI~TXTCONTAMT~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~COMPTYPEIN~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_SPREAD_ADJ_COMP_METH~SPREAD_ADJ~RFR_RATE_COMPOUNDING~RFR_RATE_TYPE~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~OBSERVATION_SHIFT~RISK_COMPONENT</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTRACT_INTEREST" RELATION_TYPE="N" TYPE="BLK_MARGIN_INT">CONTRACT_REF_NO~COMPONENT~MARGIN_COMPONENT~VALUE_DATE~EVENT_SEQ_NO~MARGIN_RATE~UI_MARGIN_DESC~UI_MARGIN_BASIS~UI_BASIS_AMT_TAG</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTRACT_INTEREST" RELATION_TYPE="1" TYPE="BLK_RATE_SETTING">CONTRACT_REF_NO~COMPONENT~SPLIT_SERIAL_NO~SPLIT_NUMBER~EVENT_SEQ_NO~ROUNDING_RULE~ROUNDING_UNIT~TENOR~TXTROLLPRD~TXTCCY~TXTPRINCIPALROLLAMT~TXTINTROLLAMT~TXTTOTALROLLAMT~TXTMATURITYDATE~TXTINTRATEFIXINGDATE~TXTDRIVERCONTRACT</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTRACT_INTEREST" RELATION_TYPE="N" TYPE="BLK_RTFX">RTFX_COMP~RTFX_COMPDESC~RTFX_CCY~RTFX_CCYDESC~RTFX_RTCD~RTFX_TNRVAL~RTFX_ACTFIXDT~RTFX_NXTRTFIXDT~RTFX_STDT~RTFX_NXTFIXNOTICEDT~RTFX_ENDDT~RTFX_NXTSTDT~RTFX_RATE~RTFX_REMARKS~RTFX_TNRTYPE~RTFX_ESN~RTFX_TNRUNIT~RTFX_FIXESN~RTFX_AMDESN~RTFX_FIXSTAT~RTFX_FIXTIME~RTFX_FIXDT~RTFX_FIXNOTICE~RTFX_INOTGEN~RTFX_FCCREF</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTRACT_INTEREST" RELATION_TYPE="N" TYPE="BLK_CONTRACT_RISK_PART_DTLS">COMPONENT~CONTRACT_REF_NO~FUNDING_PARTICIPANT~RISK_AMOUNT~RISK_COMPENSATION_RATE~RISK_PARTICIPANT~STATUS~FUNDING_PART_UI~RISK_PART_UI~EVENT_SEQ_NO~SSI_MNEMONIC~VALUE_DATE~DD_CURRENCY~TRANSACTION_DATE</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_INTEREST";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_MASTER_INT" : "","BLK_LFTBS_CONTRACT_INTEREST" : "BLK_MASTER_INT~N","BLK_MARGIN_INT" : "BLK_LFTBS_CONTRACT_INTEREST~N","BLK_RATE_SETTING" : "BLK_LFTBS_CONTRACT_INTEREST~1","BLK_RTFX" : "BLK_LFTBS_CONTRACT_INTEREST~N","BLK_CONTRACT_RISK_PART_DTLS" : "BLK_LFTBS_CONTRACT_INTEREST~N"}; 

 var dataSrcLocationArray = new Array("BLK_MASTER_INT","BLK_LFTBS_CONTRACT_INTEREST","BLK_MARGIN_INT","BLK_RATE_SETTING","BLK_RTFX","BLK_CONTRACT_RISK_PART_DTLS"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBCINTRS.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBCINTRS.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_MASTER_INT__CONTRACTREFNO";
pkFields[0] = "BLK_MASTER_INT__CONTRACTREFNO";
queryFields[1] = "BLK_MASTER_INT__MODULE";
pkFields[1] = "BLK_MASTER_INT__MODULE";
queryFields[2] = "BLK_MASTER_INT__LATEVNSEQNO";
pkFields[2] = "BLK_MASTER_INT__LATEVNSEQNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_CONTRACT_RISK_PART_DTLS":["COMPONENT","CONTRACT_REF_NO","FUNDING_PARTICIPANT","RISK_AMOUNT","RISK_COMPENSATION_RATE","RISK_PARTICIPANT","STATUS"],"BLK_LFTBS_CONTRACT_INTEREST":["ACCRUALCCY","ACCRUALREQD","ACQUIREDAMOUNT","ADJUSTMENTRATE","AMORTIZATIONCONSTCOMPONENT","AMOUNT","AMOUNTWISESPREAD","BILLINGNOTICEDAYS","BILLINGNOTICEREQD","BORROWLENDIND","CCYDECIMALS","CCYROUNDRULE","CCYROUNDUNIT","CHANGEDURINGAMENDMENT","CONTRACTREFERENCENO","CURRENCY","CUSTMARGIN","DISCACCRAPPLICABLE","DOMICILECCY","EVENTDESC","FIXEDRATECODE","FIXEDRATETYPE","FLOATINGRATE","HOLCOMPOUND","INTCOMPUTATION","INTERESTBASIS","INTPERIODBASIS","LIQUIDITYPREMIUM","LIQUIDITYPREMIUMCOMPONENT","LIQUIDITYPREMIUMTYPE","MAINCOMPONENT","MARGIN","MAXRATE","MAXRATESIGN","MINRATE","MINRATESIGN","NETACCRUALDESC","NETRATEDESC","NOINTONPREMATUREWITHDRAWL","OBSERVATION_SHIFT","PENALTYSTARTDATEBASIS","PENALTYTYPE","PREPAYMENTPENALTYRATECODE","RATE","RATECALCTYPE","RATECODE","RATECODEUSAGE","RATEFIXINGDAYS","RATEFIXINGREQD","RATEREVISIONMETHOD","RATESIGN","RATETYPE","RATEUI","RATE_ROUNDING_POSITION","RATE_ROUNDING_RULE","RATE_ROUNDING_UNIT","REAPPLYINTONOUTSTANDAMT","REAPPLYINTONPREPAIDAMT","REPLICATE","RESETTENOR","RETAINMAINCOMPPROP","RFR_BASE_COMP_METH","RFR_COMPONENT","RFR_INTERESTROLLOVER_METHOD","RFR_LASTRECENT_METHOD","RFR_LASTRESET_METHOD","RFR_LOCKOUT_METHOD","RFR_LOCKOUT_METHOD_DAYS","RFR_LOOKBACK_METHOD","RFR_LOOKBACK_METHOD_DAYS","RFR_MARG_COMP_METH","RFR_PAYMENTDELAY_METHOD","RFR_PLAIN_METHOD","RFR_PRINCIPALADJUSTMENT_METHOD","RFR_RATE_COMP_ROUND_UNIT","RFR_SPREAD_ADJ_COMP_METH","SHOWNINCONTRACTMAINSCREEN","SPECIALRATETYPE","SPREAD","SPREAD_ADJ","STATUS","TENORAMTSPREAD","TENORWISESPREAD","TOTALAMTLIQUIDATEDDESC","TRANSACTIONDATEI","VALUEDATEI","WAIVER"],"BLK_MARGIN_INT":["MARGIN_RATE"],"BLK_RATE_SETTING":["ROUNDING_RULE","ROUNDING_UNIT","TENOR"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_LFTBS_CONTRACT_INTEREST__PREPAYMENTPENALTYRATECODE__LOV_PREPAYMENT_PENALTY":["BLK_LFTBS_CONTRACT_INTEREST__PREPAYMENTPENALTYRATECODE~~","","N~N",""],"BLK_LFTBS_CONTRACT_INTEREST__FIXEDRATECODE__LOV_RATE_CODE":["BLK_LFTBS_CONTRACT_INTEREST__FIXEDRATECODE~~","BLK_LFTBS_CONTRACT_INTEREST__FIXEDRATETYPE!varchar2~BLK_LFTBS_CONTRACT_INTEREST__CURRENCY!varchar2~BLK_LFTBS_CONTRACT_INTEREST__RATETYPE!varchar2~BLK_LFTBS_CONTRACT_INTEREST__FIXEDRATETYPE!varchar2~BLK_MASTER_INT__CONTRACTREFNO!varchar2","N~N",""],"BLK_LFTBS_CONTRACT_INTEREST__RATECODE__LOV_FLT_RATE_CODE":["BLK_LFTBS_CONTRACT_INTEREST__RATECODE~~","BLK_LFTBS_CONTRACT_INTEREST__RFR_RATE_TYPE!VARCHAR2","N~N",""],"BLK_RTFX__RTFX_RTCD__LOV_RATE_CODE":["BLK_RTFX__RTFX_RTCD~~","BLK_RTFX__RTFX_CCY!VARCHAR2","N~N",""],"BLK_CONTRACT_RISK_PART_DTLS__FUNDING_PARTICIPANT__LOV_PARAT":["BLK_CONTRACT_RISK_PART_DTLS__FUNDING_PARTICIPANT~BLK_CONTRACT_RISK_PART_DTLS__FUNDING_PART_UI~","","N~N",""],"BLK_CONTRACT_RISK_PART_DTLS__RISK_PARTICIPANT__LOV_PARAT":["BLK_CONTRACT_RISK_PART_DTLS__RISK_PARTICIPANT~BLK_CONTRACT_RISK_PART_DTLS__RISK_PART_UI~","","N~N",""],"BLK_CONTRACT_RISK_PART_DTLS__SSI_MNEMONIC__LOV_SSI":["~~~~~~~BLK_CONTRACT_RISK_PART_DTLS__SSI_MNEMONIC~~~~~~~~~~","BLK_CONTRACT_RISK_PART_DTLS__RISK_PARTICIPANT!VARCHAR2~BLK_CONTRACT_RISK_PART_DTLS__DD_CURRENCY!VARCHAR2","N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_MARGIN_INT","BLK_CONTRACT_RISK_PART_DTLS");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array(); 

 var CallFormRelat=new Array(); 

 var CallRelatType= new Array(); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBCINTRS"]="KERNEL";
ArrPrntFunc["LBCINTRS"]="";
ArrPrntOrigin["LBCINTRS"]="";
ArrRoutingType["LBCINTRS"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBCINTRS"]="N";
ArrCustomModified["LBCINTRS"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_INTEREST":"CONTRACTREFNO~MODULE~EVENTSEQNO"};
var scrArgSource = {};
var scrArgVals = {"CVS_INTEREST":"~~"};
var scrArgDest = {"CVS_INTEREST":"BLK_MASTER_INT__CONTRACTREFNO~BLK_MASTER_INT__MODULE~BLK_MASTER_INT__LATEVNSEQNO"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {};
var dpndntOnSrvs = {};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------