/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDCOROL_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_MASTER":"CONFREFNO~USEREFNO~LATESTEVNTSEQ~COUNTERPARTY~CONTRACTCCY~PRODUCTCODE~CUSTREFNO~CONTRACTSTAT~AUTHSTAT~PRODTYPE~MODULECODE~CURREVENTCODE~LATESTVERSIONO~TXT_CONREF_LBCINTSH~TXT_CONCCY_LBCINTSH~TXT_PRODCODE_LBCINTSH~TXT_PRODTYPE_LBCINTSH~TXT_BORRREFNO_LBCINTSH~TXT_USERREFNO_LBCINTSH~TXT_BORRAMTDUE_LBCINTSH~TXT_CUSTNO_LBCINTSH~TXT_CUSTDESC_LBCINTSH~TXT_FAC_LBCINTSH~UI_TOTAL_INTSH~TXT_BORRAMTPAID_LBCINTSH~TXT_PRODDESC_LBCINTSH~TXT_CONREF_LBCROIFX~TXT_MODCODE_LBCROIFX~TXT_PRODCODE_LBCROIFX~TXT_PRODTYP_LBCROIFX~TXT_BRANCH_LBCROIFX~TXT_USERREFNO_LBCROIFX~TXT_COUNPARTY_LBCROIFX~TXT_FAC_NAME_LBCROIFX~TXT_CCY_LBCROIFX~TXTPRO_LBCEXRFX~TXTPRODES_LBCEXRFX~TXTUSERREF_LBCEXRFX~TXTCUST_LBCEXRFX~TXTCUSTNAME_LBCEXRFX~TXTFACNAME_LBCEXRFX~TXTCONREF_LBCEXRFX~TXTLTEVNTSEQ_LBCEXRFX~TXT_UI_CURRENCY","BLK_CONSOL_MASTER":"CONTREFNO~TRANCHEREFNO~VALUEDATE~INTRATEFIXINGDATE~EXCHANGERATE~CONSOLIDATIONTYPE~ROLLOVERAMTYPE~REFERENCERATE~LIQDINTPREPAYMENT~ROLLOVERTYPE~SETTLEMENTBASIS~SCHEDULEBASIS~MISBASIS~COUNTERPARYT~USDBASIS~HOLIDAYPARBASIS~INTPARMBASIS~MAKERDTDTAMP~MAKERID~CHECKERID~MATURITYDATE~CHECKERDTSTAMP~REFORDSTAT~AUTHSTAT~ONCEAUTH~CONTCURRENCY~MODNO~MATURITYTPE~PRODCODE~ROLLOVERSTAT~ROLLBY~MATURITYDAYS~DEFAULTFRONTING~ROLLOVERNETMETHOD~USEREFNO~ROLLOVERCONTREFNO~TXT_CONTRACT_ST~ECAREQSTATUS","BLK_CONSOL_DETAIL":"PARTICIPANTREFNO~CONFREFNO~PRICROLLAMOUNT~INTROLLAMOUNT~ROLLOVERAMOUNT~PIKROLLAMOUNT~DRIVERCONTRACT~LIQPRINCIPLE~LIQINTEREST~CASHINTAMOUNT","BLK_ROLL_RATES":"VERSIONO~CONFREFNO~COMPONENT~SPLITNO~RATETYPE~EVNTSEQNO~FIXEDRATEYPE~FIXEDRATECODE~SPREAD~RATE~FLOATRATECODE~INTPERBASIS~INTBASIS~CCYROUNDUNITS~DECIMALS~AMOUNT~CCYROUND~TXTRATEFIXINGREQD~RATEFIXINGDAYS~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~SPREAD_ADJ~SPLIT_RATEREVISIONMETHOD~RATEFIXINGREQDNORM~BORROW_LEND_IND~RATE_CODE_USAGE~RESET_TENOR","BLK_ROLL_MARGIN":"SPLITNO~VERSIONO~CONFREFNO~COMPONENT~MARGINCOMP~MARGINBASIS~BASISAMTAG~MARGINRATE","BLK_SPLIT_ROLL":"CONFREFNO~VERSIONO~SPLITNO~ROLLOVERPROD~LIQINTPREPAY~ROLLAMOUNT~PRINCIROLLAMT~INTROLLAMT~PIKROLLAMT~MATURITYDATE~MATURITYDAYS~ROLLBY~ROLLCONFREFNO~CONSIDERSPLIT~ROLL_BY","BLK_CONSOL_INT_RATE":"CONFREFNO~VERSIONNO~COMPONENT~SPLITNO~EVNTSEQNO~RATETYPE~FIXEDRATETYPE~FIXEDRATECODE~FLOATRATECODE~SPREAD~RATE~INTBASIS~INTPERIODBASIS~CCYROUNDUNIT~DECIMALS~ROUNDRULE~AMOUNT~TXTRATEFIXINGREQD~RATEFIXINGDAYS~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~SPREAD_ADJ~COROL_RATEREVISIONMETHOD~RATEFIXINGREQD~BORROW_LEND_IND~RATE_CODE_USAGE~RESET_TENOR","BLK_CONSOL_MARGIN":"CONFREFNO~VERSIONO~SPLITNO~COMPONENT~MARGINCOMP~MARGINBASIS~BASISAMTAG~MARGINRATE","BLK_PROCESS_EXCEPTION":"PROCESSID~REFNO~DATESTAMP~COUNTERPARTY~ERRORPARAM~EXCEPLOG~ERRCODE~TXT_ERR_DESC","BLK_BORR_LINKAGE":"CONFREFNO~COUNTERPARYT~BORROWECONF","BLK_CONTRACT_EVENT_LOG":"CONREF~MAKERID~MKRDTSTMP~CHECKERID~CHKDTST~EVENTSEQNO~TXNSTAT~AUTHSTAT","BLK_LBTBS_PARTICIPANT_SHARE_AMT":"EVENT_SEQ_NO~CONSOL_REF_NO~AMOUNT_PAID~TOTAL_OUTSTANDING~BORROWER_REF_NO~COMPONENT~VALUE_DATE~EVENT_CODE~PARTICIPANT_REF_NO~PARTICIPANT~PROCESS_STAT","BLK_INTRATE_FIX":"RATE_EFFECTIVE_START_DATE~TENOR_VALUE~CONTRACT_REF_NO~RATE_EFFECTIVE_END_DATE~RATE~RATE_CODE~SPLIT_NO~REMARKS~COMPONENT~TENOR_UNIT~UI_COMP_DESC~UI_CCY~UI_CCY_DESC~UI_RATE_CODE_DESC","BLK_RATE_SETTING":"CONTRACT_REF_NO~COMPONENT~SPLIT_SERIAL_NO~SPLIT_NUMBER~EVENT_SEQ_NO~ROUNDING_RULE~ROUNDING_UNIT~TENOR~TXTPRD~TXTPRDDESC~TXTUSERREF~TXTCOUNTERPARTY~TXTCUSTNAME~TXTFACILITYNAME~TXTPRDTYPE~TXTROLLPRD~TXTPRINCIPALROLLAMT~TXTINTROLLAMT~TXTTOTALROLLAMT~TXTMATURITYDATE~TXTINTRATEFIXINGDATE~TXTDRIVERCONTRACT","BLK_EXRATE_FIXING_DETAILS":"CONTREFNO~EXCHANGERATE~REMARKS~EXRATEEFFESTARTDATE~EVENTSEQNO~EXRATEEFFENDDATE~EXRATEFIXINGDATE~CONTRACTCCY~TRANCHECCY~EXRATEFIXNOTIFICATIONDATE~NEXTEFFECTIVESTARTDATE~TXTREVALRATECODE~TXTREVALRATETYPE~TXTCONTRACTAMT~TXTTRANCHEEQVAMT","BLK_LFTBS_CONT_ADDL_INT_DTL":"COMPONENT~CONTRACT_REF_NO~OBSERVATION_SHIFT~PRODUCT_CODE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_METHOD~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_RATE_COMPOUNDING~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~RFR_RATE_TYPE~RFR_SPREAD_ADJ_COMP_METH~SERIAL_NO~SPLIT_SERIAL_NO~VERSION_NO","BLK_LFTBS_CONT_ADDL_INT_DTL_S":"COMPONENT~CONTRACT_REF_NO~OBSERVATION_SHIFT~PRODUCT_CODE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_METHOD~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_RATE_COMPOUNDING~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~RFR_RATE_TYPE~RFR_SPREAD_ADJ_COMP_METH~SERIAL_NO~SPLIT_SERIAL_NO~VERSION_NO"};

var multipleEntryPageSize = {"BLK_CONSOL_DETAIL" :"15" ,"BLK_ROLL_MARGIN" :"15" ,"BLK_SPLIT_ROLL" :"15" ,"BLK_CONSOL_MARGIN" :"15" ,"BLK_PROCESS_EXCEPTION" :"15" ,"BLK_BORR_LINKAGE" :"15" ,"BLK_LBTBS_PARTICIPANT_SHARE_AMT" :"15" };

var multipleEntrySVBlocks = "BLK_ROLL_RATES~BLK_CONSOL_INT_RATE~BLK_SPLIT_ROLL~BLK_LFTBS_CONT_ADDL_INT_DTL~BLK_LFTBS_CONT_ADDL_INT_DTL_S";

var tabMEBlks = {"CVS_MAIN__TAB_MAIN":"BLK_CONSOL_DETAIL","CVS_MAIN__TAB_NORMAL":"BLK_ROLL_MARGIN","CVS_MAIN__TAB_SPLIT":"BLK_SPLIT_ROLL","CVS_INT_DTLS_S__TAB_MAIN":"BLK_CONSOL_MARGIN","CVS_EXCEPTON__TAB_MAIN":"BLK_PROCESS_EXCEPTION","CVS_PART_BORR__TAB_MAIN":"BLK_BORR_LINKAGE","CVS_PART_SHARE__TAB_MAIN":"BLK_LBTBS_PARTICIPANT_SHARE_AMT"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_MASTER">CONFREFNO~USEREFNO~LATESTEVNTSEQ~COUNTERPARTY~CONTRACTCCY~PRODUCTCODE~CUSTREFNO~CONTRACTSTAT~AUTHSTAT~PRODTYPE~MODULECODE~CURREVENTCODE~LATESTVERSIONO~TXT_CONREF_LBCINTSH~TXT_CONCCY_LBCINTSH~TXT_PRODCODE_LBCINTSH~TXT_PRODTYPE_LBCINTSH~TXT_BORRREFNO_LBCINTSH~TXT_USERREFNO_LBCINTSH~TXT_BORRAMTDUE_LBCINTSH~TXT_CUSTNO_LBCINTSH~TXT_CUSTDESC_LBCINTSH~TXT_FAC_LBCINTSH~UI_TOTAL_INTSH~TXT_BORRAMTPAID_LBCINTSH~TXT_PRODDESC_LBCINTSH~TXT_CONREF_LBCROIFX~TXT_MODCODE_LBCROIFX~TXT_PRODCODE_LBCROIFX~TXT_PRODTYP_LBCROIFX~TXT_BRANCH_LBCROIFX~TXT_USERREFNO_LBCROIFX~TXT_COUNPARTY_LBCROIFX~TXT_FAC_NAME_LBCROIFX~TXT_CCY_LBCROIFX~TXTPRO_LBCEXRFX~TXTPRODES_LBCEXRFX~TXTUSERREF_LBCEXRFX~TXTCUST_LBCEXRFX~TXTCUSTNAME_LBCEXRFX~TXTFACNAME_LBCEXRFX~TXTCONREF_LBCEXRFX~TXTLTEVNTSEQ_LBCEXRFX~TXT_UI_CURRENCY</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="1" TYPE="BLK_CONSOL_MASTER">CONTREFNO~TRANCHEREFNO~VALUEDATE~INTRATEFIXINGDATE~EXCHANGERATE~CONSOLIDATIONTYPE~ROLLOVERAMTYPE~REFERENCERATE~LIQDINTPREPAYMENT~ROLLOVERTYPE~SETTLEMENTBASIS~SCHEDULEBASIS~MISBASIS~COUNTERPARYT~USDBASIS~HOLIDAYPARBASIS~INTPARMBASIS~MAKERDTDTAMP~MAKERID~CHECKERID~MATURITYDATE~CHECKERDTSTAMP~REFORDSTAT~AUTHSTAT~ONCEAUTH~CONTCURRENCY~MODNO~MATURITYTPE~PRODCODE~ROLLOVERSTAT~ROLLBY~MATURITYDAYS~DEFAULTFRONTING~ROLLOVERNETMETHOD~USEREFNO~ROLLOVERCONTREFNO~TXT_CONTRACT_ST~ECAREQSTATUS</FN>'; 
msgxml += '      <FN PARENT="BLK_CONSOL_MASTER" RELATION_TYPE="N" TYPE="BLK_CONSOL_DETAIL">PARTICIPANTREFNO~CONFREFNO~PRICROLLAMOUNT~INTROLLAMOUNT~ROLLOVERAMOUNT~PIKROLLAMOUNT~DRIVERCONTRACT~LIQPRINCIPLE~LIQINTEREST~CASHINTAMOUNT</FN>'; 
msgxml += '      <FN PARENT="BLK_CONSOL_MASTER" RELATION_TYPE="N" TYPE="BLK_ROLL_RATES">VERSIONO~CONFREFNO~COMPONENT~SPLITNO~RATETYPE~EVNTSEQNO~FIXEDRATEYPE~FIXEDRATECODE~SPREAD~RATE~FLOATRATECODE~INTPERBASIS~INTBASIS~CCYROUNDUNITS~DECIMALS~AMOUNT~CCYROUND~TXTRATEFIXINGREQD~RATEFIXINGDAYS~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~SPREAD_ADJ~SPLIT_RATEREVISIONMETHOD~RATEFIXINGREQDNORM~BORROW_LEND_IND~RATE_CODE_USAGE~RESET_TENOR</FN>'; 
msgxml += '      <FN PARENT="BLK_ROLL_RATES" RELATION_TYPE="N" TYPE="BLK_ROLL_MARGIN">SPLITNO~VERSIONO~CONFREFNO~COMPONENT~MARGINCOMP~MARGINBASIS~BASISAMTAG~MARGINRATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONSOL_MASTER" RELATION_TYPE="N" TYPE="BLK_SPLIT_ROLL">CONFREFNO~VERSIONO~SPLITNO~ROLLOVERPROD~LIQINTPREPAY~ROLLAMOUNT~PRINCIROLLAMT~INTROLLAMT~PIKROLLAMT~MATURITYDATE~MATURITYDAYS~ROLLBY~ROLLCONFREFNO~CONSIDERSPLIT~ROLL_BY</FN>'; 
msgxml += '      <FN PARENT="BLK_SPLIT_ROLL" RELATION_TYPE="N" TYPE="BLK_CONSOL_INT_RATE">CONFREFNO~VERSIONNO~COMPONENT~SPLITNO~EVNTSEQNO~RATETYPE~FIXEDRATETYPE~FIXEDRATECODE~FLOATRATECODE~SPREAD~RATE~INTBASIS~INTPERIODBASIS~CCYROUNDUNIT~DECIMALS~ROUNDRULE~AMOUNT~TXTRATEFIXINGREQD~RATEFIXINGDAYS~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~SPREAD_ADJ~COROL_RATEREVISIONMETHOD~RATEFIXINGREQD~BORROW_LEND_IND~RATE_CODE_USAGE~RESET_TENOR</FN>'; 
msgxml += '      <FN PARENT="BLK_CONSOL_INT_RATE" RELATION_TYPE="N" TYPE="BLK_CONSOL_MARGIN">CONFREFNO~VERSIONO~SPLITNO~COMPONENT~MARGINCOMP~MARGINBASIS~BASISAMTAG~MARGINRATE</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="N" TYPE="BLK_PROCESS_EXCEPTION">PROCESSID~REFNO~DATESTAMP~COUNTERPARTY~ERRORPARAM~EXCEPLOG~ERRCODE~TXT_ERR_DESC</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="N" TYPE="BLK_BORR_LINKAGE">CONFREFNO~COUNTERPARYT~BORROWECONF</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="1" TYPE="BLK_CONTRACT_EVENT_LOG">CONREF~MAKERID~MKRDTSTMP~CHECKERID~CHKDTST~EVENTSEQNO~TXNSTAT~AUTHSTAT</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTBS_PARTICIPANT_SHARE_AMT">EVENT_SEQ_NO~CONSOL_REF_NO~AMOUNT_PAID~TOTAL_OUTSTANDING~BORROWER_REF_NO~COMPONENT~VALUE_DATE~EVENT_CODE~PARTICIPANT_REF_NO~PARTICIPANT~PROCESS_STAT</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="1" TYPE="BLK_INTRATE_FIX">RATE_EFFECTIVE_START_DATE~TENOR_VALUE~CONTRACT_REF_NO~RATE_EFFECTIVE_END_DATE~RATE~RATE_CODE~SPLIT_NO~REMARKS~COMPONENT~TENOR_UNIT~UI_COMP_DESC~UI_CCY~UI_CCY_DESC~UI_RATE_CODE_DESC</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="1" TYPE="BLK_RATE_SETTING">CONTRACT_REF_NO~COMPONENT~SPLIT_SERIAL_NO~SPLIT_NUMBER~EVENT_SEQ_NO~ROUNDING_RULE~ROUNDING_UNIT~TENOR~TXTPRD~TXTPRDDESC~TXTUSERREF~TXTCOUNTERPARTY~TXTCUSTNAME~TXTFACILITYNAME~TXTPRDTYPE~TXTROLLPRD~TXTPRINCIPALROLLAMT~TXTINTROLLAMT~TXTTOTALROLLAMT~TXTMATURITYDATE~TXTINTRATEFIXINGDATE~TXTDRIVERCONTRACT</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER" RELATION_TYPE="1" TYPE="BLK_EXRATE_FIXING_DETAILS">CONTREFNO~EXCHANGERATE~REMARKS~EXRATEEFFESTARTDATE~EVENTSEQNO~EXRATEEFFENDDATE~EXRATEFIXINGDATE~CONTRACTCCY~TRANCHECCY~EXRATEFIXNOTIFICATIONDATE~NEXTEFFECTIVESTARTDATE~TXTREVALRATECODE~TXTREVALRATETYPE~TXTCONTRACTAMT~TXTTRANCHEEQVAMT</FN>'; 
msgxml += '      <FN PARENT="BLK_ROLL_RATES" RELATION_TYPE="1" TYPE="BLK_LFTBS_CONT_ADDL_INT_DTL">COMPONENT~CONTRACT_REF_NO~OBSERVATION_SHIFT~PRODUCT_CODE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_METHOD~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_RATE_COMPOUNDING~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~RFR_RATE_TYPE~RFR_SPREAD_ADJ_COMP_METH~SERIAL_NO~SPLIT_SERIAL_NO~VERSION_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_CONSOL_INT_RATE" RELATION_TYPE="1" TYPE="BLK_LFTBS_CONT_ADDL_INT_DTL_S">COMPONENT~CONTRACT_REF_NO~OBSERVATION_SHIFT~PRODUCT_CODE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_METHOD~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_RATE_COMPOUNDING~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~RFR_RATE_TYPE~RFR_SPREAD_ADJ_COMP_METH~SERIAL_NO~SPLIT_SERIAL_NO~VERSION_NO</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_MASTER">CONFREFNO~CONTRACTCCY~AUTHSTAT~CONTRACTSTAT</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDCOROL";
var defaultWhereClause = "CONTRACT_REF_NO IN (select contract_ref_no from LBTB_CONTRACT_CONSOL_MASTER) and exists (Select 1 From OLVW_USER_ACCESS_PRODUCTS Where PRODUCT_CODE = sypks_utils.get_product(CONTRACT_REF_NO) AND USER_ID = global.user_id)";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_MASTER";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_MASTER" : "","BLK_CONSOL_MASTER" : "BLK_MASTER~1","BLK_CONSOL_DETAIL" : "BLK_CONSOL_MASTER~N","BLK_ROLL_RATES" : "BLK_CONSOL_MASTER~N","BLK_ROLL_MARGIN" : "BLK_ROLL_RATES~N","BLK_SPLIT_ROLL" : "BLK_CONSOL_MASTER~N","BLK_CONSOL_INT_RATE" : "BLK_SPLIT_ROLL~N","BLK_CONSOL_MARGIN" : "BLK_CONSOL_INT_RATE~N","BLK_PROCESS_EXCEPTION" : "BLK_MASTER~N","BLK_BORR_LINKAGE" : "BLK_MASTER~N","BLK_CONTRACT_EVENT_LOG" : "BLK_MASTER~1","BLK_LBTBS_PARTICIPANT_SHARE_AMT" : "BLK_MASTER~N","BLK_INTRATE_FIX" : "BLK_MASTER~1","BLK_RATE_SETTING" : "BLK_MASTER~1","BLK_EXRATE_FIXING_DETAILS" : "BLK_MASTER~1","BLK_LFTBS_CONT_ADDL_INT_DTL" : "BLK_ROLL_RATES~1","BLK_LFTBS_CONT_ADDL_INT_DTL_S" : "BLK_CONSOL_INT_RATE~1"}; 

 var dataSrcLocationArray = new Array("BLK_MASTER","BLK_CONSOL_MASTER","BLK_CONSOL_DETAIL","BLK_ROLL_RATES","BLK_ROLL_MARGIN","BLK_SPLIT_ROLL","BLK_CONSOL_INT_RATE","BLK_CONSOL_MARGIN","BLK_PROCESS_EXCEPTION","BLK_BORR_LINKAGE","BLK_CONTRACT_EVENT_LOG","BLK_LBTBS_PARTICIPANT_SHARE_AMT","BLK_INTRATE_FIX","BLK_RATE_SETTING","BLK_EXRATE_FIXING_DETAILS","BLK_LFTBS_CONT_ADDL_INT_DTL","BLK_LFTBS_CONT_ADDL_INT_DTL_S"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDCOROL.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDCOROL.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_MASTER__CONFREFNO";
pkFields[0] = "BLK_MASTER__CONFREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_LBTBS_PARTICIPANT_SHARE_AMT":["AMOUNT_PAID"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_MASTER__COUNTERPARTY__LOV_CUSTOMERS_ALLOWED":["BLK_MASTER__COUNTERPARTY~~","BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2","N~N",""],"BLK_MASTER__CONTRACTCCY__LOV_CURRENCY_ALLOWED":["BLK_MASTER__CONTRACTCCY~~","BLK_CONSOL_MASTER__TRANCHEREFNO!~BLK_CONSOL_MASTER__TRANCHEREFNO!~BLK_CONSOL_MASTER__TRANCHEREFNO!","N~N",""],"BLK_MASTER__PRODUCTCODE__LOV_PROD_ALLOWED":["BLK_MASTER__PRODUCTCODE~~","BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_MASTER__COUNTERPARTY!VARCHAR2","N~N",""],"BLK_CONSOL_MASTER__TRANCHEREFNO__LOV_TRANCHE_REF":["BLK_CONSOL_MASTER__TRANCHEREFNO~~~~~~","","N~N~N~N~N~N",""],"BLK_CONSOL_MASTER__CONTCURRENCY__LOV_CURRENCY_ALLOWED":["~~","__!~__!","N~N",""],"BLK_CONSOL_DETAIL__PARTICIPANTREFNO__LOV_DRAWNCONF":["BLK_CONSOL_DETAIL__PARTICIPANTREFNO~~~BLK_CONSOL_DETAIL__PRICROLLAMOUNT~","BLK_MASTER__PRODUCTCODE!VARCHAR2~BLK_MASTER__COUNTERPARTY!VARCHAR2~BLK_MASTER__CONTRACTCCY!VARCHAR2~BLK_CONSOL_MASTER__VALUEDATE!DATE~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2","N~N~N~N",""],"BLK_ROLL_RATES__FIXEDRATECODE__LOV_FX_RATE_CODE":["BLK_ROLL_RATES__FIXEDRATECODE~~","","N~N",""],"BLK_ROLL_RATES__FLOATRATECODE__LOV_FL_RATE_CODE":["BLK_ROLL_RATES__FLOATRATECODE~~","BLK_LFTB_CONT_ADDL_INT_DTL_N__RFR_RATE_TYPE!VARCHAR2","N~N",""],"BLK_SPLIT_ROLL__ROLLOVERPROD__LOV_ROLL_PROD":["BLK_SPLIT_ROLL__ROLLOVERPROD~~","BLK_CONSOL_MASTER__TRANCHEREFNO!~BLK_CONSOL_MASTER__TRANCHEREFNO!~BLK_CONSOL_MASTER__TRANCHEREFNO!~BLK_CONSOL_MASTER__TRANCHEREFNO!~BLK_MASTER__COUNTERPARTY!","N~N",""],"BLK_CONSOL_INT_RATE__FIXEDRATECODE__LOV_FX_RATE_CODE":["BLK_CONSOL_INT_RATE__FIXEDRATECODE~~","","N~N",""],"BLK_CONSOL_INT_RATE__FLOATRATECODE__LOV_FL_RATE_CODE":["BLK_CONSOL_INT_RATE__FLOATRATECODE~~","BLK_LFTB_CONT_ADDL_INT_DTL_S__RFR_RATE_TYPE!VARCHAR2","N~N",""],"BLK_INTRATE_FIX__TENOR_VALUE__LOV_FREQ_LBCROIFX":["~~BLK_INTRATE_FIX__TENOR_UNIT~~","__!~__!","N~N~N~N",""],"BLK_INTRATE_FIX__RATE_CODE__LOV_RATE_LBCROIFX":["BLK_INTRATE_FIX__RATE_CODE~BLK_INTRATE_FIX__UI_RATE_CODE_DESC~","BLK_MASTER__CONTRACTCCY!VARCHAR2","N~N",""],"BLK_ROLLOVER__COUNTERPARTY__LOV_CUSTOMERS_ALLOWED":["BLK_ROLLOVER__COUNTERPARTY~~","BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2","N~N",""],"BLK_ROLLOVER__PRODUCT_CODE__LOV_PROD_ALLOWED":["BLK_ROLLOVER__PRODUCT_CODE~~","BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_MASTER__COUNTERPARTY!VARCHAR2","N~N",""],"BLK_ROLLOVER__CONTRACT_CCY__LOV_CURRENCY_ALLOWED":["BLK_ROLLOVER__CONTRACT_CCY~~","BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2~BLK_CONSOL_MASTER__TRANCHEREFNO!VARCHAR2","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_CONSOL_DETAIL","BLK_ROLL_MARGIN","BLK_SPLIT_ROLL","BLK_CONSOL_MARGIN","BLK_PROCESS_EXCEPTION","BLK_BORR_LINKAGE","BLK_LBTBS_PARTICIPANT_SHARE_AMT");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("LBCFPMLS~BLK_MASTER","LBCADVIC~BLK_MASTER","LBCUKUDF~BLK_MASTER"); 

 var CallFormRelat=new Array("OLTBS_CONTRACT.CONTRACT_REF_NO=LBTBS_CONT_MEDIA_FOR_ALL_PART.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_EVENT_SEQ_NO = LBTBS_CONT_MEDIA_FOR_ALL_PART.EVENT_SEQ_NO","OLTBS_CONTRACT.CONTRACT_REF_NO =OLTBS_GTEMP_EVENT_ADVICE.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_EVENT_SEQ_NO = OLTBS_GTEMP_EVENT_ADVICE.EVENT_SEQ_NO","OLTBS_CONTRACT.CONTRACT_REF_NO =LBTBS_UDF_FIELD_VALS.CONTRACT_REF_NO"); 

 var CallRelatType= new Array("1","1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDCOROL"]="KERNEL";
ArrPrntFunc["LBDCOROL"]="";
ArrPrntOrigin["LBDCOROL"]="";
ArrRoutingType["LBDCOROL"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDCOROL"]="N";
ArrCustomModified["LBDCOROL"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"LBCFPMLS":"CONTRACT_REF_NO~EVENT_SEQ_NO","LBCADVIC":"CONTREFNO~EVNTSEQNO","LBCUKUDF":"CONTRACTREFNO~RENEWALNO~SPLITNO","OLDFFMBR":"CONTRACTREFNO","OLDFFMSG":"CONTRACTREFNO","OLDEVENT":"CONTREF~ACTION_CODE","LPSCOMNT":""};
var scrArgSource = {"LBCFPMLS":"BLK_MASTER__CONFREFNO~BLK_MASTER__LATESTEVNTSEQ","LBCADVIC":"BLK_MASTER__CONFREFNO~BLK_MASTER__LATESTEVNTSEQ","LBCUKUDF":"BLK_MASTER__CONFREFNO~~","OLDFFMBR":"BLK_MASTER__CONFREFNO","OLDFFMSG":"BLK_MASTER__CONFREFNO","OLDEVENT":"BLK_MASTER__CONFREFNO~","LPSCOMNT":""};
var scrArgVals = {"LBCFPMLS":"~","LBCADVIC":"~","LBCUKUDF":"~~","OLDFFMBR":"~","OLDFFMSG":"~","OLDEVENT":"~EXECUTEQUERY","LPSCOMNT":""};
var scrArgDest = {};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"LBCFPMLS":"","LBCADVIC":"","LBCUKUDF":""};
var dpndntOnSrvs = {"LBCFPMLS":"","LBCADVIC":"","LBCUKUDF":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------