/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2024, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDFEAMD_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_OLTBS_CONTRACT_FEAMD":"CONTRACTREFNO~PRODUCTCODE~BRANCH~USERREFNO~COUNTERPARTY~TXTPRODDESC~TXTCUSTNAME~LATESTEVENTSEQNO~TXTCONTREFNO~TXTCOMP~TXTCOMPNAME~TXTTOTRATIO~MODULECODE~LATESTVERSIONNO~CONTSTATUS~PRODTYPE~TXTFESHCONREFNO~TXTFESHCMP~TXTFESHCCY~TXTFESHFEERULE~TXTFESHSTDT~TXTFESHENDDT~TXTFESHFEECOLL~TXTFESHBASISAMTATG~FEE_SCH_VISITED~CONT_AUTHSTAT~CONT_CCY","BLK_LFTBS_CONTARCT_FEE":"COMPONENT~ASSOCIATIONDATE~DISCACCRAPPLICABLE~LIQDPREFERENCE~FEEREVERSED~COMPONENTCCY~STARTDATE~ENDDATE~FEERULE~BILLINGNOTICEREQUIRED~INTERESTBASIS~BILLINGNOTICEDAYS~COMPSTAT~TXTTOTALFEEAMOUNT~TXTTILLDATEACCRUAL~CONTR~EVENTSQN~TXTPFEE~TXTFAS91~TXTRATIO~FEECOLLECTIONMODE","BLK_OLTBS_CONTRACT_EVENT_LOG":"CHECKERDTST~AUTHSTAT~CHECKERID~TXNSTAT~CONTREFNO~ESNO~MAKERID~MAKERDTST","BLK_RATIO_FEAMD":"RATVALDT~RATCOMP~RATCOMPTYPE~RATESNO~RATCONTREFNO~RATDRAWDOWNNO~RATCOMPRATIO~RATCONTRACTTYPE~RATCUSTOMERNO~TXTTOTPARTRATIO","BLK_LBTBS_PARTICIPANT_RATIO":"DRAWDOWNNO~CONREFNO~ESN~COMPTYPE~COMP~VALDT~CONTTYPE~COMPONENTRATIO~RATCUSTNO~TXTCUTNAME","BLK_FEE_SCH":"SCH_CONT_REF~SCH_COMP~SCH_COMP_CCY~SCH_FEE_COLLECT_MODE~SCH_FEE_START_DT~SCH_END_DT~SCH_FEE_RULE~SCH_ESN","BLK_CONT_SCH_LIQD":"LIQD_STDATE~LIQD_NOOFSCH~LIQD_FREQUENCY~LIQD_FUNIT~LIQD_AMT~LIQD_COMPONENT~LIQD_FCCREF~LIQD_ENDDT~LIQD_SCHTYPE~LIQD_VERNO","BLK_OLTBS_CONTRACT_SCHEDULES":"STDATE~COMPON~CONTREFNUMBER~SCHTYP~VERSIONNUM~NOOFSCHEDULES~AMT~FREQUENCYUNIT~FREQUENCY~TXTENDDT","BLK_PFEE":"PFEEESN~PFEECOMP~PFEECONTREFNO~PFEEPART~TXTTOTPFEE~PFEESCHDT~TXTPFEECURRENCY","BLK_OLTBS_AMOUNT_DUE_CS":"DUEDAT~CONREFNUMBR~COMPNEN~AMTSETTLED~AMTDUE","BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI":"FEEAMT~CONRE~CMP~EVESNO~PARTI~TXTPARTNAME~TXTPFEEAMT~SCHDAT","BLK_FAS91FEE":"FASREFNO~FASCOMP~FASESNO~FASCUSTNO~TXTFASCURR~TXTTOTFASFACAMT~TXTTOTFASMGMTCOMP~TXTTOTFASYIELDADJCOMP~TXTFASTOTCITIFEES~TXTFASTOTNONCITIFEES~TXTFASFEESTORECOGNIZE~TXTFASFEESTOAMORTIZE~TXTFASFEESTOWAVERAGEYIELD","BLK_LFTBS_FAS91_FEE_DETAIL":"CONTREF~CMPO~EVENSENO~CUSTOMERNO~MANAGEMENTCOMP~PARTICIPANTTYPE~YIELDADJCOMP~SELFPARTICIPANT~FACILITYAMOUNT~TXTFAS91PARTNAME~TXTTOTFACAMT~TXTTOTMGMTAMT~TXTTOTYELDADJCOMP~TXTFAS91CCY","BLK_LFTBS_FAS91_FEE_MASTER_MULTI":"WTAVERAGEYIELD~FESTOAMORTIZE~FESTORECOGNIZE~TOTCITIFEES~TOTNONCITIFEES~COMPNEN~CREFNO~ESNUMBER~FESCHORIGINATOR~FESCHORIGINATORMISCODE~FASPASSACCTENTRY","BLK_FAS_FESCH":"FESCHMISCODE~FESCHBRNCODE~FESCHESN~FESCHCOMP~FESCHCONTREFNO~TXTTOTFESCHTRAIO","BLK_LFTBS_FAS91_FEE_SPLIT_DTLS":"BRNCODE~ESEQNO~CONREFNUMBER~COMPON~MISCODE~ACCOUNT~RATIO~AMT~TXTTOTFESHRATIO","BLK_NRM_SUBSYS":"NRMCONTREFNO~SUBSYSSTAT"};

var multipleEntryPageSize = {"BLK_LFTBS_CONTARCT_FEE" :"15" ,"BLK_LBTBS_PARTICIPANT_RATIO" :"15" ,"BLK_CONT_SCH_LIQD" :"15" ,"BLK_OLTBS_CONTRACT_SCHEDULES" :"15" ,"BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI" :"15" ,"BLK_OLTBS_AMOUNT_DUE_CS" :"15" ,"BLK_LFTBS_FAS91_FEE_SPLIT_DTLS" :"15" ,"BLK_LFTBS_FAS91_FEE_DETAIL" :"15" };

var multipleEntrySVBlocks = "BLK_FEE_SCH~BLK_RATIO_FEAMD~BLK_PFEE~BLK_FAS91FEE~BLK_FAS_FESCH~BLK_LFTBS_FAS91_FEE_MASTER_MULTI";

var tabMEBlks = {"CVS_MAIN__TAB_MAIN":"BLK_LFTBS_CONTARCT_FEE","CVS_RATIO__TAB_MAIN":"BLK_LBTBS_PARTICIPANT_RATIO","CVS_FESCH__TAB_MAIN":"BLK_CONT_SCH_LIQD~BLK_OLTBS_CONTRACT_SCHEDULES~BLK_OLTBS_AMOUNT_DUE_CS","CVS_PARTFEE__TAB_MAIN":"BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI","CVS_FEESH__TAB_MAIN":"BLK_LFTBS_FAS91_FEE_SPLIT_DTLS","CVS_FAS91FEE__TAB_MAIN":"BLK_LFTBS_FAS91_FEE_DETAIL"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT_FEAMD">CONTRACTREFNO~PRODUCTCODE~BRANCH~USERREFNO~COUNTERPARTY~TXTPRODDESC~TXTCUSTNAME~LATESTEVENTSEQNO~TXTCONTREFNO~TXTCOMP~TXTCOMPNAME~TXTTOTRATIO~MODULECODE~LATESTVERSIONNO~CONTSTATUS~PRODTYPE~TXTFESHCONREFNO~TXTFESHCMP~TXTFESHCCY~TXTFESHFEERULE~TXTFESHSTDT~TXTFESHENDDT~TXTFESHFEECOLL~TXTFESHBASISAMTATG~FEE_SCH_VISITED~CONT_AUTHSTAT~CONT_CCY</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT_FEAMD" RELATION_TYPE="N" TYPE="BLK_LFTBS_CONTARCT_FEE">COMPONENT~ASSOCIATIONDATE~DISCACCRAPPLICABLE~LIQDPREFERENCE~FEEREVERSED~COMPONENTCCY~STARTDATE~ENDDATE~FEERULE~BILLINGNOTICEREQUIRED~INTERESTBASIS~BILLINGNOTICEDAYS~COMPSTAT~TXTTOTALFEEAMOUNT~TXTTILLDATEACCRUAL~CONTR~EVENTSQN~TXTPFEE~TXTFAS91~TXTRATIO~FEECOLLECTIONMODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT_FEAMD" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT_EVENT_LOG">CHECKERDTST~AUTHSTAT~CHECKERID~TXNSTAT~CONTREFNO~ESNO~MAKERID~MAKERDTST</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTARCT_FEE" RELATION_TYPE="N" TYPE="BLK_RATIO_FEAMD">RATVALDT~RATCOMP~RATCOMPTYPE~RATESNO~RATCONTREFNO~RATDRAWDOWNNO~RATCOMPRATIO~RATCONTRACTTYPE~RATCUSTOMERNO~TXTTOTPARTRATIO</FN>'; 
msgxml += '      <FN PARENT="BLK_RATIO_FEAMD" RELATION_TYPE="N" TYPE="BLK_LBTBS_PARTICIPANT_RATIO">DRAWDOWNNO~CONREFNO~ESN~COMPTYPE~COMP~VALDT~CONTTYPE~COMPONENTRATIO~RATCUSTNO~TXTCUTNAME</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTARCT_FEE" RELATION_TYPE="N" TYPE="BLK_FEE_SCH">SCH_CONT_REF~SCH_COMP~SCH_COMP_CCY~SCH_FEE_COLLECT_MODE~SCH_FEE_START_DT~SCH_END_DT~SCH_FEE_RULE~SCH_ESN</FN>'; 
msgxml += '      <FN PARENT="BLK_FEE_SCH" RELATION_TYPE="N" TYPE="BLK_CONT_SCH_LIQD">LIQD_STDATE~LIQD_NOOFSCH~LIQD_FREQUENCY~LIQD_FUNIT~LIQD_AMT~LIQD_COMPONENT~LIQD_FCCREF~LIQD_ENDDT~LIQD_SCHTYPE~LIQD_VERNO</FN>'; 
msgxml += '      <FN PARENT="BLK_FEE_SCH" RELATION_TYPE="N" TYPE="BLK_OLTBS_CONTRACT_SCHEDULES">STDATE~COMPON~CONTREFNUMBER~SCHTYP~VERSIONNUM~NOOFSCHEDULES~AMT~FREQUENCYUNIT~FREQUENCY~TXTENDDT</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTARCT_FEE" RELATION_TYPE="N" TYPE="BLK_PFEE">PFEEESN~PFEECOMP~PFEECONTREFNO~PFEEPART~TXTTOTPFEE~PFEESCHDT~TXTPFEECURRENCY</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT_SCHEDULES" RELATION_TYPE="N" TYPE="BLK_OLTBS_AMOUNT_DUE_CS">DUEDAT~CONREFNUMBR~COMPNEN~AMTSETTLED~AMTDUE</FN>'; 
msgxml += '      <FN PARENT="BLK_PFEE" RELATION_TYPE="N" TYPE="BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI">FEEAMT~CONRE~CMP~EVESNO~PARTI~TXTPARTNAME~TXTPFEEAMT~SCHDAT</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTARCT_FEE" RELATION_TYPE="N" TYPE="BLK_FAS91FEE">FASREFNO~FASCOMP~FASESNO~FASCUSTNO~TXTFASCURR~TXTTOTFASFACAMT~TXTTOTFASMGMTCOMP~TXTTOTFASYIELDADJCOMP~TXTFASTOTCITIFEES~TXTFASTOTNONCITIFEES~TXTFASFEESTORECOGNIZE~TXTFASFEESTOAMORTIZE~TXTFASFEESTOWAVERAGEYIELD</FN>'; 
msgxml += '      <FN PARENT="BLK_FAS91FEE" RELATION_TYPE="N" TYPE="BLK_LFTBS_FAS91_FEE_DETAIL">CONTREF~CMPO~EVENSENO~CUSTOMERNO~MANAGEMENTCOMP~PARTICIPANTTYPE~YIELDADJCOMP~SELFPARTICIPANT~FACILITYAMOUNT~TXTFAS91PARTNAME~TXTTOTFACAMT~TXTTOTMGMTAMT~TXTTOTYELDADJCOMP~TXTFAS91CCY</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTARCT_FEE" RELATION_TYPE="N" TYPE="BLK_LFTBS_FAS91_FEE_MASTER_MULTI">WTAVERAGEYIELD~FESTOAMORTIZE~FESTORECOGNIZE~TOTCITIFEES~TOTNONCITIFEES~COMPNEN~CREFNO~ESNUMBER~FESCHORIGINATOR~FESCHORIGINATORMISCODE~FASPASSACCTENTRY</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTARCT_FEE" RELATION_TYPE="N" TYPE="BLK_FAS_FESCH">FESCHMISCODE~FESCHBRNCODE~FESCHESN~FESCHCOMP~FESCHCONTREFNO~TXTTOTFESCHTRAIO</FN>'; 
msgxml += '      <FN PARENT="BLK_FAS_FESCH" RELATION_TYPE="N" TYPE="BLK_LFTBS_FAS91_FEE_SPLIT_DTLS">BRNCODE~ESEQNO~CONREFNUMBER~COMPON~MISCODE~ACCOUNT~RATIO~AMT~TXTTOTFESHRATIO</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT_FEAMD" RELATION_TYPE="1" TYPE="BLK_NRM_SUBSYS">NRMCONTREFNO~SUBSYSSTAT</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_OLTBS_CONTRACT_FEAMD" RELATION_TYPE="1" TYPE="BLK_LBVW_AMND_FEE_SUMMARY">AUTHSTATUS~CONTRACTSTATUS~CONTRACTREFNO~COUNTERPARTY~CUSTNAM~PRODUCT~BRANCH~MODULE</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDFEAMD";
var defaultWhereClause = "BRANCH=GLOBAL.CURRENT_BRANCH";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_LBVW_AMND_FEE_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_OLTBS_CONTRACT_FEAMD" : "","BLK_LFTBS_CONTARCT_FEE" : "BLK_OLTBS_CONTRACT_FEAMD~N","BLK_OLTBS_CONTRACT_EVENT_LOG" : "BLK_OLTBS_CONTRACT_FEAMD~1","BLK_RATIO_FEAMD" : "BLK_LFTBS_CONTARCT_FEE~N","BLK_LBTBS_PARTICIPANT_RATIO" : "BLK_RATIO_FEAMD~N","BLK_FEE_SCH" : "BLK_LFTBS_CONTARCT_FEE~N","BLK_CONT_SCH_LIQD" : "BLK_FEE_SCH~N","BLK_OLTBS_CONTRACT_SCHEDULES" : "BLK_FEE_SCH~N","BLK_PFEE" : "BLK_LFTBS_CONTARCT_FEE~N","BLK_OLTBS_AMOUNT_DUE_CS" : "BLK_OLTBS_CONTRACT_SCHEDULES~N","BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI" : "BLK_PFEE~N","BLK_FAS91FEE" : "BLK_LFTBS_CONTARCT_FEE~N","BLK_LFTBS_FAS91_FEE_DETAIL" : "BLK_FAS91FEE~N","BLK_LFTBS_FAS91_FEE_MASTER_MULTI" : "BLK_LFTBS_CONTARCT_FEE~N","BLK_FAS_FESCH" : "BLK_LFTBS_CONTARCT_FEE~N","BLK_LFTBS_FAS91_FEE_SPLIT_DTLS" : "BLK_FAS_FESCH~N","BLK_NRM_SUBSYS" : "BLK_OLTBS_CONTRACT_FEAMD~1"}; 

 var dataSrcLocationArray = new Array("BLK_OLTBS_CONTRACT_FEAMD","BLK_LFTBS_CONTARCT_FEE","BLK_OLTBS_CONTRACT_EVENT_LOG","BLK_RATIO_FEAMD","BLK_LBTBS_PARTICIPANT_RATIO","BLK_FEE_SCH","BLK_CONT_SCH_LIQD","BLK_OLTBS_CONTRACT_SCHEDULES","BLK_PFEE","BLK_OLTBS_AMOUNT_DUE_CS","BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI","BLK_FAS91FEE","BLK_LFTBS_FAS91_FEE_DETAIL","BLK_LFTBS_FAS91_FEE_MASTER_MULTI","BLK_FAS_FESCH","BLK_LFTBS_FAS91_FEE_SPLIT_DTLS","BLK_NRM_SUBSYS"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDFEAMD.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDFEAMD.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO";
pkFields[0] = "BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_LBTBS_PARTICIPANT_RATIO":["COMPONENTRATIO"],"BLK_LFTBS_CONTARCT_FEE":["LIQDPREFERENCE"],"BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI":["FEEAMT"],"BLK_LFTBS_FAS91_FEE_DETAIL":["CUSTOMERNO","FACILITYAMOUNT","MANAGEMENTCOMP","PARTICIPANTTYPE","SELFPARTICIPANT","YIELDADJCOMP"],"BLK_LFTBS_FAS91_FEE_MASTER_MULTI":["FASPASSACCTENTRY","FESCHORIGINATOR","FESCHORIGINATORMISCODE"],"BLK_LFTBS_FAS91_FEE_SPLIT_DTLS":["ACCOUNT","BRNCODE","MISCODE","RATIO"],"BLK_OLTBS_CONTRACT_FEAMD":["BTN_CALCULATE","BTN_COMPUTE","BTN_FASCAL","BTN_FEESHAR","BTN_FESHCAL","BTN_PARTCAL","BTN_POPULATE"],"BLK_OLTBS_CONTRACT_SCHEDULES":["AMT","FREQUENCY","FREQUENCYUNIT","NOOFSCHEDULES","STDATEI"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO__LOV_CONTRACT":["BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO~BLK_OLTBS_CONTRACT_FEAMD__USERREFNO~BLK_OLTBS_CONTRACT_FEAMD__PRODUCTCODE~BLK_OLTBS_CONTRACT_FEAMD__TXTPRODDESC~BLK_OLTBS_CONTRACT_FEAMD__COUNTERPARTY~BLK_OLTBS_CONTRACT_FEAMD__TXTCUSTNAME~BLK_OLTBS_CONTRACT_FEAMD__BRANCH~","","N~N~N~N~N~N~N",""],"BLK_LFTBS_CONTARCT_FEE__COMPONENT__LOV_COMPONENT":["BLK_LFTBS_CONTARCT_FEE__COMPONENT~BLK_LFTBS_CONTARCT_FEE__FEERULE~~~","BLK_OLTBS_CONTRACT_FEAMD__PRODUCTCODE!VARCHAR2~BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO!VARCHAR2~BLK_OLTBS_CONTRACT_FEAMD__PRODUCTCODE!VARCHAR2~BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO!VARCHAR2","N~N~N~N",""],"BLK_LFTBS_CONTARCT_FEE__COMPONENTCCY__LOV_CURRENCIES":["BLK_LFTBS_CONTARCT_FEE__COMPONENTCCY~~","BLK_OLTBS_CONTRACT_FEAMD__PRODUCTCODE!VARCHAR2","N~N",""],"BLK_LFTBS_CONTARCT_FEE__FEERULE__LOV_FEE_RULE":["BLK_LFTBS_CONTARCT_FEE__FEERULE~~","","N~N",""],"BLK_LBTBS_PARTICIPANT_RATIO__RATCUSTNO__LOV_PARTICIPANT":["BLK_LBTBS_PARTICIPANT_RATIO__RATCUSTNO~BLK_LBTBS_PARTICIPANT_RATIO__TXTCUTNAME~","","N~N",""],"BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI__PARTI__LOV_PARTICIPANT":["BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI__PARTI~BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI__TXTPARTNAME~","","N~N",""],"BLK_LFTBS_FAS91_FEE_DETAIL__CUSTOMERNO__LOV_PARTICIPANT":["BLK_LFTBS_FAS91_FEE_DETAIL__CUSTOMERNO~BLK_LFTBS_FAS91_FEE_DETAIL__TXTFAS91PARTNAME~","","N~N",""],"BLK_LFTBS_FAS91_FEE_MASTER_MULTI__FESCHORIGINATOR__LOV_ORIGINATOR":["BLK_LFTBS_FAS91_FEE_MASTER_MULTI__FESCHORIGINATOR~~","","N~N",""],"BLK_LFTBS_FAS91_FEE_MASTER_MULTI__FESCHORIGINATORMISCODE__LOV_ORG_MIS_CODE":["BLK_LFTBS_FAS91_FEE_MASTER_MULTI__FESCHORIGINATORMISCODE~~","","N~N",""],"BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__BRNCODE__LOV_BRANCH":["BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__BRNCODE~~","","N~N",""],"BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__MISCODE__LOV_MIS_CODE":["BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__MISCODE~~","BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO!VARCHAR2~BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__COMPON!VARCHAR2~BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__BRNCODE!VARCHAR2","N~N",""],"BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__ACCOUNT__LOV_ACCOUNT":["BLK_LFTBS_FAS91_FEE_SPLIT_DTLS__ACCOUNT~~","","N~N",""],"BLK_LBVW_AMND_FEE_SUMMARY__COUNTERPARTY__LOV_CUST_NAME_S":["BLK_LBVW_AMND_FEE_SUMMARY__COUNTERPARTY~BLK_LBVW_AMND_FEE_SUMMARY__CUSTNAM~~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_LFTBS_CONTARCT_FEE","BLK_LBTBS_PARTICIPANT_RATIO","BLK_CONT_SCH_LIQD","BLK_OLTBS_CONTRACT_SCHEDULES","BLK_LFTBS_CONTRACT_PARTDRIVEN_FEE_MULTI","BLK_OLTBS_AMOUNT_DUE_CS","BLK_LFTBS_FAS91_FEE_SPLIT_DTLS","BLK_LFTBS_FAS91_FEE_DETAIL");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("OLCONDET~BLK_OLTBS_CONTRACT_FEAMD","LFCFRMNT~BLK_OLTBS_CONTRACT_FEAMD"); 

 var CallFormRelat=new Array("OLTBS_CONTRACT__FEAMD.CONTRACT_REF_NO=OLTBS_CONTRACT__SETT.CONTRACT_REF_NO","OLTBS_CONTRACT__FEAMD.CONTRACT_REF_NO=OLTBS_CONTRACT__SETT.CONTRACT_REF_NO"); 

 var CallRelatType= new Array("1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDFEAMD"]="KERNEL";
ArrPrntFunc["LBDFEAMD"]="";
ArrPrntOrigin["LBDFEAMD"]="";
ArrRoutingType["LBDFEAMD"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDFEAMD"]="N";
ArrCustomModified["LBDFEAMD"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_RATIO":"RATCOMP","CVS_FESCH":"FESCHCOMP~FESCHCCY~FESCHFERULE~FESCHDSTDT~FESCHCONTREF~FESCHESN","CVS_PARTFEE":"PFEECOMP~PFEESCHDT~TXTPFEECURRENCY","CVS_FAS91FEE":"FASCOMP~TXTFASCURR","OLCONDET":"CONREFNO~ESN","LFCFRMNT":"MODULE~CONTREFNO~USERREFNO~BOOKDATE~VALUEDATE~CUST~CCY","OLDEVENT":"CONTREF~ACTION_CODE~"};
var scrArgSource = {"CVS_RATIO":"BLK_LFTBS_CONTARCT_FEE__COMPONENT","CVS_FESCH":"BLK_LFTBS_CONTARCT_FEE__COMPONENT~BLK_LFTBS_CONTARCT_FEE__COMPONENTCCY~BLK_LFTBS_CONTARCT_FEE__FEERULE~BLK_LFTBS_CONTARCT_FEE__ASSOCIATIONDATE~BLK_LFTBS_CONTARCT_FEE__CONTR~BLK_LFTBS_CONTARCT_FEE__EVENTSQN","CVS_PARTFEE":"BLK_LFTBS_CONTARCT_FEE__COMPONENT~BLK_LFTBS_CONTARCT_FEE__ASSOCIATIONDATE~BLK_LFTBS_CONTARCT_FEE__COMPONENTCCY","CVS_FAS91FEE":"BLK_LFTBS_CONTARCT_FEE__COMPONENT~BLK_LFTBS_CONTARCT_FEE__COMPONENTCCY","OLCONDET":"BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO~BLK_OLTBS_CONTRACT_FEAMD__LATESTEVENTSEQNO","LFCFRMNT":"BLK_OLTBS_CONTRACT_FEAMD__MODULECODE~BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO~BLK_OLTBS_CONTRACT_FEAMD__USERREFNO~BLK_LFTBS_CONTARCT_FEE__STARTDATE~BLK_LFTBS_CONTARCT_FEE__STARTDATE~BLK_OLTBS_CONTRACT_FEAMD__COUNTERPARTY~BLK_OLTBS_CONTRACT_FEAMD__CONT_CCY","OLDEVENT":"BLK_OLTBS_CONTRACT_FEAMD__CONTRACTREFNO~~"};
var scrArgVals = {"CVS_RATIO":"","CVS_FESCH":"~~~~~","CVS_PARTFEE":"~~","CVS_FAS91FEE":"~","OLCONDET":"~","LFCFRMNT":"~~~~~~","OLDEVENT":"~EXECUTEQUERY~"};
var scrArgDest = {"CVS_RATIO":"BLK_RATIO_FEAMD__RATCOMP","CVS_FESCH":"BLK_FEE_SCH__SCH_COMP~BLK_FEE_SCH__SCH_COMP_CCY~BLK_FEE_SCH__SCH_FEE_RULE~BLK_FEE_SCH__SCH_FEE_START_DT~BLK_FEE_SCH__SCH_CONT_REF~BLK_FEE_SCH__SCH_ESN","CVS_PARTFEE":"BLK_PFEE__PFEECOMP~BLK_PFEE__PFEESCHDT~BLK_PFEE__TXTPFEECURRENCY","CVS_FAS91FEE":"BLK_FAS91FEE__FASCOMP~BLK_FAS91FEE__TXTFASCURR"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"OLCONDET":"","LFCFRMNT":""};
var dpndntOnSrvs = {"OLCONDET":"","LFCFRMNT":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"2","DELETE":"2","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------