/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDINSTR_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_OLTMS_INSTR_HDR":"SSIMNEMONIC~SETTLEMENTSEQNO~PRODUCTCODE~CURRENCY~COUNTERPARTY~MODULE~BRANCH~COUNTERPARTYTYPE~TXTSHORTNAME~TXTCUSTNAME~TXTGFCID~MAKER~MAKERSTAMP~CHECKER~CHECKERSTAMP~MODNO~TXNSTAT~AUTHSTAT~ONCEAUTH","BLK_ACC_DET_BODY_1":"CHARGEACBRANCH~CHARGEACCOUNT~CHARGEACCCY~RECVACBRANCH~RECVACCOUNT~RECVACCOUNTCCY~PAYACBRANCH~PAYACCOUNT~PAYACCOUNTCCY~INSTRTYPEREC~INSTRTYPEPAY~TRANSFERBYRECV~TRANSFERBYPAY~RECVACCCIF~PAYACCCIF~PAYMENTBYREC~PAYMENTBYPAY","BLK_ACC_DET_BODY_2":"TRANSACTIONTYPECODE~BANKOPERATIONCODE~GENERATEMT210~GENERATEDDMSG~COVERREQUIRED~COVERBY~ERICCY","BLK_ACC_DET_BODY_3":"CHARGESDETAILS~USDCLGNETWORK~INSTRUCTIONCODE6~TXTINSTRCODE6~INSTRUCTIONCODE5~TXTINSTRCODE5~INSTRUCTIONCODE4~TXTINSTRCODE4~INSTRUCTIONCODE3~TXTINSTRCODE3~INSTRUCTIONCODE2~TXTINSTRCODE2~INSTRUCTIONCODE1~TXTINSTRCODE1","BLK_MSG_DET_BODY_1":"REGULATORYREPORT3~REGULATORYREPORT2~REGULATORYREPORT1~SNDRTORCVRINFO6~SNDRTORCVRINFO5~SNDRTORCVRINFO4~SNDRTORCVRINFO3~SNDRTORCVRINFO2~SNDRTORCVRINFO1","BLK_PAY_PART_BODY_1":"ORDERINGINSTITUTION5~ORDERINGINSTITUTION4~ORDERINGINSTITUTION3~ORDERINGINSTITUTION2~ORDERINGINSTITUTION1~ULTIBENSORTCODE~TXTULTIBENFCD~ULTBENEFICIARY5~ULTBENEFICIARY4~ULTBENEFICIARY3~ULTBENEFICIARY2~ULTBENEFICIARY1~BENEFINSTSORTCODE~TXTBENFSCODE~BENEFINSTITUTION5~BENEFINSTITUTION4~BENEFINSTITUTION3~BENEFINSTITUTION2~BENEFINSTITUTION1~ORDERINGCUSTOMER5~ORDERINGCUSTOMER4~ORDERINGCUSTOMER3~ORDERINGCUSTOMER2~ORDERINGCUSTOMER1","BLK_PAY_PART_BODY_2":"INTERMEDIARYSORTCODE~TXTINTSCODE~INTERMEDIARY5~INTERMEDIARY4~INTERMEDIARY3~INTERMEDIARY2~INTERMEDIARY1~RCVR_CORRESP5~RCVRCORRESP4~RCVRCORRESP3~RCVRCORRESP2~RCVRCORRESP1~INTREIMINST5~INTREIMINST4~INTREIMINST3~INTREIMINST2~INTREIMINST1~AWISORTCODE~TXTAWISCODE~ACCWITHINSTN5~ACCWITHINSTN4~ACCWITHINSTN3~ACCWITHINSTN2~ACCWITHINSTN1","BLK_RCV_NOT_BODY":"RECVORDERINGCUST5~RECVORDERINGCUST4~RECVORDERINGCUST3~RECVORDERINGCUST2~RECVORDERINGCUST1~RECVORDERINGINSTN5~RECVORDERINGINSTN4~RECVORDERINGINSTN3~RECVORDERINGINSTN2~RECVORDERINGINSTN1~RECVINTERMEDIARY5~RECVINTERMEDIARY4~RECVINTERMEDIARY3~RECVINTERMEDIARY2~RECVINTERMEDIARY1","BLK_DD_PART_BODY":"CREDITORSORTCODE~TXTCRESCODE~CREDITORACCT5~CREDITORACCT4~CREDITORACCT3~CREDITORACCT2~CREDITORACCT1~CREDITORBANK5~CREDITORBANK4~CREDITORBANK3~CREDITORBANK2~CREDITORBANK1~DEBTORSORTCODE~TXTDEBSCODE~DEBTORACCT5~DEBTORACCT4~DEBTORACCT3~DEBTORACCT2~DEBTORACCT1~DEBTORBANK5~DEBTORBANK4~DEBTORBANK3~DEBTORBANK2~DEBTORBANK1","BLK_COV_CLR_DET":"EXTPAYBANKCODE~TXTEXTPAYDESC~EXTPAYCPTYACPREFIX~EXTPAYACCOUNT~EXTPAYPARTYNAME~EXTRECVBANKCODE~TXTEXTRECDESC~EXTCOVERCPTYACPREFIX~EXTCOVERACCOUNT~EXTCOVERPARTYNAME~EXTCOVERBANKCODE~TXTCOVBANKDESC~EXTRECVCPTYACPREFIX~EXTRECVACCOUNT~EXTRECVPARTYNAME"};

var multipleEntryPageSize = {};

var multipleEntrySVBlocks = "";

var tabMEBlks = {};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_OLTMS_INSTR_HDR">SSIMNEMONIC~SETTLEMENTSEQNO~PRODUCTCODE~CURRENCY~COUNTERPARTY~MODULE~BRANCH~COUNTERPARTYTYPE~TXTSHORTNAME~TXTCUSTNAME~TXTGFCID~MAKER~MAKERSTAMP~CHECKER~CHECKERSTAMP~MODNO~TXNSTAT~AUTHSTAT~ONCEAUTH</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_ACC_DET_BODY_1">CHARGEACBRANCH~CHARGEACCOUNT~CHARGEACCCY~RECVACBRANCH~RECVACCOUNT~RECVACCOUNTCCY~PAYACBRANCH~PAYACCOUNT~PAYACCOUNTCCY~INSTRTYPEREC~INSTRTYPEPAY~TRANSFERBYRECV~TRANSFERBYPAY~RECVACCCIF~PAYACCCIF~PAYMENTBYREC~PAYMENTBYPAY</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_ACC_DET_BODY_2">TRANSACTIONTYPECODE~BANKOPERATIONCODE~GENERATEMT210~GENERATEDDMSG~COVERREQUIRED~COVERBY~ERICCY</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_ACC_DET_BODY_3">CHARGESDETAILS~USDCLGNETWORK~INSTRUCTIONCODE6~TXTINSTRCODE6~INSTRUCTIONCODE5~TXTINSTRCODE5~INSTRUCTIONCODE4~TXTINSTRCODE4~INSTRUCTIONCODE3~TXTINSTRCODE3~INSTRUCTIONCODE2~TXTINSTRCODE2~INSTRUCTIONCODE1~TXTINSTRCODE1</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_MSG_DET_BODY_1">REGULATORYREPORT3~REGULATORYREPORT2~REGULATORYREPORT1~SNDRTORCVRINFO6~SNDRTORCVRINFO5~SNDRTORCVRINFO4~SNDRTORCVRINFO3~SNDRTORCVRINFO2~SNDRTORCVRINFO1</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_PAY_PART_BODY_1">ORDERINGINSTITUTION5~ORDERINGINSTITUTION4~ORDERINGINSTITUTION3~ORDERINGINSTITUTION2~ORDERINGINSTITUTION1~ULTIBENSORTCODE~TXTULTIBENFCD~ULTBENEFICIARY5~ULTBENEFICIARY4~ULTBENEFICIARY3~ULTBENEFICIARY2~ULTBENEFICIARY1~BENEFINSTSORTCODE~TXTBENFSCODE~BENEFINSTITUTION5~BENEFINSTITUTION4~BENEFINSTITUTION3~BENEFINSTITUTION2~BENEFINSTITUTION1~ORDERINGCUSTOMER5~ORDERINGCUSTOMER4~ORDERINGCUSTOMER3~ORDERINGCUSTOMER2~ORDERINGCUSTOMER1</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_PAY_PART_BODY_2">INTERMEDIARYSORTCODE~TXTINTSCODE~INTERMEDIARY5~INTERMEDIARY4~INTERMEDIARY3~INTERMEDIARY2~INTERMEDIARY1~RCVR_CORRESP5~RCVRCORRESP4~RCVRCORRESP3~RCVRCORRESP2~RCVRCORRESP1~INTREIMINST5~INTREIMINST4~INTREIMINST3~INTREIMINST2~INTREIMINST1~AWISORTCODE~TXTAWISCODE~ACCWITHINSTN5~ACCWITHINSTN4~ACCWITHINSTN3~ACCWITHINSTN2~ACCWITHINSTN1</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_RCV_NOT_BODY">RECVORDERINGCUST5~RECVORDERINGCUST4~RECVORDERINGCUST3~RECVORDERINGCUST2~RECVORDERINGCUST1~RECVORDERINGINSTN5~RECVORDERINGINSTN4~RECVORDERINGINSTN3~RECVORDERINGINSTN2~RECVORDERINGINSTN1~RECVINTERMEDIARY5~RECVINTERMEDIARY4~RECVINTERMEDIARY3~RECVINTERMEDIARY2~RECVINTERMEDIARY1</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_DD_PART_BODY">CREDITORSORTCODE~TXTCRESCODE~CREDITORACCT5~CREDITORACCT4~CREDITORACCT3~CREDITORACCT2~CREDITORACCT1~CREDITORBANK5~CREDITORBANK4~CREDITORBANK3~CREDITORBANK2~CREDITORBANK1~DEBTORSORTCODE~TXTDEBSCODE~DEBTORACCT5~DEBTORACCT4~DEBTORACCT3~DEBTORACCT2~DEBTORACCT1~DEBTORBANK5~DEBTORBANK4~DEBTORBANK3~DEBTORBANK2~DEBTORBANK1</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTMS_INSTR_HDR" RELATION_TYPE="1" TYPE="BLK_COV_CLR_DET">EXTPAYBANKCODE~TXTEXTPAYDESC~EXTPAYCPTYACPREFIX~EXTPAYACCOUNT~EXTPAYPARTYNAME~EXTRECVBANKCODE~TXTEXTRECDESC~EXTCOVERCPTYACPREFIX~EXTCOVERACCOUNT~EXTCOVERPARTYNAME~EXTCOVERBANKCODE~TXTCOVBANKDESC~EXTRECVCPTYACPREFIX~EXTRECVACCOUNT~EXTRECVPARTYNAME</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_OLTMS_INSTR_HDR">AUTHSTAT~TXNSTAT~COUNTERPARTY~MODULE~COUNTERPARTYTYPE~BRANCH~PRODUCTCODE~SSIMNEMONIC~CURRENCY~SETTLEMENTSEQNO</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDINSTR";
var defaultWhereClause = "(COUNTERPARTY IN (SELECT CUSTOMER_NO FROM STTM_CORE_CUSTOMER B WHERE COUNTERPARTY = B.CUSTOMER_NO AND ((B.ACCESS_GROUP IS NOT NULL AND EXISTS (SELECT 1 FROM STVW_USER_ACCESS C WHERE C.USER_ID = global.user_id AND C.ACCESS_GROUP = B.ACCESS_GROUP)) OR B.ACCESS_GROUP IS NULL)) OR COUNTERPARTY = 'ALL') AND (SMPKS_MASK_USER.pr_setusrctx(global.user_id,'LBSINSTR') IN ('N','Y')) AND NVL(IS_FORGOTTEN,'N') = 'N'";
var defaultOrderByClause ="";
var multiBrnWhereClause ="(COUNTERPARTY IN (SELECT CUSTOMER_NO FROM STTM_CORE_CUSTOMER B WHERE COUNTERPARTY = B.CUSTOMER_NO AND ((B.ACCESS_GROUP IS NOT NULL AND EXISTS (SELECT 1 FROM STVW_USER_ACCESS C WHERE C.USER_ID = global.user_id AND C.ACCESS_GROUP = B.ACCESS_GROUP)) OR B.ACCESS_GROUP IS NULL)) OR COUNTERPARTY = 'ALL') AND (SMPKS_MASK_USER.pr_setusrctx(global.user_id,'LBSINSTR') IN ('N','Y')) AND NVL(IS_FORGOTTEN,'N') = 'N'";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_OLTMS_INSTR_HDR";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_OLTMS_INSTR_HDR" : "","BLK_ACC_DET_BODY_1" : "BLK_OLTMS_INSTR_HDR~1","BLK_ACC_DET_BODY_2" : "BLK_OLTMS_INSTR_HDR~1","BLK_ACC_DET_BODY_3" : "BLK_OLTMS_INSTR_HDR~1","BLK_MSG_DET_BODY_1" : "BLK_OLTMS_INSTR_HDR~1","BLK_PAY_PART_BODY_1" : "BLK_OLTMS_INSTR_HDR~1","BLK_PAY_PART_BODY_2" : "BLK_OLTMS_INSTR_HDR~1","BLK_RCV_NOT_BODY" : "BLK_OLTMS_INSTR_HDR~1","BLK_DD_PART_BODY" : "BLK_OLTMS_INSTR_HDR~1","BLK_COV_CLR_DET" : "BLK_OLTMS_INSTR_HDR~1"}; 

 var dataSrcLocationArray = new Array("BLK_OLTMS_INSTR_HDR","BLK_ACC_DET_BODY_1","BLK_ACC_DET_BODY_2","BLK_ACC_DET_BODY_3","BLK_MSG_DET_BODY_1","BLK_PAY_PART_BODY_1","BLK_PAY_PART_BODY_2","BLK_RCV_NOT_BODY","BLK_DD_PART_BODY","BLK_COV_CLR_DET"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDINSTR.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDINSTR.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_OLTMS_INSTR_HDR__SETTLEMENTSEQNO";
pkFields[0] = "BLK_OLTMS_INSTR_HDR__SETTLEMENTSEQNO";
queryFields[1] = "BLK_OLTMS_INSTR_HDR__PRODUCTCODE";
pkFields[1] = "BLK_OLTMS_INSTR_HDR__PRODUCTCODE";
queryFields[2] = "BLK_OLTMS_INSTR_HDR__CURRENCY";
pkFields[2] = "BLK_OLTMS_INSTR_HDR__CURRENCY";
queryFields[3] = "BLK_OLTMS_INSTR_HDR__COUNTERPARTY";
pkFields[3] = "BLK_OLTMS_INSTR_HDR__COUNTERPARTY";
queryFields[4] = "BLK_OLTMS_INSTR_HDR__MODULE";
pkFields[4] = "BLK_OLTMS_INSTR_HDR__MODULE";
queryFields[5] = "BLK_OLTMS_INSTR_HDR__BRANCH";
pkFields[5] = "BLK_OLTMS_INSTR_HDR__BRANCH";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_ACC_DET_BODY_1":["CHARGEACBRANCH","CHARGEACCCY","CHARGEACCOUNT","INSTRTYPEPAY","INSTRTYPEREC","PAYACBRANCH","PAYACCCIF","PAYACCOUNT","PAYACCOUNTCCY","PAYMENTBYPAY","PAYMENTBYREC","RECVACBRANCH","RECVACCCIF","RECVACCOUNT","RECVACCOUNTCCY","TRANSFERBYPAY","TRANSFERBYRECV"],"BLK_ACC_DET_BODY_2":["BANKOPERATIONCODE","COVERBY","COVERREQUIRED","ERICCY","GENERATEDDMSG","GENERATEMT210","TRANSACTIONTYPECODE"],"BLK_ACC_DET_BODY_3":["CHARGESDETAILS","INSTRUCTIONCODE1","INSTRUCTIONCODE2","INSTRUCTIONCODE3","INSTRUCTIONCODE4","INSTRUCTIONCODE5","INSTRUCTIONCODE6","TXTINSTRCODE1","TXTINSTRCODE2","TXTINSTRCODE3","TXTINSTRCODE4","TXTINSTRCODE5","TXTINSTRCODE6","USDCLGNETWORK"],"BLK_COV_CLR_DET":["EXTCOVERACCOUNT","EXTCOVERBANKCODE","EXTCOVERCPTYACPREFIX","EXTCOVERPARTYNAME","EXTPAYACCOUNT","EXTPAYBANKCODE","EXTPAYCPTYACPREFIX","EXTPAYPARTYNAME","EXTRECVACCOUNT","EXTRECVBANKCODE","EXTRECVCPTYACPREFIX","EXTRECVPARTYNAME","TXTCOVBANKDESC","TXTEXTPAYDESC","TXTEXTRECDESC"],"BLK_DD_PART_BODY":["CREDITORACCT1","CREDITORACCT2","CREDITORACCT3","CREDITORACCT4","CREDITORACCT5","CREDITORBANK1","CREDITORBANK2","CREDITORBANK3","CREDITORBANK4","CREDITORBANK5","CREDITORSORTCODE","DEBTORACCT1","DEBTORACCT2","DEBTORACCT3","DEBTORACCT4","DEBTORACCT5","DEBTORBANK1","DEBTORBANK2","DEBTORBANK3","DEBTORBANK4","DEBTORBANK5","DEBTORSORTCODE","TXTCRESCODE","TXTDEBSCODE"],"BLK_MSG_DET_BODY_1":["REGULATORYREPORT1","REGULATORYREPORT2","REGULATORYREPORT3","SNDRTORCVRINFO1","SNDRTORCVRINFO2","SNDRTORCVRINFO3","SNDRTORCVRINFO4","SNDRTORCVRINFO5","SNDRTORCVRINFO6"],"BLK_OLTMS_INSTR_HDR":["COUNTERPARTYTYPE"],"BLK_PAY_PART_BODY_1":["BENEFINSTITUTION1","BENEFINSTITUTION2","BENEFINSTITUTION3","BENEFINSTITUTION4","BENEFINSTITUTION5","BENEFINSTSORTCODE","ORDERINGCUSTOMER1","ORDERINGCUSTOMER2","ORDERINGCUSTOMER3","ORDERINGCUSTOMER4","ORDERINGCUSTOMER5","ORDERINGINSTITUTION1","ORDERINGINSTITUTION2","ORDERINGINSTITUTION3","ORDERINGINSTITUTION4","ORDERINGINSTITUTION5","TXTBENFSCODE","TXTULTIBENFCD","ULTBENEFICIARY1","ULTBENEFICIARY2","ULTBENEFICIARY3","ULTBENEFICIARY4","ULTBENEFICIARY5","ULTIBENSORTCODE"],"BLK_PAY_PART_BODY_2":["ACCWITHINSTN1","ACCWITHINSTN2","ACCWITHINSTN3","ACCWITHINSTN4","ACCWITHINSTN5","AWISORTCODE","INTERMEDIARY1","INTERMEDIARY2","INTERMEDIARY3","INTERMEDIARY4","INTERMEDIARY5","INTERMEDIARYSORTCODE","INTREIMINST1","INTREIMINST2","INTREIMINST3","INTREIMINST4","INTREIMINST5","RCVRCORRESP1","RCVRCORRESP2","RCVRCORRESP3","RCVRCORRESP4","RCVR_CORRESP5","TXTAWISCODE","TXTINTSCODE"],"BLK_RCV_NOT_BODY":["RECVINTERMEDIARY1","RECVINTERMEDIARY2","RECVINTERMEDIARY3","RECVINTERMEDIARY4","RECVINTERMEDIARY5","RECVORDERINGCUST1","RECVORDERINGCUST2","RECVORDERINGCUST3","RECVORDERINGCUST4","RECVORDERINGCUST5","RECVORDERINGINSTN1","RECVORDERINGINSTN2","RECVORDERINGINSTN3","RECVORDERINGINSTN4","RECVORDERINGINSTN5"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
//***** Fields Amendable while Query *****
var queryAmendArr = {"BLK_OLTMS_INSTR_HDR":["SETTLEMENTSEQNO","SSIMNEMONIC"]};
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_OLTMS_INSTR_HDR__PRODUCTCODE__LOV_PRODUCT":["BLK_OLTMS_INSTR_HDR__PRODUCTCODE~~","BLK_ISTMS_INSTR_HDR__MODULE!VARCHAR2","N~N",""],"BLK_OLTMS_INSTR_HDR__CURRENCY__LOV_CURRENCY":["BLK_OLTMS_INSTR_HDR__CURRENCY~~","","N~N",""],"BLK_OLTMS_INSTR_HDR__COUNTERPARTY__LOV_COUNTERPARTY":["BLK_OLTMS_INSTR_HDR__COUNTERPARTY~BLK_OLTMS_INSTR_HDR__TXTCUSTNAME~BLK_OLTMS_INSTR_HDR__TXTSHORTNAME~BLK_OLTMS_INSTR_HDR__COUNTERPARTYTYPE~BLK_ACC_DET_BODY_1__TRANSFERBYPAY~BLK_ACC_DET_BODY_1__TRANSFERBYRECV~","","N~N~N~N~N~N",""],"BLK_OLTMS_INSTR_HDR__MODULE__LOV_MODULES":["BLK_OLTMS_INSTR_HDR__MODULE~~","","N~N",""],"BLK_OLTMS_INSTR_HDR__BRANCH__LOV_BRANCH":["BLK_OLTMS_INSTR_HDR__BRANCH~~","","N~N",""],"BLK_ACC_DET_BODY_1__CHARGEACBRANCH__LOV_CHARGE_ACC_BRANCH":["BLK_ACC_DET_BODY_1__CHARGEACBRANCH~~","","N~N",""],"BLK_ACC_DET_BODY_1__CHARGEACCOUNT__LOV_CHARGE_ACCOUNT":["BLK_ACC_DET_BODY_1__CHARGEACCOUNT~BLK_ACC_DET_BODY_1__CHARGEACCCY~~","BLK_ACC_DET_BODY_1__CHARGEACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__CHARGEACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__CHARGEACBRANCH!VARCHAR2~BLK_OLTMS_INSTR_HDR__PRODUCTCODE!VARCHAR2","N~N~N",""],"BLK_ACC_DET_BODY_1__CHARGEACCCY__LOV_CHARGE_AC_CCY":["BLK_ACC_DET_BODY_1__CHARGEACCCY~~","","N~N",""],"BLK_ACC_DET_BODY_1__RECVACBRANCH__LOV_RECV_ACC_BRANCH":["BLK_ACC_DET_BODY_1__RECVACBRANCH~~","","N~N",""],"BLK_ACC_DET_BODY_1__RECVACCOUNT__LOV_RECV_ACCOUNT":["BLK_ACC_DET_BODY_1__RECVACCOUNT~BLK_ACC_DET_BODY_1__RECVACCOUNTCCY~~","BLK_ACC_DET_BODY_1__RECVACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__RECVACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__RECVACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__RECVACCCIF!VARCHAR2~BLK_ACC_DET_BODY_1__RECVACCCIF!VARCHAR2~BLK_ACC_DET_BODY_1__RECVACCCIF!VARCHAR2~BLK_OLTMS_INSTR_HDR__PRODUCTCODE!VARCHAR2","N~N~N",""],"BLK_ACC_DET_BODY_1__RECVACCOUNTCCY__LOV_RECV_AC_CCY":["BLK_ACC_DET_BODY_1__RECVACCOUNTCCY~~","","N~N",""],"BLK_ACC_DET_BODY_1__PAYACBRANCH__LOV_PAY_ACC_BRANCH":["BLK_ACC_DET_BODY_1__PAYACBRANCH~~","","N~N",""],"BLK_ACC_DET_BODY_1__PAYACCOUNT__LOV_PAY_ACCOUNT":["BLK_ACC_DET_BODY_1__PAYACCOUNT~BLK_ACC_DET_BODY_1__PAYACCOUNTCCY~~","BLK_ACC_DET_BODY_1__PAYACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__PAYACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__PAYACBRANCH!VARCHAR2~BLK_ACC_DET_BODY_1__PAYACCCIF!VARCHAR2~BLK_ACC_DET_BODY_1__PAYACCCIF!VARCHAR2~BLK_ACC_DET_BODY_1__PAYACCCIF!VARCHAR2~BLK_OLTMS_INSTR_HDR__PRODUCTCODE!VARCHAR2","N~N~N",""],"BLK_ACC_DET_BODY_1__PAYACCOUNTCCY__LOV_PAY_AC_CCY":["BLK_ACC_DET_BODY_1__PAYACCOUNTCCY~~","","N~N",""],"BLK_ACC_DET_BODY_1__RECVACCCIF__LOV_RECVACC_CIF":["BLK_ACC_DET_BODY_1__RECVACCCIF~~","","N~N",""],"BLK_ACC_DET_BODY_1__PAYACCCIF__LOV_PAYACC_CIF":["BLK_ACC_DET_BODY_1__PAYACCCIF~~","","N~N",""],"BLK_ACC_DET_BODY_2__BANKOPERATIONCODE__LOV_BANK_OPERATION_CODE":["BLK_ACC_DET_BODY_2__BANKOPERATIONCODE~~","","N~N",""],"BLK_ACC_DET_BODY_2__ERICCY__LOV_ERI_CCY":["BLK_ACC_DET_BODY_2__ERICCY~~","","N~N",""],"BLK_ACC_DET_BODY_3__USDCLGNETWORK__LOV_USD_CLR_NET":["~BLK_ACC_DET_BODY_3__USDCLGNETWORK~","","N~N",""],"BLK_ACC_DET_BODY_3__INSTRUCTIONCODE6__LOV_INSTRUCTION_CODE6":["BLK_ACC_DET_BODY_3__INSTRUCTIONCODE6~BLK_ACC_DET_BODY_3__TXTINSTRCODE6~","","N~N",""],"BLK_ACC_DET_BODY_3__INSTRUCTIONCODE5__LOV_INSTRUCTION_CODE5":["BLK_ACC_DET_BODY_3__INSTRUCTIONCODE5~BLK_ACC_DET_BODY_3__TXTINSTRCODE5~","","N~N",""],"BLK_ACC_DET_BODY_3__INSTRUCTIONCODE4__LOV_INSTRUCTION_CODE4":["BLK_ACC_DET_BODY_3__INSTRUCTIONCODE4~BLK_ACC_DET_BODY_3__TXTINSTRCODE4~","","N~N",""],"BLK_ACC_DET_BODY_3__INSTRUCTIONCODE3__LOV_INSTRUCTION_CODE3":["BLK_ACC_DET_BODY_3__INSTRUCTIONCODE3~BLK_ACC_DET_BODY_3__TXTINSTRCODE3~","","N~N",""],"BLK_ACC_DET_BODY_3__INSTRUCTIONCODE2__LOV_INSTRUCTION_CODE2":["BLK_ACC_DET_BODY_3__INSTRUCTIONCODE2~BLK_ACC_DET_BODY_3__TXTINSTRCODE2~","","N~N",""],"BLK_ACC_DET_BODY_3__INSTRUCTIONCODE1__LOV_INSTRUCTION_CODE1":["BLK_ACC_DET_BODY_3__INSTRUCTIONCODE1~BLK_ACC_DET_BODY_3__TXTINSTRCODE1~","","N~N",""],"BLK_PAY_PART_BODY_1__ORDERINGINSTITUTION1__LOV_ORDERING_INSTITUTION":["BLK_PAY_PART_BODY_1__ORDERINGINSTITUTION1~~~","","N~N~N","N"],"BLK_PAY_PART_BODY_1__ULTIBENSORTCODE__LOV_ULT_BENF":["BLK_PAY_PART_BODY_1__ULTIBENSORTCODE~BLK_PAY_PART_BODY_1__TXTULTIBENFCD~","","N~N",""],"BLK_PAY_PART_BODY_1__BENEFINSTSORTCODE__LOV_BENF_INST":["BLK_PAY_PART_BODY_1__BENEFINSTSORTCODE~BLK_PAY_PART_BODY_1__TXTBENFSCODE~","","N~N",""],"BLK_PAY_PART_BODY_1__BENEFINSTITUTION2__LOV_BENEFICIARY_INST2":["BLK_PAY_PART_BODY_1__BENEFINSTITUTION2~~~","","N~N~N","N"],"BLK_PAY_PART_BODY_1__BENEFINSTITUTION1__LOV_BENEFICIARY_INST1":["BLK_PAY_PART_BODY_1__BENEFINSTITUTION1~~~","","N~N~N","N"],"BLK_PAY_PART_BODY_2__INTERMEDIARYSORTCODE__LOV_INTERMEDIARY":["BLK_PAY_PART_BODY_2__INTERMEDIARYSORTCODE~BLK_PAY_PART_BODY_2__TXTINTSCODE~","","N~N",""],"BLK_PAY_PART_BODY_2__INTERMEDIARY2__LOV_INTERMEDIARY2":["BLK_PAY_PART_BODY_2__INTERMEDIARY2~~~","","N~N~N","N"],"BLK_PAY_PART_BODY_2__INTERMEDIARY1__LOV_INTERMEDIARY1":["BLK_PAY_PART_BODY_2__INTERMEDIARY1~~~","","N~N~N","N"],"BLK_PAY_PART_BODY_2__RCVRCORRESP1__LOV_RECVR_CORRES":["BLK_PAY_PART_BODY_2__RCVRCORRESP1~~~","","N~N~N",""],"BLK_PAY_PART_BODY_2__INTREIMINST1__LOV_REIM_INSTN":["BLK_PAY_PART_BODY_2__INTREIMINST1~~~","","N~N~N",""],"BLK_PAY_PART_BODY_2__AWISORTCODE__LOV_ACCT_INST":["BLK_PAY_PART_BODY_2__AWISORTCODE~BLK_PAY_PART_BODY_2__TXTAWISCODE~","","N~N",""],"BLK_PAY_PART_BODY_2__ACCWITHINSTN2__LOV_AWI2":["BLK_PAY_PART_BODY_2__ACCWITHINSTN2~~~","","N~N~N","N"],"BLK_PAY_PART_BODY_2__ACCWITHINSTN1__LOV_AWI":["BLK_PAY_PART_BODY_2__ACCWITHINSTN1~~~","","N~N~N","N"],"BLK_RCV_NOT_BODY__RECVINTERMEDIARY1__LOV_RECV_INTERMEDIARY":["BLK_RCV_NOT_BODY__RECVINTERMEDIARY1~~~","","N~N~N",""],"BLK_DD_PART_BODY__CREDITORSORTCODE__LOV_CRED_ACCT":["BLK_DD_PART_BODY__CREDITORSORTCODE~BLK_DD_PART_BODY__TXTCRESCODE~","","N~N",""],"BLK_DD_PART_BODY__DEBTORSORTCODE__LOV_DEBT_ACCT":["BLK_DD_PART_BODY__DEBTORSORTCODE~BLK_DD_PART_BODY__TXTDEBSCODE~","","N~N",""],"BLK_COV_CLR_DET__EXTPAYBANKCODE__LOV_PAY_BANKCODE":["BLK_COV_CLR_DET__EXTPAYBANKCODE~BLK_COV_CLR_DET__TXTEXTPAYDESC~","","N~N",""],"BLK_COV_CLR_DET__EXTRECVBANKCODE__LOV_RECV_BANKCODE":["BLK_COV_CLR_DET__EXTRECVBANKCODE~BLK_COV_CLR_DET__TXTEXTRECDESC~","","N~N",""],"BLK_COV_CLR_DET__EXTCOVERBANKCODE__LOV_COVER_BANK_CODE":["BLK_COV_CLR_DET__EXTCOVERBANKCODE~BLK_COV_CLR_DET__TXTCOVBANKDESC~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_ACCT_DET';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array();
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array(); 

 var CallFormRelat=new Array(); 

 var CallRelatType= new Array(); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDINSTR"]="KERNEL";
ArrPrntFunc["LBDINSTR"]="";
ArrPrntOrigin["LBDINSTR"]="";
ArrRoutingType["LBDINSTR"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDINSTR"]="N";
ArrCustomModified["LBDINSTR"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {};
var scrArgSource = {};
var scrArgVals = {};
var scrArgDest = {};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {};
var dpndntOnSrvs = {};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------