/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDPRMNT_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_PRODUCT":"PRDCD~PRDDESC~PRDGRP~PRDGRPDESC~PRDSLOGAN~PRDREMARKS~PRDSTARTDT~PRDENDDT~MODU~FORMATNAME~RTGSPROD~PRODTYPE~VALIDATEIBANFRRTGS~PREFPRDCD~PAYMNTMETHOD~SCHTYPE~NOTCEDAYBASIS~GRACEDAYS~DEFALTCLUSTER~ALLUSRINPINSTAL~ALLWREAMORTIZATION~ACCTLINKDEPOSIT~BILNGNOTICEDAYS~NORMALRATEVRNCE~MAXRATEVARNC~ACRLFREQNCY~ACURLSTARTMONTH~ACURLSTRTDATE~MINTENOR~STDTENOR~MAXTENOR~TENORUNIT~SCHDLELEVELPROCES~REVALBALMOVREQ~TRANSFRATHISTRICRATE~SPREADTYPE~BASISGAAP~BASISGAPDESC~LCTYPE~LCDRAWDWN~ONRATEREV~ONPREPAYMNT~UTLREVALREQRD~REVALFREQ~REVALRATECODE~REVALRATETYP~REVALSTRTMONTH~REVALSTARDATE~REVALTYPE~MINAMTCCY~MINAMTPARTLIQ~LIQMODE~PARTIALIQALOWED~INITIATIONMODE~PAYMNTSCHPROCSNG~RETAINPMNTSCHFREQ~TAXAPPLCBLE~ALLOWTAXREFND~TAXTYPE~INTFEEDISTRBTION~PAYPASTSCHDL~RLVRALLWD~CERTOFDEPOSIT~NEGOTIABLE~PREMPTWITHOLDSCH~FWDDATINGALLWD~INTRSTONSCHAMNT~SETTLEACCCHANGE~AERCALCREQD~APPLYLIMITBLCK~PRIMELOAN~ANNNIVERSRYBILLING~PRMPTAFTRMATURTY~TRACKPAYRCV~FLRCLRESTRICTED~PARTIALREDNFORCMT~HOLDPRPMTSINTLBROWSER~SETTLMNTMSG~TRACKACREDINTRST~PREPAYMNTPENALTY~ALLOWPREPMNT~ALLOWINSTALMNT~LIQDINTONPREPADSCHD~EFFTCUSTLOAN~RECOMPUTESCHEDULES~ROLINGLOAN~LIMITTRACKREQD~PARTIALINTRPMT~OVRPAYMNTALLOWED~TENORBASDSPREAD~VALIDTEASSGNMNT~CONFRM~EFFLOANRTE~EFFDEPRATE~TRACKDELIQNCY~PARTIALPRMTALLWD~AMENDCURRFUND~INCLUDEIN1098~SUPRSADVICES~MEDIAPRIORITY~PROPSTATTOLOAN~AGENCYCONTRACT~INTRADAYPRDT~REPRICEPRDT~COCVALUATIONREQD~SHFTNGFUNDSAPP~CHKFINRTE~CHKFINPOOL~CHKINFDEPT~CHKINFBRNCH~CHKINFCUSTMR~CHKINFCCCY~CHKINFPRNCPL~CHKINFVALDATE~CHKINFMATURITY~CHKINFRATE~CHKINFPOOLRATE~CHKFINDEPT~CHKFINBRNCH~CHKFINCUSTOMER~CHKFINCURRENCY~CHKFINPRINCPAL~CHKFINVALUDATE~CHKFINMATURITY~REKEYCCY~REKEYRATE~REKEYVALDATE~REKEYCONTRCTAMNT~REKEYCPARTY~REKYMATURITYDATE~BROKERAGEAPPLCBLE~REKEYINTRATE~REKYACFREFUNDAMNT~REKYACFVALDATE~REKYACFSTARTDATE~REKYACFENDDATE~ROLLCCY~ROLLREKVALDATE~ROLLREKAMNT~ROLLRKMATDATE~ROLLREKYINTRATE~ROLLREKYREFRATE~INSTALMNTDEPST~INSTALMENTLOAN~ILRATETYPE~ILRATECODE~ILINTCALCTYPE~ILBORROWLENDIND~ILINTRESTBASIS~ADJUSTMNTTYPE~INSDEPPROCESSING~INSDEPROUNDINGTYPE~INSDEPMATDLIMIT~INSDEPTNETTINGREQD~INDESPNETMAX~INDESHOLTREAT~APLYFACHOLCCY~APLYCONHOLCCY~APLYLOCHOLCCY~MOVPAYSCH~MOVREVSCH~MOVCOMREDSCH~MOVDISBSCH~CONSDRBRNCHHOLSCH~CONSBRNCHOLMAT~APFACHOLCCYMAT~APLCONTRHOLCCYMAT~APLLOCLHOLCCYMAT~MOVACRSMNTHMATVALDAT~IGNRHOLDMATVALDAT~REVOLREPMNTSCH~VALIDATEREPMNTSCH~REPYMNTPROCESING~AVAILBLTYEXPIRYPRO~CANCELLATIONPROCESS~PREPAYMNTPROCSING~HOLDAYCCYSCH~HOLDAYCCYMAT~REKEYACRCCY~REKEYACRFEAMNT~IGNOREHOLIDAYS~MOVEACROSSMONTH~SCHEDMVMNT~CASCDSCH~HOLIDAYCCY~HOLIDAYCHECK~APPLYPRNHOLTRT~APPLTPMTHOLTRT~RVNIGNOREHOL~RVNCHKRTCDCCY~RVNHOLCHECK~RVNHOLCCY~RVNMOVACRSMON~RVNCASCSCHD~RVNSCHMOV~APPLYVALDTHOLTRT~MATCHKCONTCCY~MATCHKLOCCY~MATCHKRTCDCCY~MATHOLCHK~MATHOLCCY~MSCHIGNHOL~MSCHMOVACRSMON~MSCHSCHMOV~POOLFUNDREQ~MASTERFUNDREQ~CHGFUTAMTSCH~CHGFUTRVNSCH~CHGFUTMATSCH~HOLTOWORKAFFCT~WORKTOHOLAFFCT~REVSNOTCDAYS~LOANSTMTCYC~LOANSTMTTYP~MINPRINBAL~DEFTRNTYP~STMTDAY~PRNHOLCHK~PRNHOLCCY~PRNIGNHOL~PRNCASSCH~PRNMOVACRSMON~PRNSCHMOV~PRDTYP~BRNLST~CCYLST~CATGLIS~NRMLRTVARI~MAXRTVARI~RTCODEPRFERD~RATETYPPRFERED~NETNEGINTEREST~PARTICIPANTPRODUCT~CASCADEPARTICIPATION~HOLIDAYDEFAULTBASIS~NOTICEDAYSBASIS~SCHEDULEMOVEMENTMATVALDT~PROD_CODE_UI~PROD_CODE_DESC_UI~PART_PROD_DESC_UI~CHKIGNOREHOLIDAY_TXT~SETTLEMENTREQD~BANKER_ACCEPTANCE~APPLY_FC_HOL_TREATMENT~APPLY_MAT_FC_HOL_TREATMENT~SGENDURING~ZERO_CASH_FLOW~ALLOW_DISCOUNTED_SCH~PRINCIPAL_ECA_CHK_REQD~MAKER~MAKERSTAMP~CHECKER~CHECKERSTAMP~MODNO~TXNSTAT~AUTHSTAT~ONCEAUTH","BLK_ROLLOVER_DETAILS":"PRDCD~PRDDESC~ROLLOVRICCFFROM~APPLYTAX~ROLLOVERWITHINTEST~UPDATEUTLSATON~DEDUCTTAXONROLLOVER~ROLLOVRTYPE~ROLLBY~ROLLOVRMECHANSM~ROLLOVRMETHD~ROLLRESTTENR~ROLLOVER~CONTBOOKADDLAMT~APPLCHRGE~LIQONSCHDLES~REPICKINTRATE~ROLLMATRTYBASIS","BLK_SCHEDULES_DETAILS":"PRDCD~PRDDESC~COMPONNT~STARTREFRNCE~FREQNCY~FREQNCYUNIT~STARTDATE~STARTMONTH~SCHEDULTYPE","BLK_LIQORDER_DETAILS":"PROD~PRDDESC~COMP~LIQORD~COMPAUTOLIQ~GENMSG~STAT","BLK_PENALTYCOMP_DETAILS":"PRODUCT_CODE~COMPONENT~LATE_PAYMENT_PENALTY","BLK_PRDSTAT_MASTER":"PROD~PRODDESC~STAT~STATDESC~STATSEQ~ADVSTAT","BLK_DISCLOSURE":"PRODUCTCODE~PRODUCTDESC~DISCLOSURECODE~DISCLOSUREDESC","BLK_LS_ADD_PREF":"PRODUCTCODE~CCY~EXCHRATEFIXINGDAYS~INTRATEFIXINGDAYS~EXCHRATEFIXINGTIME~DDNOTIFICATIONDAYS~DDNOTIFICATIONTIME~CANCELLATIONDAYS","BLK_LSTM_PRODUCT_EXRATE_CCY":"PRODUCT~EXRATECCY~HOLIDAYCCY","BLK_LSTM_PRODUCT_INTRATE_CCY":"PRODUCT~INTRATECCY~HOLIDAYCCY","BLK_LSTM_PRODUCT_NOTICE_CCY":"PRODUCT~NOTICECCY~HOLIDAYCCY","BLK_PRODUCT_STATUS_COMPS":"MATURITY_DAYS~TRANSFER_DAYS~COMPONENT~STATUS~PRODUCT","BLK_PRODUCT_STATUS_ADVICES":"MSG_CODE~STATUS~PRODUCT","BLK_PRODUCT_STATUS_GL":"REVERSAL_GL~GL_AMT_TFR~TRANSFER_GL~ACCOUNT_ROLE~STATUS~PRODUCT","BLK_PROD_FINCENTRE_SCH":"FIN_CENTRE~FIN_CENTRE_DESC~PRODUCT_CODE~SCHEDULE_TYPE","BLK_PROD_FINCENTRE_MAT":"FIN_CENTRE~FIN_CENTRE_DESC~PRODUCT_CODE~SCHEDULE_TYPE"};

var multipleEntryPageSize = {"BLK_PENALTYCOMP_DETAILS" :"15" ,"BLK_SCHEDULES_DETAILS" :"15" ,"BLK_LIQORDER_DETAILS" :"15" ,"BLK_PRDSTAT_MASTER" :"15" ,"BLK_DISCLOSURE" :"15" ,"BLK_LS_ADD_PREF" :"15" ,"BLK_LSTM_PRODUCT_EXRATE_CCY" :"15" ,"BLK_LSTM_PRODUCT_INTRATE_CCY" :"15" ,"BLK_LSTM_PRODUCT_NOTICE_CCY" :"15" ,"BLK_PROD_FINCENTRE_SCH" :"15" ,"BLK_PROD_FINCENTRE_MAT" :"15" };

var multipleEntrySVBlocks = "";

var tabMEBlks = {"CVS_SPECIALPENALTY__TAB_MAIN":"BLK_PENALTYCOMP_DETAILS","CVS_DEFLTSCHDLES__TAB_MAIN":"BLK_SCHEDULES_DETAILS","CVS_LIQ_ORDER__TAB_MAIN":"BLK_LIQORDER_DETAILS","CVS_STATUSMASTER__TAB_MAIN":"BLK_PRDSTAT_MASTER","CVS_DISCLOSURE__TAB_MAIN":"BLK_DISCLOSURE","CVS_PREFERENCES__TAB_LS_ADDL_PREF":"BLK_LS_ADD_PREF~BLK_LSTM_PRODUCT_EXRATE_CCY~BLK_LSTM_PRODUCT_INTRATE_CCY~BLK_LSTM_PRODUCT_NOTICE_CCY","CVS_PREFERENCES__TAB_HOLIDAYPREF":"BLK_PROD_FINCENTRE_SCH~BLK_PROD_FINCENTRE_MAT"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_PRODUCT">PRDCD~PRDDESC~PRDGRP~PRDGRPDESC~PRDSLOGAN~PRDREMARKS~PRDSTARTDT~PRDENDDT~MODU~FORMATNAME~RTGSPROD~PRODTYPE~VALIDATEIBANFRRTGS~PREFPRDCD~PAYMNTMETHOD~SCHTYPE~NOTCEDAYBASIS~GRACEDAYS~DEFALTCLUSTER~ALLUSRINPINSTAL~ALLWREAMORTIZATION~ACCTLINKDEPOSIT~BILNGNOTICEDAYS~NORMALRATEVRNCE~MAXRATEVARNC~ACRLFREQNCY~ACURLSTARTMONTH~ACURLSTRTDATE~MINTENOR~STDTENOR~MAXTENOR~TENORUNIT~SCHDLELEVELPROCES~REVALBALMOVREQ~TRANSFRATHISTRICRATE~SPREADTYPE~BASISGAAP~BASISGAPDESC~LCTYPE~LCDRAWDWN~ONRATEREV~ONPREPAYMNT~UTLREVALREQRD~REVALFREQ~REVALRATECODE~REVALRATETYP~REVALSTRTMONTH~REVALSTARDATE~REVALTYPE~MINAMTCCY~MINAMTPARTLIQ~LIQMODE~PARTIALIQALOWED~INITIATIONMODE~PAYMNTSCHPROCSNG~RETAINPMNTSCHFREQ~TAXAPPLCBLE~ALLOWTAXREFND~TAXTYPE~INTFEEDISTRBTION~PAYPASTSCHDL~RLVRALLWD~CERTOFDEPOSIT~NEGOTIABLE~PREMPTWITHOLDSCH~FWDDATINGALLWD~INTRSTONSCHAMNT~SETTLEACCCHANGE~AERCALCREQD~APPLYLIMITBLCK~PRIMELOAN~ANNNIVERSRYBILLING~PRMPTAFTRMATURTY~TRACKPAYRCV~FLRCLRESTRICTED~PARTIALREDNFORCMT~HOLDPRPMTSINTLBROWSER~SETTLMNTMSG~TRACKACREDINTRST~PREPAYMNTPENALTY~ALLOWPREPMNT~ALLOWINSTALMNT~LIQDINTONPREPADSCHD~EFFTCUSTLOAN~RECOMPUTESCHEDULES~ROLINGLOAN~LIMITTRACKREQD~PARTIALINTRPMT~OVRPAYMNTALLOWED~TENORBASDSPREAD~VALIDTEASSGNMNT~CONFRM~EFFLOANRTE~EFFDEPRATE~TRACKDELIQNCY~PARTIALPRMTALLWD~AMENDCURRFUND~INCLUDEIN1098~SUPRSADVICES~MEDIAPRIORITY~PROPSTATTOLOAN~AGENCYCONTRACT~INTRADAYPRDT~REPRICEPRDT~COCVALUATIONREQD~SHFTNGFUNDSAPP~CHKFINRTE~CHKFINPOOL~CHKINFDEPT~CHKINFBRNCH~CHKINFCUSTMR~CHKINFCCCY~CHKINFPRNCPL~CHKINFVALDATE~CHKINFMATURITY~CHKINFRATE~CHKINFPOOLRATE~CHKFINDEPT~CHKFINBRNCH~CHKFINCUSTOMER~CHKFINCURRENCY~CHKFINPRINCPAL~CHKFINVALUDATE~CHKFINMATURITY~REKEYCCY~REKEYRATE~REKEYVALDATE~REKEYCONTRCTAMNT~REKEYCPARTY~REKYMATURITYDATE~BROKERAGEAPPLCBLE~REKEYINTRATE~REKYACFREFUNDAMNT~REKYACFVALDATE~REKYACFSTARTDATE~REKYACFENDDATE~ROLLCCY~ROLLREKVALDATE~ROLLREKAMNT~ROLLRKMATDATE~ROLLREKYINTRATE~ROLLREKYREFRATE~INSTALMNTDEPST~INSTALMENTLOAN~ILRATETYPE~ILRATECODE~ILINTCALCTYPE~ILBORROWLENDIND~ILINTRESTBASIS~ADJUSTMNTTYPE~INSDEPPROCESSING~INSDEPROUNDINGTYPE~INSDEPMATDLIMIT~INSDEPTNETTINGREQD~INDESPNETMAX~INDESHOLTREAT~APLYFACHOLCCY~APLYCONHOLCCY~APLYLOCHOLCCY~MOVPAYSCH~MOVREVSCH~MOVCOMREDSCH~MOVDISBSCH~CONSDRBRNCHHOLSCH~CONSBRNCHOLMAT~APFACHOLCCYMAT~APLCONTRHOLCCYMAT~APLLOCLHOLCCYMAT~MOVACRSMNTHMATVALDAT~IGNRHOLDMATVALDAT~REVOLREPMNTSCH~VALIDATEREPMNTSCH~REPYMNTPROCESING~AVAILBLTYEXPIRYPRO~CANCELLATIONPROCESS~PREPAYMNTPROCSING~HOLDAYCCYSCH~HOLDAYCCYMAT~REKEYACRCCY~REKEYACRFEAMNT~IGNOREHOLIDAYS~MOVEACROSSMONTH~SCHEDMVMNT~CASCDSCH~HOLIDAYCCY~HOLIDAYCHECK~APPLYPRNHOLTRT~APPLTPMTHOLTRT~RVNIGNOREHOL~RVNCHKRTCDCCY~RVNHOLCHECK~RVNHOLCCY~RVNMOVACRSMON~RVNCASCSCHD~RVNSCHMOV~APPLYVALDTHOLTRT~MATCHKCONTCCY~MATCHKLOCCY~MATCHKRTCDCCY~MATHOLCHK~MATHOLCCY~MSCHIGNHOL~MSCHMOVACRSMON~MSCHSCHMOV~POOLFUNDREQ~MASTERFUNDREQ~CHGFUTAMTSCH~CHGFUTRVNSCH~CHGFUTMATSCH~HOLTOWORKAFFCT~WORKTOHOLAFFCT~REVSNOTCDAYS~LOANSTMTCYC~LOANSTMTTYP~MINPRINBAL~DEFTRNTYP~STMTDAY~PRNHOLCHK~PRNHOLCCY~PRNIGNHOL~PRNCASSCH~PRNMOVACRSMON~PRNSCHMOV~PRDTYP~BRNLST~CCYLST~CATGLIS~NRMLRTVARI~MAXRTVARI~RTCODEPRFERD~RATETYPPRFERED~NETNEGINTEREST~PARTICIPANTPRODUCT~CASCADEPARTICIPATION~HOLIDAYDEFAULTBASIS~NOTICEDAYSBASIS~SCHEDULEMOVEMENTMATVALDT~PROD_CODE_UI~PROD_CODE_DESC_UI~PART_PROD_DESC_UI~CHKIGNOREHOLIDAY_TXT~SETTLEMENTREQD~BANKER_ACCEPTANCE~APPLY_FC_HOL_TREATMENT~APPLY_MAT_FC_HOL_TREATMENT~SGENDURING~ZERO_CASH_FLOW~ALLOW_DISCOUNTED_SCH~PRINCIPAL_ECA_CHK_REQD~MAKER~MAKERSTAMP~CHECKER~CHECKERSTAMP~MODNO~TXNSTAT~AUTHSTAT~ONCEAUTH</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="1" TYPE="BLK_ROLLOVER_DETAILS">PRDCD~PRDDESC~ROLLOVRICCFFROM~APPLYTAX~ROLLOVERWITHINTEST~UPDATEUTLSATON~DEDUCTTAXONROLLOVER~ROLLOVRTYPE~ROLLBY~ROLLOVRMECHANSM~ROLLOVRMETHD~ROLLRESTTENR~ROLLOVER~CONTBOOKADDLAMT~APPLCHRGE~LIQONSCHDLES~REPICKINTRATE~ROLLMATRTYBASIS</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_SCHEDULES_DETAILS">PRDCD~PRDDESC~COMPONNT~STARTREFRNCE~FREQNCY~FREQNCYUNIT~STARTDATE~STARTMONTH~SCHEDULTYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_LIQORDER_DETAILS">PROD~PRDDESC~COMP~LIQORD~COMPAUTOLIQ~GENMSG~STAT</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_PENALTYCOMP_DETAILS">PRODUCT_CODE~COMPONENT~LATE_PAYMENT_PENALTY</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_PRDSTAT_MASTER">PROD~PRODDESC~STAT~STATDESC~STATSEQ~ADVSTAT</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_DISCLOSURE">PRODUCTCODE~PRODUCTDESC~DISCLOSURECODE~DISCLOSUREDESC</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_LS_ADD_PREF">PRODUCTCODE~CCY~EXCHRATEFIXINGDAYS~INTRATEFIXINGDAYS~EXCHRATEFIXINGTIME~DDNOTIFICATIONDAYS~DDNOTIFICATIONTIME~CANCELLATIONDAYS</FN>'; 
msgxml += '      <FN PARENT="BLK_LS_ADD_PREF" RELATION_TYPE="N" TYPE="BLK_LSTM_PRODUCT_EXRATE_CCY">PRODUCT~EXRATECCY~HOLIDAYCCY</FN>'; 
msgxml += '      <FN PARENT="BLK_LS_ADD_PREF" RELATION_TYPE="N" TYPE="BLK_LSTM_PRODUCT_INTRATE_CCY">PRODUCT~INTRATECCY~HOLIDAYCCY</FN>'; 
msgxml += '      <FN PARENT="BLK_LS_ADD_PREF" RELATION_TYPE="N" TYPE="BLK_LSTM_PRODUCT_NOTICE_CCY">PRODUCT~NOTICECCY~HOLIDAYCCY</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="1" TYPE="BLK_PRODUCT_STATUS_COMPS">MATURITY_DAYS~TRANSFER_DAYS~COMPONENT~STATUS~PRODUCT</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="1" TYPE="BLK_PRODUCT_STATUS_ADVICES">MSG_CODE~STATUS~PRODUCT</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="1" TYPE="BLK_PRODUCT_STATUS_GL">REVERSAL_GL~GL_AMT_TFR~TRANSFER_GL~ACCOUNT_ROLE~STATUS~PRODUCT</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_PROD_FINCENTRE_SCH">FIN_CENTRE~FIN_CENTRE_DESC~PRODUCT_CODE~SCHEDULE_TYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_PRODUCT" RELATION_TYPE="N" TYPE="BLK_PROD_FINCENTRE_MAT">FIN_CENTRE~FIN_CENTRE_DESC~PRODUCT_CODE~SCHEDULE_TYPE</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_PRODUCT";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_PRODUCT">AUTHSTAT~TXNSTAT~PRDCD~PRDDESC~PRDGRP~PRDSLOGAN~PRDREMARKS~PRDSTARTDT~PRDENDDT</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDPRMNT";
var defaultWhereClause = "MODULE = 'LB'";
var defaultOrderByClause ="";
var multiBrnWhereClause ="MODULE = 'LB'";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_PRODUCT";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_PRODUCT" : "","BLK_ROLLOVER_DETAILS" : "BLK_PRODUCT~1","BLK_SCHEDULES_DETAILS" : "BLK_PRODUCT~N","BLK_LIQORDER_DETAILS" : "BLK_PRODUCT~N","BLK_PENALTYCOMP_DETAILS" : "BLK_PRODUCT~N","BLK_PRDSTAT_MASTER" : "BLK_PRODUCT~N","BLK_DISCLOSURE" : "BLK_PRODUCT~N","BLK_LS_ADD_PREF" : "BLK_PRODUCT~N","BLK_LSTM_PRODUCT_EXRATE_CCY" : "BLK_LS_ADD_PREF~N","BLK_LSTM_PRODUCT_INTRATE_CCY" : "BLK_LS_ADD_PREF~N","BLK_LSTM_PRODUCT_NOTICE_CCY" : "BLK_LS_ADD_PREF~N","BLK_PRODUCT_STATUS_COMPS" : "BLK_PRODUCT~1","BLK_PRODUCT_STATUS_ADVICES" : "BLK_PRODUCT~1","BLK_PRODUCT_STATUS_GL" : "BLK_PRODUCT~1","BLK_PROD_FINCENTRE_SCH" : "BLK_PRODUCT~N","BLK_PROD_FINCENTRE_MAT" : "BLK_PRODUCT~N"}; 

 var dataSrcLocationArray = new Array("BLK_PRODUCT","BLK_ROLLOVER_DETAILS","BLK_SCHEDULES_DETAILS","BLK_LIQORDER_DETAILS","BLK_PENALTYCOMP_DETAILS","BLK_PRDSTAT_MASTER","BLK_DISCLOSURE","BLK_LS_ADD_PREF","BLK_LSTM_PRODUCT_EXRATE_CCY","BLK_LSTM_PRODUCT_INTRATE_CCY","BLK_LSTM_PRODUCT_NOTICE_CCY","BLK_PRODUCT_STATUS_COMPS","BLK_PRODUCT_STATUS_ADVICES","BLK_PRODUCT_STATUS_GL","BLK_PROD_FINCENTRE_SCH","BLK_PROD_FINCENTRE_MAT"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDPRMNT.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDPRMNT.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_PRODUCT__PRDCD";
pkFields[0] = "BLK_PRODUCT__PRDCD";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_DISCLOSURE":["DISCLOSURECODE","DISCLOSUREDESC"],"BLK_LIQORDER_DETAILS":["COMP","COMPAUTOLIQ","GENMSG","LIQORD","STAT"],"BLK_LSTM_PRODUCT_EXRATE_CCY":["EXRATECCY","HOLIDAYCCY","PRODUCT"],"BLK_LSTM_PRODUCT_INTRATE_CCY":["HOLIDAYCCY","INTRATECCY","PRODUCT"],"BLK_LSTM_PRODUCT_NOTICE_CCY":["HOLIDAYCCY","NOTICECCY","PRODUCT"],"BLK_LS_ADD_PREF":["CANCELLATIONDAYS","CCY","DDNOTIFICATIONDAYS","DDNOTIFICATIONTIME","EXCHRATEFIXINGDAYS","EXCHRATEFIXINGTIME","INTRATEFIXINGDAYS","PRODUCTCODE"],"BLK_PENALTYCOMP_DETAILS":["COMPONENT","LATE_PAYMENT_PENALTY"],"BLK_PRDSTAT_MASTER":["ADVSTAT","STAT","STATDESC","STATSEQ"],"BLK_PRODUCT":["ACCTLINKDEPOSIT","ACRLFREQNCY","ACURLSTARTMONTH","ACURLSTRTDATE","ADJUSTMNTTYPE","AERCALCREQD","AGENCYCONTRACT","ALLOWINSTALMNT","ALLOWPREPMNT","ALLOWTAXREFND","ALLOW_DISCOUNTED_SCH","ALLUSRINPINSTAL","ALLWREAMORTIZATION","AMENDCURRFUND","ANNNIVERSRYBILLING","APFACHOLCCYMAT","APLCONTRHOLCCYMAT","APLLOCLHOLCCYMAT","APLYCONHOLCCY","APLYFACHOLCCY","APLYLOCHOLCCY","APPLTPMTHOLTRT","APPLYLIMITBLCK","APPLYPRNHOLTRT","APPLYVALDTHOLTRT","APPLY_FC_HOL_TREATMENT","APPLY_MAT_FC_HOL_TREATMENT","AVAILBLTYEXPIRYPRO","BANKER_ACCEPTANCE","BASISGAAP","BASISGAPDESC","BILNGNOTICEDAYS","BRNLST","BROKERAGEAPPLCBLE","CANCELLATIONPROCESS","CASCADEPARTICIPATION","CASCDSCH","CATGLIS","CCYLST","CERTOFDEPOSIT","CHGFUTAMTSCH","CHGFUTMATSCH","CHGFUTRVNSCH","CHKCASCADESCH_TXT","CHKFINBRNCH","CHKFINCURRENCY","CHKFINCUSTOMER","CHKFINDEPT","CHKFINMATURITY","CHKFINPOOL","CHKFINPRINCPAL","CHKFINRTE","CHKFINVALUDATE","CHKIGNOREHOLIDAY_TXT","CHKINFBRNCH","CHKINFCCCY","CHKINFCUSTMR","CHKINFDEPT","CHKINFMATURITY","CHKINFPOOLRATE","CHKINFPRNCPL","CHKINFRATE","CHKINFVALDATE","CHKMOVEACCCMONTHS_TXT","CHKRTCDCCY","COCVALUATIONREQD","CONFRM","CONSBRNCHOLMAT","CONSDRBRNCHHOLSCH","DEFALTCLUSTER","DEFTRNTYP","EFFDEPRATE","EFFLOANRTE","EFFTCUSTLOAN","FLRCLRESTRICTED","FORMATNAME","FWDDATINGALLWD","GRACEDAYS","HOLDAYCCYMAT","HOLDAYCCYSCH","HOLDPRPMTSINTLBROWSER","HOLIDAYCCY","HOLIDAYCHECK","HOLIDAYDEFAULTBASIS","HOLTOWORKAFFCT","IGNOREHOLIDAYS","IGNRHOLDMATVALDAT","ILBORROWLENDIND","ILINTCALCTYPE","ILINTRESTBASIS","ILRATECODE","ILRATETYPE","INCLUDEIN1098","INDESHOLTREAT","INDESPNETMAX","INITIATIONMODE","INSDEPMATDLIMIT","INSDEPPROCESSING","INSDEPROUNDINGTYPE","INSDEPTNETTINGREQD","INSTALMENTLOAN","INSTALMNTDEPST","INTFEEDISTRBTION","INTRADAYPRDT","INTRSTONSCHAMNT","LCDRAWDWN","LCTYPE","LIMITTRACKREQD","LIQDINTONPREPADSCHD","LIQMODE","LOANSTMTCYC","LOANSTMTTYP","MASTERFUNDREQ","MATCHKCONTCCY","MATCHKLOCCY","MATCHKRTCDCCY","MATHOLCCY","MATHOLCHK","MAXRATEVARNC","MAXRTVARI","MAXTENOR","MEDIAPRIORITY","MINAMTCCY","MINAMTPARTLIQ","MINPRINBAL","MINTENOR","MOVACRSMNTHMATVALDAT","MOVCOMREDSCH","MOVDISBSCH","MOVEACROSSMONTH","MOVPAYSCH","MOVREVSCH","MSCHIGNHOL","MSCHMOVACRSMON","MSCHSCHMOV","NEGOTIABLE","NETNEGINTEREST","NORMALRATEVRNCE","NOTICEDAYSBASIS","NRMLRTVARI","ONPREPAYMNT","ONRATEREV","OVRPAYMNTALLOWED","PARTIALINTRPMT","PARTIALIQALOWED","PARTIALPRMTALLWD","PARTIALREDNFORCMT","PARTICIPANTPRODUCT","PART_PROD_DESC_UI","PAYMNTSCHPROCSNG","PAYPASTSCHDL","POOLFUNDREQ","PRDCDLIQD","PRDCDLIQDDESC","PRDCDSCH","PRDCDSCHDESC","PRDCDSPLDESC","PRDCDSPLPN","PRDCDSTATUS","PRDCDSTATUSDESC","PRDDESC","PRDENDDTI","PRDGRP","PRDREMARKS","PRDSLOGAN","PRDSTARTDTI","PRDTYP","PREMPTWITHOLDSCH","PREPAYMNTPENALTY","PREPAYMNTPROCSING","PRIMELOAN","PRINCIPAL_ECA_CHK_REQD","PRMPTAFTRMATURTY","PRNCASSCH","PRNHOLCCY","PRNHOLCHK","PRNIGNHOL","PRNMOVACRSMON","PRNSCHMOV","PROD_CODE_DESC_UI","PROD_CODE_UI","PROPSTATTOLOAN","RATETYPPRFERED","RECOMPUTESCHEDULES","REKEYACRCCY","REKEYACRFEAMNT","REKEYCCY","REKEYCONTRCTAMNT","REKEYCPARTY","REKEYINTRATE","REKEYRATE","REKEYVALDATE","REKYACFENDDATE","REKYACFREFUNDAMNT","REKYACFSTARTDATE","REKYACFVALDATE","REKYMATURITYDATE","REPRICEPRDT","REPYMNTPROCESING","RETAINPMNTSCHFREQ","REVALBALMOVREQ","REVALFREQ","REVALRATECODE","REVALRATETYP","REVALSTARDATE","REVALSTRTMONTH","REVALTYPE","REVOLREPMNTSCH","REVSNOTCDAYS","RLVRALLWD","ROLINGLOAN","ROLLCCY","ROLLREKAMNT","ROLLREKVALDATE","ROLLREKYINTRATE","ROLLREKYREFRATE","ROLLRKMATDATE","RTCODEPRFERD","RVNCASCSCHD","RVNCHKRTCDCCY","RVNHOLCCY","RVNHOLCHECK","RVNIGNOREHOL","RVNMOVACRSMON","RVNSCHMOV","SCHDLELEVELPROCES","SCHEDMVMNT","SCHEDULEMOVEMENTMATVALDT","SETTLEACCCHANGE","SETTLEMENTREQD","SETTLMNTMSG","SGENDURING","SHFTNGFUNDSAPP","SPREADTYPE","STATLIQD","STDTENOR","STMTDAY","SUPRSADVICES","TAXAPPLCBLE","TAXTYPE","TENORBASDSPREAD","TENORUNIT","TRACKACREDINTRST","TRACKDELIQNCY","TRACKPAYRCV","TRANSFRATHISTRICRATE","UTLREVALREQRD","VALIDATEREPMNTSCH","VALIDTEASSGNMNT","WORKTOHOLAFFCT","ZERO_CASH_FLOW"],"BLK_PROD_FINCENTRE_MAT":["FIN_CENTRE","FIN_CENTRE_DESC","PRODUCT_CODE","SCHEDULE_TYPE"],"BLK_PROD_FINCENTRE_SCH":["FIN_CENTRE","FIN_CENTRE_DESC","PRODUCT_CODE","SCHEDULE_TYPE"],"BLK_ROLLOVER_DETAILS":["APPLCHRGE","APPLYTAX","CONTBOOKADDLAMT","DEDUCTTAXONROLLOVER","LIQONSCHDLES","REPICKINTRATE","ROLLBY","ROLLMATRTYBASIS","ROLLOVER","ROLLOVERWITHINTEST","ROLLOVRICCFFROM","ROLLOVRMECHANSM","ROLLOVRTYPE","ROLLRESTTENR","UPDATEUTLSATON"],"BLK_SCHEDULES_DETAILS":["COMPONNT","FREQNCY","FREQNCYUNIT","SCHEDULTYPE","STARTDATE","STARTMONTH","STARTREFRNCE"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_PRODUCT__PRDGRP__LOV_GROUPS":["BLK_PRODUCT__PRDGRP~BLK_PRODUCT__PRDGRPDESC~","","N~N",""],"BLK_PRODUCT__FORMATNAME__LOV_FORMAT_NAME":["BLK_PRODUCT__FORMATNAME~~","","N~N",""],"BLK_PRODUCT__DEFALTCLUSTER__LOV_CLUSTER":["BLK_PRODUCT__DEFALTCLUSTER~~","","N~N",""],"BLK_PRODUCT__BASISGAAP__LOV_BASIS_GAP":["BLK_PRODUCT__BASISGAAP~BLK_PRODUCT__BASISGAPDESC~","","N~N",""],"BLK_PRODUCT__REVALRATECODE__LOV_REVAL_RATE_TYPE":["BLK_PRODUCT__REVALRATECODE~~","","N~N",""],"BLK_PRODUCT__MINAMTCCY__LOV_MIN_AMT_CCY":["BLK_PRODUCT__MINAMTCCY~","","N",""],"BLK_PRODUCT__ILRATECODE__LOV_RATE_CODE_PP":["BLK_PRODUCT__ILRATECODE~","","N",""],"BLK_PRODUCT__HOLDAYCCYSCH__LOV_OTHER_HOLIDAY_CCY":["BLK_PRODUCT__HOLDAYCCYSCH~~","","N~N",""],"BLK_PRODUCT__HOLDAYCCYMAT__LOV_OTHER_HOLIDAY_CURRENCY":["BLK_PRODUCT__HOLDAYCCYMAT~~","","N~N",""],"BLK_PRODUCT__HOLIDAYCCY__LOV_CCY":["BLK_PRODUCT__HOLIDAYCCY~~","","N~N",""],"BLK_PRODUCT__RVNHOLCCY__LOV_CCY":["BLK_PRODUCT__RVNHOLCCY~~","","N~N",""],"BLK_PRODUCT__MATHOLCCY__LOV_CCY":["BLK_PRODUCT__MATHOLCCY~~","","N~N",""],"BLK_PRODUCT__DEFTRNTYP__LOV_TRN_TYPES":["BLK_PRODUCT__DEFTRNTYP~~","","N~N",""],"BLK_PRODUCT__PRNHOLCCY__LOV_CCY":["BLK_PRODUCT__PRNHOLCCY~~","","N~N",""],"BLK_PRODUCT__RATETYPPRFERED__LOV_RATETYPE":["BLK_PRODUCT__RATETYPPRFERED~~","","N~N",""],"BLK_SCHEDULES_DETAILS__COMPONNT__LOV_SCH_COMPONENT":["BLK_SCHEDULES_DETAILS__COMPONNT~~","BLK_PRODUCT__PRDCDSCH!VARCHAR2","N~N",""],"BLK_LIQORDER_DETAILS__COMP__LOV_LIQ_COMPONENT":["BLK_LIQORDER_DETAILS__COMP~~","BLK_PRODUCT__PRDCD!VARCHAR2~BLK_PRODUCT__PRDCD!VARCHAR2~BLK_PRODUCT__PRDCD!VARCHAR2~BLK_PRODUCT__MODU!VARCHAR2","N~N","N"],"BLK_PRDSTAT_MASTER__STAT__LOV_STATUS":["BLK_PRDSTAT_MASTER__STAT~BLK_PRDSTAT_MASTER__STATDESC~","","N~N",""],"BLK_DISCLOSURE__DISCLOSURECODE__LOV_DISLCOSURE":["BLK_DISCLOSURE__DISCLOSURECODE~BLK_DISCLOSURE__DISCLOSUREDESC~","","N~N",""],"BLK_LS_ADD_PREF__CCY__LOV_CCY_PREF":["BLK_LS_ADD_PREF__CCY~~","","N~N",""],"BLK_LSTM_PRODUCT_EXRATE_CCY__HOLIDAYCCY__LOV_CCY":["BLK_LSTM_PRODUCT_EXRATE_CCY__HOLIDAYCCY~~","","N~N",""],"BLK_LSTM_PRODUCT_INTRATE_CCY__HOLIDAYCCY__LOV_CCY":["BLK_LSTM_PRODUCT_INTRATE_CCY__HOLIDAYCCY~~","","N~N",""],"BLK_LSTM_PRODUCT_NOTICE_CCY__HOLIDAYCCY__LOV_CCY":["BLK_LSTM_PRODUCT_NOTICE_CCY__HOLIDAYCCY~~","","N~N",""],"BLK_PROD_FINCENTRE_SCH__FIN_CENTRE__LOV_FINCENTRE":["BLK_PROD_FINCENTRE_SCH__FIN_CENTRE~BLK_PROD_FINCENTRE_SCH__FIN_CENTRE_DESC~","","N~N",""],"BLK_PROD_FINCENTRE_SCH__FIN_CENTRE_DESC__LOV_FINCENTRE":["BLK_PROD_FINCENTRE_SCH__FIN_CENTRE~BLK_PROD_FINCENTRE_SCH__FIN_CENTRE_DESC~","","N~N",""],"BLK_PROD_FINCENTRE_MAT__FIN_CENTRE__LOV_FINCENTRE":["BLK_PROD_FINCENTRE_MAT__FIN_CENTRE~BLK_PROD_FINCENTRE_MAT__FIN_CENTRE_DESC~","","N~N",""],"BLK_PROD_FINCENTRE_MAT__FIN_CENTRE_DESC__LOV_FINCENTRE":["BLK_PROD_FINCENTRE_MAT__FIN_CENTRE~BLK_PROD_FINCENTRE_MAT__FIN_CENTRE_DESC~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_PENALTYCOMP_DETAILS","BLK_SCHEDULES_DETAILS","BLK_LIQORDER_DETAILS","BLK_PRDSTAT_MASTER","BLK_DISCLOSURE","BLK_LS_ADD_PREF","BLK_LSTM_PRODUCT_EXRATE_CCY","BLK_LSTM_PRODUCT_INTRATE_CCY","BLK_LSTM_PRODUCT_NOTICE_CCY","BLK_PROD_FINCENTRE_SCH","BLK_PROD_FINCENTRE_MAT");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("OLCACRHM~BLK_PRODUCT","OLCACADD~BLK_PRODUCT","LFCPRCHG~BLK_PRODUCT","LFCLSFEE~BLK_PRODUCT","OLCACRCL~BLK_PRODUCT","OLCPDFDM~BLK_PRODUCT","LFCPRDIA~BLK_PRODUCT","LFCPRACF~BLK_PRODUCT","OLCPRMNT~BLK_PRODUCT","LFCPRTAX~BLK_PRODUCT","LFCLICCF~BLK_PRODUCT","LFCROPAR~BLK_PRODUCT"); 

 var CallFormRelat=new Array("OLTMS_PRODUCT.PRODUCT_CODE = OLTMS_PRODUCT__RH.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=CSTM_PRODUCT__AC.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=CSTMS_PRODUCT__CH.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=CSTMS_PRODUCT_FE.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=OLTMS_PRODUCT__AD.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=CSTM_PRODUCT__CD.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=OLTMS_PRODUCT__DY.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE = OLTMS_PRODUCT__AC.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=OLTMS_PRODUCT__MI.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=OLTMS_PRODUCT__TA.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=OLTMS_PRODUCT__ICCF.PRODUCT_CODE","OLTMS_PRODUCT.PRODUCT_CODE=OLTMS_PRODUCT__OLPRD.PRODUCT_CODE"); 

 var CallRelatType= new Array("1","1","1","1","1","1","1","1","1","1","1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDPRMNT"]="KERNEL";
ArrPrntFunc["LBDPRMNT"]="";
ArrPrntOrigin["LBDPRMNT"]="";
ArrRoutingType["LBDPRMNT"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDPRMNT"]="N";
ArrCustomModified["LBDPRMNT"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_PREFERENCES":"PRDCD~PRDDESC","CVS_SPECIALPENALTY":"PRDCD~PRDDESC","CVS_DEFLTSCHDLES":"PRDCD~PRDDESC","CVS_LIQ_ORDER":"PRDCD~PRDDESC","CVS_ROLLOVER":"PRDCD~PRDDESC","CVS_STATUSMASTER":"PRDCD~PRDDESC","CVS_DISCLOSURE":"PRDCD~PRDDESC","OLCACRHM":"MODULE~PRDCD~PRDDESC~PRDTYP~PRD","OLCACADD":"MODULE~PRDCD~PRDDESC~PRDTYP","LFCPRCHG":"PROD~PRODDESC~MODU~PRODTYPE~MOD","LFCLSFEE":"PROD~PRODDESC~MODU~PRODTYPE","OLCACRCL":"PRDCD~PRDDESC~PRD","OLCPDFDM":"PRDCD~PRDDESC","LFCPRDIA":"PRDCD~PRDDESC~MODU~PRDTYP","LFCPRACF":"PRDCD~PRDDESC~MODU~PRDTYP~PRD","OLCPRMNT":"PRDCD","LFCPRTAX":"PRDCD~PRDDESC~MODU~PRDTYP~PRD","LFCLICCF":"PRDCD~PRDDESC~MODULE","LFCROPAR":"PRODUCT_CODE~PRODUCT_DESCRIPTION"};
var scrArgSource = {"CVS_PREFERENCES":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC","CVS_SPECIALPENALTY":"BLK_PRODUCT__PREFPRDCD~BLK_PRODUCT__PREFPRDDESCR","CVS_DEFLTSCHDLES":"BLK_PRODUCT__PREFPRDCD~BLK_PRODUCT__PREFPRDDESCR","CVS_LIQ_ORDER":"BLK_PRODUCT__PREFPRDCD~BLK_PRODUCT__PREFPRDDESCR","CVS_ROLLOVER":"BLK_PRODUCT__PREFPRDCD~BLK_PRODUCT__PREFPRDDESCR","CVS_STATUSMASTER":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC","CVS_DISCLOSURE":"BLK_PRODUCT__PREFPRDCD~BLK_PRODUCT__PREFPRDDESCR","OLCACRHM":"BLK_PRODUCT__MODU~BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__PRODTYPE~BLK_PRODUCT__PRDCD","OLCACADD":"BLK_PRODUCT__MODU~BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__PRODTYPE","LFCPRCHG":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__MODU~BLK_PRODUCT__PRODTYPE~BLK_PRODUCT__MODU","LFCLSFEE":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__MODU~BLK_PRODUCT__PRODTYPE","OLCACRCL":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__PRDCD","OLCPDFDM":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC","LFCPRDIA":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__MODU~BLK_PRODUCT__PRODTYPE","LFCPRACF":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__MODU~BLK_PRODUCT__PRODTYPE~BLK_PRODUCT__PRDCD","OLCPRMNT":"BLK_PRODUCT__PRDCD","LFCPRTAX":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__MODU~BLK_PRODUCT__PRODTYPE~BLK_PRODUCT__PRDCD","LFCLICCF":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC~BLK_PRODUCT__MODU","LFCROPAR":"BLK_PRODUCT__PRDCD~BLK_PRODUCT__PRDDESC"};
var scrArgVals = {"CVS_PREFERENCES":"~","CVS_SPECIALPENALTY":"~","CVS_DEFLTSCHDLES":"~","CVS_LIQ_ORDER":"~","CVS_ROLLOVER":"~","CVS_STATUSMASTER":"~","CVS_DISCLOSURE":"~","OLCACRHM":"~~~~","OLCACADD":"~~~","LFCPRCHG":"~~~~","LFCLSFEE":"~~~","OLCACRCL":"~~","OLCPDFDM":"~","LFCPRDIA":"~~~","LFCPRACF":"~~~~","OLCPRMNT":"","LFCPRTAX":"~~~~","LFCLICCF":"~~","LFCROPAR":"~"};
var scrArgDest = {"CVS_PREFERENCES":"BLK_PRODUCT__PREFPRDCD~BLK_PRODUCT__PREFPRDDESCR","CVS_SPECIALPENALTY":"BLK_PRODUCT__PRDCDSPLPN~BLK_PRODUCT__PRDCDSPLDESC","CVS_DEFLTSCHDLES":"BLK_PRODUCT__PRDCDSCH~BLK_PRODUCT__PRDCDSCHDESC","CVS_LIQ_ORDER":"BLK_PRODUCT__PRDCDLIQD~BLK_PRODUCT__PRDCDLIQDDESC","CVS_ROLLOVER":"BLK_ROLLOVER_DETAILS__PRDCD~BLK_ROLLOVER_DETAILS__PRDDESC","CVS_STATUSMASTER":"BLK_PRODUCT__PRDCDSTATUS~BLK_PRODUCT__PRDCDSTATUSDESC","CVS_DISCLOSURE":"BLK_DISCLOSURE__PRODUCTCODE~BLK_DISCLOSURE__PRODUCTDESC"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"OLCACRHM":"","OLCACADD":"","LFCPRCHG":"","LFCLSFEE":"","OLCACRCL":"","OLCPDFDM":"","LFCPRDIA":"","LFCPRACF":"","OLCPRMNT":"","LFCPRTAX":"","LFCLICCF":"","LFCROPAR":""};
var dpndntOnSrvs = {"OLCACRHM":"","OLCACADD":"","LFCPRCHG":"","LFCLSFEE":"","OLCACRCL":"","OLCPDFDM":"","LFCPRDIA":"","LFCPRACF":"","OLCPRMNT":"","LFCPRTAX":"","LFCLICCF":"","LFCROPAR":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"2","DELETE":"2","CLOSE":"2","REOPEN":"2","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------