/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDPTFR_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_OLTBS_CONTRACT":"MODULECODE~CONTRACTSTATUS~CONTRACTREFNO~TREASURYSOURCE~PRODUCTCODE~PRODUCTTYPE~BRANCH~DEPARTMENTCODE~AUTHSTATUS~USERREFNO~COUNTERPARTY~LATESTEVENTSEQNO~LATESTVERSIONNO~TXT_AUTH_CUSTNAME1~TXT_AUTH_CUSTNAME2~TXT_UNAUTH_CUSTNAME1~TXT_UNAUTH_CUSTNAME2~SELF_PARTICIPATION~ORIGINATOR~NETTING_PREF~SSI_MNEMONIC~PARTICIPANT_TYPE~CONTRACTCCY~TXT_SUM_TRF_AMT~TXT_SUM_TRF_AMT2~FEE_CONTREFNO_UI~FEE_USEREFNO_UI~FEE_PART_PROD_CODE_UI~FEE_PART_PROD_DESC_UI~FEE_TXT_COMPONENT~FEE_TXT_FEE_RULE~TXT_LOG~TXT_VAL_DATE~TXT_EVENT_SEQ_NO~TXT_ENTRY_SEQ_NO~TXT_TABLE_TYPE~TXT_SUMMARY_ID~SIMULATE","BLK_LBVWS_BORROWER_DETAILS":"BORROWER_NAME~CONTRACTREFNO~FCCONTRACTREFNO~FCUSERREFNO~TRCONTRACTREFNO~TRUSERREFNO~DRCONTRACTREFNO~DRUSERREFNO~DRAWDOWNNO~BORROWER~CONTRACTTYPE","BLK_LBVWS_TRANSFER_MASTER":"ESN~VALUEDATE~TRANSFERTYPE~CONTRACTREFNO~TRANSFERREFNO~TABLETYPE~ENTRYSEQNO~AUTH_STAUS","BLK_LBTWS_TRANSFER_MASTER":"TXNSTAT~AUTHSTAT~TXT_PROCESS_STATUS~CHECKER_ID~CHECKER_DT_STAMP~MAKERID~FIRSTTIMEBUY~PAMBESN~ENTRYSEQNO~PAMIESN~USERREFNO~AUTHSTATUS~MAKERDTSTAMP~CONTRACTREFNO~TRANSFERSTATUS~TRANSFERTYPE~BRANCH~TRANSFERREFNO~VALUEDATE~ACCENTRYREQUIRED~TRANSACTIONDATE~CONTRACTSTATUS~CASCADE_PARTICIPATION~INSTRUCTION_TYPE~HFS_TRANSFER~TXT_TICKET_ID~TXT_TRANSFER_STATUS","BLK_LBTWS_PART_TRANSFER_MASTER":"ENTRYSEQNO~TRANSFERFROM~SEQNO~TRANSFERORFEEAMT~VALUEDATE~CONTRACTREFNO~TRANSFERFEEBY~TXT_PARTICIPANT_NAME~UPDT_LT_POS","BLK_LBTWS_PART_TRANSFER":"IS3WAYTFR~ENTRYSEQNO~AMOUNT3WAY~SEQNO~TRANSFERFROM~TRANSFEREEOLDAMT~TICKETID~VALUEDATE~HFSTRANSFER~TRANSFEREEFEEAMT~TRANFERTO~TRANSFEREENEWAMT~TRANSFEROROLDAMT~TRANSFERRATIO~TRANSFERORNEWAMT~TRANSFERAMT~TRANSFEBY3WAY~TRANSFERPRICE~CONTRACTREFNO~TXT_TRANSFEROR_NAME~TXT_TRANSFEREE_NAME~TXT_INTERMEDIATOR_NAME","BLK_LBTWS_CONSOL_TRANSFER":"ENTRYSEQNO~PARTICIPANT~CONTRACTREFNO~TRANSFERPRICE~TRANSFERAMT~EVENTSEQNO~PARTICIPANTNEWAMT~VALUEDATE~PARTICIPANTOLDAMT~SENDMESSAGE~HFSTRANSFER~TRANSFERRATIO~TXT_CONSOL_PARTY_NAME~UPDT_LT_POS","BLK_OLTBS_CONTRACT_EVENT_LOG":"TXT_CONTRACT_STATUS~TXT_AUTH_STATUS~AUTHSTATUS~CHECKERDTSTAMP~CHECKERID~CONTRACTREFNO~CONTRACTSTATUS~EVENTCODE~EVENTSEQNO~MAKERDTSTAMP~MAKERID~NEWVERSIONINDICATOR","BLK_LBTWS_PRAM_FEE_TEMP":"TXT_PARTICIPANT_NAME~TXT_COMPONENT_STATUS~COMPONENT~PARTICIPANT~COMPONENTCCY~ASSOCIATIONDATE~VALUEDATE~CONTRACTREFNO~COMPONENTSTATUS~COMPONENTONCEAUTH~FEEAMT~FEERULE~ENDDATE~STARTDATE~ENTRYSEQNO~TRANSFERFEEBY~FEECOLLECTIONMODE","BLK_CONTRACT_PARTICIPANT":"SETTLEMENTSEQNO~OPERATION~ASSETRATIO~VERSIONNO~SELFPARTICIPATION~VALUEDATE~NETTINGPREF~ORIGINATOR~DRAWDOWNNO~SSIMNEMONIC~CONTRACTREFNO~ENTRYSEQNO~CONTRACTTYPE~TXT_PART_NAME~TXT_ASSET_AMOUNT~PARTICIPANT~PARTICIPANT_TYPE_UI~ASSET_AMOUNT~LMAPARTICIPATION~SWINGLINE_PARTICIPANT~SILENTPART","BLK_PARTICIPANT_RATIO":"DRAWDOWNNO~CONTRACTREFNO~CUSTOMERNO~ENTRYSEQNO~SSIPICKUPAT~SSIMNEMONIC~VALUEDATE~SETTLEMENTSEQNO~VERSIONNO~COMPONENT~CONTRACTTYPE~COMPONENTRATIO~FEEBPSRATE~COMPONENTTYPE","BLK_OLTWS_CONTRACT_ENTITY":"TXT_ENTITY_NAME~CONTRACTTYPE~VALUEDATE~CUSTOMERNO~DRAWDOWNNO~REMARKS~ENTRYSEQNO~CONTRACTREFNO~PRIMARYENTITY~ENTITYID","BLK_LBTWS_PART_SETTLE_CURR_DET":"CONTRACTTYPE~ENTRYSEQNO~VALUEDATE~SSIMNEMONIC~DRAWDOWNNO~PARTICIPANT~CONTRACTREFNO~SETTLEMENTSEQNO~CURRENCY","BLK_LOR_ADJ_DTLS":"ACCOUNT_ENTRIES_CREATED~ACTUAL_TRANSFEREE_AMT~ACTUAL_TRANSFEROR_AMT~BUY_PARTY_CONTRACT_REF_NO~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~CURRENCY~DIFF_AMNT~EVENT_SEQ_NO~SELL_PARTY_CONTRACT_REF_NO~SETTLE_ACCURED_AMT~TRADE_REF_NO~TRANSFEREE~TRANSFEREE_AMT~TRANSFEROR~TRANSFEROR_AMT~USER_REF_NO~VALUE_DATE~SILENT_PART~SILENT_PART_ACC_ENTRY_CREATED","BLK_COLL_TRANSFER":"CONTRACT_REF_NO~CUSTOMER_NO~TRANCHE_REF_NO~EVENT_SEQ_NO","BLK_COLL_TRANSFER_DETAILS":"AMT_TAG~BLOCK_REF_NO~BRANCH_CODE~COLLATERAL_CATEGORY~COMMITMENT_PRODUCT~CONTRACT_REF_NO~CUSTOMER_NO~DESCRIPTION~HAIRCUT~LIMIT_AMOUNT~LINKAGE_BRANCH~LINKAGE_CURRENCY~LINKAGE_TYPE~LINKED_AMOUNT~LINKED_PERCENT_NUMBER~LINKED_REFERENCE_NO~OVERALL_AMOUNT~PARTICIPANT~REINSTATE_ORDER~STATUS~TAKEN_OVER~UTIL_ACTION~UTIL_AMOUNT~UTIL_CCY~UTIL_ORDER~VERSION_NO~EVENT_SEQ_NO~TXTPARTNAME","BLK_SILENT_DETAILS":"CONTRACT_REF_NO~EVENT_SEQ_NO~PARTICIPANT~CCY~TRANSFER_AMOUNT","BLK_RELCON":"CONTRACT_REF_NO~CUSTOMER_NO~EVENT_SEQ_NO~TRANCHE_REF_NO~PRODUCT_CODE~CURRENCY","BLK_NONCASCPART":"ASSET_AMOUNT~ASSET_RATIO~CONTRACT_REF_NO~CONTRACT_TYPE~DRAWDOWN_NO~ENTRY_SEQ_NO~LMA_PARTICIPATION~NETTING_PREF~OPERATION~ORIGINATOR~PARTICIPANT~SELF_PARTICIPATION~SETTLEMENT_SEQ_NO~SILENT_PARTICIPANT~SSI_MNEMONIC~SWINGLINE_PARTICIPANT~VALUE_DATE~VERSION_NO~EVENT_SEQ_NO","BLK_NONCASCSSI":"CONTRACT_REF_NO~CONTRACT_TYPE~CURRENCY~DRAWDOWN_NO~ENTRY_SEQ_NO~EVENT_SEQ_NO~PARTICIPANT~SETTELMENT_SEQ_NO~SSI_MNEMONIC~VALUE_DATE","BLK_NONCASCENTITY":"CONTRACT_REF_NO~CONTRACT_TYPE~CUSTOMER_NO~DRAWDOWN_NO~ENTITY_ID~ENTRY_SEQ_NO~EVENT_SEQ_NO~PRIMARY_ENTITY~REMARKS~VALUE_DATE","BLK_TRNNONCASC":"AMOUNT_3WAY~CONTRACT_REF_NO~ENTRY_SEQ_NO~EVENT_SEQ_NO~EXT_TRADE_ID~HFS_TRANSFER~IS_3WAY_TFR~SEQ_NO~TICKET_ID~TRANSFEREE_FEE_AMT~TRANSFEREE_NEW_AMT~TRANSFEREE_OLD_AMT~TRANSFEROR_NEW_AMT~TRANSFEROR_OLD_AMT~TRANSFER_AMT~TRANSFER_BY_3WAY~TRANSFER_FROM~TRANSFER_PRICE~TRANSFER_RATIO~TRANSFER_TO~UPDATE_LT_POSITION~VALUE_DATE"};

var multipleEntryPageSize = {"BLK_LBTWS_PART_SETTLE_CURR_DET" :"15" ,"BLK_OLTWS_CONTRACT_ENTITY" :"15" ,"BLK_LBTWS_PART_TRANSFER_MASTER" :"15" ,"BLK_LBTWS_PART_TRANSFER" :"15" ,"BLK_LBTWS_CONSOL_TRANSFER" :"15" ,"BLK_CONTRACT_PARTICIPANT" :"15" ,"BLK_PARTICIPANT_RATIO" :"15" ,"BLK_LBTWS_PRAM_FEE_TEMP" :"15" ,"BLK_LOR_ADJ_DTLS" :"15" ,"BLK_COLL_TRANSFER" :"15" ,"BLK_COLL_TRANSFER_DETAILS" :"15" ,"BLK_SILENT_DETAILS" :"15" ,"BLK_RELCON" :"15" ,"BLK_NONCASCPART" :"15" ,"BLK_NONCASCSSI" :"15" ,"BLK_NONCASCENTITY" :"15" ,"BLK_TRNNONCASC" :"15" };

var multipleEntrySVBlocks = "";

var tabMEBlks = {"CVS_MAIN__TAB_PARTICIPANT":"BLK_LBTWS_PART_SETTLE_CURR_DET~BLK_OLTWS_CONTRACT_ENTITY~BLK_LBTWS_PART_TRANSFER_MASTER~BLK_LBTWS_PART_TRANSFER~BLK_LBTWS_CONSOL_TRANSFER~BLK_CONTRACT_PARTICIPANT~BLK_PARTICIPANT_RATIO~BLK_LOR_ADJ_DTLS","CVS_FEES__TAB_MAIN":"BLK_LBTWS_PRAM_FEE_TEMP","CVS_MAIN__TAB_LINKAGES":"BLK_COLL_TRANSFER~BLK_COLL_TRANSFER_DETAILS","CVS_SILENT__TAB_MAIN":"BLK_SILENT_DETAILS","CVS_MAIN__TAB_NONCASC":"BLK_RELCON~BLK_NONCASCPART~BLK_NONCASCSSI~BLK_NONCASCENTITY~BLK_TRNNONCASC"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT">MODULECODE~CONTRACTSTATUS~CONTRACTREFNO~TREASURYSOURCE~PRODUCTCODE~PRODUCTTYPE~BRANCH~DEPARTMENTCODE~AUTHSTATUS~USERREFNO~COUNTERPARTY~LATESTEVENTSEQNO~LATESTVERSIONNO~TXT_AUTH_CUSTNAME1~TXT_AUTH_CUSTNAME2~TXT_UNAUTH_CUSTNAME1~TXT_UNAUTH_CUSTNAME2~SELF_PARTICIPATION~ORIGINATOR~NETTING_PREF~SSI_MNEMONIC~PARTICIPANT_TYPE~CONTRACTCCY~TXT_SUM_TRF_AMT~TXT_SUM_TRF_AMT2~FEE_CONTREFNO_UI~FEE_USEREFNO_UI~FEE_PART_PROD_CODE_UI~FEE_PART_PROD_DESC_UI~FEE_TXT_COMPONENT~FEE_TXT_FEE_RULE~TXT_LOG~TXT_VAL_DATE~TXT_EVENT_SEQ_NO~TXT_ENTRY_SEQ_NO~TXT_TABLE_TYPE~TXT_SUMMARY_ID~SIMULATE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="1" TYPE="BLK_LBVWS_BORROWER_DETAILS">BORROWER_NAME~CONTRACTREFNO~FCCONTRACTREFNO~FCUSERREFNO~TRCONTRACTREFNO~TRUSERREFNO~DRCONTRACTREFNO~DRUSERREFNO~DRAWDOWNNO~BORROWER~CONTRACTTYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBVWS_BORROWER_DETAILS" RELATION_TYPE="1" TYPE="BLK_LBVWS_TRANSFER_MASTER">ESN~VALUEDATE~TRANSFERTYPE~CONTRACTREFNO~TRANSFERREFNO~TABLETYPE~ENTRYSEQNO~AUTH_STAUS</FN>'; 
msgxml += '      <FN PARENT="BLK_LBVWS_TRANSFER_MASTER" RELATION_TYPE="1" TYPE="BLK_LBTWS_TRANSFER_MASTER">TXNSTAT~AUTHSTAT~TXT_PROCESS_STATUS~CHECKER_ID~CHECKER_DT_STAMP~MAKERID~FIRSTTIMEBUY~PAMBESN~ENTRYSEQNO~PAMIESN~USERREFNO~AUTHSTATUS~MAKERDTSTAMP~CONTRACTREFNO~TRANSFERSTATUS~TRANSFERTYPE~BRANCH~TRANSFERREFNO~VALUEDATE~ACCENTRYREQUIRED~TRANSACTIONDATE~CONTRACTSTATUS~CASCADE_PARTICIPATION~INSTRUCTION_TYPE~HFS_TRANSFER~TXT_TICKET_ID~TXT_TRANSFER_STATUS</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTWS_TRANSFER_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTWS_PART_TRANSFER_MASTER">ENTRYSEQNO~TRANSFERFROM~SEQNO~TRANSFERORFEEAMT~VALUEDATE~CONTRACTREFNO~TRANSFERFEEBY~TXT_PARTICIPANT_NAME~UPDT_LT_POS</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTWS_PART_TRANSFER_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTWS_PART_TRANSFER">IS3WAYTFR~ENTRYSEQNO~AMOUNT3WAY~SEQNO~TRANSFERFROM~TRANSFEREEOLDAMT~TICKETID~VALUEDATE~HFSTRANSFER~TRANSFEREEFEEAMT~TRANFERTO~TRANSFEREENEWAMT~TRANSFEROROLDAMT~TRANSFERRATIO~TRANSFERORNEWAMT~TRANSFERAMT~TRANSFEBY3WAY~TRANSFERPRICE~CONTRACTREFNO~TXT_TRANSFEROR_NAME~TXT_TRANSFEREE_NAME~TXT_INTERMEDIATOR_NAME</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTWS_TRANSFER_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTWS_CONSOL_TRANSFER">ENTRYSEQNO~PARTICIPANT~CONTRACTREFNO~TRANSFERPRICE~TRANSFERAMT~EVENTSEQNO~PARTICIPANTNEWAMT~VALUEDATE~PARTICIPANTOLDAMT~SENDMESSAGE~HFSTRANSFER~TRANSFERRATIO~TXT_CONSOL_PARTY_NAME~UPDT_LT_POS</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT_EVENT_LOG">TXT_CONTRACT_STATUS~TXT_AUTH_STATUS~AUTHSTATUS~CHECKERDTSTAMP~CHECKERID~CONTRACTREFNO~CONTRACTSTATUS~EVENTCODE~EVENTSEQNO~MAKERDTSTAMP~MAKERID~NEWVERSIONINDICATOR</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTWS_TRANSFER_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTWS_PRAM_FEE_TEMP">TXT_PARTICIPANT_NAME~TXT_COMPONENT_STATUS~COMPONENT~PARTICIPANT~COMPONENTCCY~ASSOCIATIONDATE~VALUEDATE~CONTRACTREFNO~COMPONENTSTATUS~COMPONENTONCEAUTH~FEEAMT~FEERULE~ENDDATE~STARTDATE~ENTRYSEQNO~TRANSFERFEEBY~FEECOLLECTIONMODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_CONTRACT_PARTICIPANT">SETTLEMENTSEQNO~OPERATION~ASSETRATIO~VERSIONNO~SELFPARTICIPATION~VALUEDATE~NETTINGPREF~ORIGINATOR~DRAWDOWNNO~SSIMNEMONIC~CONTRACTREFNO~ENTRYSEQNO~CONTRACTTYPE~TXT_PART_NAME~TXT_ASSET_AMOUNT~PARTICIPANT~PARTICIPANT_TYPE_UI~ASSET_AMOUNT~LMAPARTICIPATION~SWINGLINE_PARTICIPANT~SILENTPART</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_PARTICIPANT_RATIO">DRAWDOWNNO~CONTRACTREFNO~CUSTOMERNO~ENTRYSEQNO~SSIPICKUPAT~SSIMNEMONIC~VALUEDATE~SETTLEMENTSEQNO~VERSIONNO~COMPONENT~CONTRACTTYPE~COMPONENTRATIO~FEEBPSRATE~COMPONENTTYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_OLTWS_CONTRACT_ENTITY">TXT_ENTITY_NAME~CONTRACTTYPE~VALUEDATE~CUSTOMERNO~DRAWDOWNNO~REMARKS~ENTRYSEQNO~CONTRACTREFNO~PRIMARYENTITY~ENTITYID</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_LBTWS_PART_SETTLE_CURR_DET">CONTRACTTYPE~ENTRYSEQNO~VALUEDATE~SSIMNEMONIC~DRAWDOWNNO~PARTICIPANT~CONTRACTREFNO~SETTLEMENTSEQNO~CURRENCY</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_LOR_ADJ_DTLS">ACCOUNT_ENTRIES_CREATED~ACTUAL_TRANSFEREE_AMT~ACTUAL_TRANSFEROR_AMT~BUY_PARTY_CONTRACT_REF_NO~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~CURRENCY~DIFF_AMNT~EVENT_SEQ_NO~SELL_PARTY_CONTRACT_REF_NO~SETTLE_ACCURED_AMT~TRADE_REF_NO~TRANSFEREE~TRANSFEREE_AMT~TRANSFEROR~TRANSFEROR_AMT~USER_REF_NO~VALUE_DATE~SILENT_PART~SILENT_PART_ACC_ENTRY_CREATED</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_COLL_TRANSFER">CONTRACT_REF_NO~CUSTOMER_NO~TRANCHE_REF_NO~EVENT_SEQ_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_COLL_TRANSFER" RELATION_TYPE="N" TYPE="BLK_COLL_TRANSFER_DETAILS">AMT_TAG~BLOCK_REF_NO~BRANCH_CODE~COLLATERAL_CATEGORY~COMMITMENT_PRODUCT~CONTRACT_REF_NO~CUSTOMER_NO~DESCRIPTION~HAIRCUT~LIMIT_AMOUNT~LINKAGE_BRANCH~LINKAGE_CURRENCY~LINKAGE_TYPE~LINKED_AMOUNT~LINKED_PERCENT_NUMBER~LINKED_REFERENCE_NO~OVERALL_AMOUNT~PARTICIPANT~REINSTATE_ORDER~STATUS~TAKEN_OVER~UTIL_ACTION~UTIL_AMOUNT~UTIL_CCY~UTIL_ORDER~VERSION_NO~EVENT_SEQ_NO~TXTPARTNAME</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_SILENT_DETAILS">CONTRACT_REF_NO~EVENT_SEQ_NO~PARTICIPANT~CCY~TRANSFER_AMOUNT</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_CONTRACT" RELATION_TYPE="N" TYPE="BLK_RELCON">CONTRACT_REF_NO~CUSTOMER_NO~EVENT_SEQ_NO~TRANCHE_REF_NO~PRODUCT_CODE~CURRENCY</FN>'; 
msgxml += '      <FN PARENT="BLK_RELCON" RELATION_TYPE="N" TYPE="BLK_NONCASCPART">ASSET_AMOUNT~ASSET_RATIO~CONTRACT_REF_NO~CONTRACT_TYPE~DRAWDOWN_NO~ENTRY_SEQ_NO~LMA_PARTICIPATION~NETTING_PREF~OPERATION~ORIGINATOR~PARTICIPANT~SELF_PARTICIPATION~SETTLEMENT_SEQ_NO~SILENT_PARTICIPANT~SSI_MNEMONIC~SWINGLINE_PARTICIPANT~VALUE_DATE~VERSION_NO~EVENT_SEQ_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_NONCASCPART" RELATION_TYPE="N" TYPE="BLK_NONCASCSSI">CONTRACT_REF_NO~CONTRACT_TYPE~CURRENCY~DRAWDOWN_NO~ENTRY_SEQ_NO~EVENT_SEQ_NO~PARTICIPANT~SETTELMENT_SEQ_NO~SSI_MNEMONIC~VALUE_DATE</FN>'; 
msgxml += '      <FN PARENT="BLK_NONCASCPART" RELATION_TYPE="N" TYPE="BLK_NONCASCENTITY">CONTRACT_REF_NO~CONTRACT_TYPE~CUSTOMER_NO~DRAWDOWN_NO~ENTITY_ID~ENTRY_SEQ_NO~EVENT_SEQ_NO~PRIMARY_ENTITY~REMARKS~VALUE_DATE</FN>'; 
msgxml += '      <FN PARENT="BLK_RELCON" RELATION_TYPE="N" TYPE="BLK_TRNNONCASC">AMOUNT_3WAY~CONTRACT_REF_NO~ENTRY_SEQ_NO~EVENT_SEQ_NO~EXT_TRADE_ID~HFS_TRANSFER~IS_3WAY_TFR~SEQ_NO~TICKET_ID~TRANSFEREE_FEE_AMT~TRANSFEREE_NEW_AMT~TRANSFEREE_OLD_AMT~TRANSFEROR_NEW_AMT~TRANSFEROR_OLD_AMT~TRANSFER_AMT~TRANSFER_BY_3WAY~TRANSFER_FROM~TRANSFER_PRICE~TRANSFER_RATIO~TRANSFER_TO~UPDATE_LT_POSITION~VALUE_DATE</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_LBVWS_BORROWER_DETAILS" RELATION_TYPE="1" TYPE="BLK_SUMMARY">CONTRACTREFNO~VALUEDATE~EVENTSEQNO~ENTRYSEQNO~TABLETYPE~TRANSFERTYPE~TRANSFERREFNO~AUTHSTATUS</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDPTFR";
var defaultWhereClause = "BRANCH =GLOBAL.CURRENT_BRANCH";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_OLTBS_CONTRACT" : "","BLK_LBVWS_BORROWER_DETAILS" : "BLK_OLTBS_CONTRACT~1","BLK_LBVWS_TRANSFER_MASTER" : "BLK_LBVWS_BORROWER_DETAILS~1","BLK_LBTWS_TRANSFER_MASTER" : "BLK_LBVWS_TRANSFER_MASTER~1","BLK_LBTWS_PART_TRANSFER_MASTER" : "BLK_LBTWS_TRANSFER_MASTER~N","BLK_LBTWS_PART_TRANSFER" : "BLK_LBTWS_PART_TRANSFER_MASTER~N","BLK_LBTWS_CONSOL_TRANSFER" : "BLK_LBTWS_TRANSFER_MASTER~N","BLK_OLTBS_CONTRACT_EVENT_LOG" : "BLK_OLTBS_CONTRACT~1","BLK_LBTWS_PRAM_FEE_TEMP" : "BLK_LBTWS_TRANSFER_MASTER~N","BLK_CONTRACT_PARTICIPANT" : "BLK_OLTBS_CONTRACT~N","BLK_PARTICIPANT_RATIO" : "BLK_CONTRACT_PARTICIPANT~N","BLK_OLTWS_CONTRACT_ENTITY" : "BLK_CONTRACT_PARTICIPANT~N","BLK_LBTWS_PART_SETTLE_CURR_DET" : "BLK_CONTRACT_PARTICIPANT~N","BLK_LOR_ADJ_DTLS" : "BLK_OLTBS_CONTRACT~N","BLK_COLL_TRANSFER" : "BLK_OLTBS_CONTRACT~N","BLK_COLL_TRANSFER_DETAILS" : "BLK_COLL_TRANSFER~N","BLK_SILENT_DETAILS" : "BLK_CONTRACT_PARTICIPANT~N","BLK_RELCON" : "BLK_OLTBS_CONTRACT~N","BLK_NONCASCPART" : "BLK_RELCON~N","BLK_NONCASCSSI" : "BLK_NONCASCPART~N","BLK_NONCASCENTITY" : "BLK_NONCASCPART~N","BLK_TRNNONCASC" : "BLK_RELCON~N"}; 

 var dataSrcLocationArray = new Array("BLK_OLTBS_CONTRACT","BLK_LBVWS_BORROWER_DETAILS","BLK_LBVWS_TRANSFER_MASTER","BLK_LBTWS_TRANSFER_MASTER","BLK_LBTWS_PART_TRANSFER_MASTER","BLK_LBTWS_PART_TRANSFER","BLK_LBTWS_CONSOL_TRANSFER","BLK_OLTBS_CONTRACT_EVENT_LOG","BLK_LBTWS_PRAM_FEE_TEMP","BLK_CONTRACT_PARTICIPANT","BLK_PARTICIPANT_RATIO","BLK_OLTWS_CONTRACT_ENTITY","BLK_LBTWS_PART_SETTLE_CURR_DET","BLK_LOR_ADJ_DTLS","BLK_COLL_TRANSFER","BLK_COLL_TRANSFER_DETAILS","BLK_SILENT_DETAILS","BLK_RELCON","BLK_NONCASCPART","BLK_NONCASCSSI","BLK_NONCASCENTITY","BLK_TRNNONCASC"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDPTFR.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDPTFR.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_OLTBS_CONTRACT__CONTRACTREFNO";
pkFields[0] = "BLK_OLTBS_CONTRACT__CONTRACTREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_CONTRACT_PARTICIPANT":["ASSETRATIO","CONTRACTREFNO","CONTRACTTYPE","DRAWDOWNNO","ENTRYSEQNO","NETTINGPREF","OPERATION","ORIGINATOR","PARTICIPANT","SELFPARTICIPATION","SETTLEMENTSEQNO","SILENTPART","SSIMNEMONIC","TXT_ASSET_AMOUNT","TXT_PART_NAME","VALUEDATE","VERSIONNO"],"BLK_LBTWS_CONSOL_TRANSFER":["CONTRACTREFNO","ENTRYSEQNO","EVENTSEQNO","HFSTRANSFER","PARTICIPANT","PARTICIPANTNEWAMT","PARTICIPANTOLDAMT","SENDMESSAGE","TRANSFERAMT","TRANSFERPRICE","TRANSFERRATIO","TXT_CONSOL_PARTY_NAME","VALUEDATE"],"BLK_LBTWS_PART_SETTLE_CURR_DET":["CONTRACTREFNO","CONTRACTTYPE","CURRENCY","DRAWDOWNNO","ENTRYSEQNO","PARTICIPANT","SETTLEMENTSEQNO","SSIMNEMONIC","VALUEDATE"],"BLK_LBTWS_PART_TRANSFER_MASTER":["CONTRACTREFNO","ENTRYSEQNO","SEQNO","TRANSFERFEEBY","TRANSFERFROM","TRANSFERORFEEAMT","TXT_PARTICIPANT_NAME","VALUEDATE"],"BLK_LBTWS_PART_TRANSFER":["AMOUNT3WAY","CONTRACTREFNO","ENTRYSEQNO","HFSTRANSFER","IS3WAYTFR","SEQNO","TICKETID","TRANFERTO","TRANSFEBY3WAY","TRANSFERAMT","TRANSFEREEFEEAMT","TRANSFEREENEWAMT","TRANSFEREEOLDAMT","TRANSFERFROM","TRANSFERORNEWAMT","TRANSFEROROLDAMT","TRANSFERPRICE","TRANSFERRATIO","TXT_INTERMEDIATOR_NAME","TXT_TRANSFEREE_NAME","TXT_TRANSFEROR_NAME","VALUEDATE"],"BLK_LBTWS_PRAM_FEE_TEMP":["ASSOCIATIONDATE","COMPONENT","COMPONENTCCY","COMPONENTONCEAUTH","COMPONENTSTATUS","CONTRACTREFNO","ENDDATE","ENTRYSEQNO","FEEAMT","FEECOLLECTIONMODE","FEERULE","PARTICIPANT","STARTDATE","TRANSFERFEEBY","TXT_COMPONENT_STATUS","TXT_PARTICIPANT_NAME","VALUEDATE"],"BLK_LBTWS_TRANSFER_MASTER":["ACCENTRYREQUIRED","AUTHSTAT","AUTHSTATUS","CHECKER_DT_STAMP","CHECKER_ID","CONTRACTSTATUS","ENTRYSEQNO","FIRSTTIMEBUY","HFS_TRANSFER","INSTRUCTION_TYPE","MAKERDTSTAMP","MAKERID","PAMBESN","PAMIESN","TRANSACTIONDATE","TRANSFERSTATUS","TRANSFERTYPE","TXNSTAT","TXT_PROCESS_STATUS","VALUEDATEI"],"BLK_LBVWS_TRANSFER_MASTER":["AUTH_STAUS","ENTRYSEQNO","ESN","TABLETYPE","TRANSFERREFNO","VALUEDATE"],"BLK_OLTBS_CONTRACT_EVENT_LOG":["AUTHSTATUS","CHECKERDTSTAMP","CHECKERID","CONTRACTREFNO","CONTRACTSTATUS","EVENTCODE","EVENTSEQNO","MAKERDTSTAMP","MAKERID","NEWVERSIONINDICATOR","TXT_AUTH_STATUS","TXT_CONTRACT_STATUS"],"BLK_OLTBS_CONTRACT":["BTN_DEFAULT","BTN_DEFAULT_COMPONENTS","BTN_FEE_DEFAULT","TXT_ENTRY_SEQ_NO","TXT_EVENT_SEQ_NO","TXT_SUMMARY_ID","TXT_TABLE_TYPE","TXT_VAL_DATEI"],"BLK_OLTWS_CONTRACT_ENTITY":["CONTRACTREFNO","CONTRACTTYPE","CUSTOMERNO","DRAWDOWNNO","ENTITYID","ENTRYSEQNO","PRIMARYENTITY","REMARKS","TXT_ENTITY_NAME","VALUEDATE"],"BLK_PARTICIPANT_RATIO":["COMPONENT","COMPONENTRATIO","COMPONENTTYPE","CONTRACTREFNO","CONTRACTTYPE","CUSTOMERNO","DRAWDOWNNO","ENTRYSEQNO","FEEBPSRATE","SETTLEMENTSEQNO","SSIMNEMONIC","SSIPICKUPAT","VALUEDATE","VERSIONNO"],"BLK_SILENT_DETAILS":["EVENT_SEQ_NO","PARTICIPANT","TRANSFER_AMOUNT"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_OLTBS_CONTRACT__CONTRACTREFNO__LOV_CONTRACT":["BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__BRANCH~BLK_OLTBS_CONTRACT__CONTRACTCCY~BLK_OLTBS_CONTRACT__USERREFNO~BLK_OLTBS_CONTRACT__MODULECODE~BLK_OLTBS_CONTRACT__LATESTVERSIONNO~BLK_OLTBS_CONTRACT__LATESTEVENTSEQNO~","","N~N~N~N~N~N~N",""],"BLK_OLTBS_CONTRACT__SSI_MNEMONIC__LOV_SSI_MNEMONIC":["BLK_OLTBS_CONTRACT__SSI_MNEMONIC~~~~~~~","BLK_CONTRACT_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_OLTBS_CONTRACT__BRANCH!VARCHAR2~BLK_OLTBS_CONTRACT__BRANCH!VARCHAR2~BLK_OLTBS_CONTRACT__CONTRACTCCY!VARCHAR2~BLK_OLTBS_CONTRACT__CONTRACTCCY!VARCHAR2~BLK_OLTBS_CONTRACT__PRODUCTCODE!VARCHAR2~BLK_OLTBS_CONTRACT__PRODUCTCODE!VARCHAR2~BLK_OLTBS_CONTRACT__PRODUCTCODE!VARCHAR2","N~N~N~N~N~N~N","N"],"BLK_OLTBS_CONTRACT__FEE_TXT_COMPONENT__LOV_PARTICIPANT_COMP":["BLK_OLTBS_CONTRACT__FEE_TXT_COMPONENT~BLK_OLTBS_CONTRACT__FEE_TXT_FEE_RULE~","BLK_OLTBS_CONTRACT__FEE_PART_PROD_CODE_UI!VARCHAR2","N~N",""],"BLK_LBTWS_PART_TRANSFER_MASTER__TRANSFERFROM__LOV_TRANSFER_FROM":["BLK_LBTWS_PART_TRANSFER_MASTER__TRANSFERFROM~BLK_LBTWS_PART_TRANSFER_MASTER__TXT_PARTICIPANT_NAME~","","N~N",""],"BLK_LBTWS_PART_TRANSFER__TRANFERTO__LOV_TRANSFER_TO":["BLK_LBTWS_PART_TRANSFER__TRANFERTO~BLK_LBTWS_PART_TRANSFER__TXT_TRANSFEREE_NAME~","","N~N",""],"BLK_LBTWS_PART_TRANSFER__TRANSFEBY3WAY__LOV_TRANSFERBY3WAY":["BLK_LBTWS_PART_TRANSFER__TRANSFEBY3WAY~BLK_LBTWS_PART_TRANSFER__TXT_INTERMEDIATOR_NAME~","BLK_OLTBS_CONTRACT__CONTRACTREFNO!String~BLK_OLTBS_CONTRACT__CONTRACTREFNO!String~BLK_LBTWS_PART_TRANSFER__TRANSFERFROM!String~BLK_LBTWS_PART_TRANSFER__TRANFERTO!String","N~N",""],"BLK_LBTWS_CONSOL_TRANSFER__PARTICIPANT__LOV_CUSTOMER_NO":["BLK_LBTWS_CONSOL_TRANSFER__PARTICIPANT~BLK_LBTWS_CONSOL_TRANSFER__TXT_CONSOL_PARTY_NAME~","","N~N",""],"BLK_CONTRACT_PARTICIPANT__PARTICIPANT__LOV_CUSTOMER_NO":["BLK_CONTRACT_PARTICIPANT__PARTICIPANT~BLK_CONTRACT_PARTICIPANT__TXT_PART_NAME~","","N~N",""],"BLK_OLTWS_CONTRACT_ENTITY__ENTITYID__LOV_ENTITY":["BLK_OLTWS_CONTRACT_ENTITY__ENTITYID~BLK_OLTWS_CONTRACT_ENTITY__TXT_ENTITY_NAME~~~~~","BLK_CONTRACT_PARTICIPANT__PARTICIPANT!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!~BLK_LBVWS_BORROWER_DETAILS__FCCONTRACTREFNO!~BLK_LBVWS_BORROWER_DETAILS__TRCONTRACTREFNO!~BLK_OLTBS_CONTRACT__CONTRACTREFNO!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!~BLK_LBVWS_BORROWER_DETAILS__FCCONTRACTREFNO!~BLK_LBVWS_BORROWER_DETAILS__TRCONTRACTREFNO!~BLK_OLTBS_CONTRACT__CONTRACTREFNO!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!~BLK_LBVWS_BORROWER_DETAILS__DRAWDOWNNO!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!~BLK_LBVWS_BORROWER_DETAILS__DRAWDOWNNO!~BLK_CONTRACT_PARTICIPANT__PARTICIPANT!~BLK_LBVWS_BORROWER_DETAILS__CONTRACTTYPE!","N~N~N~N~N~N",""],"BLK_LBTWS_PART_SETTLE_CURR_DET__SSIMNEMONIC__LOV_SSI_MNEMONIC":["BLK_LBTWS_PART_SETTLE_CURR_DET__SSIMNEMONIC~~~~~~~","BLK_CONTRACT_PARTICIPANT__PARTICIPANT!~BLK_OLTBS_CONTRACT__BRANCH!~BLK_OLTBS_CONTRACT__BRANCH!~BLK_LBTWS_PART_SETTLE_CURR_DET__CURRENCY!~BLK_LBTWS_PART_SETTLE_CURR_DET__CURRENCY!~BLK_OLTBS_CONTRACT__PRODUCTCODE!~BLK_OLTBS_CONTRACT__PRODUCTCODE!~BLK_OLTBS_CONTRACT__PRODUCTCODE!","N~N~N~N~N~N~N",""],"BLK_LBTWS_PART_SETTLE_CURR_DET__CURRENCY__LOV_SSI_CCY":["BLK_LBTWS_PART_SETTLE_CURR_DET__CURRENCY~~","BLK_OLTBS_CONTRACT__CONTRACTREFNO!VARCHAR2~BLK_OLTBS_CONTRACT__CONTRACTREFNO!VARCHAR2~BLK_OLTBS_CONTRACT__CONTRACTREFNO!VARCHAR2~BLK_OLTBS_CONTRACT__PRODUCTCODE!VARCHAR2","N~N",""],"BLK_COLL_TRANSFER_DETAILS__CUSTOMER_NO__LOV_COLL_CUST":["BLK_COLL_TRANSFER_DETAILS__CUSTOMER_NO~","","N",""],"BLK_COLL_TRANSFER_DETAILS__LINKED_REFERENCE_NO__LOV_LBTRLINKAGEREFNO":["BLK_COLL_TRANSFER_DETAILS__LINKED_REFERENCE_NO~~~~BLK_COLL_TRANSFER_DETAILS__LINKAGE_BRANCH~BLK_COLL_TRANSFER_DETAILS__LINKAGE_CURRENCY~BLK_COLL_TRANSFER_DETAILS__DESCRIPTION~~","__!~__!~__!~__!~__!~__!~__!~__!~__!","",""],"BLK_COLL_TRANSFER_DETAILS__PARTICIPANT__LOV_PART_COLL":["BLK_COLL_TRANSFER_DETAILS__PARTICIPANT~BLK_COLL_TRANSFER_DETAILS__TXTPARTNAME~","","N~N",""],"BLK_SILENT_DETAILS__PARTICIPANT__LOV_CUSTOMER_NO":["BLK_SILENT_DETAILS__PARTICIPANT~~","","N~N",""],"BLK_NONCASCPART__PARTICIPANT__LOV_CUSTOMER_NO":["BLK_NONCASCPART__PARTICIPANT~~","","N~N",""],"BLK_NONCASCSSI__CURRENCY__LOV_SSI_CCY":["BLK_NONCASCSSI__CURRENCY~~","BLK_RELCON__CONTRACT_REF_NO!~BLK_RELCON__CONTRACT_REF_NO!~BLK_RELCON__CONTRACT_REF_NO!~BLK_RELCON__PRODUCT_CODE!","N~N",""],"BLK_NONCASCSSI__SSI_MNEMONIC__LOV_SSI_MNEMONIC":["BLK_NONCASCSSI__SSI_MNEMONIC~~~~~~~","BLK_NONCASCPART__PARTICIPANT!~BLK_OLTBS_CONTRACT__BRANCH!~BLK_OLTBS_CONTRACT__BRANCH!~BLK_NONCASCSSI__CURRENCY!~BLK_NONCASCSSI__CURRENCY!~BLK_RELCON__PRODUCT_CODE!~BLK_RELCON__PRODUCT_CODE!~BLK_RELCON__PRODUCT_CODE!","N~N~N~N~N~N~N",""],"BLK_NONCASCENTITY__ENTITY_ID__LOV_ENT":["BLK_NONCASCENTITY__ENTITY_ID~~~~~~","BLK_NONCASCPART__PARTICIPANT!","N~N~N~N~N~N",""],"BLK_TRNNONCASC__TRANSFER_FROM__LOV_TRANSFER_FROM":["BLK_TRNNONCASC__TRANSFER_FROM~~","","N~N",""],"BLK_TRNNONCASC__TRANSFER_TO__LOV_TRANSFER_TO":["BLK_TRNNONCASC__TRANSFER_TO~~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_CONTRACT';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_LBTWS_PART_SETTLE_CURR_DET","BLK_OLTWS_CONTRACT_ENTITY","BLK_LBTWS_PART_TRANSFER_MASTER","BLK_LBTWS_PART_TRANSFER","BLK_LBTWS_CONSOL_TRANSFER","BLK_CONTRACT_PARTICIPANT","BLK_PARTICIPANT_RATIO","BLK_LBTWS_PRAM_FEE_TEMP","BLK_LOR_ADJ_DTLS","BLK_COLL_TRANSFER","BLK_COLL_TRANSFER_DETAILS","BLK_SILENT_DETAILS","BLK_RELCON","BLK_NONCASCPART","BLK_NONCASCSSI","BLK_NONCASCENTITY","BLK_TRNNONCASC");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("OLCTRUDF~BLK_OLTBS_CONTRACT","LBCPARAT~BLK_OLTBS_CONTRACT","LBCPCDTR~BLK_OLTBS_CONTRACT","LBCPRCTR~BLK_OLTBS_CONTRACT","LPCRCMTT~BLK_OLTBS_CONTRACT"); 

 var CallFormRelat=new Array("OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_CONTRACT__FLD.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_VERSION_NO = OLTBS_CONTRACT__FLD.LATEST_VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_CONTRACT__PARAT.CONTRACT_REF_NO AND OLTBS_CONTRACT.LATEST_VERSION_NO = OLTBS_CONTRACT__PARAT.LATEST_VERSION_NO","OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_CONTRACT__PROCESS.CONTRACT_REF_NO","OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_CONTRACT__PROCESSED.CONTRACT_REF_NO","OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_CONTRACT__PM.CONTRACT_REF_NO AND OLTBS_CONTRACT.BRANCH = OLTBS_CONTRACT__PM.BRANCH AND OLTBS_CONTRACT.COUNTERPARTY = OLTBS_CONTRACT__PM.COUNTERPARTY"); 

 var CallRelatType= new Array("1","1","1","1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDPTFR"]="KERNEL";
ArrPrntFunc["LBDPTFR"]="";
ArrPrntOrigin["LBDPTFR"]="";
ArrRoutingType["LBDPTFR"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDPTFR"]="N";
ArrCustomModified["LBDPTFR"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_FEES":"CONTREFNUM~USERREFNO","OLCTRUDF":"CONTREFNO~LATVERNO","LBCPARAT":"fccref~esn~verno","LBCPCDTR":"CONTRACT_REF_NO~CCY","LBCPRCTR":"CONTRACT_REF_NO~CCY","LPCRCMTT":"CONTRACTREFNO~BRANCH~COUNTERPARTY~ACTION_CODE","OLDFFMSG":""};
var scrArgSource = {"CVS_FEES":"BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__USERREFNO","OLCTRUDF":"BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__LATESTVERSIONNO","LBCPARAT":"BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__LATESTEVENTSEQNO~BLK_OLTBS_CONTRACT__LATESTVERSIONNO","LBCPCDTR":"BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__CONTRACTCCY","LBCPRCTR":"BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__CONTRACTCCY","LPCRCMTT":"BLK_OLTBS_CONTRACT__CONTRACTREFNO~BLK_OLTBS_CONTRACT__BRANCH~BLK_LBVWS_BORROWER_DETAILS__BORROWER~","OLDFFMSG":""};
var scrArgVals = {"CVS_FEES":"~","OLCTRUDF":"~","LBCPARAT":"~~","LBCPCDTR":"~","LBCPRCTR":"~","LPCRCMTT":"~~~EXECUTEQUERY","OLDFFMSG":""};
var scrArgDest = {"CVS_FEES":"BLK_OLTBS_CONTRACT__FEE_CONTREFNO_UI~BLK_OLTBS_CONTRACT__FEE_USEREFNO_UI"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"OLCTRUDF":"","LBCPARAT":"","LBCPCDTR":"","LBCPRCTR":"","LPCRCMTT":""};
var dpndntOnSrvs = {"OLCTRUDF":"","LBCPARAT":"","LBCPCDTR":"","LBCPRCTR":"","LPCRCMTT":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"2","DELETE":"2","CLOSE":"1","REOPEN":"1","REVERSE":"2","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------