/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDREPRS_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_CONTRACT":"CONREFNO~LATESTEVNTSEQ~USER_REF_NO~PRODUCT_CODE~PRODUCT_TYPE~CONTRACT_CCY~COUNTERPARTY~TXT_FACILITY_NAME~TXT_TRANCHE_REF~TXT_PRM_TRANCHE_CCY~TXT_PRM_RATE_CODE~TXT_PRM_RATE_TYPE","BLK_CONT_SPLIT_MASTER":"CONREFNO~SPLITSERIALNO~LIQPRINCIPLE~LIQINTEREST~COUNTERPARTY~CONTCCY~OUTPRINCIPLE~SPLITBOOKDATE~SPLITVALUEDATE~PRODUCT~INTRATEFIXINGDATE~PRODESCR~COUNTRPARTYDESC~CCYDESCR~DEFAULTFRONTING~TXT_TRNREFNUM~SUBSYSTAT~AUTH_STAT~ONCE_AUTH~MAKER_ID~MAKER_DT_STAMP~CHECKER_ID~CHECKER_DT_STAMP~MOD_NO~EVENT_COMPLETE~LIQD_REQD~SPLIT_STATUS~SPTI_ESN~TOTAL_SPLIT_AMOUNT~PROCESS_TIME_STAMP~KEEP_THIS_CONTRACT_ACTIVE~VAMB_ESN~PARENT_CONTRACT_STATUS~SPTR_ESN~RECORD_STAT~SPTB_ESN~LIQD_ESN~UI_ENABLE_PART_BA_YN~SCHEDULE_DEFINITION_BASIS~HOLIDAY_PARAMETERS_BASIS~MIS_BASIS~UDF_BASIS~ECAREQSTATUS~SETTLEMENT_BASIS","BLK_CONT_SPLIT_DETAIL":"SERIALNO~SPLITSERIALNO~CONDREFNO~AMOUNT~PROD~LIQINTPREP~AMORTAMOUNT~MATURITYDATE~CINSDISPLIT~CCY~CHILDREFNO~TXT_PROD_DESC_DETAIL","BLK_SPLIT_PROD_INTCOMP":"CONFREFNO~SPLITSERIALNO~SERIALNO~PROCODE~COMPONENET~RESETENOR~RAETYPE~RATECODE~INTBASIS~BASERATE~SPREAD~MARGINRATE~RATE~SHOWNINCONTRACTMAINSCREEN~FIXEDRATETYPE~TXT_RATE_FIXING_REQD~BORROW_LEND_IND~RATE_CALC_TYPE~ACQUIRED_AMOUNT~PLACEMENT_MIS_RATE~RATEFIXINGREQD~RATEFIXINGDAYS~RATE_ROUNDING_POSITION~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~SPREAD_ADJ~RATE_REVISION_METHOD~DEFAULT_FROM~RATE_CODE_USAGE~SPIN_CCY_RND_DEC~SPIN_CCY_RND_RULE~SPIN_CCY_RND_UNIT~SPIN_INT_PEROID_BASIS","BLK_SPLIT_PROD_MRGCOMP":"CONTRACTREFNO~SPLITSERIALNO~SERIALNO~COMPONENET~MARGINCOMP~MARGINBASIS~BASISAMTAG~MARGINRATE","BLK_EVNT_LOG":"EVENTSEQNO~CONTRACTREFNO~CHECKERDTSTAMP~AUTHSTAT~CHECKERID~TXNSTAT~MAKERID~MAKERDTSTAMP~MOD_NO~RECORD_STATUS~REPRICE_STATUS_UI","BLK_CONTRACT_SUMMARY":"SPLITVALUEDATE~AUTHSTATUS~CONREFNO~SPLITBOOKDATE","BLK_SPLIT_AMOUNT":"REMARKS~TXT_SPLI_AMOUNT","BLK_INT_RATE_FIXING":"TENORUNIT~RATECODE~RATE~REMARKS~CONTRACTREFNO~SPLITSERIALNO~SPLITNO~COMPONENT~RATE_EFFECTIVESTARTDATE~RATEEFFECTIVEENDDATE~TENORVALUE~TXT_PROD_CODE~TXT_PROD_DESC~TXT_PROD_TYPE_DESC~TXT_USER_REF_NO~TXT_CUSTOMER~TXT_CUSTOMER_NAME~TXT_FACILITY_NAME~TXT_COMP_DESC~TXT_CCY~TXT_CCY_DESC~TXT_PRM_MATURITY_DT","BLK_EXRATE_FIXING":"CONTRACTREFNO~SPLITSERIALNO~SPLITNO~EXRATESTARTDATE~EXRATEENDDATE~CONTRACTCCY~TRANCHECCY~EXCHANGERATE~REMARKS~TXT_PROD_CD~TXT_PROD_DESCR~TXT_PROD_TYPE_DESC~TXT_USERREF~TXT_CUSTOMER~TXT_CUST_NAME~TXT_FACILITY_NAME~TXT_RATE_CODE~TXT_RATE_TYPE~TXT_PRM_MAT_DATE~TXT_PRM_TRANCHE_REF_NO","BLK_RATE_SETTING":"CONTRACTREFNO~COMPONENT~SPLITSERIALNO~SPLITNUMBER~EVENTSEQNO~ROUNDINGRULE~ROUNDINGUNIT~TENOR~TXT_PROD_CD~TXT_PROD_DESC~TXT_PROD_TYPE~TXT_USERREF~TXT_CUSTOMER~TXT_CUST_NAME~TXT_FACILITY~TXT_ROLL_PROD~TXT_CURRENCY~TXT_PRIN_ROLL_AMT~TXT_INT_ROLL_AMT~TXT_TOT_ROLL_AMT~TXT_MAT_DATE","BLK_BA_CONT_DETAILS":"AGENT_RATE~BA_BROKER_PROD~COF_AMT~CONTRACT_REF_NO~DISCOUNTED_RATE~DISCOUNT_AMT~INTEREST_DAY_BASIS~NET_BORROWING_AMT~PNL_AMT~SPLIT_NUMBER~SPLIT_SERIAL_NO~STAMPING_FEE_AMT~STAMPING_FEE_RATE~TREASURY_RATE","BLK_LFTB_CONT_ADDL_INT_DTL":"COMPONENT~CONTRACT_REF_NO~OBSERVATION_SHIFT~PRODUCT_CODE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_METHOD~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_RATE_COMPOUNDING~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~RFR_RATE_TYPE~RFR_SPREAD_ADJ_COMP_METH~SERIAL_NO~SPLIT_SERIAL_NO~VERSION_NO","BLK_BA_PART_RPRS_DTLS":"AGENT_RATE~BA_BROKER_PROD~COF_AMT~CONTRACT_REF_NO~DISCOUNTED~DISCOUNTED_AMT~DISCOUNTED_PRICE~DISCOUNT_RATE~DISC_PRICE_ROUNDING_RULE~DISC_PRICE_ROUNDING_UNIT~EVENT_SEQ_NO~INTEREST_DAY_BASIS~NET_BORROWING_AMT~PARTICIPANT~PNL_AMT~SPLIT_NUMBER~SPLIT_SERIAL_NO~STAMPING_FEE_AMT~STAMPING_FEE_RATE~TREASURY_RATE~VERSION_NO~MAX_RATE","BLK_ADDL_BA_DTLS":"AGENT_RATE~BA_BROKER_PROD~CONTRACT_REF_NO~DISC_PRICE_ROUNDING_UNIT~MAX_RATE~SPLIT_NUMBER~SPLIT_SERIAL_NO~TREASURY_RATE"};

var multipleEntryPageSize = {"BLK_CONT_SPLIT_DETAIL" :"15" ,"BLK_SPLIT_PROD_MRGCOMP" :"15" ,"BLK_BA_CONT_DETAILS" :"15" ,"BLK_BA_PART_RPRS_DTLS" :"15" };

var multipleEntrySVBlocks = "BLK_SPLIT_PROD_INTCOMP~BLK_CONT_SPLIT_DETAIL~BLK_INT_RATE_FIXING~BLK_EXRATE_FIXING~BLK_RATE_SETTING~BLK_LFTB_CONT_ADDL_INT_DTL~BLK_ADDL_BA_DTLS";

var tabMEBlks = {"CVS_MAIN__TAB_MAIN":"BLK_CONT_SPLIT_DETAIL~BLK_BA_CONT_DETAILS~BLK_BA_PART_RPRS_DTLS","CVS_INT_DTLS__TAB_MAIN":"BLK_SPLIT_PROD_MRGCOMP"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_CONTRACT">CONREFNO~LATESTEVNTSEQ~USER_REF_NO~PRODUCT_CODE~PRODUCT_TYPE~CONTRACT_CCY~COUNTERPARTY~TXT_FACILITY_NAME~TXT_TRANCHE_REF~TXT_PRM_TRANCHE_CCY~TXT_PRM_RATE_CODE~TXT_PRM_RATE_TYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT" RELATION_TYPE="1" TYPE="BLK_CONT_SPLIT_MASTER">CONREFNO~SPLITSERIALNO~LIQPRINCIPLE~LIQINTEREST~COUNTERPARTY~CONTCCY~OUTPRINCIPLE~SPLITBOOKDATE~SPLITVALUEDATE~PRODUCT~INTRATEFIXINGDATE~PRODESCR~COUNTRPARTYDESC~CCYDESCR~DEFAULTFRONTING~TXT_TRNREFNUM~SUBSYSTAT~AUTH_STAT~ONCE_AUTH~MAKER_ID~MAKER_DT_STAMP~CHECKER_ID~CHECKER_DT_STAMP~MOD_NO~EVENT_COMPLETE~LIQD_REQD~SPLIT_STATUS~SPTI_ESN~TOTAL_SPLIT_AMOUNT~PROCESS_TIME_STAMP~KEEP_THIS_CONTRACT_ACTIVE~VAMB_ESN~PARENT_CONTRACT_STATUS~SPTR_ESN~RECORD_STAT~SPTB_ESN~LIQD_ESN~UI_ENABLE_PART_BA_YN~SCHEDULE_DEFINITION_BASIS~HOLIDAY_PARAMETERS_BASIS~MIS_BASIS~UDF_BASIS~ECAREQSTATUS~SETTLEMENT_BASIS</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_MASTER" RELATION_TYPE="N" TYPE="BLK_CONT_SPLIT_DETAIL">SERIALNO~SPLITSERIALNO~CONDREFNO~AMOUNT~PROD~LIQINTPREP~AMORTAMOUNT~MATURITYDATE~CINSDISPLIT~CCY~CHILDREFNO~TXT_PROD_DESC_DETAIL</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_DETAIL" RELATION_TYPE="N" TYPE="BLK_SPLIT_PROD_INTCOMP">CONFREFNO~SPLITSERIALNO~SERIALNO~PROCODE~COMPONENET~RESETENOR~RAETYPE~RATECODE~INTBASIS~BASERATE~SPREAD~MARGINRATE~RATE~SHOWNINCONTRACTMAINSCREEN~FIXEDRATETYPE~TXT_RATE_FIXING_REQD~BORROW_LEND_IND~RATE_CALC_TYPE~ACQUIRED_AMOUNT~PLACEMENT_MIS_RATE~RATEFIXINGREQD~RATEFIXINGDAYS~RATE_ROUNDING_POSITION~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~SPREAD_ADJ~RATE_REVISION_METHOD~DEFAULT_FROM~RATE_CODE_USAGE~SPIN_CCY_RND_DEC~SPIN_CCY_RND_RULE~SPIN_CCY_RND_UNIT~SPIN_INT_PEROID_BASIS</FN>'; 
msgxml += '      <FN PARENT="BLK_SPLIT_PROD_INTCOMP" RELATION_TYPE="N" TYPE="BLK_SPLIT_PROD_MRGCOMP">CONTRACTREFNO~SPLITSERIALNO~SERIALNO~COMPONENET~MARGINCOMP~MARGINBASIS~BASISAMTAG~MARGINRATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_MASTER" RELATION_TYPE="1" TYPE="BLK_EVNT_LOG">EVENTSEQNO~CONTRACTREFNO~CHECKERDTSTAMP~AUTHSTAT~CHECKERID~TXNSTAT~MAKERID~MAKERDTSTAMP~MOD_NO~RECORD_STATUS~REPRICE_STATUS_UI</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT" RELATION_TYPE="1" TYPE="BLK_CONTRACT_SUMMARY">SPLITVALUEDATE~AUTHSTATUS~CONREFNO~SPLITBOOKDATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_MASTER" RELATION_TYPE="1" TYPE="BLK_SPLIT_AMOUNT">REMARKS~TXT_SPLI_AMOUNT</FN>'; 
msgxml += '      <FN PARENT="BLK_SPLIT_PROD_INTCOMP" RELATION_TYPE="N" TYPE="BLK_INT_RATE_FIXING">TENORUNIT~RATECODE~RATE~REMARKS~CONTRACTREFNO~SPLITSERIALNO~SPLITNO~COMPONENT~RATE_EFFECTIVESTARTDATE~RATEEFFECTIVEENDDATE~TENORVALUE~TXT_PROD_CODE~TXT_PROD_DESC~TXT_PROD_TYPE_DESC~TXT_USER_REF_NO~TXT_CUSTOMER~TXT_CUSTOMER_NAME~TXT_FACILITY_NAME~TXT_COMP_DESC~TXT_CCY~TXT_CCY_DESC~TXT_PRM_MATURITY_DT</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_DETAIL" RELATION_TYPE="N" TYPE="BLK_EXRATE_FIXING">CONTRACTREFNO~SPLITSERIALNO~SPLITNO~EXRATESTARTDATE~EXRATEENDDATE~CONTRACTCCY~TRANCHECCY~EXCHANGERATE~REMARKS~TXT_PROD_CD~TXT_PROD_DESCR~TXT_PROD_TYPE_DESC~TXT_USERREF~TXT_CUSTOMER~TXT_CUST_NAME~TXT_FACILITY_NAME~TXT_RATE_CODE~TXT_RATE_TYPE~TXT_PRM_MAT_DATE~TXT_PRM_TRANCHE_REF_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_SPLIT_PROD_INTCOMP" RELATION_TYPE="N" TYPE="BLK_RATE_SETTING">CONTRACTREFNO~COMPONENT~SPLITSERIALNO~SPLITNUMBER~EVENTSEQNO~ROUNDINGRULE~ROUNDINGUNIT~TENOR~TXT_PROD_CD~TXT_PROD_DESC~TXT_PROD_TYPE~TXT_USERREF~TXT_CUSTOMER~TXT_CUST_NAME~TXT_FACILITY~TXT_ROLL_PROD~TXT_CURRENCY~TXT_PRIN_ROLL_AMT~TXT_INT_ROLL_AMT~TXT_TOT_ROLL_AMT~TXT_MAT_DATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_DETAIL" RELATION_TYPE="N" TYPE="BLK_BA_CONT_DETAILS">AGENT_RATE~BA_BROKER_PROD~COF_AMT~CONTRACT_REF_NO~DISCOUNTED_RATE~DISCOUNT_AMT~INTEREST_DAY_BASIS~NET_BORROWING_AMT~PNL_AMT~SPLIT_NUMBER~SPLIT_SERIAL_NO~STAMPING_FEE_AMT~STAMPING_FEE_RATE~TREASURY_RATE</FN>'; 
msgxml += '      <FN PARENT="BLK_SPLIT_PROD_INTCOMP" RELATION_TYPE="1" TYPE="BLK_LFTB_CONT_ADDL_INT_DTL">COMPONENT~CONTRACT_REF_NO~OBSERVATION_SHIFT~PRODUCT_CODE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_METHOD~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_RATE_COMPOUNDING~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~RFR_RATE_TYPE~RFR_SPREAD_ADJ_COMP_METH~SERIAL_NO~SPLIT_SERIAL_NO~VERSION_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_DETAIL" RELATION_TYPE="N" TYPE="BLK_BA_PART_RPRS_DTLS">AGENT_RATE~BA_BROKER_PROD~COF_AMT~CONTRACT_REF_NO~DISCOUNTED~DISCOUNTED_AMT~DISCOUNTED_PRICE~DISCOUNT_RATE~DISC_PRICE_ROUNDING_RULE~DISC_PRICE_ROUNDING_UNIT~EVENT_SEQ_NO~INTEREST_DAY_BASIS~NET_BORROWING_AMT~PARTICIPANT~PNL_AMT~SPLIT_NUMBER~SPLIT_SERIAL_NO~STAMPING_FEE_AMT~STAMPING_FEE_RATE~TREASURY_RATE~VERSION_NO~MAX_RATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONT_SPLIT_DETAIL" RELATION_TYPE="N" TYPE="BLK_ADDL_BA_DTLS">AGENT_RATE~BA_BROKER_PROD~CONTRACT_REF_NO~DISC_PRICE_ROUNDING_UNIT~MAX_RATE~SPLIT_NUMBER~SPLIT_SERIAL_NO~TREASURY_RATE</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_CONTRACT" RELATION_TYPE="1" TYPE="BLK_CONTRACT_SUMMARY">CONREFNO~SPLITVALUEDATE~SPLITBOOKDATE~AUTHSTATUS</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDREPRS";
var defaultWhereClause = "";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_CONTRACT_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_CONTRACT" : "","BLK_CONT_SPLIT_MASTER" : "BLK_CONTRACT~1","BLK_CONT_SPLIT_DETAIL" : "BLK_CONT_SPLIT_MASTER~N","BLK_SPLIT_PROD_INTCOMP" : "BLK_CONT_SPLIT_DETAIL~N","BLK_SPLIT_PROD_MRGCOMP" : "BLK_SPLIT_PROD_INTCOMP~N","BLK_EVNT_LOG" : "BLK_CONT_SPLIT_MASTER~1","BLK_CONTRACT_SUMMARY" : "BLK_CONTRACT~1","BLK_SPLIT_AMOUNT" : "BLK_CONT_SPLIT_MASTER~1","BLK_INT_RATE_FIXING" : "BLK_SPLIT_PROD_INTCOMP~N","BLK_EXRATE_FIXING" : "BLK_CONT_SPLIT_DETAIL~N","BLK_RATE_SETTING" : "BLK_SPLIT_PROD_INTCOMP~N","BLK_BA_CONT_DETAILS" : "BLK_CONT_SPLIT_DETAIL~N","BLK_LFTB_CONT_ADDL_INT_DTL" : "BLK_SPLIT_PROD_INTCOMP~1","BLK_BA_PART_RPRS_DTLS" : "BLK_CONT_SPLIT_DETAIL~N","BLK_ADDL_BA_DTLS" : "BLK_CONT_SPLIT_DETAIL~N"}; 

 var dataSrcLocationArray = new Array("BLK_CONTRACT","BLK_CONT_SPLIT_MASTER","BLK_CONT_SPLIT_DETAIL","BLK_SPLIT_PROD_INTCOMP","BLK_SPLIT_PROD_MRGCOMP","BLK_EVNT_LOG","BLK_CONTRACT_SUMMARY","BLK_SPLIT_AMOUNT","BLK_INT_RATE_FIXING","BLK_EXRATE_FIXING","BLK_RATE_SETTING","BLK_BA_CONT_DETAILS","BLK_LFTB_CONT_ADDL_INT_DTL","BLK_BA_PART_RPRS_DTLS","BLK_ADDL_BA_DTLS"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDREPRS.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDREPRS.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_CONTRACT__CONREFNO";
pkFields[0] = "BLK_CONTRACT__CONREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
var modifyAmendArr = new Array(); 
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_CONTRACT__CONREFNO__LOV_CONTRACT":["BLK_CONTRACT__CONREFNO~BLK_CONTRACT__USER_REF_NO~BLK_CONT_SPLIT_MASTER__PRODUCT~BLK_CONT_SPLIT_MASTER__COUNTERPARTY~BLK_CONT_SPLIT_MASTER__CONTCCY~BLK_CONTRACT__LATESTEVNTSEQ~BLK_CONTRACT__PRODUCT_TYPE~BLK_CONT_SPLIT_MASTER__OUTPRINCIPLE~BLK_CONTRACT__TXT_FACILITY_NAME~BLK_CONTRACT__TXT_TRANCHE_REF~BLK_CONT_SPLIT_MASTER__PRODESCR~BLK_CONT_SPLIT_MASTER__COUNTRPARTYDESC~","","N~N~N~N~N~N~N~N~N~N~N~N",""],"BLK_CONT_SPLIT_DETAIL__PROD__LOV_PRODUCT":["BLK_CONT_SPLIT_DETAIL__PROD~BLK_CONT_SPLIT_DETAIL__TXT_PROD_DESC_DETAIL~","BLK_CONTRACT__CONREFNO!VARCHAR2~BLK_CONT_SPLIT_MASTER__TXT_TRNREFNUM!VARCHAR2~BLK_CONT_SPLIT_MASTER__TXT_TRNREFNUM!VARCHAR2~BLK_CONT_SPLIT_MASTER__TXT_TRNREFNUM!VARCHAR2~BLK_CONT_SPLIT_MASTER__TXT_TRNREFNUM!VARCHAR2~BLK_CONT_SPLIT_MASTER__COUNTERPARTY!VARCHAR2","N~N",""],"BLK_SPLIT_PROD_INTCOMP__RATECODE__LOV_RATE_CODE_COMBINED":["BLK_SPLIT_PROD_INTCOMP__RATECODE~~","BLK_CONT_SPLIT_MASTER__CONTCCY!~BLK_CONTRACT__CONREFNO!~BLK_SPLIT_PROD_INTCOMP__RAETYPE!~BLK_SPLIT_PROD_INTCOMP__RAETYPE!~BLK_LFTB_CONT_ADDL_INT_DTL__RFR_RATE_TYPE!","N~N",""],"BLK_INT_RATE_FIXING__RATECODE__LOV_RATE_CODE_INT_FIXING":["BLK_INT_RATE_FIXING__RATECODE~~","BLK_CONT_SPLIT_MASTER__CONTCCY!VARCHAR2","N~N",""],"BLK_INT_RATE_FIXING__TENORVALUE__LOV_TENOR_VALUE_INT_RATE":["BLK_INT_RATE_FIXING__TENORVALUE~~~~","BLK_INT_RATE_FIXING__RATECODE!~BLK_INT_RATE_FIXING__TXT_CCY!","N~N~N~N",""],"BLK_BA_CONT_DETAILS__BA_BROKER_PROD__LOV_BROKER_PROD":["BLK_BA_CONT_DETAILS__BA_BROKER_PROD~~","","N~N",""],"BLK_ADDL_BA_DTLS__BA_BROKER_PROD__LOV_BROKER_PROD":["BLK_ADDL_BA_DTLS__BA_BROKER_PROD~~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_CONT_SPLIT_DETAIL","BLK_SPLIT_PROD_MRGCOMP","BLK_BA_CONT_DETAILS","BLK_BA_PART_RPRS_DTLS");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("LBCADVIC~BLK_CONTRACT","LBCFPMLS~BLK_CONTRACT"); 

 var CallFormRelat=new Array("OLTBS_CONTRACT.CONTRACT_REF_NO = OLTBS_GTEMP_EVENT_ADVICE.CONTRACT_REF_NO","OLTBS_CONTRACT.CONTRACT_REF_NO = LBTBS_CONT_MEDIA_FOR_ALL_PART.CONTRACT_REF_NO"); 

 var CallRelatType= new Array("1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDREPRS"]="KERNEL";
ArrPrntFunc["LBDREPRS"]="";
ArrPrntOrigin["LBDREPRS"]="";
ArrRoutingType["LBDREPRS"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDREPRS"]="N";
ArrCustomModified["LBDREPRS"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_EXCHANGE_RATE":"PRODCD~PRODDESC~PRODTYPE~CONTRACT~USERREFNO~CUST~CUSTNAME~REFFSTRTDATE~CCY~MATUDATE~TRANCHREF~FACILITYNAME~TRANCHECCY~RATECODE~RATETYPE~SPLITNO","LBCADVIC":"CONTREFNO~EVNTSEQNO","LBCFPMLS":"CONTRACT_REF_NO~EVENT_SEQ_NO","OLDEVENT":"CONTREF~ACTION_CODE"};
var scrArgSource = {"CVS_EXCHANGE_RATE":"BLK_CONT_SPLIT_DETAIL__PROD~BLK_CONT_SPLIT_DETAIL__TXT_PROD_DESC_DETAIL~BLK_CONTRACT__PRODUCT_TYPE~BLK_CONTRACT__CONREFNO~BLK_CONTRACT__USER_REF_NO~BLK_CONT_SPLIT_MASTER__COUNTERPARTY~BLK_CONT_SPLIT_MASTER__COUNTRPARTYDESC~BLK_CONT_SPLIT_MASTER__SPLITVALUEDATE~BLK_CONT_SPLIT_MASTER__CONTCCY~BLK_CONT_SPLIT_DETAIL__MATURITYDATE~BLK_CONTRACT__TXT_TRANCHE_REF~BLK_CONTRACT__TXT_FACILITY_NAME~BLK_CONTRACT__TXT_PRM_TRANCHE_CCY~BLK_CONTRACT__TXT_PRM_RATE_CODE~BLK_CONTRACT__TXT_PRM_RATE_TYPE~BLK_CONT_SPLIT_DETAIL__SERIALNO","LBCADVIC":"BLK_CONTRACT__CONREFNO~BLK_CONTRACT__LATESTEVNTSEQ","LBCFPMLS":"BLK_CONTRACT__CONREFNO~BLK_CONTRACT__LATESTEVNTSEQ","OLDEVENT":"BLK_CONTRACT__CONREFNO~"};
var scrArgVals = {"CVS_EXCHANGE_RATE":"~~~~~~~~~~~~~~~","LBCADVIC":"~","LBCFPMLS":"~","OLDEVENT":"~EXECUTEQUERY"};
var scrArgDest = {"CVS_EXCHANGE_RATE":"BLK_EXRATE_FIXING__TXT_PROD_CD~BLK_EXRATE_FIXING__TXT_PROD_DESCR~BLK_EXRATE_FIXING__TXT_PROD_TYPE_DESC~BLK_EXRATE_FIXING__CONTRACTREFNO~BLK_EXRATE_FIXING__TXT_USERREF~BLK_EXRATE_FIXING__TXT_CUSTOMER~BLK_EXRATE_FIXING__TXT_CUST_NAME~BLK_EXRATE_FIXING__EXRATESTARTDATE~BLK_EXRATE_FIXING__CONTRACTCCY~BLK_EXRATE_FIXING__TXT_PRM_MAT_DATE~BLK_EXRATE_FIXING__TXT_PRM_TRANCHE_REF_NO~BLK_EXRATE_FIXING__TXT_FACILITY_NAME~BLK_EXRATE_FIXING__TRANCHECCY~BLK_EXRATE_FIXING__TXT_RATE_CODE~BLK_EXRATE_FIXING__TXT_RATE_TYPE~BLK_EXRATE_FIXING__SPLITNO"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"LBCADVIC":"","LBCFPMLS":""};
var dpndntOnSrvs = {"LBCADVIC":"","LBCFPMLS":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------