/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2024, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LBDTRUPL_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_OLTBS_UPLOAD_MASTER":"AMOUNT~PROD~COUNTPARTY~TXTCUSTNAME~EXTREFNO~SYNDREFNO~USERREFNO~BOOKDATE~DEALDATE~MATURITYDATE~ORIGSTRTDATE~VALUEDATE~DEPTCODE~EXPIRYDATE~MAXDDAMT~MINDDAMT~CURRDDNO~DDALLOWED~DFLTACC~DFLTACCBRNCH~DFLTSETTLECCY~APPBKVALREV~CASPTCPN~LIMTRKREQD~LIQBKVALSCH~NETACROSSDD~PRIMSYND~REVCOMM~SUPCONF~SUPPBKMSG~VERFUNDS~CASCSCH~CHAP3WAIV~DDEXPIRY~FATCAWAIV~GF~IGNHOL~MVACRSMNTH~INITMODE~PARTSSIPKUP~SCHMVMNT~INCLSWINGCOMFEE~INTFEEDIST~MSCHIGNHOLS~CONSBRNCHHOL~MSCHMVACRSMNTH~MSCHAPFCHOLCCY~MSCHAPCONHOLCCY~MSCHAPLCHOLCCY~MVCOMMREDNSCH~RPYMNTRULE~CANCELRULE~AVEXPRULE~PREPYMNTRUL~AUTREPYSCH~REDNSCHAPP~TXTSYNDUSRREF~PRODTYPE~TXTPRODDESC~CCY~HOLCCY~ADMIN~REMARKS~TMSTMP~USERID~TXTDRFTSTATUS~SRCCODE~TXTFACNAME~ORGACTCOD~TRANCHEREFNO","BLK_OLTBS_UPLOAD_SCHEDULES":"AMT~CMPT~FREQ~FREQUNIT~NUMSCH~SCHTYP~STRTDT~BRANCHCODE~EXTCONTREFNO~SRCCODE","BLK_LBTBS_UPLOAD_BRR_CCY":"BLOCKCCY~CCY~EXCHRATEFXDYS~EXCHRATEFXTIM~INTRATEFXDYS~NOTCDAYS~NOTCTIM~TXTDESC~BRANCHCODE~EXTCONTREFNO~SRCCODE","BLK_LBTBS_UPLOAD_HOL_CCY":"DDCCY~TXTDESC~BRANCHCODE~CCY~EXTCONTREF~SRCCODE","BLK_LBTBS_UPLOAD_BORROWERS":"BLOCKED~CONTRACTUAL~CUSTNO~NETTINGPREF~SSICOUNTERPARTY~TXTCUSTNAME~TXTSSICPARTY~BRANCH~EXTREFNO~SRCCODE","BLK_LBTBS_BORR_SETTLE_UPLOAD_DET":"CURRENCY~SSIMNEMONIC~BRANCH~CUSTNO~EXTREFNO~SRCCODE~SSICNTRPARTY","BLK_LBTBS_UPLOAD_BORR_ENTITIES":"ENTITY~PRIMARY~TXTENTITYDESC~BRANCH~CUSTNO~EXTCONTREFNO~SRCCODE","BLK_LBTBS_UPLOAD_PARTICIPANT":"ASSTAMT~ASSTRATIO~PARTICIPANT~SELFPART~TXTPARTNAME~TXTCOMPONENTDESC~BRANCH~EXTCONTREFNO~SRCCODE","BLK_OLTBS_UPLOAD_ENTITY":"ENTITYID~PRIMARYENTITY~TXTENTITYDESC~BRANCH~CUSTNO~EXTCONTRACTREFNO~SRCCODE","BLK_LBTBS_UPLOAD_DRAWDOWN_PROD":"PRDCODE~ROUNDINGRULE~TXTPRODDESC~BRANCHCODE~EXTCONTREFNO~SRCCODE","BLK_LBTBS_UPLOAD_DRAWDOWN_COMP":"COMPONENT~TXTCOMPDESC~BRANCH~EXTCONTREFNO~PROD~SRCCODE","BLK_LBTBS_UPLOAD_PART_CURR_DET":"CURRENCY~SSIMNEMONIC~BRANCH~EXTCONTREFNO~PARTICIPANT~SRCCODE","BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO":"COMPONENTRATIO~COMPONENT~COMPONENTTYPE~BRANCH~CUSTNO~EXTREFNO~SRCCODE","BLK_OLTBS_UPLOAD_PARTY_DETAILS":"PARTYID~PARTYTYPE~TXTPARTYNAME~BRANCH~EXTREFNO~SRCCODE","BLK_LFTBS_UPLOAD_FEE":"BILLNOTCDAYS~BILLNOTCREQD~CMPT~CMPTCCY~ENDDATE~FEECOLLMODE~FEERUL~INTBASIS~LIQDPREF~STRTDATE~BRANCH~EXTREFNO~SRCCODE","BLK_LFTBS_UPLOAD_FEE_SCHEDULES":"AMT~FREQ~FREQUNIT~NUMSCH~STRTDT~BRANCH~COMPONENT~EXTREFNO~SRCCODE","BLK_OLTBS_EXT_CONTRACT_STAT":"ERRCODE~ERRMSG~BRANCH~EXTREFNO~SOURCE","BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN":"AMT~ENDDATE~FREQ~NUMSCH~RPYMNTRULE~STARTDATE~UNIT~BRANCH~EXTREFNO~SRCCODE","BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES":"AMT~DUEDATE~REPAYMENTRULE~BRANCH~EXTREFNO~SRCCODE"};

var multipleEntryPageSize = {"BLK_OLTBS_UPLOAD_SCHEDULES" :"15" ,"BLK_LBTBS_UPLOAD_BRR_CCY" :"15" ,"BLK_LBTBS_UPLOAD_HOL_CCY" :"15" ,"BLK_LBTBS_UPLOAD_BORROWERS" :"15" ,"BLK_LBTBS_BORR_SETTLE_UPLOAD_DET" :"15" ,"BLK_LBTBS_UPLOAD_BORR_ENTITIES" :"15" ,"BLK_LBTBS_UPLOAD_PARTICIPANT" :"15" ,"BLK_OLTBS_UPLOAD_ENTITY" :"15" ,"BLK_LBTBS_UPLOAD_DRAWDOWN_PROD" :"15" ,"BLK_LBTBS_UPLOAD_DRAWDOWN_COMP" :"15" ,"BLK_LBTBS_UPLOAD_PART_CURR_DET" :"15" ,"BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO" :"15" ,"BLK_OLTBS_UPLOAD_PARTY_DETAILS" :"15" ,"BLK_LFTBS_UPLOAD_FEE" :"15" ,"BLK_LFTBS_UPLOAD_FEE_SCHEDULES" :"15" ,"BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN" :"15" ,"BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES" :"15" };

var multipleEntrySVBlocks = "";

var tabMEBlks = {"CVS_MAIN__TAB_SCH":"BLK_OLTBS_UPLOAD_SCHEDULES","CVS_MAIN__TAB_CURR":"BLK_LBTBS_UPLOAD_BRR_CCY~BLK_LBTBS_UPLOAD_HOL_CCY","CVS_MAIN__TAB_BORR":"BLK_LBTBS_UPLOAD_BORROWERS~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET~BLK_LBTBS_UPLOAD_BORR_ENTITIES","CVS_MAIN__TAB_PART":"BLK_LBTBS_UPLOAD_PARTICIPANT~BLK_OLTBS_UPLOAD_ENTITY~BLK_LBTBS_UPLOAD_PART_CURR_DET~BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO","CVS_MAIN__TAB_DDPRD":"BLK_LBTBS_UPLOAD_DRAWDOWN_PROD~BLK_LBTBS_UPLOAD_DRAWDOWN_COMP","CVS_MAIN__TAB_PARTYTYP":"BLK_OLTBS_UPLOAD_PARTY_DETAILS","CVS_MAIN__TAB_FEES":"BLK_LFTBS_UPLOAD_FEE~BLK_LFTBS_UPLOAD_FEE_SCHEDULES","CVS_MAIN__TAB_TRSCH":"BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN~BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_OLTBS_UPLOAD_MASTER">AMOUNT~PROD~COUNTPARTY~TXTCUSTNAME~EXTREFNO~SYNDREFNO~USERREFNO~BOOKDATE~DEALDATE~MATURITYDATE~ORIGSTRTDATE~VALUEDATE~DEPTCODE~EXPIRYDATE~MAXDDAMT~MINDDAMT~CURRDDNO~DDALLOWED~DFLTACC~DFLTACCBRNCH~DFLTSETTLECCY~APPBKVALREV~CASPTCPN~LIMTRKREQD~LIQBKVALSCH~NETACROSSDD~PRIMSYND~REVCOMM~SUPCONF~SUPPBKMSG~VERFUNDS~CASCSCH~CHAP3WAIV~DDEXPIRY~FATCAWAIV~GF~IGNHOL~MVACRSMNTH~INITMODE~PARTSSIPKUP~SCHMVMNT~INCLSWINGCOMFEE~INTFEEDIST~MSCHIGNHOLS~CONSBRNCHHOL~MSCHMVACRSMNTH~MSCHAPFCHOLCCY~MSCHAPCONHOLCCY~MSCHAPLCHOLCCY~MVCOMMREDNSCH~RPYMNTRULE~CANCELRULE~AVEXPRULE~PREPYMNTRUL~AUTREPYSCH~REDNSCHAPP~TXTSYNDUSRREF~PRODTYPE~TXTPRODDESC~CCY~HOLCCY~ADMIN~REMARKS~TMSTMP~USERID~TXTDRFTSTATUS~SRCCODE~TXTFACNAME~ORGACTCOD~TRANCHEREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_OLTBS_UPLOAD_SCHEDULES">AMT~CMPT~FREQ~FREQUNIT~NUMSCH~SCHTYP~STRTDT~BRANCHCODE~EXTCONTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_BRR_CCY">BLOCKCCY~CCY~EXCHRATEFXDYS~EXCHRATEFXTIM~INTRATEFXDYS~NOTCDAYS~NOTCTIM~TXTDESC~BRANCHCODE~EXTCONTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_BRR_CCY" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_HOL_CCY">DDCCY~TXTDESC~BRANCHCODE~CCY~EXTCONTREF~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_BORROWERS">BLOCKED~CONTRACTUAL~CUSTNO~NETTINGPREF~SSICOUNTERPARTY~TXTCUSTNAME~TXTSSICPARTY~BRANCH~EXTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_BORROWERS" RELATION_TYPE="N" TYPE="BLK_LBTBS_BORR_SETTLE_UPLOAD_DET">CURRENCY~SSIMNEMONIC~BRANCH~CUSTNO~EXTREFNO~SRCCODE~SSICNTRPARTY</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_BORROWERS" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_BORR_ENTITIES">ENTITY~PRIMARY~TXTENTITYDESC~BRANCH~CUSTNO~EXTCONTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_PARTICIPANT">ASSTAMT~ASSTRATIO~PARTICIPANT~SELFPART~TXTPARTNAME~TXTCOMPONENTDESC~BRANCH~EXTCONTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_OLTBS_UPLOAD_ENTITY">ENTITYID~PRIMARYENTITY~TXTENTITYDESC~BRANCH~CUSTNO~EXTCONTRACTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_DRAWDOWN_PROD">PRDCODE~ROUNDINGRULE~TXTPRODDESC~BRANCHCODE~EXTCONTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_DRAWDOWN_PROD" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_DRAWDOWN_COMP">COMPONENT~TXTCOMPDESC~BRANCH~EXTCONTREFNO~PROD~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_PART_CURR_DET">CURRENCY~SSIMNEMONIC~BRANCH~EXTCONTREFNO~PARTICIPANT~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LBTBS_UPLOAD_PARTICIPANT" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO">COMPONENTRATIO~COMPONENT~COMPONENTTYPE~BRANCH~CUSTNO~EXTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_OLTBS_UPLOAD_PARTY_DETAILS">PARTYID~PARTYTYPE~TXTPARTYNAME~BRANCH~EXTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_LFTBS_UPLOAD_FEE">BILLNOTCDAYS~BILLNOTCREQD~CMPT~CMPTCCY~ENDDATE~FEECOLLMODE~FEERUL~INTBASIS~LIQDPREF~STRTDATE~BRANCH~EXTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_UPLOAD_FEE" RELATION_TYPE="N" TYPE="BLK_LFTBS_UPLOAD_FEE_SCHEDULES">AMT~FREQ~FREQUNIT~NUMSCH~STRTDT~BRANCH~COMPONENT~EXTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="1" TYPE="BLK_OLTBS_EXT_CONTRACT_STAT">ERRCODE~ERRMSG~BRANCH~EXTREFNO~SOURCE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="N" TYPE="BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN">AMT~ENDDATE~FREQ~NUMSCH~RPYMNTRULE~STARTDATE~UNIT~BRANCH~EXTREFNO~SRCCODE</FN>'; 
msgxml += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="1" TYPE="BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES">AMT~DUEDATE~REPAYMENTRULE~BRANCH~EXTREFNO~SRCCODE</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_OLTBS_UPLOAD_MASTER" RELATION_TYPE="1" TYPE="BLK_LBVWS_TRNUPLD_SUMMARY">COUNTERPARTY~CUSTOMER_NAME~EXTREFNO~PRODUCT</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "LBDTRUPL";
var defaultWhereClause = "BRANCH = GLOBAL.CURRENT_BRANCH AND MODULE = 'LB' and exists (Select 1 From OLVW_USER_ACCESS_PRODUCTS Where PRODUCT_CODE = PRODUCT AND USER_ID = global.user_id)";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_LBVWS_TRNUPLD_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_OLTBS_UPLOAD_MASTER" : "","BLK_OLTBS_UPLOAD_SCHEDULES" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LBTBS_UPLOAD_BRR_CCY" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LBTBS_UPLOAD_HOL_CCY" : "BLK_LBTBS_UPLOAD_BRR_CCY~N","BLK_LBTBS_UPLOAD_BORROWERS" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LBTBS_BORR_SETTLE_UPLOAD_DET" : "BLK_LBTBS_UPLOAD_BORROWERS~N","BLK_LBTBS_UPLOAD_BORR_ENTITIES" : "BLK_LBTBS_UPLOAD_BORROWERS~N","BLK_LBTBS_UPLOAD_PARTICIPANT" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_OLTBS_UPLOAD_ENTITY" : "BLK_LBTBS_UPLOAD_PARTICIPANT~N","BLK_LBTBS_UPLOAD_DRAWDOWN_PROD" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LBTBS_UPLOAD_DRAWDOWN_COMP" : "BLK_LBTBS_UPLOAD_DRAWDOWN_PROD~N","BLK_LBTBS_UPLOAD_PART_CURR_DET" : "BLK_LBTBS_UPLOAD_PARTICIPANT~N","BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO" : "BLK_LBTBS_UPLOAD_PARTICIPANT~N","BLK_OLTBS_UPLOAD_PARTY_DETAILS" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LFTBS_UPLOAD_FEE" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LFTBS_UPLOAD_FEE_SCHEDULES" : "BLK_LFTBS_UPLOAD_FEE~N","BLK_OLTBS_EXT_CONTRACT_STAT" : "BLK_OLTBS_UPLOAD_MASTER~1","BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN" : "BLK_OLTBS_UPLOAD_MASTER~N","BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES" : "BLK_OLTBS_UPLOAD_MASTER~1"}; 

 var dataSrcLocationArray = new Array("BLK_OLTBS_UPLOAD_MASTER","BLK_OLTBS_UPLOAD_SCHEDULES","BLK_LBTBS_UPLOAD_BRR_CCY","BLK_LBTBS_UPLOAD_HOL_CCY","BLK_LBTBS_UPLOAD_BORROWERS","BLK_LBTBS_BORR_SETTLE_UPLOAD_DET","BLK_LBTBS_UPLOAD_BORR_ENTITIES","BLK_LBTBS_UPLOAD_PARTICIPANT","BLK_OLTBS_UPLOAD_ENTITY","BLK_LBTBS_UPLOAD_DRAWDOWN_PROD","BLK_LBTBS_UPLOAD_DRAWDOWN_COMP","BLK_LBTBS_UPLOAD_PART_CURR_DET","BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO","BLK_OLTBS_UPLOAD_PARTY_DETAILS","BLK_LFTBS_UPLOAD_FEE","BLK_LFTBS_UPLOAD_FEE_SCHEDULES","BLK_OLTBS_EXT_CONTRACT_STAT","BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN","BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LBDTRUPL.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LBDTRUPL.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_OLTBS_UPLOAD_MASTER__EXTREFNO";
pkFields[0] = "BLK_OLTBS_UPLOAD_MASTER__EXTREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_LBTBS_BORR_SETTLE_UPLOAD_DET":["CURRENCY","SSIMNEMONIC"],"BLK_LBTBS_UPLOAD_BORROWERS":["BLOCKED","CONTRACTUAL","CUSTNO","NETTINGPREF","SSICOUNTERPARTY"],"BLK_LBTBS_UPLOAD_BORR_ENTITIES":["ENTITY","PRIMARY"],"BLK_LBTBS_UPLOAD_BRR_CCY":["BLOCKCCY","CCY","EXCHRATEFXDYS","EXCHRATEFXTIM","INTRATEFXDYS","NOTCDAYS","NOTCTIM"],"BLK_LBTBS_UPLOAD_DRAWDOWN_PROD":["BTN_POPULATE2","PRDCODE","ROUNDINGRULE"],"BLK_LBTBS_UPLOAD_HOL_CCY":["DDCCY"],"BLK_LBTBS_UPLOAD_PARTICIPANT":["ASSTAMT","ASSTRATIO","BTN_POPULATE","PARTICIPANT","SELFPART","TXTPARTNAME"],"BLK_LBTBS_UPLOAD_PART_CURR_DET":["CURRENCY","SSIMNEMONIC"],"BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN":["AMT","BTN_PYMNTSCH","ENDDATEI","FREQ","NUMSCH","RPYMNTRULE","STARTDATEI","UNIT"],"BLK_LFTBS_UPLOAD_FEE_SCHEDULES":["AMT","FREQ","FREQUNIT","NUMSCH","STRTDTI"],"BLK_LFTBS_UPLOAD_FEE":["BTN_DFLT_FEE","CMPT","ENDDATEI","STRTDATEI"],"BLK_OLTBS_UPLOAD_ENTITY":["ENTITYID","PRIMARYENTITY"],"BLK_OLTBS_UPLOAD_MASTER":["ADMIN","AMOUNT","APPBKVALREV","AUTREPYSCH","AVEXPRULE","BOOKDATEI","BTN_UPLD","CANCELRULE","CASCSCH","CASPTCPN","CCY","CHAP3WAIV","CONSBRNCHHOL","DDALLOWED","DDEXPIRY","DEALDATEI","DEPTCODE","DFLTACC","DFLTACCBRNCH","DFLTSETTLECCY","EXPIRYDATEI","FATCAWAIV","GF","HOLCCY","IGNHOL","INCLSWINGCOMFEE","INITMODE","INTFEEDIST","LIMTRKREQD","LIQBKVALSCH","MATURITYDATEI","MAXDDAMT","MINDDAMT","MSCHAPCONHOLCCY","MSCHAPFCHOLCCY","MSCHAPLCHOLCCY","MSCHIGNHOLS","MSCHMVACRSMNTH","MVACRSMNTH","MVCOMMREDNSCH","NETACROSSDD","ORIGSTRTDATEI","PARTSSIPKUP","PREPYMNTRUL","PRIMSYND","REVCOMM","RPYMNTRULE","SCHMVMNT","SUPCONF","SUPPBKMSG","VALUEDATEI","VERFUNDS"],"BLK_OLTBS_UPLOAD_PARTY_DETAILS":["PARTYID","PARTYTYPE","TXTPARTYNAME"],"BLK_OLTBS_UPLOAD_SCHEDULES":["AMT","CMPT","FREQ","FREQUNIT","NUMSCH","SCHTYP","STRTDTI"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
//***** Fields Amendable while Query *****
var queryAmendArr = {"BLK_OLTBS_UPLOAD_MASTER":["BTN_UPLD"]};
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_OLTBS_UPLOAD_MASTER__PROD__LOV_TRANCHE_PRODUCT":["BLK_OLTBS_UPLOAD_MASTER__PROD~BLK_OLTBS_UPLOAD_MASTER__TXTPRODDESC~","","N~N",""],"BLK_OLTBS_UPLOAD_MASTER__COUNTPARTY__LOV_CUSTOMERS_ALLOWED":["BLK_OLTBS_UPLOAD_MASTER__COUNTPARTY~~BLK_OLTBS_UPLOAD_MASTER__TXTCUSTNAME~","BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SRCCODE!VARCHAR2","N~N~N",""],"BLK_OLTBS_UPLOAD_MASTER__SYNDREFNO__LOV_SYNDICATION_REF":["BLK_OLTBS_UPLOAD_MASTER__SYNDREFNO~BLK_OLTBS_UPLOAD_MASTER__TXTSYNDUSRREF~~","","N~N~N",""],"BLK_OLTBS_UPLOAD_MASTER__DEPTCODE__LOV_DEP_COD":["~BLK_OLTBS_UPLOAD_MASTER__DEPTCODE~~","","N~N~N",""],"BLK_OLTBS_UPLOAD_MASTER__DFLTACC__LOV_SETTLE_ACCOUNT":["BLK_OLTBS_UPLOAD_MASTER__DFLTACC~BLK_OLTBS_UPLOAD_MASTER__DFLTSETTLECCY~~","BLK_OLTBS_UPLOAD_MASTER__DFLTACCBRNCH!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__DFLTACCBRNCH!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__CCY!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__COUNTPARTY!VARCHAR2","N~N~N",""],"BLK_OLTBS_UPLOAD_MASTER__DFLTACCBRNCH__LOV_SETTLE_ACCOUNT_BRANCH":["BLK_OLTBS_UPLOAD_MASTER__DFLTACCBRNCH~~","","N~N",""],"BLK_OLTBS_UPLOAD_MASTER__CCY__LOV_TRANCHE_CCY":["BLK_OLTBS_UPLOAD_MASTER__CCY~~","","N~N",""],"BLK_OLTBS_UPLOAD_MASTER__HOLCCY__LOV_HOLIDAY_CCY":["BLK_OLTBS_UPLOAD_MASTER__HOLCCY~~","","N~N",""],"BLK_OLTBS_UPLOAD_MASTER__ADMIN__LOV_ADMIN":["BLK_OLTBS_UPLOAD_MASTER__ADMIN~~","","N~N",""],"BLK_OLTBS_UPLOAD_SCHEDULES__CMPT__LOV_SCHEDULE_COMPONENT":["BLK_OLTBS_UPLOAD_SCHEDULES__CMPT~","BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2","N",""],"BLK_LBTBS_UPLOAD_BRR_CCY__CCY__LOV_UPLOAD_BORROWER_CCY":["BLK_LBTBS_UPLOAD_BRR_CCY__CCY~BLK_LBTBS_UPLOAD_BRR_CCY__TXTDESC~","","N~N",""],"BLK_LBTBS_UPLOAD_HOL_CCY__DDCCY__LOV_UPLOAD_HOL_CCY":["BLK_LBTBS_UPLOAD_HOL_CCY__DDCCY~BLK_LBTBS_UPLOAD_HOL_CCY__TXTDESC~","","N~N",""],"BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO__LOV_BORROWERS_ALLOWED":["BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO~~BLK_LBTBS_UPLOAD_BORROWERS__TXTCUSTNAME~","BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SRCCODE!VARCHAR2","N~N~N",""],"BLK_LBTBS_UPLOAD_BORROWERS__SSICOUNTERPARTY__LOV_SSI_COUNTERPARTY":["BLK_LBTBS_UPLOAD_BORROWERS__SSICOUNTERPARTY~~~BLK_LBTBS_UPLOAD_BORROWERS__TXTSSICPARTY~","","N~N~N~N",""],"BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY__LOV_BORR_SETL_CCY":["BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY~~","","N~N",""],"BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__SSIMNEMONIC__LOV_BORR_SSI_MNEMONIC":["~~~~~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__SSIMNEMONIC~~~~","BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2","N~N~N~N~N~N~N~N~N",""],"BLK_LBTBS_UPLOAD_BORR_ENTITIES__ENTITY__LOV_BORROWER_ENTITY":["BLK_LBTBS_UPLOAD_BORR_ENTITIES__ENTITY~BLK_LBTBS_UPLOAD_BORR_ENTITIES__TXTENTITYDESC~~","BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SRCCODE!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2","N~N~N",""],"BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT__LOV_PARTICIPANTS_ALLOWED":["BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT~~BLK_LBTBS_UPLOAD_PARTICIPANT__TXTPARTNAME~","BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SRCCODE!VARCHAR2","N~N~N",""],"BLK_OLTBS_UPLOAD_ENTITY__ENTITYID__LOV_PARTICIPANT_ENTITY":["BLK_OLTBS_UPLOAD_ENTITY__ENTITYID~BLK_OLTBS_UPLOAD_ENTITY__TXTENTITYDESC~~","BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SRCCODE!VARCHAR2~BLK_LBTBS_UPLOAD_BORROWERS__CUSTNO!VARCHAR2","N~N~N",""],"BLK_LBTBS_UPLOAD_DRAWDOWN_PROD__PRDCODE__LOV_PROD":["BLK_LBTBS_UPLOAD_DRAWDOWN_PROD__PRDCODE~BLK_LBTBS_UPLOAD_DRAWDOWN_PROD__TXTPRODDESC~","BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SYNDREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__SRCCODE!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__CASPTCPN!VARCHAR2","N~N",""],"BLK_LBTBS_UPLOAD_DRAWDOWN_COMP__COMPONENT__LOV_COMP":["BLK_LBTBS_UPLOAD_DRAWDOWN_COMP__COMPONENT~BLK_LBTBS_UPLOAD_DRAWDOWN_COMP__TXTCOMPDESC~","BLK_LBTBS_UPLOAD_DRAWDOWN_PROD__PRDCODE!VARCHAR2~BLK_LBTBS_UPLOAD_DRAWDOWN_COMP__TXTCONTRACTREFNO!VARCHAR2~BLK_LBTBS_UPLOAD_DRAWDOWN_COMP__TXTVERSION!VARCHAR2~BLK_LBTBS_UPLOAD_DRAWDOWN_PROD__PRDCODE!VARCHAR2","N~N",""],"BLK_LBTBS_UPLOAD_PART_CURR_DET__CURRENCY__LOV_PART_SETL_CCY":["BLK_LBTBS_UPLOAD_PART_CURR_DET__CURRENCY~~","","N~N",""],"BLK_LBTBS_UPLOAD_PART_CURR_DET__SSIMNEMONIC__LOV_PART_SSI_MNEMONIC":["~~~~~BLK_LBTBS_UPLOAD_PART_CURR_DET__SSIMNEMONIC~~~~","BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2~BLK_LBTBS_UPLOAD_PARTICIPANT__PARTICIPANT!VARCHAR2~BLK_LBTBS_BORR_SETTLE_UPLOAD_DET__CURRENCY!VARCHAR2","N~N~N~N~N~N~N~N~N",""],"BLK_OLTBS_UPLOAD_PARTY_DETAILS__PARTYID__LOV_PARTIES":["BLK_OLTBS_UPLOAD_PARTY_DETAILS__PARTYID~BLK_OLTBS_UPLOAD_PARTY_DETAILS__TXTPARTYNAME~","BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2~BLK_OLTBS_UPLOAD_MASTER__EXTREFNO!VARCHAR2~BLK_OLTBS_UPLOAD_PARTY_DETAILS__PARTYTYPE!VARCHAR2","N~N",""],"BLK_OLTBS_UPLOAD_PARTY_DETAILS__PARTYTYPE__LOV_PARTY_TYPE":["BLK_OLTBS_UPLOAD_PARTY_DETAILS__PARTYTYPE~~","BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2","N~N",""],"BLK_LFTBS_UPLOAD_FEE__CMPT__LOV_FEE_COMPONENT":["BLK_LFTBS_UPLOAD_FEE__CMPT~~","BLK_OLTBS_UPLOAD_MASTER__PROD!VARCHAR2","N~N",""],"BLK_LBVWS_TRNUPLD_SUMMARY__COUNTERPARTY__LOV_CUST_NAME_S":["BLK_LBVWS_TRNUPLD_SUMMARY__COUNTERPARTY~BLK_LBVWS_TRNUPLD_SUMMARY__CUSTOMER_NAME~~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_OLTBS_UPLOAD_SCHEDULES","BLK_LBTBS_UPLOAD_BRR_CCY","BLK_LBTBS_UPLOAD_HOL_CCY","BLK_LBTBS_UPLOAD_BORROWERS","BLK_LBTBS_BORR_SETTLE_UPLOAD_DET","BLK_LBTBS_UPLOAD_BORR_ENTITIES","BLK_LBTBS_UPLOAD_PARTICIPANT","BLK_OLTBS_UPLOAD_ENTITY","BLK_LBTBS_UPLOAD_DRAWDOWN_PROD","BLK_LBTBS_UPLOAD_DRAWDOWN_COMP","BLK_LBTBS_UPLOAD_PART_CURR_DET","BLK_LBTBS_UPLOAD_PARTICIPANT_RATIO","BLK_OLTBS_UPLOAD_PARTY_DETAILS","BLK_LFTBS_UPLOAD_FEE","BLK_LFTBS_UPLOAD_FEE_SCHEDULES","BLK_LBTBS_UPLOAD_TR_SCHEDULE_IN","BLK_LBTBS_UPLOAD_TRANCHE_SCHEDULES");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array(); 

 var CallFormRelat=new Array(); 

 var CallRelatType= new Array(); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LBDTRUPL"]="KERNEL";
ArrPrntFunc["LBDTRUPL"]="";
ArrPrntOrigin["LBDTRUPL"]="";
ArrRoutingType["LBDTRUPL"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LBDTRUPL"]="N";
ArrCustomModified["LBDTRUPL"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {};
var scrArgSource = {};
var scrArgVals = {};
var scrArgDest = {};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {};
var dpndntOnSrvs = {};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------