/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : LFCINTCH_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = '';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_MASTER_INT":"CONTRACTREFNO~MODULE~PRDCD~LATEVNSEQNO~PRODUCTDESC~ACTION_CD~CURRENCY~COUNTERPARTY~AGENCY_CONTRACT~MATURITY_DATE~AMOUNT~VALUE_DATE~FUNC_ID~TENOR_BASED_SPREAD~SHOW_ALL_PREVIOUS~SHOW_AMENDABLE_PREVIOUS~TXTCONTAMT~TXTSPREADTYPE~TXTMAINFUNCTION~ONCE_AUTH","BLK_LFTBS_CONTRACT_INTEREST":"NETRATEDESC~AMORTIZATIONCONSTCOMPONENT~RATESIGN~NETACCRUALDESC~SPECIALRATETYPE~CURRENCY~TOTALAMTLIQUIDATEDDESC~COMPONENT~EVENTDESC~CONTRACTREFERENCENO~COMPONENTDESC~EVENT~INTERESTBASIS~RATE~BORROWLENDINDDESC~SPREAD~RATETYPE~LIQUIDITYPREMIUMTYPE~LIQUIDITYPREMIUM~MARGIN~FIXEDRATETYPEDESC~PENALTYTENOR~SPECIALPENALTYCOMPONENTDESC~RATECALCTYPE~BORROWLENDIND~MAINCOMPONENT~RESETTENOR~WAIVER~ACQUIREDAMOUNT~AMOUNT~PREPAYMENTPENALTYRATECODE~FIXEDRATECODE~FIXEDRATETYPE~DOMICILECCY~FLOATINGRATE~LIQUIDITYPREMIUMCOMPONENT~RATECODEUSAGE~RATEREVISIONMETHOD~MINRATE~MAXRATE~ACCRUALREQD~STATUS~RATECODE~PICKUPEVENTSEQNO~EVENTSEQNO~CHANGEDURINGAMENDMENT~TRANSACTIONDATE~VALUEDATE~SHOWNINCONTRACTMAINSCREEN~PENALTYTYPE~ADJUSTMENTRATE~DISCACCRAPPLICABLE~CUSTMARGIN~ACCRUALCCY~INTPERIODBASIS~CCYROUNDUNIT~CCYDECIMALS~CCYROUNDRULE~NOINTONPREMATUREWITHDRAWL~REAPPLYINTONOUTSTANDAMT~REAPPLYINTONPREPAIDAMT~REPLICATE~RETAINMAINCOMPPROP~BILLINGNOTICEDAYS~BILLINGNOTICEREQD~INTCOMPUTATION~PENALTYSTARTDATEBASIS~MAXRATESIGN~MINRATESIGN~TENORAMTSPREAD~TENORWISESPREAD~AMOUNTWISESPREAD~TILLDATEACCDESC~HOLCOMPOUND~NEGATIVE_INTEREST_RATE_ALLOWED~RATEUI~RATEFIXINGREQD~RATEFIXINGDAYS~TXT_RATE_FIXING_DATE_ACTUAL~MORAINTRATE~EXPONENTIAL_FLAG~RATE_BASIS~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~ACCL_FLT_RATE_PCT~ALLOW_REPORTING_ONLY~REPORTING_COMP_TYPE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_SPREAD_ADJ_COMP_METH~SPREAD_ADJ~ALLOW_ACCL_FLT_RATE~CREDIT_COMPONENT~RFR_RATE_COMPOUNDING~RFR_RATE_TYPE~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~OBSERVATION_SHIFT~PEN_CMPDNG_REQD~BKDT_VAMI_RTPK_FG","BLK_RATEFIX":"COMPONENT~CURRESETDT~RATECODE~SPREAD~NXTRESETDT~RESETVALDT~RTFIXESN~RTFIXSTAT~REMARKS~RATE~EXTTRNREFNO~TXTCOMPONENTDESC~CURRENCY~FINALRATE","BLK_SPREAD_INT":"CONTRACTREFNO~PRDCD~CUSTOMERNO~BRANCHCODE~DEPTCODE~SPREADTYPE~TSOURCE~AMTTYPE","BLK_SPREAD_CCY":"CCY~CCYDESC~CONTRACT_REF_NO~CUSTOMER_NO~PRODUCT_CODE~BRANCH_CODE","BLK_SPREAD_EFFDATE":"CUSTOMER_NO~PRODUCT_CODE~CONTRACT_REF_NO~EFFECTIVE_DATE~BRANCH_CODE~LAST_CHANGE_TIMESTAMP~RECALC_REQD~CURRENCY","BLK_SPREAD_DETAILS":"SPREAD_RATE~CURRENCY~TO_BASIS_AMT~FROM_BASIS_AMT~EFFECTIVE_DATE~BRANCH_CODE~PRODUCT_CODE~CONTRACT_REF_NO~CUSTOMER_NO","BLK_AGENCY_RT":"CONTRACT_REF_NO~EFFECTIVE_DATE~COMPONENT~BASE_RATE~SPREAD~FINAL_RATE~STATUS"};

var multipleEntryPageSize = {"BLK_SPREAD_CCY" :"15" ,"BLK_SPREAD_EFFDATE" :"15" ,"BLK_SPREAD_DETAILS" :"15" ,"BLK_AGENCY_RT" :"15" };

var multipleEntrySVBlocks = "BLK_LFTBS_CONTRACT_INTEREST~BLK_RATEFIX";

var tabMEBlks = {"CVS_SPREAD_INT__TAB_MAIN":"BLK_SPREAD_CCY~BLK_SPREAD_EFFDATE~BLK_SPREAD_DETAILS","CVS_AGENCY_RATE__TAB_MAIN":"BLK_AGENCY_RT"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_MASTER_INT">CONTRACTREFNO~MODULE~PRDCD~LATEVNSEQNO~PRODUCTDESC~ACTION_CD~CURRENCY~COUNTERPARTY~AGENCY_CONTRACT~MATURITY_DATE~AMOUNT~VALUE_DATE~FUNC_ID~TENOR_BASED_SPREAD~SHOW_ALL_PREVIOUS~SHOW_AMENDABLE_PREVIOUS~TXTCONTAMT~TXTSPREADTYPE~TXTMAINFUNCTION~ONCE_AUTH</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER_INT" RELATION_TYPE="N" TYPE="BLK_LFTBS_CONTRACT_INTEREST">NETRATEDESC~AMORTIZATIONCONSTCOMPONENT~RATESIGN~NETACCRUALDESC~SPECIALRATETYPE~CURRENCY~TOTALAMTLIQUIDATEDDESC~COMPONENT~EVENTDESC~CONTRACTREFERENCENO~COMPONENTDESC~EVENT~INTERESTBASIS~RATE~BORROWLENDINDDESC~SPREAD~RATETYPE~LIQUIDITYPREMIUMTYPE~LIQUIDITYPREMIUM~MARGIN~FIXEDRATETYPEDESC~PENALTYTENOR~SPECIALPENALTYCOMPONENTDESC~RATECALCTYPE~BORROWLENDIND~MAINCOMPONENT~RESETTENOR~WAIVER~ACQUIREDAMOUNT~AMOUNT~PREPAYMENTPENALTYRATECODE~FIXEDRATECODE~FIXEDRATETYPE~DOMICILECCY~FLOATINGRATE~LIQUIDITYPREMIUMCOMPONENT~RATECODEUSAGE~RATEREVISIONMETHOD~MINRATE~MAXRATE~ACCRUALREQD~STATUS~RATECODE~PICKUPEVENTSEQNO~EVENTSEQNO~CHANGEDURINGAMENDMENT~TRANSACTIONDATE~VALUEDATE~SHOWNINCONTRACTMAINSCREEN~PENALTYTYPE~ADJUSTMENTRATE~DISCACCRAPPLICABLE~CUSTMARGIN~ACCRUALCCY~INTPERIODBASIS~CCYROUNDUNIT~CCYDECIMALS~CCYROUNDRULE~NOINTONPREMATUREWITHDRAWL~REAPPLYINTONOUTSTANDAMT~REAPPLYINTONPREPAIDAMT~REPLICATE~RETAINMAINCOMPPROP~BILLINGNOTICEDAYS~BILLINGNOTICEREQD~INTCOMPUTATION~PENALTYSTARTDATEBASIS~MAXRATESIGN~MINRATESIGN~TENORAMTSPREAD~TENORWISESPREAD~AMOUNTWISESPREAD~TILLDATEACCDESC~HOLCOMPOUND~NEGATIVE_INTEREST_RATE_ALLOWED~RATEUI~RATEFIXINGREQD~RATEFIXINGDAYS~TXT_RATE_FIXING_DATE_ACTUAL~MORAINTRATE~EXPONENTIAL_FLAG~RATE_BASIS~RATE_ROUNDING_RULE~RATE_ROUNDING_UNIT~RATE_ROUNDING_POSITION~ACCL_FLT_RATE_PCT~ALLOW_REPORTING_ONLY~REPORTING_COMP_TYPE~RFR_BASE_COMP_METH~RFR_COMPONENT~RFR_INTERESTROLLOVER_METHOD~RFR_LASTRECENT_METHOD~RFR_LASTRESET_METHOD~RFR_LOCKOUT_METHOD~RFR_LOCKOUT_METHOD_DAYS~RFR_LOOKBACK_METHOD~RFR_LOOKBACK_METHOD_DAYS~RFR_MARG_COMP_METH~RFR_PAYMENTDELAY_METHOD~RFR_PAYMENTDELAY_METHOD_DAYS~RFR_PLAIN_METHOD~RFR_PRINCIPALADJUSTMENT_METHOD~RFR_SPREAD_ADJ_COMP_METH~SPREAD_ADJ~ALLOW_ACCL_FLT_RATE~CREDIT_COMPONENT~RFR_RATE_COMPOUNDING~RFR_RATE_TYPE~RFR_RATE_COMPOUNDING_METHOD~RFR_RATE_COMP_ROUND_UNIT~OBSERVATION_SHIFT~PEN_CMPDNG_REQD~BKDT_VAMI_RTPK_FG</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER_INT" RELATION_TYPE="N" TYPE="BLK_RATEFIX">COMPONENT~CURRESETDT~RATECODE~SPREAD~NXTRESETDT~RESETVALDT~RTFIXESN~RTFIXSTAT~REMARKS~RATE~EXTTRNREFNO~TXTCOMPONENTDESC~CURRENCY~FINALRATE</FN>'; 
msgxml += '      <FN PARENT="BLK_MASTER_INT" RELATION_TYPE="1" TYPE="BLK_SPREAD_INT">CONTRACTREFNO~PRDCD~CUSTOMERNO~BRANCHCODE~DEPTCODE~SPREADTYPE~TSOURCE~AMTTYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_SPREAD_INT" RELATION_TYPE="N" TYPE="BLK_SPREAD_CCY">CCY~CCYDESC~CONTRACT_REF_NO~CUSTOMER_NO~PRODUCT_CODE~BRANCH_CODE</FN>'; 
msgxml += '      <FN PARENT="BLK_SPREAD_CCY" RELATION_TYPE="N" TYPE="BLK_SPREAD_EFFDATE">CUSTOMER_NO~PRODUCT_CODE~CONTRACT_REF_NO~EFFECTIVE_DATE~BRANCH_CODE~LAST_CHANGE_TIMESTAMP~RECALC_REQD~CURRENCY</FN>'; 
msgxml += '      <FN PARENT="BLK_SPREAD_EFFDATE" RELATION_TYPE="N" TYPE="BLK_SPREAD_DETAILS">SPREAD_RATE~CURRENCY~TO_BASIS_AMT~FROM_BASIS_AMT~EFFECTIVE_DATE~BRANCH_CODE~PRODUCT_CODE~CONTRACT_REF_NO~CUSTOMER_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_LFTBS_CONTRACT_INTEREST" RELATION_TYPE="N" TYPE="BLK_AGENCY_RT">CONTRACT_REF_NO~EFFECTIVE_DATE~COMPONENT~BASE_RATE~SPREAD~FINAL_RATE~STATUS</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_INTEREST";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_MASTER_INT" : "","BLK_LFTBS_CONTRACT_INTEREST" : "BLK_MASTER_INT~N","BLK_RATEFIX" : "BLK_MASTER_INT~N","BLK_SPREAD_INT" : "BLK_MASTER_INT~1","BLK_SPREAD_CCY" : "BLK_SPREAD_INT~N","BLK_SPREAD_EFFDATE" : "BLK_SPREAD_CCY~N","BLK_SPREAD_DETAILS" : "BLK_SPREAD_EFFDATE~N","BLK_AGENCY_RT" : "BLK_LFTBS_CONTRACT_INTEREST~N"}; 

 var dataSrcLocationArray = new Array("BLK_MASTER_INT","BLK_LFTBS_CONTRACT_INTEREST","BLK_RATEFIX","BLK_SPREAD_INT","BLK_SPREAD_CCY","BLK_SPREAD_EFFDATE","BLK_SPREAD_DETAILS","BLK_AGENCY_RT"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside LFCINTCH.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside LFCINTCH.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_MASTER_INT__CONTRACTREFNO";
pkFields[0] = "BLK_MASTER_INT__CONTRACTREFNO";
queryFields[1] = "BLK_MASTER_INT__LATEVNSEQNO";
pkFields[1] = "BLK_MASTER_INT__LATEVNSEQNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_LFTBS_CONTRACT_INTEREST":["ACCL_FLT_RATE_PCT","ACCRUALCCY","ACCRUALREQD","ACQUIREDAMOUNT","ADJUSTMENTRATE","AMORTIZATIONCONSTCOMPONENT","AMOUNT","AMOUNTWISESPREAD","BILLINGNOTICEDAYS","BILLINGNOTICEREQD","BKDT_VAMI_RTPK_FG","BORROWLENDIND","CCYDECIMALS","CCYROUNDRULE","CCYROUNDUNIT","CHANGEDURINGAMENDMENT","COMPONENTDESC","CONTRACTREFERENCENO","CURRENCY","CUSTMARGIN","DISCACCRAPPLICABLE","DOMICILECCY","EVENTDESC","FIXEDRATECODE","FIXEDRATETYPE","FIXEDRATETYPEDESC","FLOATINGRATE","HOLCOMPOUND","INTCOMPUTATION","INTERESTBASIS","INTPERIODBASIS","LIQUIDITYPREMIUM","LIQUIDITYPREMIUMCOMPONENT","LIQUIDITYPREMIUMTYPE","MAINCOMPONENT","MARGIN","MAXRATE","MAXRATESIGN","MINRATE","MINRATESIGN","NETACCRUALDESC","NETRATEDESC","NOINTONPREMATUREWITHDRAWL","OBSERVATION_SHIFT","PENALTYSTARTDATEBASIS","PENALTYTYPE","PREPAYMENTPENALTYRATECODE","RATE","RATECALCTYPE","RATECODE","RATECODEUSAGE","RATEFIXINGDAYS","RATEFIXINGREQD","RATEREVISIONMETHOD","RATESIGN","RATETYPE","RATETYPEPREV","RATE_BASIS","RATE_ROUNDING_POSITION","RATE_ROUNDING_RULE","RATE_ROUNDING_UNIT","REAPPLYINTONOUTSTANDAMT","REAPPLYINTONPREPAIDAMT","REPLICATE","RESETTENOR","RETAINMAINCOMPPROP","RFR_BASE_COMP_METH","RFR_COMPONENT","RFR_INTERESTROLLOVER_METHOD","RFR_LASTRECENT_METHOD","RFR_LASTRESET_METHOD","RFR_LOCKOUT_METHOD","RFR_LOCKOUT_METHOD_DAYS","RFR_LOOKBACK_METHOD","RFR_LOOKBACK_METHOD_DAYS","RFR_MARG_COMP_METH","RFR_PAYMENTDELAY_METHOD","RFR_PLAIN_METHOD","RFR_PRINCIPALADJUSTMENT_METHOD","RFR_RATE_COMP_ROUND_UNIT","RFR_SPREAD_ADJ_COMP_METH","SHOWNINCONTRACTMAINSCREEN","SPECIALRATETYPE","SPREAD","SPREAD_ADJ","STATUS","TENORAMTSPREAD","TENORWISESPREAD","TOTALAMTLIQUIDATEDDESC","TRANSACTIONDATEI","VALUEDATEI","WAIVER"],"BLK_SPREAD_CCY":["CCY"],"BLK_SPREAD_DETAILS":["SPREAD_RATE","TO_BASIS_AMT"],"BLK_SPREAD_EFFDATE":["EFFECTIVE_DATEI"],"BLK_SPREAD_INT":["AMTTYPE","TSOURCE"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_LFTBS_CONTRACT_INTEREST__PREPAYMENTPENALTYRATECODE__LOV_PREPAYMENT_PENALTY":["BLK_LFTBS_CONTRACT_INTEREST__PREPAYMENTPENALTYRATECODE~~","","N~N",""],"BLK_LFTBS_CONTRACT_INTEREST__FIXEDRATECODE__LOV_RATE_CODE":["BLK_LFTBS_CONTRACT_INTEREST__FIXEDRATECODE~~","BLK_CFTBS_CONTRACT_INTEREST__FIXEDRATETYPE!varchar2~BLK_CFTBS_CONTRACT_INTEREST__CURRENCY!varchar2~BLK_CFTBS_CONTRACT_INTEREST__RATETYPE!varchar2~BLK_CFTBS_CONTRACT_INTEREST__FIXEDRATETYPE!varchar2~BLK_CFTBS_CONTRACT_INTEREST__CONTRACTREFERENCENO!varchar2","N~N",""],"BLK_LFTBS_CONTRACT_INTEREST__RATECODE__LOV_FLT_RATE_CODE":["BLK_LFTBS_CONTRACT_INTEREST__RATECODE~~","","N~N",""],"BLK_SPREAD_CCY__CCY__LOV_CCY":["BLK_SPREAD_CCY__CCY~BLK_SPREAD_CCY__CCYDESC~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_SPREAD_CCY","BLK_SPREAD_EFFDATE","BLK_SPREAD_DETAILS","BLK_AGENCY_RT");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array(); 

 var CallFormRelat=new Array(); 

 var CallRelatType= new Array(); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["LFCINTCH"]="KERNEL";
ArrPrntFunc["LFCINTCH"]="";
ArrPrntOrigin["LFCINTCH"]="";
ArrRoutingType["LFCINTCH"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["LFCINTCH"]="N";
ArrCustomModified["LFCINTCH"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_INTEREST":"CONTRACTREFNO~MODULE~EVENTSEQNO"};
var scrArgSource = {};
var scrArgVals = {"CVS_INTEREST":"~~"};
var scrArgDest = {"CVS_INTEREST":"BLK_MASTER_INT__CONTRACTREFNO~BLK_MASTER_INT__MODULE~BLK_MASTER_INT__LATEVNSEQNO"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {};
var dpndntOnSrvs = {};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------