/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2025, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : OLCONDET_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = '';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_SETTLEMENTS":"CONREFNO~LATEVNSEQNO~PRDCD~MODCD~CURR_EVENT_CODE~COMPNT","BLK_STL_SPLIT_MASTER":"GEN_DD_MSG~GEN_MSG~GEN_RECV_NOT~BASIS_AMT_TAG~TAG_CCY~BASIS_AMT~PAY_RECEIVE~SPLM_FCCREF~SPLM_ESN~PARENT_STL","BLK_OLTBS_SETTLEMENTS_CONIS":"SPL_ORDER~AMTTAG~ACCCIF~ACCBRN~PAYRECEIVE~STL_SEQ_NO~SSIMNEMONIC~ACCCCY~ACCOUNT~STL_AMT~SPL_RATIO~RATECODEPREFERRED~EXRATE~ERICCY~ERIAMT~INSTRUCTIONSTATUS~INSTRUCTIONTYPE~DET_NETIND~SPREAD~GENMESSAGE~GENRECVNOTICE~GENERATEDDMSG~TAGCCY~PAYMENTBY~COVERBY~COVERREQD~TRANSFERTYPE~CHARGESDETAILS~USDCLEARINGNETWORK~INSTRUMENTTYPE~INSTRUMENTNO~RTGSPAYMENT~PAYMENTDETAILS1~PAYMENTDETAILS2~PAYMENTDETAILS3~PAYMENTDETAILS4~TIMEIND1~TIMEIND2~TIMEIND3~SNDRTORCVRINFO1~SNDRTORCVRINFO2~SNDRTORCVRINFO3~SNDRTORCVRINFO4~SNDRTORCVRINFO5~SNDRTORCVRINFO6~ORDERINGINSTITUTION1~ORDERINGINSTITUTION2~ORDERINGINSTITUTION3~ORDERINGINSTITUTION4~ORDERINGINSTITUTION5~BENEFINSTITUTION1~BENEFINSTITUTION2~BENEFINSTITUTION3~BENEFINSTITUTION4~BENEFINSTITUTION5~BENEFINSTSORTCODE~DISBENFINSTSCODE~ORDERINGCUSTOMER1~ORDERINGCUSTOMER2~ORDERINGCUSTOMER3~ORDERINGCUSTOMER4~ORDERINGCUSTOMER5~ULTBENEFICIARY1~ULTBENEFICIARY2~ULTBENEFICIARY3~ULTBENEFICIARY4~ULTBENEFICIARY5~ULTIBENSORTCODE~DISUTLBENSCODE~RCVRCORRESP1~RCVRCORRESP2~RCVRCORRESP3~RCVRCORRESP4~RCVRCORRESP5~RECEIVER~INTREIMINST1~INTREIMINST2~INTREIMINST3~INTREIMINST4~INTERMEDIARY1~INTERMEDIARY2~INTERMEDIARY3~INTERMEDIARY4~ACCWITHINSTN1~ACCWITHINSTN2~ACCWITHINSTN3~ACCWITHINSTN4~ACCWITHINSTN5~INTERMEDIARY5~INTREIMINST5~INTERMEDIARYSORTCODE~AWISORTCODE~OURCORRESPONDENT~RECEIVERACCOUNT~DISINTSCODE~DISAWISCODE~RECVINTERMEDIARY5~RECVINTERMEDIARY4~RECVINTERMEDIARY3~RECVINTERMEDIARY2~RECVINTERMEDIARY1~RECVORDERINGCUST5~RECVORDERINGCUST4~RECVORDERINGCUST3~RECVORDERINGCUST2~RECVORDERINGCUST1~RECVORDERINGINSTN5~RECVORDERINGINSTN4~RECVORDERINGINSTN3~RECVORDERINGINSTN2~RECVORDERINGINSTN1~DEBTORACCT5~DEBTORACCT4~DEBTORACCT3~DEBTORACCT2~DEBTORACCT1~DEBTORSORTCODE~CREDITORSORTCODE~DEBTORBANK5~DEBTORBANK4~DEBTORBANK3~DEBTORBANK2~DEBTORBANK1~CREDITORACCT5~CREDITORACCT4~CREDITORACCT3~CREDITORACCT2~CREDITORACCT1~CREDITORBANK5~CREDITORBANK4~CREDITORBANK3~CREDITORBANK2~CREDITORBANK1~DISDEBTORSCODE~DISCREDITORSCODE~EXTPRODCATEGORY~EXTCPTYACPREFIX~EXTPARTYACCOUNT~EXTPARTYNAME~DISEXTBANKCODE~RECEIVEROFDD~IBANACNO~ACCOUNTDESC~EXTPARTYBIC~CONTRACTREFNUMBER~CHANGEAC~CCYRESTRICTION~CHANGERATE~PARTYINFOALLOWED~DISACCDESC~EXTSTATIONID~EXTSOURCE~DET_BASIS_AMT_TAG~SDET_ESN~DET_DFLTREQD~CHILD_STL~PARENT_STL~ECA_ALLOWED","BLK_OLTBS_CONTRACT_DETAILS_DET":"BANKOPERCODE~TRANTYPECODE~RECEIVERCHARGEAMOUNT~RECEIVERCHARGECCY~SENDERCHARGEAMOUNT1~SENDERCHARGEAMOUNT2~SENDERCHARGEAMOUNT3~SENDERCHARGEAMOUNT4~SENDERCHARGEAMOUNT5~SENDERCHARGEAMOUNT6~SENDERCHARGECCY1~SENDERCHARGECCY2~SENDERCHARGECCY3~SENDERCHARGECCY4~SENDERCHARGECCY5~SENDERCHARGECCY6~INSTRUCTIONCODE1~INSTRUCTIONCODE2~INSTRUCTIONCODE3~INSTRUCTIONCODE4~INSTRUCTIONCODE5~INSTRUCTIONCODE6~RELATEDREFNO~INSTRUCTIONCODEDESC1~INSTRUCTIONCODEDESC2~INSTRUCTIONCODEDESC3~INSTRUCTIONCODEDESC4~INSTRUCTIONCODEDESC5~INSTRUCTIONCODEDESC6~REGULATORYREP1~REGULATORYREP2~REGULATORYREP3~ENVELOPECONTENTS1~ENVELOPECONTENTS2~ENVELOPECONTENTS3~ENVELOPECONTENTS4~ENVELOPECONTENTS5~CONTREF~ESN~INSTRCODELIST~INSTRCODETEXT~AMTTG"};

var multipleEntryPageSize = {"BLK_STL_SPLIT_MASTER" :"15" ,"BLK_OLTBS_SETTLEMENTS_CONIS" :"15" };

var multipleEntrySVBlocks = "BLK_OLTBS_SETTLEMENTS_CONIS";

var tabMEBlks = {"CVS_SETTLEMENTS__TAB_MAIN":"BLK_STL_SPLIT_MASTER~BLK_OLTBS_SETTLEMENTS_CONIS"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_SETTLEMENTS">CONREFNO~LATEVNSEQNO~PRDCD~MODCD~CURR_EVENT_CODE~COMPNT</FN>'; 
msgxml += '      <FN PARENT="BLK_SETTLEMENTS" RELATION_TYPE="N" TYPE="BLK_STL_SPLIT_MASTER">GEN_DD_MSG~GEN_MSG~GEN_RECV_NOT~BASIS_AMT_TAG~TAG_CCY~BASIS_AMT~PAY_RECEIVE~SPLM_FCCREF~SPLM_ESN~PARENT_STL</FN>'; 
msgxml += '      <FN PARENT="BLK_STL_SPLIT_MASTER" RELATION_TYPE="N" TYPE="BLK_OLTBS_SETTLEMENTS_CONIS">SPL_ORDER~AMTTAG~ACCCIF~ACCBRN~PAYRECEIVE~STL_SEQ_NO~SSIMNEMONIC~ACCCCY~ACCOUNT~STL_AMT~SPL_RATIO~RATECODEPREFERRED~EXRATE~ERICCY~ERIAMT~INSTRUCTIONSTATUS~INSTRUCTIONTYPE~DET_NETIND~SPREAD~GENMESSAGE~GENRECVNOTICE~GENERATEDDMSG~TAGCCY~PAYMENTBY~COVERBY~COVERREQD~TRANSFERTYPE~CHARGESDETAILS~USDCLEARINGNETWORK~INSTRUMENTTYPE~INSTRUMENTNO~RTGSPAYMENT~PAYMENTDETAILS1~PAYMENTDETAILS2~PAYMENTDETAILS3~PAYMENTDETAILS4~TIMEIND1~TIMEIND2~TIMEIND3~SNDRTORCVRINFO1~SNDRTORCVRINFO2~SNDRTORCVRINFO3~SNDRTORCVRINFO4~SNDRTORCVRINFO5~SNDRTORCVRINFO6~ORDERINGINSTITUTION1~ORDERINGINSTITUTION2~ORDERINGINSTITUTION3~ORDERINGINSTITUTION4~ORDERINGINSTITUTION5~BENEFINSTITUTION1~BENEFINSTITUTION2~BENEFINSTITUTION3~BENEFINSTITUTION4~BENEFINSTITUTION5~BENEFINSTSORTCODE~DISBENFINSTSCODE~ORDERINGCUSTOMER1~ORDERINGCUSTOMER2~ORDERINGCUSTOMER3~ORDERINGCUSTOMER4~ORDERINGCUSTOMER5~ULTBENEFICIARY1~ULTBENEFICIARY2~ULTBENEFICIARY3~ULTBENEFICIARY4~ULTBENEFICIARY5~ULTIBENSORTCODE~DISUTLBENSCODE~RCVRCORRESP1~RCVRCORRESP2~RCVRCORRESP3~RCVRCORRESP4~RCVRCORRESP5~RECEIVER~INTREIMINST1~INTREIMINST2~INTREIMINST3~INTREIMINST4~INTERMEDIARY1~INTERMEDIARY2~INTERMEDIARY3~INTERMEDIARY4~ACCWITHINSTN1~ACCWITHINSTN2~ACCWITHINSTN3~ACCWITHINSTN4~ACCWITHINSTN5~INTERMEDIARY5~INTREIMINST5~INTERMEDIARYSORTCODE~AWISORTCODE~OURCORRESPONDENT~RECEIVERACCOUNT~DISINTSCODE~DISAWISCODE~RECVINTERMEDIARY5~RECVINTERMEDIARY4~RECVINTERMEDIARY3~RECVINTERMEDIARY2~RECVINTERMEDIARY1~RECVORDERINGCUST5~RECVORDERINGCUST4~RECVORDERINGCUST3~RECVORDERINGCUST2~RECVORDERINGCUST1~RECVORDERINGINSTN5~RECVORDERINGINSTN4~RECVORDERINGINSTN3~RECVORDERINGINSTN2~RECVORDERINGINSTN1~DEBTORACCT5~DEBTORACCT4~DEBTORACCT3~DEBTORACCT2~DEBTORACCT1~DEBTORSORTCODE~CREDITORSORTCODE~DEBTORBANK5~DEBTORBANK4~DEBTORBANK3~DEBTORBANK2~DEBTORBANK1~CREDITORACCT5~CREDITORACCT4~CREDITORACCT3~CREDITORACCT2~CREDITORACCT1~CREDITORBANK5~CREDITORBANK4~CREDITORBANK3~CREDITORBANK2~CREDITORBANK1~DISDEBTORSCODE~DISCREDITORSCODE~EXTPRODCATEGORY~EXTCPTYACPREFIX~EXTPARTYACCOUNT~EXTPARTYNAME~DISEXTBANKCODE~RECEIVEROFDD~IBANACNO~ACCOUNTDESC~EXTPARTYBIC~CONTRACTREFNUMBER~CHANGEAC~CCYRESTRICTION~CHANGERATE~PARTYINFOALLOWED~DISACCDESC~EXTSTATIONID~EXTSOURCE~DET_BASIS_AMT_TAG~SDET_ESN~DET_DFLTREQD~CHILD_STL~PARENT_STL~ECA_ALLOWED</FN>'; 
msgxml += '      <FN PARENT="BLK_SETTLEMENTS" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT_DETAILS_DET">BANKOPERCODE~TRANTYPECODE~RECEIVERCHARGEAMOUNT~RECEIVERCHARGECCY~SENDERCHARGEAMOUNT1~SENDERCHARGEAMOUNT2~SENDERCHARGEAMOUNT3~SENDERCHARGEAMOUNT4~SENDERCHARGEAMOUNT5~SENDERCHARGEAMOUNT6~SENDERCHARGECCY1~SENDERCHARGECCY2~SENDERCHARGECCY3~SENDERCHARGECCY4~SENDERCHARGECCY5~SENDERCHARGECCY6~INSTRUCTIONCODE1~INSTRUCTIONCODE2~INSTRUCTIONCODE3~INSTRUCTIONCODE4~INSTRUCTIONCODE5~INSTRUCTIONCODE6~RELATEDREFNO~INSTRUCTIONCODEDESC1~INSTRUCTIONCODEDESC2~INSTRUCTIONCODEDESC3~INSTRUCTIONCODEDESC4~INSTRUCTIONCODEDESC5~INSTRUCTIONCODEDESC6~REGULATORYREP1~REGULATORYREP2~REGULATORYREP3~ENVELOPECONTENTS1~ENVELOPECONTENTS2~ENVELOPECONTENTS3~ENVELOPECONTENTS4~ENVELOPECONTENTS5~CONTREF~ESN~INSTRCODELIST~INSTRCODETEXT~AMTTG</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_SETTLEMENTS";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_SETTLEMENTS" : "","BLK_STL_SPLIT_MASTER" : "BLK_SETTLEMENTS~N","BLK_OLTBS_SETTLEMENTS_CONIS" : "BLK_STL_SPLIT_MASTER~N","BLK_OLTBS_CONTRACT_DETAILS_DET" : "BLK_SETTLEMENTS~1"}; 

 var dataSrcLocationArray = new Array("BLK_SETTLEMENTS","BLK_STL_SPLIT_MASTER","BLK_OLTBS_SETTLEMENTS_CONIS","BLK_OLTBS_CONTRACT_DETAILS_DET"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside OLCONDET.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside OLCONDET.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_SETTLEMENTS__CONREFNO";
pkFields[0] = "BLK_SETTLEMENTS__CONREFNO";
queryFields[1] = "BLK_SETTLEMENTS__LATEVNSEQNO";
pkFields[1] = "BLK_SETTLEMENTS__LATEVNSEQNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_OLTBS_SETTLEMENTS_CONIS":["ACCOUNT","DET_NETIND","ECA_ALLOWED","STL_AMT"],"BLK_SETTLEMENTS":["BTN_DFLT"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
//***** Fields Amendable while Rollover *****
var rolloverAmendArr = {"BLK_OLTBS_SETTLEMENTS_CONIS":["ACCOUNT","DET_NETIND","STL_AMT"],"BLK_SETTLEMENTS":["BTN_DFLT"]};
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF__LOV_ACC_CIF":["BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF~~BLK_OLTBS_SETTLEMENTS_CONIS__DET_DFLTREQD~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN__LOV_ACC_BRS_US":["BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN~~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__STL_SEQ_NO__LOV_SSI":["BLK_OLTBS_SETTLEMENTS_CONIS__STL_SEQ_NO~BLK_OLTBS_SETTLEMENTS_CONIS__SSIMNEMONIC~~BLK_OLTBS_SETTLEMENTS_CONIS__ACCOUNT~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY~BLK_OLTBS_SETTLEMENTS_CONIS__INSTRUCTIONTYPE~BLK_OLTBS_SETTLEMENTS_CONIS__DET_DFLTREQD~","BLK_OLTBS_SETTLEMENTS_CONIS__PAYRECEIVE!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__PAYRECEIVE!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_SETTLEMENTS__MODCD!VARCHAR2~BLK_SETTLEMENTS__MODCD!VARCHAR2~BLK_SETTLEMENTS__PRDCD!VARCHAR2~BLK_SETTLEMENTS__PRDCD!VARCHAR2~BLK_SETTLEMENTS__PRDCD!VARCHAR2","N~N~N~N~N~N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY__LOV_ERI_ACC_CCY":["BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY~~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__ACCOUNT__LOV_ACCOUNT_US":["BLK_OLTBS_SETTLEMENTS_CONIS__ACCOUNT~~~~","BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF!VARCHAR2~BLK_STL_SPLIT_MASTER__TAG_CCY!VARCHAR2~BLK_STL_SPLIT_MASTER__TAG_CCY!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF!VARCHAR2~BLK_STL_SPLIT_MASTER__TAG_CCY!VARCHAR2~BLK_STL_SPLIT_MASTER__TAG_CCY!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCCIF!VARCHAR2~BLK_SETTLEMENTS__PRDCD!VARCHAR2","N~N~N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__ERICCY__LOV_ERI_CCYS":["BLK_OLTBS_SETTLEMENTS_CONIS__ERICCY~~","BLK_OLTBS_SETTLEMENTS_CONIS__ACCCCY!VARCHAR2","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__USDCLEARINGNETWORK__LOV_SRCD":["BLK_OLTBS_SETTLEMENTS_CONIS__USDCLEARINGNETWORK~~","","N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__ORDERINGINSTITUTION1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__ORDERINGINSTITUTION1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__BENEFINSTITUTION1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__BENEFINSTITUTION1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__BENEFINSTITUTION2__LOV_BIC2":["BLK_OLTBS_SETTLEMENTS_CONIS__BENEFINSTITUTION2~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__BENEFINSTSORTCODE__LOV_SORTCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__BENEFINSTSORTCODE~BLK_OLTBS_SETTLEMENTS_CONIS__DISBENFINSTSCODE~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__ORDERINGCUSTOMER1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__ORDERINGCUSTOMER1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__ULTBENEFICIARY2__LOV_BIC2":["BLK_OLTBS_SETTLEMENTS_CONIS__ULTBENEFICIARY2~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__ULTIBENSORTCODE__LOV_SORTCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__ULTIBENSORTCODE~BLK_OLTBS_SETTLEMENTS_CONIS__DISUTLBENSCODE~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__RCVRCORRESP1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__RCVRCORRESP1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__RECEIVER__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__RECEIVER~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__INTREIMINST1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__INTREIMINST1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__INTERMEDIARY1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__INTERMEDIARY1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__INTERMEDIARY2__LOV_BIC2":["BLK_OLTBS_SETTLEMENTS_CONIS__INTERMEDIARY2~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__ACCWITHINSTN1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__ACCWITHINSTN1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__ACCWITHINSTN2__LOV_BIC2":["BLK_OLTBS_SETTLEMENTS_CONIS__ACCWITHINSTN2~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__INTERMEDIARYSORTCODE__LOV_SORTCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__INTERMEDIARYSORTCODE~BLK_OLTBS_SETTLEMENTS_CONIS__DISINTSCODE~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__AWISORTCODE__LOV_SORTCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__AWISORTCODE~BLK_OLTBS_SETTLEMENTS_CONIS__DISAWISCODE~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__RECVINTERMEDIARY1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__RECVINTERMEDIARY1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__RECVORDERINGCUST1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__RECVORDERINGCUST1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__RECVORDERINGINSTN1__LOV_BIC":["BLK_OLTBS_SETTLEMENTS_CONIS__RECVORDERINGINSTN1~~~","","N~N~N","N"],"BLK_OLTBS_SETTLEMENTS_CONIS__DEBTORSORTCODE__LOV_SORTCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__DEBTORSORTCODE~BLK_OLTBS_SETTLEMENTS_CONIS__DISDEBTORSCODE~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__CREDITORSORTCODE__LOV_SORTCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__CREDITORSORTCODE~BLK_OLTBS_SETTLEMENTS_CONIS__DISCREDITORSCODE~","","N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__IBANACNO__LOV_ACCOUNTS":["BLK_OLTBS_SETTLEMENTS_CONIS__IBANACNO~~~~","BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2~BLK_OLTBS_SETTLEMENTS_CONIS__ACCBRN!VARCHAR2","N~N~N~N",""],"BLK_OLTBS_SETTLEMENTS_CONIS__EXTPARTYBIC__LOV_PAY_BANKCODE":["BLK_OLTBS_SETTLEMENTS_CONIS__EXTPARTYBIC~BLK_OLTBS_SETTLEMENTS_CONIS__DISEXTBANKCODE~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__BANKOPERCODE__LOV_BANK_OPER_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__BANKOPERCODE~~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE1__LOV_INSTRUCTION_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE1~BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODEDESC1~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE2__LOV_INSTRUCTION_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE2~BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODEDESC2~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE3__LOV_INSTRUCTION_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE3~BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODEDESC3~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE4__LOV_INSTRUCTION_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE4~BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODEDESC4~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE5__LOV_INSTRUCTION_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE5~BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODEDESC5~","","N~N",""],"BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE6__LOV_INSTRUCTION_CODE":["BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODE6~BLK_OLTBS_CONTRACT_DETAILS_DET__INSTRUCTIONCODEDESC6~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_STL_SPLIT_MASTER","BLK_OLTBS_SETTLEMENTS_CONIS");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array(); 

 var CallFormRelat=new Array(); 

 var CallRelatType= new Array(); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["OLCONDET"]="KERNEL";
ArrPrntFunc["OLCONDET"]="";
ArrPrntOrigin["OLCONDET"]="";
ArrRoutingType["OLCONDET"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["OLCONDET"]="N";
ArrCustomModified["OLCONDET"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_SETTLEMENTS":"CONREFNO~ESN"};
var scrArgSource = {};
var scrArgVals = {"CVS_SETTLEMENTS":"~"};
var scrArgDest = {"CVS_SETTLEMENTS":"BLK_SETTLEMENTS__CONREFNO~BLK_SETTLEMENTS__LATEVNSEQNO"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {};
var dpndntOnSrvs = {};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"2","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"1"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------