/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2024, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : OLCTRMIS_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = '';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_MISDETAILS":"CONREFNO~LATESN~BRNCD~UNITREFNO~MISGRP~RELACC~RELREF~MISHEAD~RATEFLG~POOLCD~REFRATE~REFRATETYP~CALCMTH~REFXRATE~REFSPREAD~REFRATECD~COSTCD1~COSTCD2~COSTCD3~COSTCD4~COSTCD5~TXNMIS1~TXNMIS10~TXNMIS2~TXNMIS3~TXNMIS4~TXNMIS5~TXNMIS6~TXNMIS7~TXNMIS8~TXNMIS9~CCY~MISGRPCOMP~MISGRPTXN~COMPMIS1~COMPMIS10~COMPMIS2~COMPMIS3~COMPMIS4~COMPMIS5~COMPMIS6~COMPMIS7~COMPMIS8~COMPMIS9~FUNDMIS1~FUNDMIS10~FUNDMIS2~FUNDMIS3~FUNDMIS4~FUNDMIS5~FUNDMIS6~FUNDMIS7~FUNDMIS8~FUNDMIS9~MODUCD~CONTCCY~MISGRPFUN~TRANMIS1~TRANMIS2~TRANMIS3~TRANMIS4~TRANMIS5~TRANMIS6~TRANMIS7~TRANMIS8~TRANMIS9~TRANMIS10~COMMIS1~COMMIS2~COMMIS3~COMMIS4~COMMIS5~COMMIS6~COMMIS7~COMMIS8~COMMIS9~COMMIS10~FUNMIS1~FUNMIS2~FUNMIS3~FUNMIS4~FUNMIS5~FUNMIS6~FUNMIS7~FUNMIS8~FUNMIS9~FUNMIS10~PRDCD~FXD_RATE_CODE~FXD_RATE_TYPE~USER_RATE","BLK_TXNMISDETAILS":"MISTXNCLS~MISTXNCD","BLK_COMPMISDETAILS":"MISCOMPCLS~MISCOMPCD","BLK_FUNDMISDETAILS":"MISFUNDCLS~MISFUNDCD","BLK_CHGLOGDETAILS":"REFNO~MISCLS~TXNDT~OLDMISCD~NEWMISCD","BLK_RATEDETAILS":"EFFDATE~BOOKINGDATE~REFRATE~UNIT_REF_NO~REF_RATE_SIGN","BLK_AMNDRATEDETAILS":"CONREFNO~RATECD~RATETYP~RATE~SPREAD","BLK_CONTROL":"","BLK_BALANCE_TRNSFER_LOG_DETAILS":"BRANCH~PERIOD_CODE~FIN_YEAR~REFERENCE_NO~GL_CODE~REFERENCE_TYPE~TRANSFER_IND~MIS_CLASS~TXN_DATE~OLD_MIS_CODE~NEW_MIS_CODE~CCY~AMOUNT~EX_RATE"};

var multipleEntryPageSize = {"BLK_RATEDETAILS" :"15" ,"BLK_CHGLOGDETAILS" :"15" ,"BLK_TXNMISDETAILS" :"15" ,"BLK_COMPMISDETAILS" :"15" ,"BLK_FUNDMISDETAILS" :"15" ,"BLK_BALANCE_TRNSFER_LOG_DETAILS" :"15" };

var multipleEntrySVBlocks = "";

var tabMEBlks = {"CVS_RATE__ALL":"BLK_RATEDETAILS","CVS_CHG_LOG__ALL":"BLK_CHGLOGDETAILS","CVS_MIS__TAB_ALL":"BLK_TXNMISDETAILS~BLK_COMPMISDETAILS~BLK_FUNDMISDETAILS","CVS_BALANCE_TRANSFER_LOG__TAB_MAIN":"BLK_BALANCE_TRNSFER_LOG_DETAILS"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_MISDETAILS">CONREFNO~LATESN~BRNCD~UNITREFNO~MISGRP~RELACC~RELREF~MISHEAD~RATEFLG~POOLCD~REFRATE~REFRATETYP~CALCMTH~REFXRATE~REFSPREAD~REFRATECD~COSTCD1~COSTCD2~COSTCD3~COSTCD4~COSTCD5~TXNMIS1~TXNMIS10~TXNMIS2~TXNMIS3~TXNMIS4~TXNMIS5~TXNMIS6~TXNMIS7~TXNMIS8~TXNMIS9~CCY~MISGRPCOMP~MISGRPTXN~COMPMIS1~COMPMIS10~COMPMIS2~COMPMIS3~COMPMIS4~COMPMIS5~COMPMIS6~COMPMIS7~COMPMIS8~COMPMIS9~FUNDMIS1~FUNDMIS10~FUNDMIS2~FUNDMIS3~FUNDMIS4~FUNDMIS5~FUNDMIS6~FUNDMIS7~FUNDMIS8~FUNDMIS9~MODUCD~CONTCCY~MISGRPFUN~TRANMIS1~TRANMIS2~TRANMIS3~TRANMIS4~TRANMIS5~TRANMIS6~TRANMIS7~TRANMIS8~TRANMIS9~TRANMIS10~COMMIS1~COMMIS2~COMMIS3~COMMIS4~COMMIS5~COMMIS6~COMMIS7~COMMIS8~COMMIS9~COMMIS10~FUNMIS1~FUNMIS2~FUNMIS3~FUNMIS4~FUNMIS5~FUNMIS6~FUNMIS7~FUNMIS8~FUNMIS9~FUNMIS10~PRDCD~FXD_RATE_CODE~FXD_RATE_TYPE~USER_RATE</FN>'; 
msgxml += '      <FN PARENT="BLK_MISDETAILS" RELATION_TYPE="1" TYPE="BLK_TXNMISDETAILS">MISTXNCLS~MISTXNCD</FN>'; 
msgxml += '      <FN PARENT="BLK_MISDETAILS" RELATION_TYPE="1" TYPE="BLK_COMPMISDETAILS">MISCOMPCLS~MISCOMPCD</FN>'; 
msgxml += '      <FN PARENT="BLK_MISDETAILS" RELATION_TYPE="1" TYPE="BLK_FUNDMISDETAILS">MISFUNDCLS~MISFUNDCD</FN>'; 
msgxml += '      <FN PARENT="BLK_MISDETAILS" RELATION_TYPE="N" TYPE="BLK_CHGLOGDETAILS">REFNO~MISCLS~TXNDT~OLDMISCD~NEWMISCD</FN>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="N" TYPE="BLK_RATEDETAILS">EFFDATE~BOOKINGDATE~REFRATE~UNIT_REF_NO~REF_RATE_SIGN</FN>'; 
msgxml += '      <FN PARENT="BLK_MISDETAILS" RELATION_TYPE="1" TYPE="BLK_AMNDRATEDETAILS">CONREFNO~RATECD~RATETYP~RATE~SPREAD</FN>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_CONTROL"></FN>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_BALANCE_TRNSFER_LOG_DETAILS">BRANCH~PERIOD_CODE~FIN_YEAR~REFERENCE_NO~GL_CODE~REFERENCE_TYPE~TRANSFER_IND~MIS_CLASS~TXN_DATE~OLD_MIS_CODE~NEW_MIS_CODE~CCY~AMOUNT~EX_RATE</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MIS";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_MISDETAILS" : "","BLK_TXNMISDETAILS" : "BLK_MISDETAILS~1","BLK_COMPMISDETAILS" : "BLK_MISDETAILS~1","BLK_FUNDMISDETAILS" : "BLK_MISDETAILS~1","BLK_CHGLOGDETAILS" : "BLK_MISDETAILS~N","BLK_RATEDETAILS" : "","BLK_AMNDRATEDETAILS" : "BLK_MISDETAILS~1","BLK_CONTROL" : "","BLK_BALANCE_TRNSFER_LOG_DETAILS" : ""}; 

 var dataSrcLocationArray = new Array("BLK_MISDETAILS","BLK_TXNMISDETAILS","BLK_COMPMISDETAILS","BLK_FUNDMISDETAILS","BLK_CHGLOGDETAILS","BLK_RATEDETAILS","BLK_AMNDRATEDETAILS","BLK_CONTROL","BLK_BALANCE_TRNSFER_LOG_DETAILS"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside OLCTRMIS.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside OLCTRMIS.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_MISDETAILS__CONREFNO";
pkFields[0] = "BLK_MISDETAILS__CONREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_AMNDRATEDETAILS":["BTN_RATE","RATE","RATECD","RATETYP","SPREAD"],"BLK_CHGLOGDETAILS":["MISCLS","NEWMISCD","OLDMISCD","TXNDTI"],"BLK_MISDETAILS":["BTN_MIS_DEFAULT_GROUP","CALCMTH","COMPMIS1","COMPMIS10","COMPMIS2","COMPMIS3","COMPMIS4","COMPMIS5","COMPMIS6","COMPMIS7","COMPMIS8","COMPMIS9","COSTCD1","COSTCD2","COSTCD3","COSTCD4","COSTCD5","FUNDMIS1","FUNDMIS10","FUNDMIS2","FUNDMIS3","FUNDMIS4","FUNDMIS5","FUNDMIS6","FUNDMIS7","FUNDMIS8","FUNDMIS9","FXD_RATE_CODE","FXD_RATE_TYPE","MISGRP","MISGRPCOMP","MISGRPTXN","MISHEAD","POOLCD","RATEFLG","REFRATE","REFRATECD","REFRATETYP","REFSPREAD","REFXRATE","RELACC","RELREF","RGREL","TXNMIS1","TXNMIS10","TXNMIS2","TXNMIS3","TXNMIS4","TXNMIS5","TXNMIS6","TXNMIS7","TXNMIS8","TXNMIS9","TXTLINKGRP","USER_RATE"],"BLK_RATEDETAILS":["BOOKINGDATEI","EFFDATEI","REFRATE"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
//***** Fields Amendable while Liquidate *****
var liquidateAmendArr = {"BLK_AMNDRATEDETAILS":["BTN_RATE","RATE","RATECD","RATETYP","SPREAD"],"BLK_CHGLOGDETAILS":["MISCLS","NEWMISCD","OLDMISCD","TXNDTI"],"BLK_MISDETAILS":["CALCMTH","COMPMIS1","COMPMIS10","COMPMIS2","COMPMIS3","COMPMIS4","COMPMIS5","COMPMIS6","COMPMIS7","COMPMIS8","COMPMIS9","COSTCD1","COSTCD2","COSTCD3","COSTCD4","COSTCD5","FUNDMIS1","FUNDMIS10","FUNDMIS2","FUNDMIS3","FUNDMIS4","FUNDMIS5","FUNDMIS6","FUNDMIS7","FUNDMIS8","FUNDMIS9","MISGRP","MISGRPCOMP","MISGRPTXN","MISHEAD","POOLCD","RATEFLG","REFRATE","REFRATECD","REFRATETYP","REFSPREAD","REFXRATE","RELACC","RELREF","RGREL","TXNMIS1","TXNMIS10","TXNMIS2","TXNMIS3","TXNMIS4","TXNMIS5","TXNMIS6","TXNMIS7","TXNMIS8","TXNMIS9","TXTLINKGRP"],"BLK_RATEDETAILS":["BOOKINGDATEI","EFFDATEI","REFRATE"]};
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_MISDETAILS__MISGRP__LOV_MIS_GROUP":["BLK_MISDETAILS__MISGRP~~~~~~~~~~~~~~~~~~~~~~~","","N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N",""],"BLK_MISDETAILS__RELACC__LOV_RELATED_ACCOUNT":["BLK_MISDETAILS__RELACC~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~","BLK_MISDETAILS__PRDCD!","N",""],"BLK_MISDETAILS__RELREF__LOV_RELATED_REF_NO":["BLK_MISDETAILS__RELREF~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~","","N",""],"BLK_MISDETAILS__MISHEAD__LOV_MIS_HEAD":["BLK_MISDETAILS__MISHEAD~~","","N~N",""],"BLK_MISDETAILS__POOLCD__LOV_POOL_CODE":["BLK_MISDETAILS__POOLCD~~~BLK_MISDETAILS__CALCMTH~","","N~N~N",""],"BLK_MISDETAILS__REFRATECD__LOV_RATE_CODE":["BLK_MISDETAILS__REFRATECD~~","","N~N",""],"BLK_MISDETAILS__COSTCD1__LOV_COST_CODE1":["BLK_MISDETAILS__COSTCD1~~","BLK_MISDETAILS__MODUCD!STRING~BLK_MISDETAILS__CCY!STRING~BLK_MISDETAILS__COSTCD2!STRING~BLK_MISDETAILS__COSTCD3!STRING~BLK_MISDETAILS__COSTCD4!STRING~BLK_MISDETAILS__COSTCD5!STRING","N~N",""],"BLK_MISDETAILS__COSTCD2__LOV_COST_CODE2":["BLK_MISDETAILS__COSTCD2~~","BLK_MISDETAILS__MODUCD!STRING~BLK_MISDETAILS__CCY!STRING~BLK_MISDETAILS__COSTCD1!STRING~BLK_MISDETAILS__COSTCD3!STRING~BLK_MISDETAILS__COSTCD4!STRING~BLK_MISDETAILS__COSTCD5!STRING","N~N",""],"BLK_MISDETAILS__COSTCD3__LOV_COST_CODE3":["BLK_MISDETAILS__COSTCD3~~","BLK_MISDETAILS__MODUCD!STRING~BLK_MISDETAILS__CCY!STRING~BLK_MISDETAILS__COSTCD1!STRING~BLK_MISDETAILS__COSTCD2!STRING~BLK_MISDETAILS__COSTCD4!STRING~BLK_MISDETAILS__COSTCD5!STRING","N~N",""],"BLK_MISDETAILS__COSTCD4__LOV_COST_CODE4":["BLK_MISDETAILS__COSTCD4~~","BLK_MISDETAILS__MODUCD!STRING~BLK_MISDETAILS__CCY!STRING~BLK_MISDETAILS__COSTCD1!STRING~BLK_MISDETAILS__COSTCD2!STRING~BLK_MISDETAILS__COSTCD3!STRING~BLK_MISDETAILS__COSTCD5!STRING","N~N",""],"BLK_MISDETAILS__COSTCD5__LOV_COST_CODE5":["BLK_MISDETAILS__COSTCD5~~","BLK_MISDETAILS__MODUCD!STRING~BLK_MISDETAILS__CCY!STRING~BLK_MISDETAILS__COSTCD1!STRING~BLK_MISDETAILS__COSTCD2!STRING~BLK_MISDETAILS__COSTCD3!STRING~BLK_MISDETAILS__COSTCD4!STRING","N~N",""],"BLK_MISDETAILS__TXNMIS1__LOV_TXN_MIS1":["BLK_MISDETAILS__TXNMIS1~~~","BLK_MISDETAILS__PRDCD!~BLK_MISDETAILS__BRNCD!","N~N~N",""],"BLK_MISDETAILS__TXNMIS10__LOV_TXN_MIS10":["BLK_MISDETAILS__TXNMIS10~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS2__LOV_TXN_MIS2":["BLK_MISDETAILS__TXNMIS2~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS3__LOV_TXN_MIS3":["BLK_MISDETAILS__TXNMIS3~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS4__LOV_TXN_MIS4":["BLK_MISDETAILS__TXNMIS4~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS5__LOV_TXN_MIS5":["BLK_MISDETAILS__TXNMIS5~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS6__LOV_TXN_MIS6":["BLK_MISDETAILS__TXNMIS6~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS7__LOV_TXN_MIS7":["BLK_MISDETAILS__TXNMIS7~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS8__LOV_TXN_MIS8":["BLK_MISDETAILS__TXNMIS8~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__TXNMIS9__LOV_TXN_MIS9":["BLK_MISDETAILS__TXNMIS9~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__CCY__LOV_MIS_GROUP":["","","N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N",""],"BLK_MISDETAILS__COMPMIS1__LOV_COMP_MIS1":["BLK_MISDETAILS__COMPMIS1~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS10__LOV_COMP_MIS10":["BLK_MISDETAILS__COMPMIS10~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS2__LOV_COMP_MIS2":["BLK_MISDETAILS__COMPMIS2~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS3__LOV_COMP_MIS3":["BLK_MISDETAILS__COMPMIS3~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS4__LOV_COMP_MIS4":["BLK_MISDETAILS__COMPMIS4~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS5__LOV_COMP_MIS5":["BLK_MISDETAILS__COMPMIS5~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS6__LOV_COMP_MIS6":["BLK_MISDETAILS__COMPMIS6~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS7__LOV_COMP_MIS7":["BLK_MISDETAILS__COMPMIS7~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS8__LOV_COMP_MIS8":["BLK_MISDETAILS__COMPMIS8~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__COMPMIS9__LOV_COMP_MIS9":["BLK_MISDETAILS__COMPMIS9~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS1__LOV_FUND_1":["BLK_MISDETAILS__FUNDMIS1~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS10__LOV_FUND_10":["BLK_MISDETAILS__FUNDMIS10~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS2__LOV_FUND_2":["BLK_MISDETAILS__FUNDMIS2~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS3__LOV_FUND_3":["BLK_MISDETAILS__FUNDMIS3~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS4__LOV_FUND_4":["BLK_MISDETAILS__FUNDMIS4~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS5__LOV_FUND_5":["BLK_MISDETAILS__FUNDMIS5~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS6__LOV_FUND_6":["BLK_MISDETAILS__FUNDMIS6~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS7__LOV_FUND_7":["BLK_MISDETAILS__FUNDMIS7~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS8__LOV_FUND_8":["BLK_MISDETAILS__FUNDMIS8~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FUNDMIS9__LOV_FUND_9":["BLK_MISDETAILS__FUNDMIS9~~~","BLK_MISDETAILS__PRDCD!VARCHAR2~BLK_MISDETAILS__BRNCD!VARCHAR2","N~N~N",""],"BLK_MISDETAILS__FXD_RATE_CODE__LOV_FXD_RATE_CODE":["BLK_MISDETAILS__FXD_RATE_CODE~~","","N~N",""],"BLK_CHGLOGDETAILS__REFNO__LOV_MIS_GROUP":["","","N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N",""],"BLK_AMNDRATEDETAILS__BTN_RATE__LOV_MIS_GROUP":["","","N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N~N",""]};
var offlineLovInfoFlds = {"BLK_MISDETAILS__CCY__LOV_MIS_GROUP":["",""],"BLK_CHGLOGDETAILS__REFNO__LOV_MIS_GROUP":["",""],"BLK_AMNDRATEDETAILS__CONREFNO__LOV_MIS_GROUP":["",""],"BLK_AMNDRATEDETAILS__BTN_RATE__LOV_MIS_GROUP":["",""]};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_ALL';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_RATEDETAILS","BLK_CHGLOGDETAILS","BLK_TXNMISDETAILS","BLK_COMPMISDETAILS","BLK_FUNDMISDETAILS","BLK_BALANCE_TRNSFER_LOG_DETAILS");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array(); 

 var CallFormRelat=new Array(); 

 var CallRelatType= new Array(); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["OLCTRMIS"]="KERNEL";
ArrPrntFunc["OLCTRMIS"]="";
ArrPrntOrigin["OLCTRMIS"]="";
ArrRoutingType["OLCTRMIS"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["OLCTRMIS"]="N";
ArrCustomModified["OLCTRMIS"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_MIS":"CONTREF~ESN~PRDCD~BRNCD","CVS_RATE":"CONREFNO","CVS_AMEND_RATE":"CONREFNO","CVS_BALANCE_TRANSFER_LOG":"CONREFNO"};
var scrArgSource = {"CVS_RATE":"BLK_MISDETAILS__CONREFNO","CVS_AMEND_RATE":"BLK_MISDETAILS__CONREFNO","CVS_BALANCE_TRANSFER_LOG":"BLK_MISDETAILS__CONREFNO"};
var scrArgVals = {"CVS_MIS":"~~~","CVS_RATE":"","CVS_AMEND_RATE":"","CVS_BALANCE_TRANSFER_LOG":""};
var scrArgDest = {"CVS_MIS":"BLK_MISDETAILS__CONREFNO~BLK_MISDETAILS__LATESN~BLK_MISDETAILS__PRDCD~BLK_MISDETAILS__BRNCD","CVS_RATE":"BLK_RATEDETAILS__UNIT_REF_NO","CVS_AMEND_RATE":"BLK_AMNDRATEDETAILS__CONREFNO","CVS_BALANCE_TRANSFER_LOG":"BLK_CONTROL__BALANCEREFNO"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {};
var dpndntOnSrvs = {};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------