/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2024, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : OLDCLQRY_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_COMMITMENT_QUICK_SUMMARY":"ZIPCODE~FACILITYNAME~ADDRESSLINE4~ADDRESSLINE3~ADDRESSLINE2~USERDEFINEDSTATUS~LASTAVAILABLEDATE~MATURITYDATE~REVOLVING_COMMITMENT~TXNMIS1~ADDRESSLINE1~CUSTOMERNAME1~SSN~CUSTOMERNO~CONTRACTREFNO~PRODUCT_TYPE~BRANCH~TXTPARTSYSREFNO~PRODUCTTYPE1~TXTSHORTNAME~TXTPARTSYSBORRID~SECURED~GUARANTEE~FACILITYMEMONO~REVOLVER~PARTICIPATION~LCDRADOWN~ORIGINALCMTAMOUNT~ORIGINALUSDAMOUNT~UNUTILAMOUNT~UNUTILUSDAMOUNT~UTILISEDAMOUNT~UTILISEDUSDAMOUNT~DIRECTAMOUNT~DIRECTUSDAMOUNT~CONTINGENTAMOUNT~CONTINGENTUSDAMOUNT~AVAILABLEAMOUNT~AVAILABLEUSDAMOUNT~ORIGINALCURRENCY~UNUTILCURRENCY~UTILISEDCURRENCY~DIRECTCURRENCY~CONTINGENTCURRENCY~AVAILABLECURRENCY~TXTPARTSYSCOMP~TXTPLEGDEBLEIND~ZEROBALDAYS~AVGOUTSTANDINGBAL~MINOUTSTANDINGBAL~MAXOUTSTANDINGBAL~PREVAVGOUTSTANDINGBAL~PREVMINOUTSTANDINGBAL~PREVMAXOUTSTANDINGBAL","BLK_CONTRACT_LINKAGES":"TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTRACTREFNO","BLK_CONTRACT_LINKAGES_DETAIL":"FACILITYTYPE~INTTYPE~MATURITYDT~PRINCIPALOUTSTANDINGBAL~LINKED_TO_REF~CURRENCY~LCYEQUIVALENT~COUNTERPARTY~SHORTNAME~CONTRACT_REF_NO~CONTRACTREFNO","BLK_CONTRACT_FEE":"TXBORROWERNUM~TXBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTACTREFNO","BLK_CONTRACT_FEE_DETAIL":"FEETYPE~TOTALFEE~LCYTOTALFEE~CURRENCY~TILLDATEACCRUAL~PAYABLE~DDANO~CURRENTDUEDATE~CONTRACT_REF_NO","BLK_BORR_PROD_LIMIT":"TXTBORROWERNO~TXTBORROWENAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTRACTREFNO","BLK_BORR_PROD_LIMIT_DETAIL":"COUNTERPARTY~SHORTNAME~PRODUCT~LIMITAMOUNT~UTILISEDAMOUNT~AVAILABLEAMOUNT~CURRENCY~LCYEQUIVALENT~CONTRACT_REF_NO~CONTRACTREFNO","BLK_FEE_RATE":"TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTRACTREFNO","BLK_FEE_RATE_DETAIL":"FEERATE~TILLDATEACCRUAL~AQUIREDAMOUNT~PERDIEM~SCHEDULETYPE~PAYABLE~DDANO~FEEDUE~DUE_DATE~LASTFEEPAID~LASTPAIDDATE~NEXTFEEDUE~NEXTDUEDATE~PASTDUEAMOUNT~PASTDUEDAYS~CONTRACT_REF_NO~CURRENCY","BLK_CONTRACT_EVENT_LOG":"TXTCONTRACTREFNO~TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO","BLK_CONTRACT_EVENT_LOG_DETAIL":"EFFECTIVEDATE~TRANSACTIONDATE~TRANSDETAIL~DIFFERENTIALAMOUNT~FEEAMOUNT~FEEWAIVED~AVAILABLEBALANCE~FEEDUE~EVENT_CODE~EVENT_SEQ_NO~CONTRACT_REF_NO","BLK_AMOUNT_DUE":"TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~DUEDATE~CONTRACT_REF_NO","BLK_AMOUNT_DUE_DETAIL":"COMPONENT~AMOUNTDUE~TOTALDUE~CONTRACT_REF_NO~CURRENCY"};

var multipleEntryPageSize = {"BLK_CONTRACT_LINKAGES_DETAIL" : "12 ","BLK_CONTRACT_FEE_DETAIL" : "10 ","BLK_BORR_PROD_LIMIT_DETAIL" :"15" ,"BLK_CONTRACT_EVENT_LOG_DETAIL" :"15" ,"BLK_AMOUNT_DUE_DETAIL" :"15" };

var multipleEntrySVBlocks = "";

var tabMEBlks = {"CVS_LINK__TAB_MAIN":"BLK_CONTRACT_LINKAGES_DETAIL","CVS_FEE__TAB_MAIN":"BLK_CONTRACT_FEE_DETAIL","CVS_SUBLMT__TAB_MAIN":"BLK_BORR_PROD_LIMIT_DETAIL","CVS_TRNHIST__TAB_MAIN":"BLK_CONTRACT_EVENT_LOG_DETAIL","CVS_PAY__TAB_MAIN":"BLK_AMOUNT_DUE_DETAIL"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_COMMITMENT_QUICK_SUMMARY">ZIPCODE~FACILITYNAME~ADDRESSLINE4~ADDRESSLINE3~ADDRESSLINE2~USERDEFINEDSTATUS~LASTAVAILABLEDATE~MATURITYDATE~REVOLVING_COMMITMENT~TXNMIS1~ADDRESSLINE1~CUSTOMERNAME1~SSN~CUSTOMERNO~CONTRACTREFNO~PRODUCT_TYPE~BRANCH~TXTPARTSYSREFNO~PRODUCTTYPE1~TXTSHORTNAME~TXTPARTSYSBORRID~SECURED~GUARANTEE~FACILITYMEMONO~REVOLVER~PARTICIPATION~LCDRADOWN~ORIGINALCMTAMOUNT~ORIGINALUSDAMOUNT~UNUTILAMOUNT~UNUTILUSDAMOUNT~UTILISEDAMOUNT~UTILISEDUSDAMOUNT~DIRECTAMOUNT~DIRECTUSDAMOUNT~CONTINGENTAMOUNT~CONTINGENTUSDAMOUNT~AVAILABLEAMOUNT~AVAILABLEUSDAMOUNT~ORIGINALCURRENCY~UNUTILCURRENCY~UTILISEDCURRENCY~DIRECTCURRENCY~CONTINGENTCURRENCY~AVAILABLECURRENCY~TXTPARTSYSCOMP~TXTPLEGDEBLEIND~ZEROBALDAYS~AVGOUTSTANDINGBAL~MINOUTSTANDINGBAL~MAXOUTSTANDINGBAL~PREVAVGOUTSTANDINGBAL~PREVMINOUTSTANDINGBAL~PREVMAXOUTSTANDINGBAL</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_CONTRACT_LINKAGES">TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTRACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="N" TYPE="BLK_CONTRACT_LINKAGES_DETAIL">FACILITYTYPE~INTTYPE~MATURITYDT~PRINCIPALOUTSTANDINGBAL~LINKED_TO_REF~CURRENCY~LCYEQUIVALENT~COUNTERPARTY~SHORTNAME~CONTRACT_REF_NO~CONTRACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_CONTRACT_FEE">TXBORROWERNUM~TXBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="N" TYPE="BLK_CONTRACT_FEE_DETAIL">FEETYPE~TOTALFEE~LCYTOTALFEE~CURRENCY~TILLDATEACCRUAL~PAYABLE~DDANO~CURRENTDUEDATE~CONTRACT_REF_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_BORR_PROD_LIMIT">TXTBORROWERNO~TXTBORROWENAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTRACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="N" TYPE="BLK_BORR_PROD_LIMIT_DETAIL">COUNTERPARTY~SHORTNAME~PRODUCT~LIMITAMOUNT~UTILISEDAMOUNT~AVAILABLEAMOUNT~CURRENCY~LCYEQUIVALENT~CONTRACT_REF_NO~CONTRACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_FEE_RATE">TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO~TXTCONTRACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="N" TYPE="BLK_FEE_RATE_DETAIL">FEERATE~TILLDATEACCRUAL~AQUIREDAMOUNT~PERDIEM~SCHEDULETYPE~PAYABLE~DDANO~FEEDUE~DUE_DATE~LASTFEEPAID~LASTPAIDDATE~NEXTFEEDUE~NEXTDUEDATE~PASTDUEAMOUNT~PASTDUEDAYS~CONTRACT_REF_NO~CURRENCY</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_CONTRACT_EVENT_LOG">TXTCONTRACTREFNO~TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~CONTRACT_REF_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="N" TYPE="BLK_CONTRACT_EVENT_LOG_DETAIL">EFFECTIVEDATE~TRANSACTIONDATE~TRANSDETAIL~DIFFERENTIALAMOUNT~FEEAMOUNT~FEEWAIVED~AVAILABLEBALANCE~FEEDUE~EVENT_CODE~EVENT_SEQ_NO~CONTRACT_REF_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_AMOUNT_DUE">TXTBORROWERNO~TXTBORROWERNAME~TXTAPPLICATIONDATE~DUEDATE~CONTRACT_REF_NO</FN>'; 
msgxml += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="N" TYPE="BLK_AMOUNT_DUE_DETAIL">COMPONENT~AMOUNTDUE~TOTALDUE~CONTRACT_REF_NO~CURRENCY</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_MAIN";
var qryReqd = "Y";
var txnBranchFld = "" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_COMMITMENT_QUICK_SUMMARY" RELATION_TYPE="1" TYPE="BLK_CONTRACT_SUMMARY">AUTHSTATUS~CONTRACTSTS~USERDEFSTS~BRNCH~CONTRACTREFNO~EXTREFNO~FACILTYNAME~COUNTERPTY~SHORTNM~PRD~PRINCIPALOS~CONTAMT~CCY~MATURITYDT~VALUEDATE~PAYMENTMETHOS~RATECODE~RATE~RATESIGN~SPREAD~DEPTCODE~EGNUMBER~WORKFLOWSTS~RATERIVISIONSTS~CUSTOMREFNO~TRESURYSOURCE~AGENTCIF~USERREFNO~RELREFERENCE~GFCID~CREDITLINE~PARTSYBORRID~PARTSYSCOMP~PARTSYREFNO</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "OLDCLQRY";
var defaultWhereClause = "";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_CONTRACT_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_COMMITMENT_QUICK_SUMMARY" : "","BLK_CONTRACT_LINKAGES" : "BLK_COMMITMENT_QUICK_SUMMARY~1","BLK_CONTRACT_LINKAGES_DETAIL" : "BLK_COMMITMENT_QUICK_SUMMARY~N","BLK_CONTRACT_FEE" : "BLK_COMMITMENT_QUICK_SUMMARY~1","BLK_CONTRACT_FEE_DETAIL" : "BLK_COMMITMENT_QUICK_SUMMARY~N","BLK_BORR_PROD_LIMIT" : "BLK_COMMITMENT_QUICK_SUMMARY~1","BLK_BORR_PROD_LIMIT_DETAIL" : "BLK_COMMITMENT_QUICK_SUMMARY~N","BLK_FEE_RATE" : "BLK_COMMITMENT_QUICK_SUMMARY~1","BLK_FEE_RATE_DETAIL" : "BLK_COMMITMENT_QUICK_SUMMARY~N","BLK_CONTRACT_EVENT_LOG" : "BLK_COMMITMENT_QUICK_SUMMARY~1","BLK_CONTRACT_EVENT_LOG_DETAIL" : "BLK_COMMITMENT_QUICK_SUMMARY~N","BLK_AMOUNT_DUE" : "BLK_COMMITMENT_QUICK_SUMMARY~1","BLK_AMOUNT_DUE_DETAIL" : "BLK_COMMITMENT_QUICK_SUMMARY~N"}; 

 var dataSrcLocationArray = new Array("BLK_COMMITMENT_QUICK_SUMMARY","BLK_CONTRACT_LINKAGES","BLK_CONTRACT_LINKAGES_DETAIL","BLK_CONTRACT_FEE","BLK_CONTRACT_FEE_DETAIL","BLK_BORR_PROD_LIMIT","BLK_BORR_PROD_LIMIT_DETAIL","BLK_FEE_RATE","BLK_FEE_RATE_DETAIL","BLK_CONTRACT_EVENT_LOG","BLK_CONTRACT_EVENT_LOG_DETAIL","BLK_AMOUNT_DUE","BLK_AMOUNT_DUE_DETAIL"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside OLDCLQRY.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside OLDCLQRY.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO";
pkFields[0] = "BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
var modifyAmendArr = new Array(); 
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO__LOV_CONTRACT_REF":["BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~","","N",""],"BLK_CONTRACT_SUMMARY__CONTRACTREFNO__LOV_CONTRACT_REF_S":["BLK_CONTRACT_SUMMARY__CONTRACTREFNO~~","","N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_MAIN';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_CONTRACT_LINKAGES_DETAIL","BLK_CONTRACT_FEE_DETAIL","BLK_BORR_PROD_LIMIT_DETAIL","BLK_CONTRACT_EVENT_LOG_DETAIL","BLK_AMOUNT_DUE_DETAIL");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("OLCSCHDT~BLK_COMMITMENT_QUICK_SUMMARY"); 

 var CallFormRelat=new Array("OLVWS_COMMITMENT_QUICK_SUMMARY.CONTRACT_REF_NO= OLVWS_SCHEDULE_SUMMARY__A.CONTRACT_REF_NO"); 

 var CallRelatType= new Array("1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["OLDCLQRY"]="KERNEL";
ArrPrntFunc["OLDCLQRY"]="";
ArrPrntOrigin["OLDCLQRY"]="";
ArrRoutingType["OLDCLQRY"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["OLDCLQRY"]="N";
ArrCustomModified["OLDCLQRY"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_LINK":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_FEE":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_SUBLMT":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_COMTFEE":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_TRNHIST":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_PAY":"CUSTOMERNO~CUSTOMERNAME1","OLCSCHDT":"PRODTYPE~CONTRACTREFNO~VALUEDATE~PAYMENTMETHOD~MATURITYTYP~MODULE~ACTIONCODE~MAINCOMP"};
var scrArgSource = {"CVS_LINK":"BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNAME1","CVS_FEE":"BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNAME1","CVS_SUBLMT":"BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNAME1","CVS_COMTFEE":"BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNAME1","CVS_TRNHIST":"BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNAME1","CVS_PAY":"BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNO~BLK_COMMITMENT_QUICK_SUMMARY__CUSTOMERNAME1","OLCSCHDT":"~BLK_COMMITMENT_QUICK_SUMMARY__CONTRACTREFNO~~~~~~"};
var scrArgVals = {"CVS_LINK":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_FEE":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_SUBLMT":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_COMTFEE":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_TRNHIST":"CONTRACTREFNO~CUSTOMERNO~CUSTOMERNAME1","CVS_PAY":"CUSTOMERNO~CUSTOMERNAME1","OLCSCHDT":"~~~~~~~"};
var scrArgDest = {"CVS_LINK":"BLK_CONTRACT_LINKAGES__TXTCONTRACTREFNO~BLK_CONTRACT_LINKAGES__TXTBORROWERNO~BLK_CONTRACT_LINKAGES__TXTBORROWERNAME","CVS_FEE":"BLK_CONTRACT_FEE__TXTCONTACTREFNO~BLK_CONTRACT_FEE__TXBORROWERNUM~BLK_CONTRACT_FEE__TXBORROWERNAME","CVS_SUBLMT":"BLK_BORR_PROD_LIMIT__TXTCONTRACTREFNO~BLK_BORR_PROD_LIMIT__TXTBORROWERNO~BLK_BORR_PROD_LIMIT__TXTBORROWENAME","CVS_COMTFEE":"BLK_FEE_RATE__TXTCONTRACTREFNO~BLK_FEE_RATE__TXTBORROWERNO~BLK_FEE_RATE__TXTBORROWERNAME","CVS_TRNHIST":"BLK_CONTRACT_EVENT_LOG__TXTCONTRACTREFNO~BLK_CONTRACT_EVENT_LOG__TXTBORROWERNO~BLK_CONTRACT_EVENT_LOG__TXTBORROWERNAME","CVS_PAY":"BLK_AMOUNT_DUE__TXTBORROWERNO~BLK_AMOUNT_DUE__TXTBORROWERNAME"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"OLCSCHDT":""};
var dpndntOnSrvs = {"OLCSCHDT":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"2","NEW":"2","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"2"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------