/***************************************************************************************************************************
**  This source is part of the Oracle Banking Software Product. 
**  Copyright (c) 2008 ,2024, Oracle and/or its affiliates.
**  All rights reserved.
**  
**  No part of this work may be reproduced, stored in a retrieval system, 
**  adopted or transmitted in any form or by any means, electronic, mechanical, photographic, 
**  graphic, optic recording or otherwise, translated in any language or computer language, 
**  without the prior written permission of Oracle and/or its affiliates.
**  
**  Oracle Financial Services Software Limited.
**  Oracle Park, Off Western Express Highway,
**  Goregaon (East),
**  Mumbai - 400 063,
**  India.
**  
**  Written by         : 
**  Date of creation   : 
**  File Name          : OLDVAMSI_SYS.js
**  Purpose            : 
**  Called From        : 
**  
**  CHANGE LOG
**  Last Modified By   : 
**  Last modified on   : 
**  Full Version       : 
**  Reason             : 
****************************************************************************************************************************/

//***** Code for criteria Search *****
var criteriaSearch  = 'N';
//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR THE SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var fieldNameArray = {"BLK_CONTRACT_MASTER":"CCY~LCYCCY~LCYAMT~AMT~CUST_NO~PRDTYP~PRD~BRN~CONTREFNO~VALDT~USERREFNO~VERNO~REPGMCOUNTNO~TRANREFNO~DRAWDWNNO~SYNDREFNO~REPGMFLAG~MAINCOMP~MATDT~MATTYPE~PAYMTHD~EVNTSEQNO~LASTAVLDT~JOBPICUP~CONTSTAT~USERDEFSTAT~BROKERCODE~NOTICEDAY~REAMORTDT~TENORBASDSPRD~CONTMATDT~CONTEFFDT~ROLLLOAN~TEAC~TEA~TEP~CONTREFERNO~LATEVERNO~LATEVNSEQNO~LATREPGMCOUNTNO~LATEVNTDT~CONTCCY~MODCODE~CURREVNTCODE~WORKFLWSTAT~RATEREVSTAT~TREASYSOURCE~DEPTCODE~BRNCH~PRDCODE~PRDTYPE~COUNPTY~NEWCRLINE~DIFFAMNT~VALUEDT~EVNTSNO~CONREFNUM~HFSTRANS~NEWREVFLAG~VAMIESN~AMENDNTAPPL~ICCFCHANGD~TRANSNDT~CONTLMATDT~CONTLEFFTDT~CRAGMNTAMND~CRAGMNTDT~NEWMATTYPE~TRANREMRK~TRANSEXCLFRMSTAT~REMARK~AMNDINSTSTAT~NONPRORATA~EXTTRANREFNO~REASCODE~TENORBSDSPRD~REAMRTDT~LCYEQVFORINDXLCY~SUBSYSSTAT~CPTYNAME~AMNDDT~ORGSTARTDT~RATE~NEWMATDT~UNCOVRAMT~TOTLINKAMT~PRODTYPEDESC~TICKETID~SETTLESEQNO~ORIGRATE~AGENCYCONT~REDEFCLICKED~DISPRCLICKED~PMTDETFLD~IOFTAXAMOUNT~MORAAMOUNT~TXTMATTYPE~ORGACTCOD~OUTSTANDINGAMT~INTEREST_REFUND_REQUIERD~REVERSE_REASON_CODE~REVERSE_REASON_DESC~REV_REASON_CODE_DISP~REV_REASON_DESC_DISP~PMT_MSG_GEN_FLAG~PROCESSREFNUM~CHANNELREFNUM~SPOT_RATE~OPENLOAN~ECAREQSTATUS","BLK_CONTRACT_EVENT_LOG":"RATEREVSTAT~WORKFLOWSTAT~AUTHSTAT~EVNTCODE~EVNTDT~ESN~CK_DTSTAMP~AUTHBY~MK_DTSTAMP~INPUTBY~CONTREFNO~MODULE~REVESN~NEWVERIND~TXNSTAT","BLK_CONTRACT_SCHEDULES":"CONTREFNO~VERNO~ESN~SCHTYPE~SCH_FLAG~COMP~STARTDT~NOOFSCH~FREQ~FREQUNIT~AMT~RESET_TENOR~MONTH_END_IND~END_DATE~AUTOCAP~AUTOCAPINSF","BLK_CONTRACT_REVISION_SCH":"SCHEDLINK~REVAPPL~REVDT~COMP~CONTREFNO","BLK_CONTRACT_PREFERENCE":"MATHOLICCY~MATHOLICHK~INSTALNTLOAN~MSCHSCHMOVE~MSCHMOVACCMNTH~MSCHIGNHOLIDAY~STATCTRL~CASCADESCH~MOVEACCMONTH~DEDUCTTAXONCAPT~AMORTTYPE~IGNHOLIDAY~SCHMOVNT~VERFUNDS~HOLICCY~REVOLCOMMIT~PRINLIQD~LIQBACKVALSCH~CONTSCHTYPE~ESN~VERSNO~CONTREFNO~AMORTAMT~AMORTAMOUNT","BLK_CONTRACT_LINKAGES":"LINKTOCCY~CONLINKAMT~EXCHRATE~LINKAMT~LINKTYPE~LOANCCY~LINKVALID~ESN~LINKTOREF~LINKTOBRN~VERSNO~CONTREFNO~AVAILAMT~PROJAVLAMT","BLK_DRAWDOWN_SCHEDULES":"DRAWDWNAPPL~CONTCCY~AMT~PAIDDT~DRADWNDUEDT~COMP~CONTREFNO","BLK_INST_SCHEDULES":"CONTREFNO~CCY~PROCESSTAT~CALCAMT~STARTDT~COMP","BLK_LINK_SUM":"","BLK_CONT_REV_SCH_BTN":"","BLK_OLTBS_CONTRACT_CONTROL":"PROCESSCODE~ENTRYBY~CONTRACTREFNO","BLK_OLTBS_CONTRACT_SCHEDULES_PAID":"CONTRACT_REF_NO~VERSION_NO~EVENT_SEQ_NO~SCHEDULE_TYPE~SCH_FLAG~COMPONENT~START_DATE~NO_OF_SCHEDULES~FREQUENCY~FREQUENCY_UNIT~AMOUNT~RESET_TENOR~MONTH_END_IND~END_DATE~BASE_INDEX_RATE~LCY_EQVT_FOR_INDEX_LOANS~SCH_PERCENT~PREPAY_IND~AUTOCAP~AUTOCAPINSF~UILASTPAIDDATE","BLK_OLVWS_SCHEDULE_SUMMARY":"CCYAMTDUE~DUEDATE~TOTAMTADJ~TOTAMTDUE~TOTAMTPAID~EXPECTED_BALANCE~PAY_RECV_AMOUNT~AMOUNT_DUE_ACTUAL~TILL_DATE_DUE~LCY_EQUIVALENT","BLK_AMOUNT_DUE":"COMPTYPE~CCYAMTDUE~SCHPICKLIQ~MSGESN~SCHLINK~ADJAMT~BASICAMTTAG~INFLOWOUTFLOW~AMTSETTL~CPTY~BRNACCDUE~ACCDUE~AMTDUE~DUEDT~COMP~CONTREFNO~EXPECTED_BALANCE~MORA_INT~PAY_RECV_AMOUNT~PAYBYDT~AMOUNT_DUE_ACTUAL~TILL_DATE_DUE~LCY_EQUIVALENT","BLK_CONTRACT_ICCF_CALC":"RATE_SOFR~DAILY_ACC_SOFR~COMPONENT~P_ACU_INTEREST_SOFR~CONTRACT_REF_NO~CURRENCY~SPREAD_ADJUSTMENT_SOFR~NO_OF_DAYS_SOFR~PREPAYMENT_PENALTY_SEQ_NO~RATE_PICKUP_DATE~SCHEDULE_DATE~MARGIN_SOFR~CALCULATION_DATE_SOFR~INTEREST_AMOUNT_SOFR~CUM_ACCR_INTEREST~TOT_SIMPLE_INT_SOFR~RATE","BLK_MSGVW":"AUTHSTAT~DCN~MSGSTATUS~NAME~TESTINGSTATUS~ESN~MESSAGE~MSGTYPE~MEDIA~REFERENCENO~RUNNINGNO~RECEIVER~SWIFTMSGTYPE","BLK_OLVWS_AMOUNT_SETTLED":"AMTSET~CCYSETTLD~LCYEQPAID~PAIDDATE~INPUT_DATE~LCYCCY","BLK_CONTRACT_ICCF_VIEW":"BASE_INDEX_RATE~RATE_SOFR~DAILY_ACC_SOFR~COMPONENT~P_ACU_INTEREST_SOFR~CONTRACT_REF_NO~CURRENCY~SPREAD_ADJUSTMENT_SOFR~PREPAYMENT_PENALTY_SEQ_NO~RATE~RATE_CODE~RATE_PICKUP_DATE~RATE_TYPE~SCHEDULE_DATE~MARGIN_SOFR~CALCULATION_DATE_SOFR~INTEREST_AMOUNT_SOFR~TOTAL_SIMPLE_INT_SOFR~CUM_ACCR_INTEREST~ACR~NCR~RATE_FACTOR~RFR_EFFEC_RATE~UCR~NO_OF_DAYS_SOFR~RATE_UI~ADJUSTMENT_RATE~PICKEDUP_BASE_RATE","BLK_COMP_PAY_DTLS":"ADJUSTED_AMOUNT~AMOUNT_DUE~AMOUNT_DUE_ACTUAL~AMOUNT_SETTLED~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~CURRENCY_AMT_DUE~DUE_DATE~PAY_RECV_AMOUNT~SCHEDULE_DATE~TILL_DATE_ACCRUAL~TOTAL_AMOUNT_PAID~TOTAL_AMOUNT_WAIVED~TOTAL_AMOUNT_CAPITALIZED","BLK_COMP_SCH_DTLS":"ADJUSTED_AMOUNT~AMOUNT_DUE~AMOUNT_DUE_ACTUAL~AMOUNT_SETTLED~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~CURRENCY_AMT_DUE~DUE_DATE~INFLOW_OUTFLOW~LCY_REVAL_AMT~MORA_INT~PAY_RECV_AMOUNT~SCHEDULE_DATE~EXPECTED_BALANCE","BLK_COMP_ICCF_VIEW":"ACR~ADJUSTMENT_RATE~BASE_INDEX_RATE~BASE_RATE~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~MRGN_RATE~NCR~NO_OF_DAYS~PICKEDUP_BASE_RATE~PREPAYMENT_PENALTY_SEQ_NO~RATE~RATE_CODE~RATE_FACTOR~RATE_PICKUP_DATE~RFR_EFFEC_RATE~SCHEDULE_DATE~SPRD_RATE~START_DATE~TOTAL_COMP_INT~TOTAL_SIMPLE_INT~UCR~CALCULATED_AMOUNT~COMPOUND_INTEREST~RATE_UI~CUM_ACCR_INTEREST~RATE_TYPE","BLK_COMP_AMNT_SETTLED":"ACCOUNT_SETTLED~AMOUNT_SETTLED~COMPONENT~CONTRACT_REF_NO~CURRENCY_SETTLED~DUE_DATE~EVENT_SEQ_NO~LCY_EQUIVALENT_SETTLED~PAID_DATE~LCYCCY~INPUT_DATE~AMTDUECCY"};

var multipleEntryPageSize = {"BLK_CONTRACT_SCHEDULES" :"15" ,"BLK_CONTRACT_LINKAGES" :"15" ,"BLK_AMOUNT_DUE" :"15" ,"BLK_CONTRACT_REVISION_SCH" :"15" ,"BLK_DRAWDOWN_SCHEDULES" :"15" ,"BLK_INST_SCHEDULES" :"15" ,"" :"15" ,"BLK_OLTBS_CONTRACT_SCHEDULES_PAID" :"15" ,"BLK_OLVWS_SCHEDULE_SUMMARY" :"15" ,"" :"15" ,"BLK_OLVWS_AMOUNT_SETTLED" :"15" ,"BLK_CONTRACT_ICCF_VIEW" :"15" ,"BLK_COMP_PAY_DTLS" :"15" ,"BLK_COMP_SCH_DTLS" :"15" ,"BLK_COMP_ICCF_VIEW" :"15" ,"BLK_COMP_AMNT_SETTLED" :"15" };

var multipleEntrySVBlocks = "BLK_MSGVW";

var tabMEBlks = {"CVS_VAMI__TAB_SCHD":"BLK_CONTRACT_SCHEDULES","CVS_VAMI__TAB_LINK":"BLK_CONTRACT_LINKAGES","CVS_SCHEDULE_DETAILS__TAB_MAIN":"BLK_AMOUNT_DUE~BLK_OLVWS_SCHEDULE_SUMMARY~BLK_OLVWS_AMOUNT_SETTLED~BLK_CONTRACT_ICCF_VIEW","CVS_REVSCHD__TAB_MAIN":"BLK_CONTRACT_REVISION_SCH","CVS_DRAWDOWNSCH__TAB_MAIN":"BLK_DRAWDOWN_SCHEDULES","CVS_INSTSCHED__TAB_MAIN":"BLK_INST_SCHEDULES","CVS_PAID_SCHEDLS__TAB_MAIN":"BLK_OLTBS_CONTRACT_SCHEDULES_PAID","CVS_SCHEDULE_DETAILS__TAB_COMP":"BLK_COMP_PAY_DTLS~BLK_COMP_SCH_DTLS~BLK_COMP_ICCF_VIEW~BLK_COMP_AMNT_SETTLED"};

var msgxml=""; 
msgxml += '    <FLD>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_CONTRACT_MASTER">CCY~LCYCCY~LCYAMT~AMT~CUST_NO~PRDTYP~PRD~BRN~CONTREFNO~VALDT~USERREFNO~VERNO~REPGMCOUNTNO~TRANREFNO~DRAWDWNNO~SYNDREFNO~REPGMFLAG~MAINCOMP~MATDT~MATTYPE~PAYMTHD~EVNTSEQNO~LASTAVLDT~JOBPICUP~CONTSTAT~USERDEFSTAT~BROKERCODE~NOTICEDAY~REAMORTDT~TENORBASDSPRD~CONTMATDT~CONTEFFDT~ROLLLOAN~TEAC~TEA~TEP~CONTREFERNO~LATEVERNO~LATEVNSEQNO~LATREPGMCOUNTNO~LATEVNTDT~CONTCCY~MODCODE~CURREVNTCODE~WORKFLWSTAT~RATEREVSTAT~TREASYSOURCE~DEPTCODE~BRNCH~PRDCODE~PRDTYPE~COUNPTY~NEWCRLINE~DIFFAMNT~VALUEDT~EVNTSNO~CONREFNUM~HFSTRANS~NEWREVFLAG~VAMIESN~AMENDNTAPPL~ICCFCHANGD~TRANSNDT~CONTLMATDT~CONTLEFFTDT~CRAGMNTAMND~CRAGMNTDT~NEWMATTYPE~TRANREMRK~TRANSEXCLFRMSTAT~REMARK~AMNDINSTSTAT~NONPRORATA~EXTTRANREFNO~REASCODE~TENORBSDSPRD~REAMRTDT~LCYEQVFORINDXLCY~SUBSYSSTAT~CPTYNAME~AMNDDT~ORGSTARTDT~RATE~NEWMATDT~UNCOVRAMT~TOTLINKAMT~PRODTYPEDESC~TICKETID~SETTLESEQNO~ORIGRATE~AGENCYCONT~REDEFCLICKED~DISPRCLICKED~PMTDETFLD~IOFTAXAMOUNT~MORAAMOUNT~TXTMATTYPE~ORGACTCOD~OUTSTANDINGAMT~INTEREST_REFUND_REQUIERD~REVERSE_REASON_CODE~REVERSE_REASON_DESC~REV_REASON_CODE_DISP~REV_REASON_DESC_DISP~PMT_MSG_GEN_FLAG~PROCESSREFNUM~CHANNELREFNUM~SPOT_RATE~OPENLOAN~ECAREQSTATUS</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="1" TYPE="BLK_CONTRACT_EVENT_LOG">RATEREVSTAT~WORKFLOWSTAT~AUTHSTAT~EVNTCODE~EVNTDT~ESN~CK_DTSTAMP~AUTHBY~MK_DTSTAMP~INPUTBY~CONTREFNO~MODULE~REVESN~NEWVERIND~TXNSTAT</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_CONTRACT_SCHEDULES">CONTREFNO~VERNO~ESN~SCHTYPE~SCH_FLAG~COMP~STARTDT~NOOFSCH~FREQ~FREQUNIT~AMT~RESET_TENOR~MONTH_END_IND~END_DATE~AUTOCAP~AUTOCAPINSF</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_CONTRACT_REVISION_SCH">SCHEDLINK~REVAPPL~REVDT~COMP~CONTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="1" TYPE="BLK_CONTRACT_PREFERENCE">MATHOLICCY~MATHOLICHK~INSTALNTLOAN~MSCHSCHMOVE~MSCHMOVACCMNTH~MSCHIGNHOLIDAY~STATCTRL~CASCADESCH~MOVEACCMONTH~DEDUCTTAXONCAPT~AMORTTYPE~IGNHOLIDAY~SCHMOVNT~VERFUNDS~HOLICCY~REVOLCOMMIT~PRINLIQD~LIQBACKVALSCH~CONTSCHTYPE~ESN~VERSNO~CONTREFNO~AMORTAMT~AMORTAMOUNT</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_CONTRACT_LINKAGES">LINKTOCCY~CONLINKAMT~EXCHRATE~LINKAMT~LINKTYPE~LOANCCY~LINKVALID~ESN~LINKTOREF~LINKTOBRN~VERSNO~CONTREFNO~AVAILAMT~PROJAVLAMT</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_DRAWDOWN_SCHEDULES">DRAWDWNAPPL~CONTCCY~AMT~PAIDDT~DRADWNDUEDT~COMP~CONTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_INST_SCHEDULES">CONTREFNO~CCY~PROCESSTAT~CALCAMT~STARTDT~COMP</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="1" TYPE="BLK_LINK_SUM"></FN>'; 
msgxml += '      <FN PARENT="" RELATION_TYPE="1" TYPE="BLK_CONT_REV_SCH_BTN"></FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="1" TYPE="BLK_OLTBS_CONTRACT_CONTROL">PROCESSCODE~ENTRYBY~CONTRACTREFNO</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_OLTBS_CONTRACT_SCHEDULES_PAID">CONTRACT_REF_NO~VERSION_NO~EVENT_SEQ_NO~SCHEDULE_TYPE~SCH_FLAG~COMPONENT~START_DATE~NO_OF_SCHEDULES~FREQUENCY~FREQUENCY_UNIT~AMOUNT~RESET_TENOR~MONTH_END_IND~END_DATE~BASE_INDEX_RATE~LCY_EQVT_FOR_INDEX_LOANS~SCH_PERCENT~PREPAY_IND~AUTOCAP~AUTOCAPINSF~UILASTPAIDDATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_OLVWS_SCHEDULE_SUMMARY">CCYAMTDUE~DUEDATE~TOTAMTADJ~TOTAMTDUE~TOTAMTPAID~EXPECTED_BALANCE~PAY_RECV_AMOUNT~AMOUNT_DUE_ACTUAL~TILL_DATE_DUE~LCY_EQUIVALENT</FN>'; 
msgxml += '      <FN PARENT="BLK_OLVWS_SCHEDULE_SUMMARY" RELATION_TYPE="N" TYPE="BLK_AMOUNT_DUE">COMPTYPE~CCYAMTDUE~SCHPICKLIQ~MSGESN~SCHLINK~ADJAMT~BASICAMTTAG~INFLOWOUTFLOW~AMTSETTL~CPTY~BRNACCDUE~ACCDUE~AMTDUE~DUEDT~COMP~CONTREFNO~EXPECTED_BALANCE~MORA_INT~PAY_RECV_AMOUNT~PAYBYDT~AMOUNT_DUE_ACTUAL~TILL_DATE_DUE~LCY_EQUIVALENT</FN>'; 
msgxml += '      <FN PARENT="BLK_AMOUNT_DUE" RELATION_TYPE="N" TYPE="BLK_CONTRACT_ICCF_CALC">RATE_SOFR~DAILY_ACC_SOFR~COMPONENT~P_ACU_INTEREST_SOFR~CONTRACT_REF_NO~CURRENCY~SPREAD_ADJUSTMENT_SOFR~NO_OF_DAYS_SOFR~PREPAYMENT_PENALTY_SEQ_NO~RATE_PICKUP_DATE~SCHEDULE_DATE~MARGIN_SOFR~CALCULATION_DATE_SOFR~INTEREST_AMOUNT_SOFR~CUM_ACCR_INTEREST~TOT_SIMPLE_INT_SOFR~RATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_MSGVW">AUTHSTAT~DCN~MSGSTATUS~NAME~TESTINGSTATUS~ESN~MESSAGE~MSGTYPE~MEDIA~REFERENCENO~RUNNINGNO~RECEIVER~SWIFTMSGTYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_AMOUNT_DUE" RELATION_TYPE="N" TYPE="BLK_OLVWS_AMOUNT_SETTLED">AMTSET~CCYSETTLD~LCYEQPAID~PAIDDATE~INPUT_DATE~LCYCCY</FN>'; 
msgxml += '      <FN PARENT="BLK_AMOUNT_DUE" RELATION_TYPE="N" TYPE="BLK_CONTRACT_ICCF_VIEW">BASE_INDEX_RATE~RATE_SOFR~DAILY_ACC_SOFR~COMPONENT~P_ACU_INTEREST_SOFR~CONTRACT_REF_NO~CURRENCY~SPREAD_ADJUSTMENT_SOFR~PREPAYMENT_PENALTY_SEQ_NO~RATE~RATE_CODE~RATE_PICKUP_DATE~RATE_TYPE~SCHEDULE_DATE~MARGIN_SOFR~CALCULATION_DATE_SOFR~INTEREST_AMOUNT_SOFR~TOTAL_SIMPLE_INT_SOFR~CUM_ACCR_INTEREST~ACR~NCR~RATE_FACTOR~RFR_EFFEC_RATE~UCR~NO_OF_DAYS_SOFR~RATE_UI~ADJUSTMENT_RATE~PICKEDUP_BASE_RATE</FN>'; 
msgxml += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="N" TYPE="BLK_COMP_PAY_DTLS">ADJUSTED_AMOUNT~AMOUNT_DUE~AMOUNT_DUE_ACTUAL~AMOUNT_SETTLED~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~CURRENCY_AMT_DUE~DUE_DATE~PAY_RECV_AMOUNT~SCHEDULE_DATE~TILL_DATE_ACCRUAL~TOTAL_AMOUNT_PAID~TOTAL_AMOUNT_WAIVED~TOTAL_AMOUNT_CAPITALIZED</FN>'; 
msgxml += '      <FN PARENT="BLK_COMP_PAY_DTLS" RELATION_TYPE="N" TYPE="BLK_COMP_SCH_DTLS">ADJUSTED_AMOUNT~AMOUNT_DUE~AMOUNT_DUE_ACTUAL~AMOUNT_SETTLED~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~CURRENCY_AMT_DUE~DUE_DATE~INFLOW_OUTFLOW~LCY_REVAL_AMT~MORA_INT~PAY_RECV_AMOUNT~SCHEDULE_DATE~EXPECTED_BALANCE</FN>'; 
msgxml += '      <FN PARENT="BLK_COMP_SCH_DTLS" RELATION_TYPE="N" TYPE="BLK_COMP_ICCF_VIEW">ACR~ADJUSTMENT_RATE~BASE_INDEX_RATE~BASE_RATE~COMPONENT~COMPONENT_TYPE~CONTRACT_REF_NO~MRGN_RATE~NCR~NO_OF_DAYS~PICKEDUP_BASE_RATE~PREPAYMENT_PENALTY_SEQ_NO~RATE~RATE_CODE~RATE_FACTOR~RATE_PICKUP_DATE~RFR_EFFEC_RATE~SCHEDULE_DATE~SPRD_RATE~START_DATE~TOTAL_COMP_INT~TOTAL_SIMPLE_INT~UCR~CALCULATED_AMOUNT~COMPOUND_INTEREST~RATE_UI~CUM_ACCR_INTEREST~RATE_TYPE</FN>'; 
msgxml += '      <FN PARENT="BLK_COMP_SCH_DTLS" RELATION_TYPE="N" TYPE="BLK_COMP_AMNT_SETTLED">ACCOUNT_SETTLED~AMOUNT_SETTLED~COMPONENT~CONTRACT_REF_NO~CURRENCY_SETTLED~DUE_DATE~EVENT_SEQ_NO~LCY_EQUIVALENT_SETTLED~PAID_DATE~LCYCCY~INPUT_DATE~AMTDUECCY</FN>'; 
msgxml += '    </FLD>'; 

var strScreenName = "CVS_VAMI";
var qryReqd = "Y";
var txnBranchFld = "BLK_CONTRACT_MASTER__BRN" ;
var originSystem = "";
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** FCJ XML FOR SUMMARY SCREEN *****
//----------------------------------------------------------------------------------------------------------------------
var msgxml_sum=""; 
msgxml_sum += '    <FLD>'; 
msgxml_sum += '      <FN PARENT="BLK_CONTRACT_MASTER" RELATION_TYPE="1" TYPE="BLK_VAMI_SUMMARY">CONTREFNO~ESNSUM~VALDTSUM~DIFFAMTSUM~NEWMATDTSUM~TRNDTSUM~CPTY~CUSTNAM~AUTHSTATSUM~CONTSTATSUM~BRNCH~MODCODE</FN>'; 
msgxml_sum += '    </FLD>'; 

var detailFuncId = "OLDVAMSI";
var defaultWhereClause = "sypks_utils.get_branch(CONTRACT_REF_NO) =GLOBAL.CURRENT_BRANCH";
var defaultOrderByClause ="";
var multiBrnWhereClause ="";
var g_SummaryType ="S";
var g_SummaryBtnCount =0;
var g_SummaryBlock ="BLK_VAMI_SUMMARY";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR DATABINDING *****
//----------------------------------------------------------------------------------------------------------------------
 var relationArray = {"BLK_CONTRACT_MASTER" : "","BLK_CONTRACT_EVENT_LOG" : "BLK_CONTRACT_MASTER~1","BLK_CONTRACT_SCHEDULES" : "BLK_CONTRACT_MASTER~N","BLK_CONTRACT_REVISION_SCH" : "BLK_CONTRACT_MASTER~N","BLK_CONTRACT_PREFERENCE" : "BLK_CONTRACT_MASTER~1","BLK_CONTRACT_LINKAGES" : "BLK_CONTRACT_MASTER~N","BLK_DRAWDOWN_SCHEDULES" : "BLK_CONTRACT_MASTER~N","BLK_INST_SCHEDULES" : "BLK_CONTRACT_MASTER~N","BLK_LINK_SUM" : "BLK_CONTRACT_MASTER~1","BLK_CONT_REV_SCH_BTN" : "","BLK_OLTBS_CONTRACT_CONTROL" : "BLK_CONTRACT_MASTER~1","BLK_OLTBS_CONTRACT_SCHEDULES_PAID" : "BLK_CONTRACT_MASTER~N","BLK_OLVWS_SCHEDULE_SUMMARY" : "BLK_CONTRACT_MASTER~N","BLK_AMOUNT_DUE" : "BLK_OLVWS_SCHEDULE_SUMMARY~N","BLK_CONTRACT_ICCF_CALC" : "BLK_AMOUNT_DUE~N","BLK_MSGVW" : "BLK_CONTRACT_MASTER~N","BLK_OLVWS_AMOUNT_SETTLED" : "BLK_AMOUNT_DUE~N","BLK_CONTRACT_ICCF_VIEW" : "BLK_AMOUNT_DUE~N","BLK_COMP_PAY_DTLS" : "BLK_CONTRACT_MASTER~N","BLK_COMP_SCH_DTLS" : "BLK_COMP_PAY_DTLS~N","BLK_COMP_ICCF_VIEW" : "BLK_COMP_SCH_DTLS~N","BLK_COMP_AMNT_SETTLED" : "BLK_COMP_SCH_DTLS~N"}; 

 var dataSrcLocationArray = new Array("BLK_CONTRACT_MASTER","BLK_CONTRACT_EVENT_LOG","BLK_CONTRACT_SCHEDULES","BLK_CONTRACT_REVISION_SCH","BLK_CONTRACT_PREFERENCE","BLK_CONTRACT_LINKAGES","BLK_DRAWDOWN_SCHEDULES","BLK_INST_SCHEDULES","BLK_LINK_SUM","BLK_CONT_REV_SCH_BTN","BLK_OLTBS_CONTRACT_CONTROL","BLK_OLTBS_CONTRACT_SCHEDULES_PAID","BLK_OLVWS_SCHEDULE_SUMMARY","BLK_AMOUNT_DUE","BLK_CONTRACT_ICCF_CALC","BLK_MSGVW","BLK_OLVWS_AMOUNT_SETTLED","BLK_CONTRACT_ICCF_VIEW","BLK_COMP_PAY_DTLS","BLK_COMP_SCH_DTLS","BLK_COMP_ICCF_VIEW","BLK_COMP_AMNT_SETTLED"); 
 // Array of all Data Sources used in the screen 
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR QUERY MODE *****
//----------------------------------------------------------------------------------------------------------------------
var detailRequired = true ;
var intCurrentQueryResultIndex = 0;
var intCurrentQueryRecordCount = 0;

var queryFields = new Array();    //Values should be set inside OLDVAMSI.js, in "BlockName__FieldName" format
var pkFields    = new Array();    //Values should be set inside OLDVAMSI.js, in "BlockName__FieldName" format
queryFields[0] = "BLK_CONTRACT_MASTER__CONTREFNO";
pkFields[0] = "BLK_CONTRACT_MASTER__CONTREFNO";
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR AMENDABLE/SUBSYSTEM Fields *****
//----------------------------------------------------------------------------------------------------------------------
//***** Fields Amendable while Modification *****
var modifyAmendArr = {"BLK_CONTRACT_MASTER":["AMENDNTAPPL","AMNDDTI","AMNDINSTSTAT","CONTLEFFTDTI","CONTLMATDTI","CRAGMNTAMND","CRAGMNTDTI","DIFFAMNT","EXTTRANREFNO","HFSTRANS","ICCFCHANGD","INTEREST_REFUND_REQUIERD","LCYEQVFORINDXLCY","NEWCRLINE","NEWMATDTI","NEWMATTYPE","NEWREVFLAG","NONPRORATA","REAMRTDTI","REASCODE","REMARK","REPGMFLAG","SPOT_RATE","TENORBSDSPRD","TRANREMRK","TRANSEXCLFRMSTAT","TRANSNDTI","VALUEDTI"],"BLK_CONTRACT_PREFERENCE":["AMORTAMOUNT"],"BLK_CONTRACT_SCHEDULES":["AMT","AUTOCAP","AUTOCAPINSF","BTN_DEF_SCH","BTN_DIS_PRIN","BTN_REDEFINE","COMP","FREQ","FREQUNIT","NOOFSCH","SCHTYPE","STARTDTI"]};
var closeAmendArr = new Array(); 
var reopenAmendArr = new Array(); 
var reverseAmendArr = new Array(); 
var deleteAmendArr = new Array(); 
var rolloverAmendArr = new Array(); 
var confirmAmendArr = new Array(); 
var liquidateAmendArr = new Array(); 
var queryAmendArr = new Array(); 
var authorizeAmendArr = new Array(); 
//----------------------------------------------------------------------------------------------------------------------

var subsysArr    = new Array(); 

//----------------------------------------------------------------------------------------------------------------------

//***** CODE FOR LOVs *****
//----------------------------------------------------------------------------------------------------------------------
var lovInfoFlds = {"BLK_CONTRACT_MASTER__BRN__LOV_BRANCH":["BLK_CONTRACT_MASTER__BRN~~~~","","N~N~N~N",""],"BLK_CONTRACT_MASTER__CONTREFNO__LOV_CONTRACTREF":["BLK_CONTRACT_MASTER__CONTREFNO~","BLK_CONTRACT_MASTER__BRN!VARCHAR2","N",""],"BLK_CONTRACT_MASTER__REASCODE__LOV_REASON_CODE":["BLK_CONTRACT_MASTER__REASCODE~~","","N~N",""],"BLK_CONTRACT_MASTER__REVERSE_REASON_CODE__LOV_REVERSE_REASON":["BLK_CONTRACT_MASTER__REVERSE_REASON_CODE~BLK_CONTRACT_MASTER__REVERSE_REASON_DESC~","","N~N",""],"BLK_CONTRACT_SCHEDULES__COMP__LOV_COMPONENT":["BLK_CONTRACT_SCHEDULES__COMP~","BLK_CONTRACT_MASTER__PRDCODE!VARCHAR2~BLK_CONTRACT_MASTER__PRDCODE!VARCHAR2~BLK_CONTRACT_MASTER__CONTREFNO!VARCHAR2~BLK_CONTRACT_MASTER__CONTREFNO!VARCHAR2~BLK_CONTRACT_MASTER__CONTREFNO!VARCHAR2~BLK_CONTRACT_MASTER__PRDCODE!VARCHAR2~BLK_CONTRACT_MASTER__CONTREFNO!VARCHAR2~BLK_CONTRACT_MASTER__LATEVERNO!VARCHAR2~BLK_CONTRACT_MASTER__PRDCODE!VARCHAR2","N","N"],"BLK_VAMI_SUMMARY__CPTY__LOV_CUST_NAME_S":["BLK_VAMI_SUMMARY__CPTY~BLK_VAMI_SUMMARY__CUSTNAM~~","","N~N",""]};
var offlineLovInfoFlds = {};
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR TABS *****
//----------------------------------------------------------------------------------------------------------------------
var strHeaderTabId = 'TAB_HEADER';
var strFooterTabId = 'TAB_FOOTER';
var strCurrentTabId = 'TAB_AMEND';
//--------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------
var multipleEntryIDs = new Array("BLK_CONTRACT_SCHEDULES","BLK_CONTRACT_LINKAGES","BLK_AMOUNT_DUE","BLK_CONTRACT_REVISION_SCH","BLK_DRAWDOWN_SCHEDULES","BLK_INST_SCHEDULES","","BLK_OLTBS_CONTRACT_SCHEDULES_PAID","BLK_OLVWS_SCHEDULE_SUMMARY","","BLK_OLVWS_AMOUNT_SETTLED","BLK_CONTRACT_ICCF_VIEW","BLK_COMP_PAY_DTLS","BLK_COMP_SCH_DTLS","BLK_COMP_ICCF_VIEW","BLK_COMP_AMNT_SETTLED");
var multipleEntryArray = new Array();
var multipleEntryCells = new Array();
//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR MULTIPLE ENTRY VIEW SINGLE ENTRY BLOCKS *****
//----------------------------------------------------------------------------------------------------------------------

//----------------------------------------------------------------------------------------------------------------------
//***** SCRIPT FOR ATTACHED CALLFORMS *****
 //----------------------------------------------------------------------------------------------------------------------

 var CallFormArray= new Array("LFCTRCHG~BLK_CONTRACT_MASTER","LFCINTCH~BLK_CONTRACT_MASTER","OLCONDET~BLK_CONTRACT_MASTER","TXCTRTAX~BLK_CONTRACT_MASTER","OLCSTINF~BLK_CONTRACT_MASTER","OLCTRMIS~BLK_CONTRACT_MASTER","OLCTRUDF~BLK_CONTRACT_MASTER","OLCTRADV~BLK_CONTRACT_MASTER"); 

 var CallFormRelat=new Array("OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO=OLTBS_CONTRACT__CHG.CONTRACT_REF_NO AND OLTBS_CONTRACT_MASTER.EVENT_SEQ_NO=OLTBS_CONTRACT__CHG.LATEST_EVENT_SEQ_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO= OLTBS_CONTRACT__INT.CONTRACT_REF_NO AND OLTBS_CONTRACT_MASTER.EVENT_SEQ_NO = OLTBS_CONTRACT__INT.LATEST_EVENT_SEQ_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO=OLTBS_CONTRACT__SETT.CONTRACT_REF_NO AND OLTBS_CONTRACT_MASTER.EVENT_SEQ_NO=OLTBS_CONTRACT__SETT.LATEST_EVENT_SEQ_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO=OLTBS_CONTRACT__TAX.CONTRACT_REF_NO AND OLTBS_CONTRACT_MASTER.EVENT_SEQ_NO=OLTBS_CONTRACT__TAX.LATEST_EVENT_SEQ_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO=OLVW_SETTLEMENT_INFO.CONTRACT_REF_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO=OLTBS_CONTRACT__MIS.CONTRACT_REF_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO=OLTBS_CONTRACT__FLD.CONTRACT_REF_NO AND OLTBS_CONTRACT_MASTER.EVENT_SEQ_NO= OLTBS_CONTRACT__FLD.LATEST_VERSION_NO","OLTBS_CONTRACT_MASTER.CONTRACT_REF_NO= OLTBS_CONTRACT__ADV.CONTRACT_REF_NO AND OLTBS_CONTRACT_MASTER.EVENT_SEQ_NO = OLTBS_CONTRACT__ADV.LATEST_EVENT_SEQ_NO"); 

 var CallRelatType= new Array("1","1","1","1","1","1","1","1"); 


 var ArrFuncOrigin=new Array();
 var ArrPrntFunc=new Array();
 var ArrPrntOrigin=new Array();
 var ArrRoutingType=new Array();


 // Code for Loading Cluster/Custom js File Starts
 var ArrClusterModified=new Array();
 var ArrCustomModified=new Array();
 // Code for Loading Cluster/Custom js File ends

ArrFuncOrigin["OLDVAMSI"]="KERNEL";
ArrPrntFunc["OLDVAMSI"]="OLDVAMND";
ArrPrntOrigin["OLDVAMSI"]="KERNEL";
ArrRoutingType["OLDVAMSI"]="X";


 // Code for Loading Cluster/Custom js File Starts
ArrClusterModified["OLDVAMSI"]="N";
ArrCustomModified["OLDVAMSI"]="N";

 // Code for Loading Cluster/Custom js File ends


 /* Code For OBIEE functionalities */ 
var obScrArgName  = new Array(); 
var obScrArgSource  = new Array(); 
//***** CODE FOR SCREEN ARGS *****
//----------------------------------------------------------------------------------------------------------------------
var scrArgName = {"CVS_MSGVW":"REFNO","LFCTRCHG":"CONTREF~ESN~MODULECODE","LFCINTCH":"CONTRACTREFNO~MODULE~EVENTSEQNO","OLCONDET":"CONREFNO~ESN","TXCTRTAX":"CONTREF~ESN","OLCSTINF":"","OLCTRMIS":"CONTREF~ESN~PRDCD~BRNCD","OLCTRUDF":"CONTREFNO~LATVERNO","OLCTRADV":"CONTREF~ESN~","OLDEVENT":"CONTREF~ACTION_CODE","OLDMSPRV":"CONTREF~ESN~MODULE~PARENTFUNCTION~ACTION_CODE"};
var scrArgSource = {"CVS_MSGVW":"BLK_CONTRACT_MASTER__CONTREFNO","LFCTRCHG":"BLK_CONTRACT_MASTER__CONTREFNO~BLK_CONTRACT_MASTER__EVNTSEQNO~","LFCINTCH":"BLK_CONTRACT_MASTER__CONTREFNO~~BLK_CONTRACT_MASTER__EVNTSEQNO","OLCONDET":"BLK_CONTRACT_MASTER__CONTREFNO~BLK_CONTRACT_MASTER__EVNTSEQNO","TXCTRTAX":"BLK_CONTRACT_MASTER__CONTREFNO~BLK_CONTRACT_MASTER__EVNTSEQNO","OLCSTINF":"","OLCTRMIS":"BLK_CONTRACT_MASTER__CONTREFNO~BLK_CONTRACT_MASTER__EVNTSEQNO~BLK_CONTRACT_MASTER__PRD~","OLCTRUDF":"BLK_CONTRACT_MASTER__CONTREFNO~BLK_CONTRACT_MASTER__EVNTSEQNO","OLCTRADV":"BLK_CONTRACT_MASTER__CONTREFNO~BLK_CONTRACT_MASTER__EVNTSEQNO~","OLDEVENT":"BLK_CONTRACT_MASTER__CONTREFNO~","OLDMSPRV":"BLK_CONTRACT_MASTER__CONTREFNO~~~~"};
var scrArgVals = {"CVS_MSGVW":"","LFCTRCHG":"~~OL","LFCINTCH":"~OL~","OLCONDET":"~","TXCTRTAX":"~","OLCSTINF":"","OLCTRMIS":"~~~","OLCTRUDF":"~","OLCTRADV":"~~","OLDEVENT":"~EXECUTEQUERY","OLDMSPRV":"~~OL~OLDVAMND~EXECUTEQUERY"};
var scrArgDest = {"CVS_MSGVW":"BLK_MSGVW_HEADER__REF_NO_UI"};
//***** CODE FOR SUB-SYSTEM DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
var dpndntOnFlds = {"LFCTRCHG":"","LFCINTCH":"BLK_CONTRACT_MASTER__AMNDDT","OLCONDET":"","TXCTRTAX":"","OLCSTINF":"","OLCTRMIS":"","OLCTRUDF":"","OLCTRADV":""};
var dpndntOnSrvs = {"LFCTRCHG":"","LFCINTCH":"","OLCONDET":"","TXCTRTAX":"","OLCSTINF":"","OLCTRMIS":"","OLCTRUDF":"","OLCTRADV":""};
//***** CODE FOR TAB DEPENDENT  FIELDS   *****
//----------------------------------------------------------------------------------------------------------------------
//***** CODE FOR CALLFORM TABS *****
//----------------------------------------------------------------------------------------------------------------------
var callformTabArray = new Array(); 
//***** CODE FOR ACTION STAGE DETAILS *****
//----------------------------------------------------------------------------------------------------------------------
var actStageArry = {"QUERY":"1","NEW":"1","MODIFY":"2","AUTHORIZE":"1","DELETE":"1","CLOSE":"1","REOPEN":"1","REVERSE":"1","ROLLOVER":"1","CONFIRM":"1","LIQUIDATE":"1","SUMMARYQUERY":"1"};
//***** CODE FOR IMAGE FLDSET *****
//----------------------------------------------------------------------------------------------------------------------