SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH" app
DECLARE
V_TARGET_SCHEMA varchar2(30):='&TARGET_SCHEMA';
V_TARGET_DATABASE_LINK varchar2(30):=V_TARGET_SCHEMA;--Database link created in src(FIC-HOST) referring to FIC-REPORTING objects
var BOOLEAN; 
BEGIN
BEGIN
UPDATE MDTM_OTHER_PROGRAM_INFO
SET
PARAMETER_NAME_1='Source_DB_Name',
PARAMETER_VALUE_1= '&SOURCE_DB',
PARAMETER_NAME_2='Target_DB_Name',
PARAMETER_VALUE_2='&TARGET_DB',
PARAMETER_NAME_3='Source_Tablespace_Name',
PARAMETER_VALUE_3='&SOURCE_TABLESPACE_NAME',
PARAMETER_NAME_4='Target_Tablespace_Name',
PARAMETER_VALUE_4='&TARGET_TABLESPACE_NAME',
PARAMETER_NAME_5='Source_Schema_Name',
PARAMETER_VALUE_5='&SOURCE_SCHEMA',
PARAMETER_NAME_6='Target_Schema_Name',
PARAMETER_VALUE_6='&TARGET_SCHEMA',
PARAMETER_NAME_9='SOURCE_DUMP_DIRECTORY',
PARAMETER_VALUE_9='&SOURCE_DUMP_DIRECTORY',
PARAMETER_NAME_10='TARGET_DUMP_DIRECTORY',
PARAMETER_VALUE_10='&TARGET_DUMP_DIRECTORY'


WHERE PROGRAM_NAME='PRG_TTS_JOB';
--UPDATE MDTM_SCHEDULER_INFO
UPDATE MDTM_SCHEDULER_INFO SET ENABLED_FLAG='Y' WHERE SCHEDULER_PROGRAM_NAME ='PRG_TTS_JOB'; 

commit;
END;
BEGIN 
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM CREATE_ETL_DDL for '||V_TARGET_SCHEMA||'.CREATE_ETL_DDL@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ETL_LOAD_WRAPPER for '||V_TARGET_SCHEMA||'.ETL_LOAD_WRAPPER@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM PKG_ETL_UTIL for '||V_TARGET_SCHEMA||'.PKG_ETL_UTIL@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM FACT_LOAD_ETL for '||V_TARGET_SCHEMA||'.FACT_LOAD_ETL@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM POPULATE_DATE_DIM for '||V_TARGET_SCHEMA||'.POPULATE_DATE_DIM@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM TRANSPORT_TABLESPACE_WRAPPER FOR '||V_TARGET_SCHEMA||'.TRANSPORT_TABLESPACE_WRAPPER@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM COMPILE_ALL_DYNAMIC_OBJECTS FOR '||V_TARGET_SCHEMA||'.COMPILE_ALL_DYNAMIC_OBJECTS@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM INSERT_APPLICATION_LOG for '||V_TARGET_SCHEMA||'.INSERT_APPLICATION_LOG@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTB_BATCH_INFO FOR '||V_TARGET_SCHEMA||'.MDTB_BATCH_INFO@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTB_RUN_STEP_LOG FOR '||V_TARGET_SCHEMA||'.MDTB_RUN_STEP_LOG@'||V_TARGET_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTB_PROGRAM_RUN_INFO FOR '||V_TARGET_SCHEMA||'.MDTB_PROGRAM_RUN_INFO@'||V_TARGET_DATABASE_LINK;
END;

END;
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT