SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH"

-- DBLINK FROM SOURCE TO TARGET SCHEMA
CREATE DATABASE LINK &TARGET_SCHEMA 
CONNECT TO &TARGET_SCHEMA 
IDENTIFIED BY &TARGET_SCHEMA_PASSWORD 
USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = &TARGET_SCHEMA_HOST)(PORT = &TARGET_SCHEMA_PORT))
    (CONNECT_DATA =
      (SERVICE_NAME = &TARGET_SCHEMA_SID)
    )
  )'
;
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT