SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH" app
DECLARE
V_TARGET_SCHEMA varchar2(30):='&TARGET_SCHEMA';
V_SOURCE_SCHEMA varchar2(30):='&SOURCE_SCHEMA';
V_SOURCE_DATABASE_LINK varchar2(30):='&SOURCE_SCHEMA';
V_SOURCE_DB varchar2(30):='&SOURCE_DB';
V_TARGET_DB varchar2(30):='&TARGET_DB';
var BOOLEAN; 
BEGIN
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_DIMENSION_MAP FOR '||V_SOURCE_SCHEMA||'.MDTM_DIMENSION_MAP@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_ENTITY_DETAIL FOR '||V_SOURCE_SCHEMA||'.MDTM_ENTITY_DETAIL@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_ENTITY_MASTER FOR '||V_SOURCE_SCHEMA||'.MDTM_ENTITY_MASTER@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_FLTR_DET FOR  '||V_SOURCE_SCHEMA||'.MDTM_FCT_FLTR_DET@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_JOIN_DET FOR '||V_SOURCE_SCHEMA||'.MDTM_FCT_JOIN_DET@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_MAP FOR '||V_SOURCE_SCHEMA||'.MDTM_FCT_MAP@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_OTHER_PROGRAM_INFO FOR '||V_SOURCE_SCHEMA||'.MDTM_OTHER_PROGRAM_INFO@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_PROGRAM_INFO FOR '||V_SOURCE_SCHEMA||'.MDTM_PROGRAM_INFO@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_SCHED_DEPEN FOR '||V_SOURCE_SCHEMA||'.MDTM_SCHED_DEPEN@'||V_SOURCE_DATABASE_LINK;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_SCHEDULER_INFO FOR '||V_SOURCE_SCHEMA||'.MDTM_SCHEDULER_INFO@'||V_SOURCE_DATABASE_LINK;
update mdtb_batch_info set BATCH_USER=V_TARGET_SCHEMA,SOURCE_SCHEMA=V_SOURCE_SCHEMA,SOURCE_DB=V_SOURCE_DB,TARGET_DB=V_TARGET_DB,TARGET_SCHEMA=V_TARGET_SCHEMA;
COMMIT;
END;
/
-- create staging table

CREATE TABLE ESTB_STG_CUSTOMER
(
CUSTOMER_NO VARCHAR2(11) , 
CUSTOMER_NAME VARCHAR2(105) , 
ADDRESS_LINE1 VARCHAR2(105) , 
ADDRESS_LINE2 VARCHAR2(105) , 
ADDRESS_LINE3 VARCHAR2(105) , 
ADDRESS_LINE4 VARCHAR2(105) , 
COUNTRY VARCHAR2(3) , 
SHORT_NAME VARCHAR2(20) , 
NATIONALITY VARCHAR2(3) , 
LANGUAGE VARCHAR2(3) , 
LOCAL_BRANCH VARCHAR2(3) , 
FROZEN CHAR(1) , 
DECEASED CHAR(1) , 
WHEREABOUTS_UNKNOWN CHAR(1) , 
CUSTOMER_CATEGORY VARCHAR2(10) , 
CIF_CREATION_DATE DATE , 
CUSTOMER_STATUS CHAR(1) , 
DATE_OF_BIRTH DATE , 
SEX VARCHAR2(20) , 
CREDIT_RATING VARCHAR2(10) , 
CUST_CLASSIFICATION VARCHAR2(20) , 
CUSTOMER_TYPE CHAR(1) , 
CUSTOMER_SEGMENT VARCHAR2(150) , 
CUSTOMER_INDUSTRY VARCHAR2(150) , 
GROUP_CODE VARCHAR2(10) , 
BUSINESS_SEGMENT_CODE VARCHAR2(150) , 
SECTOR_CODE VARCHAR2(35) , 
EXPOSURE_COUNTRY VARCHAR2(3)
)
/
ALTER TABLE ESTB_STG_CUSTOMER
ADD CONSTRAINT C1_ESTB_STG_CUSTOMER CHECK( "CUSTOMER_NO" IS NOT NULL)
/
ALTER TABLE ESTB_STG_CUSTOMER
ADD CONSTRAINT C2_ESTB_STG_CUSTOMER CHECK( "SHORT_NAME" IS NOT NULL)
/
ALTER TABLE ESTB_STG_CUSTOMER
ADD CONSTRAINT PK_ESTB_STG_CUSTOMER PRIMARY KEY(CUSTOMER_NO)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_CUSTOMER FOR ESTB_STG_CUSTOMER
/

PROMPT PROCESSING FOR ESTB_STG_ACC_PERIOD 

CREATE TABLE ESTB_STG_ACC_PERIOD
(
BRANCH_CODE VARCHAR2(3) , 
FIN_CYCLE VARCHAR2(9) , 
PERIOD_CODE VARCHAR2(3) , 
YEAR VARCHAR2(4) , 
QUARTER VARCHAR2(3) , 
HALF VARCHAR2(3) , 
MONTH VARCHAR2(3) , 
PC_START_DATE DATE , 
PC_END_DATE DATE
)
/
ALTER TABLE ESTB_STG_ACC_PERIOD
ADD CONSTRAINT C1_ESTB_STG_ACC_PERIOD CHECK( "BRANCH_CODE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_ACC_PERIOD
ADD CONSTRAINT C2_ESTB_STG_ACC_PERIOD CHECK( "FIN_CYCLE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_ACC_PERIOD
ADD CONSTRAINT C3_ESTB_STG_ACC_PERIOD CHECK( "PERIOD_CODE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_ACC_PERIOD
ADD CONSTRAINT PK_ESTB_STG_ACC_PERIOD PRIMARY KEY(FIN_CYCLE,PERIOD_CODE)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_ACC_PERIOD FOR ESTB_STG_ACC_PERIOD
/

CREATE TABLE ESTB_STG_HOLIDAY
(
BRANCH_CODE VARCHAR2(3) , 
YEAR NUMBER(4) , 
MONTH NUMBER(2) , 
HOLIDAY_LIST VARCHAR2(31)
)
/
ALTER TABLE ESTB_STG_HOLIDAY
ADD CONSTRAINT C1_ESTB_STG_HOLIDAY CHECK( "BRANCH_CODE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_HOLIDAY
ADD CONSTRAINT C2_ESTB_STG_HOLIDAY CHECK( "YEAR" IS NOT NULL)
/
ALTER TABLE ESTB_STG_HOLIDAY
ADD CONSTRAINT C3_ESTB_STG_HOLIDAY CHECK( "MONTH" IS NOT NULL)
/
ALTER TABLE ESTB_STG_HOLIDAY
ADD CONSTRAINT PK_ESTB_STG_HOLIDAY PRIMARY KEY(BRANCH_CODE,YEAR,MONTH)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_HOLIDAY FOR ESTB_STG_HOLIDAY
/


CREATE TABLE ESTB_STG_DATES
(
BRANCH_CODE VARCHAR2(3) , 
TODAY DATE , 
PREV_WORKING_DAY DATE , 
NEXT_WORKING_DAY DATE
)
/
ALTER TABLE ESTB_STG_DATES
ADD CONSTRAINT C1_ESTB_STG_DATES CHECK( "BRANCH_CODE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_DATES
ADD CONSTRAINT PK_ESTB_STG_DATES PRIMARY KEY(BRANCH_CODE)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_DATES FOR ESTB_STG_DATES
/


CREATE TABLE ESTB_STG_CURRENCY
(
CURRENCY_CODE VARCHAR2(3) , 
CURRENCY_DESC VARCHAR2(105)
)
/
ALTER TABLE ESTB_STG_CURRENCY
ADD CONSTRAINT C1_ESTB_STG_CURRENCY CHECK( "CURRENCY_CODE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_CURRENCY
ADD CONSTRAINT PK_ESTB_STG_CURRENCY PRIMARY KEY(CURRENCY_CODE)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_CURRENCY FOR ESTB_STG_CURRENCY
/


CREATE TABLE ESTB_STG_BRANCH
(
BRANCH_CODE VARCHAR2(3) , 
BRANCH_NAME VARCHAR2(105) , 
PARENT_CODE VARCHAR2(3) , 
PARENT_NAME VARCHAR2(105) , 
REG_OFF_CODE VARCHAR2(3) , 
REG_OFF_NAME VARCHAR2(105) , 
BRANCH_LCY VARCHAR2(3) , 
BRANCH_ADDRESS1 VARCHAR2(105) , 
BRANCH_ADDRESS2 VARCHAR2(105) , 
BRANCH_ADDRESS3 VARCHAR2(105) , 
COUNTRY_CODE VARCHAR2(3) , 
CLOSURE_DATE DATE
)
/
ALTER TABLE ESTB_STG_BRANCH
ADD CONSTRAINT C1_ESTB_STG_BRANCH CHECK( "BRANCH_CODE" IS NOT NULL)
/
ALTER TABLE ESTB_STG_BRANCH
ADD CONSTRAINT PK_ESTB_STG_BRANCH PRIMARY KEY(BRANCH_CODE)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_BRANCH FOR ESTB_STG_BRANCH
/



CREATE TABLE ESTB_STG_ELCM_LIAB
(
ID NUMBER(20) , 
LIAB_NO VARCHAR2(36) , 
LIAB_NAME VARCHAR2(1020) , 
LIAB_BRANCH VARCHAR2(12) , 
LIAB_CCY VARCHAR2(12) , 
MAIN_LIAB_ID NUMBER(20)
)
/
ALTER TABLE ESTB_STG_ELCM_LIAB
ADD CONSTRAINT C1_ESTB_STG_ELCM_LIAB CHECK( "ID" IS NOT NULL)
/
ALTER TABLE ESTB_STG_ELCM_LIAB
ADD CONSTRAINT PK01_ESTB_STG_ELCM_LIAB PRIMARY KEY(ID)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_ELCM_LIAB FOR ESTB_STG_ELCM_LIAB
/
CREATE TABLE ESTB_STG_LIMITS_EXPOSURE
(
EXPOSURE_ID NUMBER(20) , 
EXPOSURE_NAME VARCHAR2(35) , 
EXPOSURE_TYPE VARCHAR2(50) , 
EXPOSURE_CODE VARCHAR2(35) , 
EXPOSURE_RATING VARCHAR2(10) , 
UTILISATION_TYPE VARCHAR2(1)
)
/
ALTER TABLE ESTB_STG_LIMITS_EXPOSURE
ADD CONSTRAINT C1_ESTB_STG_LIMITS_EXPOSURE CHECK(    "EXPOSURE_ID" IS NOT NULL)
/
ALTER TABLE ESTB_STG_LIMITS_EXPOSURE
ADD CONSTRAINT PK01_ESTB_STG_LIMITS_EXPOSURE PRIMARY KEY(EXPOSURE_ID)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_LIMITS_EXPOSURE FOR ESTB_STG_LIMITS_EXPOSURE
/

CREATE TABLE ESTB_STG_FACILITY
(
MIS_DATE DATE , 
FACILITY_ID NUMBER(20) , 
LINE_CODE VARCHAR2(200) , 
LINE_SERIAL NUMBER(3) , 
LINE_CURRENCY VARCHAR2(12) , 
LIABILITY_ID NUMBER(20) , 
LIABILITY_NO VARCHAR2(36) , 
CUSTOMER_NO VARCHAR2(9) , 
NEW_LIAB_QTR VARCHAR2(1) DEFAULT 'N' , 
LIMIT_TYPE VARCHAR2(50) , 
CURRENCY VARCHAR2(12) , 
LIMIT_SACTIONED_DATE DATE , 
LIMIT_SANCTIONED_FCY NUMBER(24,3) DEFAULT 0 , 
LIMIT_SANCTIONED_LCY NUMBER(24,3) DEFAULT 0 , 
LIMIT_UTILIZED_FCY NUMBER(24,3) DEFAULT 0 , 
LIMIT_UTILIZED_LCY NUMBER(24,3) DEFAULT 0 , 
UTIL_DATE DATE , 
LINE_EXPIRY_DATE DATE , 
LINE_EXP_AMOUNT_FCY NUMBER(24,3) DEFAULT 0 , 
LINE_EXP_AMOUNT_LCY NUMBER(24,3) DEFAULT 0 , 
LINE_AMT_RECOVERED_FCY NUMBER(24,3) DEFAULT 0 , 
LINE_AMT_RECOVERED_LCY NUMBER(24,3) DEFAULT 0 , 
RECOVERY_DATE DATE , 
STATUS VARCHAR2(200) , 
REVOLVING_LINE VARCHAR2(4) DEFAULT 'Y' , 
MATURED_UTIL NUMBER(24,3) DEFAULT 0 , 
OVERDRAWN_AMOUNT_FCY NUMBER(24,3) DEFAULT 0 , 
OVERDRAWN_AMOUNT_LCY NUMBER(24,3) DEFAULT 0 , 
OVERDRAWN_DATE DATE
)
/
ALTER TABLE ESTB_STG_FACILITY
ADD CONSTRAINT C1_ESTB_STG_FACILITY CHECK(    "FACILITY_ID" IS NOT NULL)
/
ALTER TABLE ESTB_STG_FACILITY
ADD CONSTRAINT PK01_ESTB_STG_FACILITY PRIMARY KEY(MIS_DATE,FACILITY_ID)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_FACILITY FOR ESTB_STG_FACILITY
/

CREATE TABLE ESTB_STG_TRACK_EXPOSURE
(
MIS_DATE DATE , 
EXPOSURE_ID NUMBER(20) , 
EXPOSURE_CODE VARCHAR2(35) , 
EXPOSURE_CURRENCY VARCHAR2(3) , 
EXPOSURE_AMOUNT_LCY NUMBER(24,3) DEFAULT 0 , 
EXPOSURE_AMOUNT_FCY NUMBER(24,3) DEFAULT 0 , 
UTILISATION_LCY NUMBER(24,3) DEFAULT 0 , 
UTILISATION_FCY NUMBER(24,3) DEFAULT 0 , 
AVAILABLE_AMOUNT_LCY NUMBER(24,3) DEFAULT 0 , 
AVAILABLE_AMOUNT_FCY NUMBER(24,3) DEFAULT 0
)
/
ALTER TABLE ESTB_STG_TRACK_EXPOSURE
ADD CONSTRAINT C1_ESTB_STG_TRACK_EXPOSURE CHECK(    "EXPOSURE_ID" IS NOT NULL)
/
ALTER TABLE ESTB_STG_TRACK_EXPOSURE
ADD CONSTRAINT PK01_ESTB_STG_TRACK_EXPOSURE PRIMARY KEY(MIS_DATE,EXPOSURE_ID)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_TRACK_EXPOSURE FOR ESTB_STG_TRACK_EXPOSURE
/

CREATE TABLE ESTB_STG_FACILITY_EXPOSURE
(
MIS_DATE DATE , 
FACILITY_EXP_ID NUMBER(20) , 
FACILITY_ID NUMBER(20) , 
EXPOSURE_ID NUMBER(20)
)
/
ALTER TABLE ESTB_STG_FACILITY_EXPOSURE
ADD CONSTRAINT C1_ESTB_STG_FACILITY_EXP CHECK(    "FACILITY_EXP_ID" IS NOT NULL)
/
ALTER TABLE ESTB_STG_FACILITY_EXPOSURE
ADD CONSTRAINT PK01_ESTB_STG_FACILITY_EXP PRIMARY KEY(MIS_DATE,FACILITY_EXP_ID)
/

CREATE OR REPLACE SYNONYM  ESTBS_STG_FACILITY_EXPOSURE FOR ESTB_STG_FACILITY_EXPOSURE
/

CREATE TABLE ESTB_STG_UTILS_EXP
(
UTIL_ID VARCHAR2(50) , 
VERSION_NO  NUMBER , 
EXPOSURE_ID NUMBER(20) , 
UTIL_BRN VARCHAR2(3) , 
USER_REFNO VARCHAR2(50) , 
UTIL_AMT NUMBER(24,3) DEFAULT 0 , 
UTIL_CCY VARCHAR2(3) , 
EXP_UTIL_FCY NUMBER(24,3) DEFAULT 0 , 
EXP_UTIL_LCY NUMBER(24,3) DEFAULT 0 , 
EXP_CCY VARCHAR2(3) , 
EXCH_RATE NUMBER(24,12) , 
CUSTOMER_NO VARCHAR2(140) , 
LIAB_ID NUMBER(20) , 
LIMIT_TYPE VARCHAR2(4) DEFAULT 'F' , 
LIMIT_ID NUMBER(20) , 
MAIN_LIAB_ID NUMBER(20) , 
MIS_DATE DATE , 
CPARTY_APPETITE_LCY NUMBER(24,3) , 
CPARTY_APPETITE_FCY NUMBER(24,3)
)
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT