SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH" app
DECLARE
V_SOURCE_SCHEMA varchar2(30):='&SOURCE_SCHEMA';
V_TARGET_SCHEMA varchar2(30):='&TARGET_SCHEMA';
V_SOURCE_DB varchar2(30):='&SOURCE_DB';
V_TARGET_DB varchar2(30):='&TARGET_DB';
BEGIN
--PRIVATE SYNONYMS OF SOURCE SCHEMA OBJECTS FOR TARGET SCHEMA
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_DIMENSION_MAP FOR '||V_SOURCE_SCHEMA||'.MDTM_DIMENSION_MAP';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_ENTITY_DETAIL FOR '||V_SOURCE_SCHEMA||'.MDTM_ENTITY_DETAIL';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_ENTITY_MASTER FOR '||V_SOURCE_SCHEMA||'.MDTM_ENTITY_MASTER';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_FLTR_DET FOR  '||V_SOURCE_SCHEMA||'.MDTM_FCT_FLTR_DET';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_JOIN_DET FOR '||V_SOURCE_SCHEMA||'.MDTM_FCT_JOIN_DET';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_MAP FOR '||V_SOURCE_SCHEMA||'.MDTM_FCT_MAP';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_OTHER_PROGRAM_INFO FOR '||V_SOURCE_SCHEMA||'.MDTM_OTHER_PROGRAM_INFO';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_PROGRAM_INFO FOR '||V_SOURCE_SCHEMA||'.MDTM_PROGRAM_INFO';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_SCHED_DEPEN FOR '||V_SOURCE_SCHEMA||'.MDTM_SCHED_DEPEN';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_SCHEDULER_INFO FOR '||V_SOURCE_SCHEMA||'.MDTM_SCHEDULER_INFO';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_ACC_PERIOD for '||V_SOURCE_SCHEMA||'.ESTB_STG_ACC_PERIOD';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_BRANCH for '||V_SOURCE_SCHEMA||'.ESTB_STG_BRANCH';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_CURRENCY for '||V_SOURCE_SCHEMA||'.ESTB_STG_CURRENCY';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_DATES for '||V_SOURCE_SCHEMA||'.ESTB_STG_DATES';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_HOLIDAY for '||V_SOURCE_SCHEMA||'.ESTB_STG_HOLIDAY';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_CUSTOMER for '||V_SOURCE_SCHEMA||'.ESTB_STG_CUSTOMER'; 
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_LIMITS_EXPOSURE for '||V_SOURCE_SCHEMA||'.ESTB_STG_LIMITS_EXPOSURE';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_ELCM_LIAB for '||V_SOURCE_SCHEMA||'.ESTB_STG_ELCM_LIAB';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_FACILITY for '||V_SOURCE_SCHEMA||'.ESTB_STG_FACILITY';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_TRACK_EXPOSURE for '||V_SOURCE_SCHEMA||'.ESTB_STG_TRACK_EXPOSURE';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_FACILITY_EXPOSURE for '||V_SOURCE_SCHEMA||'.ESTB_STG_FACILITY_EXPOSURE';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ESTB_STG_UTILS_EXP for '||V_SOURCE_SCHEMA||'.ESTB_STG_UTILS_EXP';
-- Grant permissions from target to source
EXECUTE IMMEDIATE 'Grant execute on CREATE_ETL_DDL to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'Grant execute on ETL_LOAD_WRAPPER to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant execute on PKG_ETL_UTIL to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant execute on FACT_LOAD_ETL to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant execute on POPULATE_DATE_DIM to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant execute on INSERT_APPLICATION_LOG to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant select on MDTB_BATCH_INFO to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant select,insert,update on MDTB_RUN_STEP_LOG to '||V_SOURCE_SCHEMA;
EXECUTE IMMEDIATE 'grant select,insert,update on MDTB_PROGRAM_RUN_INFO to '||V_SOURCE_SCHEMA;

update mdtb_batch_info set BATCH_USER=V_TARGET_SCHEMA,SOURCE_SCHEMA=V_SOURCE_SCHEMA,SOURCE_DB=V_SOURCE_DB,TARGET_DB=V_TARGET_DB,TARGET_SCHEMA=V_TARGET_SCHEMA;
COMMIT;

END;
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT