SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH" app
DECLARE
V_SOURCE_SCHEMA varchar2(30):='&SOURCE_SCHEMA';
V_TARGET_SCHEMA varchar2(30):='&TARGET_SCHEMA';
BEGIN
-- Grant permissions from source to target
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_ACC_PERIOD to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_BRANCH to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_CURRENCY to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_CUSTOMER to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_DATES to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_HOLIDAY to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_DIMENSION_MAP to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_FCT_FLTR_DET to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_FCT_JOIN_DET to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_FCT_MAP to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_OTHER_PROGRAM_INFO to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_PROGRAM_INFO to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_SCHED_DEPEN to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on MDTM_SCHEDULER_INFO to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_LIMITS_EXPOSURE to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_ELCM_LIAB to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_FACILITY to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_TRACK_EXPOSURE to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_FACILITY_EXPOSURE to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'Grant select on ESTB_STG_UTILS_EXP to '||V_TARGET_SCHEMA;
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_DIMENSION_MAP FOR MDTM_DIMENSION_MAP';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_ENTITY_DETAIL FOR MDTM_ENTITY_DETAIL';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_ENTITY_MASTER FOR MDTM_ENTITY_MASTER';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_FLTR_DET FOR  MDTM_FCT_FLTR_DET';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_JOIN_DET FOR MDTM_FCT_JOIN_DET';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_FCT_MAP FOR MDTM_FCT_MAP';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_OTHER_PROGRAM_INFO FOR MDTM_OTHER_PROGRAM_INFO';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_PROGRAM_INFO FOR MDTM_PROGRAM_INFO';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_SCHED_DEPEN FOR MDTM_SCHED_DEPEN';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTMS_SCHEDULER_INFO FOR MDTM_SCHEDULER_INFO';

--PRIVATE SYNONYMS OF TARGET SCHEMA OBJECTS FOR  SOURCE SCHEMA
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM CREATE_ETL_DDL for '||V_TARGET_SCHEMA||'.CREATE_ETL_DDL';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM ETL_LOAD_WRAPPER for '||V_TARGET_SCHEMA||'.ETL_LOAD_WRAPPER';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM PKG_ETL_UTIL for '||V_TARGET_SCHEMA||'.PKG_ETL_UTIL';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM FACT_LOAD_ETL for '||V_TARGET_SCHEMA||'.FACT_LOAD_ETL';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM POPULATE_DATE_DIM for '||V_TARGET_SCHEMA||'.POPULATE_DATE_DIM';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM INSERT_APPLICATION_LOG for '||V_TARGET_SCHEMA||'.INSERT_APPLICATION_LOG';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTB_BATCH_INFO FOR '||V_TARGET_SCHEMA||'.MDTB_BATCH_INFO';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTB_RUN_STEP_LOG FOR '||V_TARGET_SCHEMA||'.MDTB_RUN_STEP_LOG';
EXECUTE IMMEDIATE 'CREATE OR REPLACE  SYNONYM MDTB_PROGRAM_RUN_INFO FOR '||V_TARGET_SCHEMA||'.MDTB_PROGRAM_RUN_INFO';
--UPDATE MDTM_SCHEDULER_INFO
UPDATE MDTM_SCHEDULER_INFO SET ENABLED_FLAG='N' WHERE SCHEDULER_PROGRAM_NAME ='PRG_TTS_JOB'; 
COMMIT;
END;
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT