SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH" app

-- DBLINK FROM TARGET TO SOURCE SCHEMA
CREATE DATABASE LINK &SOURCE_SCHEMA 
CONNECT TO &SOURCE_SCHEMA 
IDENTIFIED BY &SOURCE_SCHEMA_PASSWORD 
USING '(DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = &SOURCE_SCHEMA_HOST)(PORT = &SOURCE_SCHEMA_PORT))
    (CONNECT_DATA =
      (SERVICE_NAME = &SOURCE_SCHEMA_SID)
    )
  )'
;
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT