SPOOL ON
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON
SET ERRORLOGGING ON
SPOOL "&SPOOL_PATH" app
DECLARE
var BOOLEAN; 
BEGIN
-- Create functions
 VAR := CREATE_ETL_DDL('LD#_DIM_BRANCH');  
 VAR := CREATE_ETL_DDL('LD#_DIM_CURRENCY');  
 VAR := CREATE_ETL_DDL('LD#_DIM_ACC_PERIOD');  
 VAR := CREATE_ETL_DDL('LD#_DIM_CUST');  
 VAR := CREATE_ETL_DDL('LD#_DIM_HOLIDAY');  
 VAR := CREATE_ETL_DDL('LD#_DIM_LIMITS_EXPOSURE'); 
 VAR := CREATE_ETL_DDL('LD#_DIM_ELCM_LIAB'); 
 VAR := CREATE_ETL_DDL('LD#_DIM_STTM_DATES');  
 VAR := CREATE_ETL_DDL('LD#_FCT_FACILITY'); 
 VAR := CREATE_ETL_DDL('LD#_FCT_TRACK_EXPOSURE'); 
 VAR := CREATE_ETL_DDL('LD#_FCT_FAC_EXP_MAP'); 
 VAR := CREATE_ETL_DDL('LD#_FCT_UTILS_EXP'); 
-- Configure batch
SCHEDULE_BATCH_JOBS;
END;
/
SET ERRORLOGGING OFF
SPOOL OFF
EXIT
