
package com.ofss.ucm.loginservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginService", targetNamespace = "http://imaging.oracle/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginService {


    /**
     * 
     * @return
     *     returns java.util.List<com.ofss.ucm.loginservice.SecurityMember>
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserRoles", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.GetUserRoles")
    @ResponseWrapper(localName = "getUserRolesResponse", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.GetUserRolesResponse")
    public List<SecurityMember> getUserRoles()
        throws ImagingException
    ;

    /**
     * 
     * @throws ImagingException
     */
    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.LoginResponse")
    public void login()
        throws ImagingException
    ;

    /**
     * 
     * @throws ImagingException
     */
    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.LogoutResponse")
    public void logout()
        throws ImagingException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.ofss.ucm.loginservice.SecurityMember>
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserGroups", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.GetUserGroups")
    @ResponseWrapper(localName = "getUserGroupsResponse", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.GetUserGroupsResponse")
    public List<SecurityMember> getUserGroups()
        throws ImagingException
    ;

    /**
     * 
     * @return
     *     returns com.ofss.ucm.loginservice.SecurityMember
     * @throws ImagingException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://imaging.oracle/", className = "com.ofss.ucm.loginservice.GetUserInfoResponse")
    public SecurityMember getUserInfo()
        throws ImagingException
    ;

}
