DELETE FROM SMTB_FUNCTION_DESCRIPTION WHERE FUNCTION_ID IN (SELECT FUNCTION_ID FROM SMTB_MENU WHERE NVL(MODULE,'*') NOT IN ('AC', 'AE', 'CO', 'CS', 'CY', 'DE', 'EG', 'EI', 'GL', 'MI', 'SM', 'ST'))
/
DELETE FROM SMTB_FCC_FCJ_MAPPING  WHERE FCJ_FUNCTION_ID IN (SELECT FUNCTION_ID FROM SMTB_MENU WHERE NVL(MODULE,'*') NOT IN ('AC', 'AE', 'CO', 'CS', 'CY', 'DE', 'EG', 'EI', 'GL', 'MI', 'SM', 'ST'))
/
DELETE FROM SMTB_ROLE_DETAIL        WHERE ROLE_FUNCTION IN (SELECT FUNCTION_ID FROM SMTB_MENU WHERE NVL(MODULE,'*') NOT IN ('AC', 'AE', 'CO', 'CS', 'CY', 'DE', 'EG', 'EI', 'GL', 'MI', 'SM', 'ST'))
/
DELETE FROM SMTB_MENU                  WHERE NVL(MODULE,'*') NOT IN ('AC', 'AE', 'CO', 'CS', 'CY', 'DE', 'EG', 'EI', 'GL', 'MI', 'SM', 'ST')
/
