set HEAD OFF
SET FEEDBACK OFF
SET LINESIZE 500
SET PAGESIZE 1000
#SET VERIFY OFF
spool &1/Module_Status.xml
SELECT '<DB>' FROM DUAL;
SELECT '<MODULE><NAME>'||MODULE||'</NAME><DESC>'||MODULE_DESC||'</DESC><STATUS>'||STATUS||'</STATUS></MODULE>'
from fcubs_registry where MODULE IN &2;
SELECT '</DB>' FROM DUAL;
spool off
exit;
