package com.ofss.ucm.contentservice;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

@WebServiceClient(wsdlLocation="/wsdls/DocumentContentService.wsdl",targetNamespace = "http://imaging.oracle/", name = "DocumentContentService")
public class DocumentContentService_Service extends Service {
	private static URL wsdlLocationURL;

	private static Logger logger;
	static {
		try {
			logger = Logger
					.getLogger("com.ofss.ucm.contentservice.DocumentContentService_Service");
			URL baseUrl = DocumentContentService_Service.class.getResource(".");
			if (baseUrl == null) {
				wsdlLocationURL = DocumentContentService_Service.class
						.getResource("/wsdls/DocumentContentService.wsdl");
				if (wsdlLocationURL == null) {
					baseUrl = new File(".").toURL();
					wsdlLocationURL = new URL(baseUrl,
							"/wsdls/DocumentContentService.wsdl");
				}
			} else {
				if (!baseUrl.getPath().endsWith("/")) {
					baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
				}
				wsdlLocationURL = new URL(baseUrl,
						"/wsdls/DocumentContentService.wsdl");
			} 
		} catch (MalformedURLException e) {
			logger.log(
					Level.ALL,
					"Failed to create wsdlLocationURL using /wsdls/DocumentContentService.wsdl",
					e);
		}
	} 

	public DocumentContentService_Service() {
		super(wsdlLocationURL, new QName("http://imaging.oracle/",
				"DocumentContentService"));
	}

	public DocumentContentService_Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	@WebEndpoint(name = "DocumentContentServicePort")
	public com.ofss.ucm.contentservice.DocumentContentService getDocumentContentServicePort() {
		return (com.ofss.ucm.contentservice.DocumentContentService) super
				.getPort(
						new QName("http://imaging.oracle/",
								"DocumentContentServicePort"),
						com.ofss.ucm.contentservice.DocumentContentService.class);
	}

	@WebEndpoint(name = "DocumentContentServicePort")
	public com.ofss.ucm.contentservice.DocumentContentService getDocumentContentServicePort(
			WebServiceFeature... features) {
		return (com.ofss.ucm.contentservice.DocumentContentService) super
				.getPort(
						new QName("http://imaging.oracle/",
								"DocumentContentServicePort"),
						com.ofss.ucm.contentservice.DocumentContentService.class,
						features);
	}
}
