update smtb_menu set process_code ='CAMB' where process_code = 'CAMP';
update smtb_menu set process_code ='ORCB' where process_code = 'ORCC';
update smtb_menu set process_code ='LMRV' where process_code = 'LMRW'; 
update smtb_menu set process_code ='CACB' where process_code = 'CACP';
update smtb_menu set process_code ='LRLC' where process_code = 'NRLC'; 
update smtb_menu set process_code ='IJCL' where process_code = 'IJCN';
update smtb_menu set process_code ='ITCL' where process_code = 'ITCN';
update smtb_menu set process_code ='MDCL' where process_code = 'MDCN'; 
update smtb_menu set process_code ='MRCL' where process_code = 'MRCN'; 
update smtb_menu set process_code ='MSCL' where process_code = 'MSCN'; 
update smtb_menu set process_code ='TWCL' where process_code = 'TWCN'; 
commit;
/
