
update smtb_menu set process_code ='CAMP' where process_code = 'CAMB';
update smtb_menu set process_code ='ORCC' where process_code = 'ORCB';
update smtb_menu set process_code ='LMRW' where process_code = 'LMRV'; 
update smtb_menu set process_code ='CACP' where process_code = 'CACB'; 
update smtb_menu set process_code ='NRLC' where process_code = 'LRLC'; 
update smtb_menu set process_code ='IJCN' where process_code = 'IJCL';
update smtb_menu set process_code ='ITCN' where process_code = 'ITCL';
update smtb_menu set process_code ='MDCN' where process_code = 'MDCL'; 
update smtb_menu set process_code ='MRCN' where process_code = 'MRCL'; 
update smtb_menu set process_code ='MSCN' where process_code = 'MSCL'; 
update smtb_menu set process_code ='TWCN' where process_code = 'TWCL'; 
commit;
/
