package com.ofss.ucm.docservice;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

@WebServiceClient(wsdlLocation="DocumentService.wsdl",targetNamespace="http://imaging.oracle/", name="DocumentService")
public class DocumentService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("com.ofss.ucm.docservice.DocumentService_Service");
       URL baseUrl = DocumentService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            DocumentService_Service.class.getResource("DocumentService.wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "DocumentService.wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
       }
                wsdlLocationURL =
            new URL(baseUrl, "DocumentService.wsdl");
      }
    } 
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using DocumentService.wsdl",
          e);
    } 
  }

  public DocumentService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://imaging.oracle/", "DocumentService"));
  }

  public DocumentService_Service(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="DocumentServicePort")
  public com.ofss.ucm.docservice.DocumentService getDocumentServicePort()
  {
    return (com.ofss.ucm.docservice.DocumentService) super.getPort(new QName("http://imaging.oracle/",
                                                                             "DocumentServicePort"),
                                                                   com.ofss.ucm.docservice.DocumentService.class);
  }

  @WebEndpoint(name="DocumentServicePort")
  public com.ofss.ucm.docservice.DocumentService getDocumentServicePort(WebServiceFeature... features)
  {
    return (com.ofss.ucm.docservice.DocumentService) super.getPort(new QName("http://imaging.oracle/",
                                                                             "DocumentServicePort"),
                                                                   com.ofss.ucm.docservice.DocumentService.class,
                                                                   features);
  }
}
