package com.ofss.ucm.docservice;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

public class DocumentServicePortClient
{
  @WebServiceRef
  private static DocumentService_Service documentService_Service;

  public static void main(String [] args)
  {
    documentService_Service = new DocumentService_Service();
    DocumentService documentService = documentService_Service.getDocumentServicePort();
    // Add your code to call the desired methods.
  }
}
