package com.ofss.ucm.docservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)

@WebService(wsdlLocation="DocumentService.wsdl",targetNamespace="http://imaging.oracle/", name="DocumentService")
@XmlSeeAlso(
  { com.ofss.ucm.docservice.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface DocumentService
{
  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/getAnnotationsRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/getAnnotations/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/getAnnotationsResponse")
  public void getAnnotations()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/setAnnotationsRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/setAnnotations/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/setAnnotationsResponse")
  public void setAnnotations()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/createDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/createDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class),
        @FaultAction(value="http://imaging.oracle/DocumentService/createDocument/Fault/ValidationException",
          className=com.ofss.ucm.docservice.ValidationException.class) },
    output="http://imaging.oracle/DocumentService/createDocumentResponse")
  @WebResult(targetNamespace="http://imaging.oracle/", partName="parameters",
    name="createDocumentResponse")
  public com.ofss.ucm.docservice.CreateDocumentResponse createDocument(@WebParam(targetNamespace="http://imaging.oracle/",
      partName="parameters", name="createDocument")
    com.ofss.ucm.docservice.CreateDocument parameters)
    throws com.ofss.ucm.docservice.ImagingException, com.ofss.ucm.docservice.ValidationException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/getDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/getDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/getDocumentResponse")
  @WebResult(targetNamespace="http://imaging.oracle/", partName="parameters",
    name="getDocumentResponse")
  public com.ofss.ucm.docservice.GetDocumentResponse getDocument(@WebParam(targetNamespace="http://imaging.oracle/",
      partName="parameters", name="getDocument")
    com.ofss.ucm.docservice.GetDocument parameters)
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/getDocumentVersionRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/getDocumentVersion/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/getDocumentVersionResponse")
  public void getDocumentVersion()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/submitToWorkflowRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/submitToWorkflow/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/submitToWorkflowResponse")
  public void submitToWorkflow()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/listTargetApplicationsRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/listTargetApplications/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/listTargetApplicationsResponse")
  @WebResult(targetNamespace="http://imaging.oracle/", partName="parameters",
    name="listTargetApplicationsResponse")
  public com.ofss.ucm.docservice.ListTargetApplicationsResponse listTargetApplications(@WebParam(targetNamespace="http://imaging.oracle/",
      partName="parameters", name="listTargetApplications")
    com.ofss.ucm.docservice.ListTargetApplications parameters)
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/getDocumentsRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/getDocuments/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/getDocumentsResponse")
  public void getDocuments()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/deleteDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/deleteDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/deleteDocumentResponse")
  @WebResult(targetNamespace="http://imaging.oracle/", partName="parameters",
    name="deleteDocumentResponse")
  public com.ofss.ucm.docservice.DeleteDocumentResponse deleteDocument(@WebParam(targetNamespace="http://imaging.oracle/",
      partName="parameters", name="deleteDocument")
    com.ofss.ucm.docservice.DeleteDocument parameters)
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/deleteDocumentsRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/deleteDocuments/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/deleteDocumentsResponse")
  @WebResult(targetNamespace="http://imaging.oracle/", partName="parameters",
    name="deleteDocumentsResponse")
  public com.ofss.ucm.docservice.DeleteDocumentsResponse deleteDocuments(@WebParam(targetNamespace="http://imaging.oracle/",
      partName="parameters", name="deleteDocuments")
    com.ofss.ucm.docservice.DeleteDocuments parameters)
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/lockDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/lockDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/lockDocumentResponse")
  public void lockDocument()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/unlockDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/unlockDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/unlockDocumentResponse")
  public void unlockDocument()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/updateDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/updateDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class),
        @FaultAction(value="http://imaging.oracle/DocumentService/updateDocument/Fault/ValidationException",
          className=com.ofss.ucm.docservice.ValidationException.class) },
    output="http://imaging.oracle/DocumentService/updateDocumentResponse")
  public void updateDocument()
    throws com.ofss.ucm.docservice.ImagingException, com.ofss.ucm.docservice.ValidationException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/copyDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/copyDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class),
        @FaultAction(value="http://imaging.oracle/DocumentService/copyDocument/Fault/ValidationException",
          className=com.ofss.ucm.docservice.ValidationException.class) },
    output="http://imaging.oracle/DocumentService/copyDocumentResponse")
  public void copyDocument()
    throws com.ofss.ucm.docservice.ImagingException, com.ofss.ucm.docservice.ValidationException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/moveDocumentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/moveDocument/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class),
        @FaultAction(value="http://imaging.oracle/DocumentService/moveDocument/Fault/ValidationException",
          className=com.ofss.ucm.docservice.ValidationException.class) },
    output="http://imaging.oracle/DocumentService/moveDocumentResponse")
  public void moveDocument()
    throws com.ofss.ucm.docservice.ImagingException, com.ofss.ucm.docservice.ValidationException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/modifyPageOrderRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/modifyPageOrder/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/modifyPageOrderResponse")
  public void modifyPageOrder()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/setSupportingContentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/setSupportingContent/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/setSupportingContentResponse")
  public void setSupportingContent()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/getSupportingContentRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/getSupportingContent/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/getSupportingContentResponse")
  public void getSupportingContent()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/getTargetApplicationRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/getTargetApplication/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/getTargetApplicationResponse")
  public void getTargetApplication()
    throws com.ofss.ucm.docservice.ImagingException;

  @WebMethod
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://imaging.oracle/DocumentService/hasStatusChangedRequest", fault =
      { @FaultAction(value="http://imaging.oracle/DocumentService/hasStatusChanged/Fault/ImagingException",
          className=com.ofss.ucm.docservice.ImagingException.class) },
    output="http://imaging.oracle/DocumentService/hasStatusChangedResponse")
  public void hasStatusChanged()
    throws com.ofss.ucm.docservice.ImagingException;
}
