package com.ofss.ucm.docservice;

import javax.xml.ws.WebFault;

@WebFault(faultBean="com.ofss.ucm.docservice.ImagingFaultInfo",
  targetNamespace="http://imaging.oracle/", name="ImagingException")
public class ImagingException
  extends Exception
{
  private com.ofss.ucm.docservice.ImagingFaultInfo faultInfo;

  public ImagingException(String message,
                          com.ofss.ucm.docservice.ImagingFaultInfo faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public ImagingException(String message,
                          com.ofss.ucm.docservice.ImagingFaultInfo faultInfo,
                          Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public com.ofss.ucm.docservice.ImagingFaultInfo getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(com.ofss.ucm.docservice.ImagingFaultInfo faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)
