package com.ofss.ucm.docservice;

import javax.xml.ws.WebFault;

@WebFault(faultBean="com.ofss.ucm.docservice.ValidationFaultInfo",
  targetNamespace="http://imaging.oracle/", name="ValidationException")
public class ValidationException
  extends Exception
{
  private com.ofss.ucm.docservice.ValidationFaultInfo faultInfo;

  public ValidationException(String message,
                             com.ofss.ucm.docservice.ValidationFaultInfo faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public ValidationException(String message,
                             com.ofss.ucm.docservice.ValidationFaultInfo faultInfo,
                             Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public com.ofss.ucm.docservice.ValidationFaultInfo getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(com.ofss.ucm.docservice.ValidationFaultInfo faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 091026.1130.19937)
